SELECT distinct 
    BR02.MENU_ID
   ,BR02.MENU_NAME
   ,BR02.SUB_MENU_ID
   ,BR02.SUB_MENU_NAME
   ,BR02.VIEW_ID
   ,BR02.PCKG_NAME
   ,BR02.INIT_VIEW_ID
   ,BR02.PARAM
   ,BR02.SORT_SEQ
   ,BR02.MENU_DISP_KBN 
   ,BR05.ENABLE_FLG
   ,BR05.EXTRA_FLG
   ,kobetu.CUSTOMIZE_FLG
   ,BR24.URL
   ,BR24.PARAM AS LINK_PARAM
   ,BR24.PARAM_USER_ID
   ,BR24.PARAM_USER_PSWD
   ,BR24.LABEL
   ,BR24.README
   ,BR24.SORT AS LINK_SORT
   ,BR24.DISABLE_STA_TMSP
   ,BR24.DISABLE_END_TMSP
   ,BR24.MAINTE_MSG
   ,BR24.IMG_PATH
   ,BR24.LOG_FLG
   ,BR24.GAISYS_FLG

FROM
    BR05ACTR BR05
   ,BR04USRL BR04
   ,BR02BMNU BR02
LEFT JOIN (
        SELECT 
            USER_ID 
           ,MENU_ID 
           ,SUB_MENU_ID 
           ,CUSTOMIZE_FLG 
        FROM 
            BR54USAC BR54
        WHERE 
            BR54.USER_ID = /*userId*/'99990001' 
    ) as kobetu ON (kobetu.MENU_ID = BR02.MENU_ID AND kobetu.SUB_MENU_ID = BR02.SUB_MENU_ID)
LEFT JOIN BR24LINK BR24 ON (BR02.PARAM = BR24.LINK_ID AND MENU_DISP_KBN = '2')
WHERE
      BR02.MENU_ID     = BR05.MENU_ID 
  AND BR02.SUB_MENU_ID = BR05.SUB_MENU_ID 
  AND BR05.ROLE_CD     = BR04.ROLE_CD 
  AND BR02.MENU_ID    != '00' 
  AND BR02.MENU_ID     = /*subMenuId*/'01' 
  AND BR05.EXTRA_FLG   = '1' 
  AND BR04.USER_ID     = /*userId*/'99990001' 
ORDER BY 
    BR02.SORT_SEQ
