select
    BR01USER.USER_ID,
    rtrim(BR01USER.USER_NAME_KJ) as user_name,
    rtrim(BR01USER.USER_NAME_KANA) as USER_NAME_KANA,
    BR01USER.USERTYPE_CD,
    BR01USER.BUMON_CD,
    BR01USER.PSWD_UPDT_DT,
    BR01USER.SEKYU_FLG,
    rtrim(BR01USER.MAIL_ADD) as MAIL_ADD,
    BR01USER.APPLIED_DT,
    BR01USER.SEKYU_DT,
    BR01USER.SEKYU_UPDT_DT,
    BR01USER.LIMIT_KBN,
    BR01USER.STOP_FLG,
    VBR01USER_BMON.R_COMPANY_CD,
    rtrim(VBR01USER_BMON.COMPANY_NAME) as COMPANY_NAME,
    rtrim(VBR01USER_BMON.BUMON_NAME) as BUMON_NAME
from
    BR01USER inner join VBR01USER_BMON on BR01USER.USER_ID = VBR01USER_BMON.USER_ID
where
    BR01USER.USER_ID = /*uesrId*/'99990003'
