SELECT BM40.CKANRI_NO
,      BM40.MENU_GROUP
,      RTRIM(BM40.MENU_GROUP_NM) AS MENU_GROUP_NM
,      BM40.FIRST_USER
,      BM40.FIRST_PGM
,      BM40.FIRST_TMSP
,      BM40.LAST_USER
,      BM40.LAST_PGM
,      BM40.LAST_TMSP
FROM BM40CMGP BM40
WHERE BM40.CKANRI_NO = /*ckanriNo*/''