SELECT PM06.SHOKU_CD
,      PM06.MST_DT
,      RTRIM(PM06.SHOKU_NAME_KNA) AS SHOKU_NAME_KNA
,      PM06.HACCHU_DT
,      PM06.IRIME1_CD,      PM06.IRIME1,      PM06.IRIME1_TANKA
,      PM06.IRIME2_CD,      PM06.IRIME2,      PM06.IRIME2_TANKA
,      PM06.IRIME3_CD
,      PM06.BUDOMARI_KEISUU
,      PM06.HACCHU_FLG,      PM06.HACCHU_KBN
,      PM06.SHOKU_KBN
,      PM06.SHIIRE_TANKA_FLG
,      PM06.HACCHU_BNR_CD,      RTRIM(PM09.HAC_BNR_NAME_KJ) AS HAC_BNR_NAME_KJ
,      PM06.HAC_TANNI_KBN,      PM06.HAC_HISSU_FLG
,      PM06.KD_RYAK_KNA
,      PM06.SHIYO_FLG
,      PM06.KOBETSU_FLG
,      PM06.SHUSEI_FLG
,      PM06.FIRST_USER,      PM06.FIRST_PGM,      PM06.FIRST_TMSP
,      PM06.LAST_USER,      PM06.LAST_PGM,      PM06.LAST_TMSP

FROM PM06SHOK PM06
,    PM09HCBR PM09
WHERE SHOKU_CD IS NOT NULL
/*IF cdFrom != null */
AND SHOKU_CD >= /*cdFrom*/'000000'
/*END*/
/*IF cdTo != null */
AND SHOKU_CD <=/*cdTo*/'999999'  
/*END*/
/*IF name != null */
AND SHOKU_NAME_KNA  like /*name*/'abc'
/*END*/
/*IF hacchuBnr != null */
AND PM06.HACCHU_BNR_CD = /*hacchuBnr*/''
/*END*/
AND PM09.HACCHU_BNR_CD = PM06.HACCHU_BNR_CD
ORDER BY PM06.HACCHU_BNR_CD
,        SHOKU_CD
