SELECT BM41.CKANRI_NO
,      BM41.MENU_GROUP
,      BM41.MENU_CD
,      RTRIM(PC10.MENU_NAME_KJ) AS MENU_NAME_KJ
,      RTRIM(BM41.SHOKU_CD) AS SHOKU_CD
,      RTRIM(PM06.SHOKU_NAME_KNA) AS SHOKU_NAME_KNA
,      BM41.CONV_VALUE
,      BM41.SUM_GROUP
,      BM41.FIRST_USER
,      BM41.FIRST_PGM
,      BM41.FIRST_TMSP
,      BM41.LAST_USER
,      BM41.LAST_PGM
,      BM41.LAST_TMSP
FROM BM41CMNU BM41
LEFT JOIN PM06SHOK PM06 ON(BM41.SHOKU_CD  = PM06.SHOKU_CD)
,    PC10SMNU PC10
WHERE BM41.CKANRI_NO = /*ckanriNo*/''
AND   BM41.MENU_CD   = PC10.MENU_CD
ORDER BY BM41.CKANRI_NO
,        BM41.MENU_GROUP
,        BM41.SUM_GROUP
,        BM41.SHOKU_CD
,        BM41.MENU_CD