SELECT RTRIM(BR17.ENTRY_YEAR) as ENTRY_YEAR
,      RTRIM(BR17.ENTRY_KAI) as ENTRY_KAI	
,      RTRIM(BR18.FROM_DT) as FROM_DT		
,      RTRIM(BR18.TO_DT) as TO_DT	
FROM   BC10ENTM BC10		
,      BR17ENTL BR17		
,      BR18ENTD BR18		
       JOIN (SELECT ENTRY_CD
                  , ENTRY_YEAR
                  , ENTRY_KAI
               FROM BR18ENTD
              WHERE ENTRY_CD = '10'
              AND USERTYPE_CD = /*userTypeCd*/'01'
              AND DAY_KBN = '05'
              AND FROM_DT <= /*sysDate*/'20060705'
            ) BR18KEKKA
         ON (BR18.ENTRY_CD   = BR18KEKKA.ENTRY_CD   AND
             BR18.ENTRY_YEAR = BR18KEKKA.ENTRY_YEAR AND
             BR18.ENTRY_KAI  = BR18KEKKA.ENTRY_KAI    )
WHERE  BC10.COMPANY_CD = /*companyCd*/'00'
AND    BC10.ENTRY_CD   = '10'		
AND    BR17.ENTRY_CD   = BC10.ENTRY_CD		
AND    BR18.ENTRY_CD   = BR17.ENTRY_CD
AND    BR17.ENTRY_YEAR = BR18.ENTRY_YEAR
AND    BR17.ENTRY_KAI  = BR18.ENTRY_KAI
AND    BR18.USERTYPE_CD = '99'
AND    BR18.DAY_KBN     = '01'
ORDER  BY ENTRY_YEAR DESC
,         ENTRY_KAI  DESC