SELECT TBL.MISE_CD                AS MISE_CD
,      TBL.EIGYO_DT               AS EIGYO_DT
,      TBL.URIAGE                 AS URIAGE
,      TBL.ONER_YOSAN             AS YOSAN
,      TBL.KYAKUSU                AS KYAKUSU
,      TBL.TENKO_KBN              AS TENKO_KBN

,      TBL.ZEN_DOYO_DT            AS ZEN_DOYO_DT
,      CASE WHEN TBL.URIAGE_ZEN_DOYO        IS NULL THEN 0 ELSE TBL.URIAGE_ZEN_DOYO        END AS URIAGE_ZEN_DOYO
,      CASE WHEN TBL.KYAKUSU_ZEN_DOYO       IS NULL THEN 0 ELSE TBL.KYAKUSU_ZEN_DOYO       END AS KYAKUSU_ZEN_DOYO
,      TBL.TENKO_KBN_ZEN_DOYO     AS TENKO_KBN_ZEN_DOYO

,      CASE WHEN TBL.URIAGE_ZEN_DOJITU      IS NULL THEN 0 ELSE TBL.URIAGE_ZEN_DOJITU      END AS URIAGE_ZEN_DOJITU
,      CASE WHEN TBL.KYAKUSU_ZEN_DOJITU     IS NULL THEN 0 ELSE TBL.KYAKUSU_ZEN_DOJITU     END AS KYAKUSU_ZEN_DOJITU

,      CASE WHEN TBL.URIAGE_RUI             IS NULL THEN 0 ELSE TBL.URIAGE_RUI             END AS URIAGE_RUI
,      CASE WHEN TBL.YOSAN_RUI              IS NULL THEN 0 ELSE TBL.YOSAN_RUI              END AS YOSAN_RUI
,      CASE WHEN TBL.KYAKUSU_RUI            IS NULL THEN 0 ELSE TBL.KYAKUSU_RUI            END AS KYAKUSU_RUI
,      CASE WHEN TBL.URIAGE_ZEN_DOJITU_RUI  IS NULL THEN 0 ELSE TBL.URIAGE_ZEN_DOJITU_RUI  END AS URIAGE_ZEN_DOJITU_RUI
,      CASE WHEN TBL.KYAKUSU_ZEN_DOJITU_RUI IS NULL THEN 0 ELSE TBL.KYAKUSU_ZEN_DOJITU_RUI END AS KYAKUSU_ZEN_DOJITU_RUI


,      DECIMAL( CASE WHEN TBL.ONER_YOSAN       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.ONER_YOSAN)*100)+0.05)
                END, 20, 1) AS YOSANHI

,      DECIMAL( CASE WHEN TBL.KYAKUSU          <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.KYAKUSU))+0.5)
                END, 11, 0) AS KYAKUTANKA

,      DECIMAL( CASE WHEN TBL.KYAKUSU_ZEN_DOYO <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE_ZEN_DOYO)/DOUBLE(TBL.KYAKUSU_ZEN_DOYO))+0.5)
                END, 11, 0) AS KYAKUTANKA_ZEN_DOYO

,      DECIMAL( CASE WHEN TBL.KYAKUSU          <= 0 THEN 0.00 
                     WHEN TBL.KYAKUSU_ZEN_DOYO <= 0 THEN 0.00
                     ELSE ((DECIMAL(((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.KYAKUSU))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(TBL.URIAGE_ZEN_DOYO)/DOUBLE(TBL.KYAKUSU_ZEN_DOYO))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS KYAKUTANKA_ZEN_DOYONENHI


,      DECIMAL( CASE WHEN TBL.YOSAN_RUI       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE_RUI)/DOUBLE(TBL.YOSAN_RUI)*100)+0.05)
                END, 20, 1) AS YOSANHI_RUI

,      DECIMAL( CASE WHEN TBL.URIAGE_ZEN_DOJITU_RUI <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE_RUI)/DOUBLE(TBL.URIAGE_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS URIAGE_ZENNENHI_RUI

,      DECIMAL( CASE WHEN TBL.KYAKUSU_ZEN_DOJITU_RUI       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KYAKUSU_RUI)/DOUBLE(TBL.KYAKUSU_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS KYAKUSU_ZENNENHI_RUI

,      CASE WHEN TBL.TENKO_KBN = 1 THEN '°'
            WHEN TBL.TENKO_KBN = 2 THEN '“Ü'
            WHEN TBL.TENKO_KBN = 3 THEN '‰J'
            WHEN TBL.TENKO_KBN = 4 THEN 'á'
            WHEN TBL.TENKO_KBN = 5 THEN '—’'
            ELSE '' END  AS TENKO_KBN_KJ

,      CASE WHEN TBL.TENKO_KBN_ZEN_DOYO = 1 THEN '°'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 2 THEN '“Ü'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 3 THEN '‰J'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 4 THEN 'á'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 5 THEN '—’'
            ELSE '' END  AS TENKO_KBN_ZEN_DOYO_KJ
FROM 
     (
        SELECT BM45.MISE_CD        AS MISE_CD
        ,      MAX(BM45.OPEN_KBN)  OVER(partition by BM45.MISE_CD) AS OPENING_FLG
        ,      BM45.EIGYO_DT       AS EIGYO_DT
        ,      URIAGE              AS URIAGE
        ,      ONER_YOSAN          AS ONER_YOSAN
        ,      KYAKUSU             AS KYAKUSU
        ,      TENKO_KBN           AS TENKO_KBN

        ,      BM45.ZEN_DOYO_DT    AS ZEN_DOYO_DT
        ,      URIAGE_ZEN_DOYO     AS URIAGE_ZEN_DOYO
        ,      KYAKUSU_ZEN_DOYO    AS KYAKUSU_ZEN_DOYO
        ,      TENKO_KBN_ZEN_DOYO  AS TENKO_KBN_ZEN_DOYO

        ,      URIAGE_ZEN_DOJITU   AS URIAGE_ZEN_DOJITU
        ,      KYAKUSU_ZEN_DOJITU  AS KYAKUSU_ZEN_DOJITU

        ,      SUM(URIAGE)             OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS URIAGE_RUI
        ,      SUM(ONER_YOSAN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS YOSAN_RUI
        ,      SUM(KYAKUSU)            OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KYAKUSU_RUI
        ,      SUM(URIAGE_ZEN_DOJITU ) OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS URIAGE_ZEN_DOJITU_RUI
        ,      SUM(KYAKUSU_ZEN_DOJITU) OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KYAKUSU_ZEN_DOJITU_RUI
        FROM BM01TENM BM01
        ,    BM45ZDAY BM45
                LEFT JOIN BT60ZNIP BT60 ON (
                          BM45.COMPANY_CD = BT60.COMPANY_CD 
                    AND   BM45.MISE_CD   = BT60.MISE_CD
                    AND   BM45.EIGYO_DT  = BT60.EIGYO_DT
                    ) 
        WHERE BM01.COMPANY_CD = /*companyCd*/'00'
        AND   BM01.ONER_CD    = /*onerCd*/'36889'
        AND   BM01.COMPANY_CD = BM45.COMPANY_CD
        AND   BM01.MISE_CD    = BM45.MISE_CD
        AND   BM45.OLDM_FLG   = '0'
        AND   SUBSTR(BM45.EIGYO_DT, 1,6)  = /*taishoYM*/'200808' 
    ) AS TBL    
WHERE OPENING_FLG =1  
ORDER BY TBL.MISE_CD,TBL.EIGYO_DT