SELECT
    T.MISE_CD,
    M.MISE_NAME_KJ,
    T.SEIKYU_BNRUI,
    S.SE_BNR_NAME,
    T.URI_KIN,
    T.SOTO_TAX ,
    T.UCHI_TAX ,
    T.STAX_URI
FROM
    BS03USSR T 
  LEFT JOIN TC26SEIK S ON(T.SEIKYU_BNRUI = S.SEIKYU_BNRUI) 
  LEFT JOIN BM01TENM M ON(T.COMPANY_CD=M.COMPANY_CD and T.MISE_CD = M.MISE_CD) 
  LEFT JOIN TM20SHOM F ON(F.SHO_CD_JITU = T.SHO_CD_JITU)
WHERE
      T.COMPANY_CD = /*companyCd*/'00'
  AND T.URIKAKE_CD = /*urikakeCd*/'36870' 
  AND T.SEIKYUSHO_ID = /*seikyushoId*/'2006053101' 
  AND ( T.URI_KIN !=0 OR T.SOTO_TAX != 0 )
ORDER BY
    T.MISE_CD,
    M.MISE_NAME_KJ,
    T.SEIKYU_BNRUI
