SELECT
    BM76.TOUROKU_NO,
	RTRIM(BM76.PLAN_NAME) AS PLAN_NAME,
	BM76.G_RENDO_KEISU,
	BM76.G_POINT_DATE,
	BM77.TOUROKU_SEQ,
	BM77.DATA_VER,
    BM77.NENDO,
    BM77.KB_COMPANY_CD,
    BM77.RANK_CD,
    BM77.KIHON_POINT,
    RTRIM(BM78.KB_COMPANY_NAME) AS KB_COMPANY_NAME,
    RTRIM(BM78.RANK_NAME) AS RANK_NAME,
    BM77.LAST_TMSP

FROM BM76SEID BM76
  INNER JOIN BM77HUYP BM77
    ON (BM76.TOUROKU_NO = BM77.TOUROKU_NO)
  INNER JOIN BM78COMR BM78
    ON (BM77.KB_COMPANY_CD = BM78.KB_COMPANY_CD
      AND BM77.RANK_CD = BM78.RANK_CD)

WHERE BM76.TOUROKU_NO = /*tourokuNo*/'0001'
    AND BM76.SAKUJO_FLG = '0'
    AND BM77.SAKUJO_FLG = '0'

ORDER BY BM77.NENDO, BM78.SORT_NO,BM77.LAST_TMSP