SELECT
	TOUROKU_NO,
	DATA_VER,
	RTRIM(PLAN_NAME) AS PLAN_NAME,
	G_RENDO_KEISU,
	G_POINT_DATE,
	G_RENDO_KEISU_YAKUIN,
	RTRIM(BIKOU) AS BIKOU,
	LAST_TMSP
FROM BM76SEID
WHERE TOUROKU_NO = /*tourokuNo*/
/*IF dataVer != "" && dataVer != null */
	AND DATA_VER =/*dataVer*/
/*END*/
AND SAKUJO_FLG ='0'
ORDER BY DATA_VER DESC
FETCH FIRST 1 ROW ONLY
