SELECT DISTINCT 
    BR18ENTD.ENTRY_CD,
    BR18ENTD.ENTRY_YEAR,
    BR18ENTD.ENTRY_KAI,
    BR18ENTD.USERTYPE_CD,
    BR18ENTD.DAY_KBN,
    BR18ENTD.FROM_DT,
    BR18ENTD.TO_DT,
    BR18ENTD.FIRST_USER,
    BR18ENTD.FIRST_PGM,
    BR18ENTD.FIRST_TMSP,
    BR18ENTD.LAST_USER,
    BR18ENTD.LAST_PGM,
    BR18ENTD.LAST_TMSP
FROM
    BR18ENTD
    INNER JOIN BR17ENTL ON BR17ENTL.ENTRY_CD = BR18ENTD.ENTRY_CD
                        AND BR17ENTL.ENTRY_YEAR = BR18ENTD.ENTRY_YEAR
                        AND BR17ENTL.ENTRY_KAI = BR18ENTD.ENTRY_KAI
WHERE
    BR18ENTD.ENTRY_CD in /*entryCdList*/('05', '30') and
    BR18ENTD.USERTYPE_CD = '99' and
    BR18ENTD.DAY_KBN = '01' and
    substr(BR18ENTD.FROM_DT, 1, 4) >= /*fromYear*/'2005' and
    BR17ENTL.SAKUJO_FLG <>'1'
ORDER BY 
    BR18ENTD.ENTRY_CD, 
    BR18ENTD.ENTRY_YEAR, 
    BR18ENTD.ENTRY_KAI
