select
    BT18.COMPANY_CD,
    BT18.ONER_CD,
    rtrim(BT18.AUTHOR_NAME) as AUTHOR_NAME,
    BT18.AUTH_DT,
    rtrim(BT18.AUTH_PHONE_NUM) as AUTH_PHONE_NUM,
    rtrim(BT18.AUTH_OTHER) as AUTH_OTHER,
    BT18.KESSAN_DT,
    BT18.FIRST_USER,
    BT18.FIRST_PGM,
    BT18.FIRST_TMSP,
    BT18.LAST_USER,
    BT18.LAST_PGM,
    BT18.LAST_TMSP
from
    BT18PLAU as BT18
where
    BT18.COMPANY_CD = '00' and
    BT18.ONER_CD = /*onerCd*/'36005'
