SELECT BD02.URIKAKE_CD
,      RTRIM(BM11.ONER_NAME_KJ) AS ONER_NAME
,      BD02.GEN_ZAN
,      BD02.JUCHU_KIN
,      BD02.HIKI_ZAN
,      BD02.SAKI_JUCHU_KIN
,      BD02.CALC_DATE

FROM   TM11ONER BM11
,      BD02CODZ BD02

WHERE  BD02.URIKAKE_CD = BM11.ONER_CD

ORDER BY BD02.URIKAKE_CD