SELECT DISTINCT
    BR34KLNK.K_LINK_ID,
    BR34KLNK.MENU_NAME,
    BR34KLNK.SUB_MENU_NAME,
    BR34KLNK.SITE_KBN,
    BR34KLNK.URL,
    BR34KLNK.PARAM,
    BR34KLNK.README,
    BR34KLNK.SORT
FROM 
    BR34KLNK
    INNER JOIN BR35KLAC ON BR35KLAC.K_LINK_ID = BR34KLNK.K_LINK_ID  
    INNER JOIN BR04USRL ON BR04USRL.ROLE_CD = BR35KLAC.ROLE_CD
WHERE
    BR04USRL.USER_ID = /*userId*/'99990003' 
AND BR34KLNK.ENABLE_FLG != '' 
ORDER BY BR34KLNK.SORT
    