select
	rtrim(BM24.KEIYAKU_UPDATE) as KEIYAKU_UPDATE,
	BM24.KEIYAKU_YACHIN,
	rtrim(BM24.KEIYAKU_ONER) as KEIYAKU_ONER,
	rtrim(BM24.YACHIN_ZEI_KBN) as YACHIN_ZEI_KBN,
	rtrim(BC22.YACHIN_ZEI_KBN_NAME) as YACHIN_ZEI_KBN_NAME
from
	BM24BUKJ BM24 left outer join BC22YZEI BC22
	on BM24.YACHIN_ZEI_KBN = BC22.YACHIN_ZEI_KBN
where
	BM24.COMPANY_CD = /*companyCd*/'00'
and BM24.MISE_CD = /*miseCd*/'01776'
order by 
	BM24.KEIYAKU_UPDATE DESC