select
	rtrim(BM01.GYOTAI_KBN) as GYOTAI_KBN,
	rtrim(BC09.GYOTAI_KBN_NAME) as GYOTAI_KBN_NAME,
	rtrim(BM25.GYOTAI_KBN_SUB) as GYOTAI_KBN_SUB,
	rtrim(BC20.GYOTAI_KBN_SUB_NAME) as GYOTAI_KBN_SUB_NAME
from BM01TENM BM01
	 LEFT JOIN BM25GTAI BM25 ON (BM25.COMPANY_CD = BM01.COMPANY_CD 
              AND BM25.MISE_CD = BM01.MISE_CD
              AND BM25.GYOTAI_KBN = BM01.GYOTAI_KBN) 
     LEFT JOIN BC09GTAI BC09 on (BC09.GYOTAI_KBN = BM01.GYOTAI_KBN) 
     LEFT JOIN BC20STAI BC20 on (BM25.GYOTAI_KBN = BC20.GYOTAI_KBN and BM25.GYOTAI_KBN_SUB = BC20.GYOTAI_KBN_SUB) 
where
	BM01.COMPANY_CD = /*companyCd*/'60'
and BM01.MISE_CD = /*miseCd*/'02001'
order by 
	BM25.GYOTAI_CHG_DT DESC