select
	rtrim(BM12.STAFF_ID) as STAFF_ID,
	rtrim(BM12.COMPANY_CD) as COMPANY_CD,
	rtrim(BM12.ONER_CD) as ONER_CD,
	rtrim(BM12.MISE_CD_1) as MISE_CD_1,
	rtrim(BM12.STAFF_L_NAME_KJ) as STAFF_L_NAME_KJ,
	rtrim(BM12.STAFF_F_NAME_KJ) as STAFF_F_NAME_KJ,
	rtrim(BM12.STAFF_L_NAME_KNA) as STAFF_L_NAME_KNA,
	rtrim(BM12.STAFF_F_NAME_KNA) as STAFF_F_NAME_KNA,
	rtrim(BM12.SEX) as SEX,
	rtrim(BM12.SITUATION_KBN) as SITUATION_KBN,
	rtrim(BT30.ENTRY_CD) as ENTRY_CD,
	rtrim(BT30.ENTRY_YEAR) as ENTRY_YEAR,
	rtrim(BT30.ENTRY_KAI) as ENTRY_KAI,
	rtrim(BT30.COURSE_STATUS) as COURSE_STATUS,
	rtrim(BT30.COMPLE_COURSE_DT) as COMPLE_COURSE_DT,
	BT30.COMPLE_POINT as COMPLE_POINT,
	rtrim(BT30.COMPLE_COURSE_CD) as COMPLE_COURSE_CD,
	rtrim(BT30.COMPLE_COURSE_NAME) as COMPLE_COURSE_NAME,
	rtrim(BR17.ENTRY_TITLE) as ENTRY_TITLE
from
    BM12STAF BM12,
    BT30ENKJ BT30
      left join BR17ENTL BR17 
        on (BT30.ENTRY_CD = BR17.ENTRY_CD 
            AND BT30.ENTRY_YEAR = BR17.ENTRY_YEAR 
            AND BT30.ENTRY_KAI = BR17.ENTRY_KAI)
where
    BM12.COMPANY_CD = /*companyCd*/'00'
and BM12.MISE_CD_1 = /*miseCd*/'00597'
and BT30.COURSE_STATUS = '1'
and BM12.STAFF_ID= BT30.STAFF_ID
order by 
    BM12.STAFF_ID,BT30.ENTRY_YEAR,BT30.ENTRY_KAI