select
	LTRIM(RTRIM(BT47.ENTRY_CD)) as ENTRY_CD,
	LTRIM(RTRIM(BT47.ENTRY_YEAR)) as ENTRY_YEAR,
	LTRIM(RTRIM(BT47.ENTRY_KAI)) as ENTRY_KAI,
	LTRIM(RTRIM(BT47.COMPANY_CD)) as COMPANY_CD,
	LTRIM(RTRIM(BT47.ONER_CD)) as ONER_CD,
	LTRIM(RTRIM(BT47.ININ_MISE_CD)) as ININ_MISE_CD,
	LTRIM(RTRIM(BT47.ININ_MISE_TOTAL)) as ININ_MISE_TOTAL,
	LTRIM(RTRIM(BT47.ININ_F_NAME)) as ININ_F_NAME,
	LTRIM(RTRIM(BT47.ININ_L_NAME)) as ININ_L_NAME,
	LTRIM(RTRIM(BT47.FIRST_USER)) as FIRST_USER,
	LTRIM(RTRIM(BT47.FIRST_PGM)) as FIRST_PGM,
	BT47.FIRST_TMSP,
	LTRIM(RTRIM(BT47.LAST_USER)) as LAST_USER,
	LTRIM(RTRIM(BT47.LAST_PGM)) as LAST_PGM,
	BT47.LAST_TMSP
from
    BT47ININ as BT47
where 
	BT47.ENTRY_CD = /*entryCd*/'25' and 
	BT47.ENTRY_YEAR = /*entryYear*/'2006' and 
	BT47.ENTRY_KAI = /*entryKai*/'999' and 
	BT47.COMPANY_CD = /*companyCd*/'00' and
	BT47.ONER_CD = /*onerCd*/'36478'