SELECT 
	MISE_CD , CONCAT(MISE_CD || '  ', MISE_NAME_KJ) as MISE_NAME_KJ , MISE_FIRST, SIBU_NAME
FROM
	((SELECT DISTINCT  BM01.MISE_CD
	   , 			BM01.MISE_NAME_KJ
	   ,		    BM11.MISE_FIRST
	   ,            BM10.SIBU_NAME
	   ,            BM01.CLOSE_DT 	   
	FROM    BM01TENM as BM01,
			BM11ONER as BM11,
			BM10GSIB as BM10
	WHERE BM01.ONER_CD = /*onerCd*/'36478' 
	AND BM01.COMPANY_CD = /*companyCd*/'00'
	AND BM01.CLOSE_DT > /*sysDate*/'20060823'
	AND BM01.COMPANY_CD = BM11.COMPANY_CD 
	AND BM01.ONER_CD =  BM11.ONER_CD 
	AND BM01.SIBU_CD = BM10.SIBU_CD
	ORDER BY BM01.MISE_CD)
	UNION ALL
	(SELECT DISTINCT BM01.MISE_CD
	   ,            (RTRIM(BM01.MISE_NAME_KJ) CONCAT '(CLOSE)') AS MISE_NAME_KJ
	   ,		   BM11.MISE_FIRST
	   ,           BM10.SIBU_NAME
	   ,            BM01.CLOSE_DT 		   
	FROM   BM01TENM as BM01,
	       BM11ONER as BM11,
	       BM10GSIB as BM10
	WHERE BM01.ONER_CD = /*onerCd*/'36478' 
	AND BM01.COMPANY_CD = /*companyCd*/'00'
	AND BM01.CLOSE_DT < /*sysDate*/'20060823'
	AND BM01.COMPANY_CD = BM11.COMPANY_CD 
	AND BM01.ONER_CD =  BM11.ONER_CD 
	AND BM01.SIBU_CD = BM10.SIBU_CD
	ORDER BY BM01.MISE_CD)) as TBL
ORDER BY CLOSE_DT DESC, MISE_CD	