SELECT DISTINCT
       BR82.SHU_DT_STA AS HAIS_SIJI_DT
,      MAX(BR56.HAIS_SIJI_SEQ) AS HAIS_SIJI_SEQ
,      BR82.COMPANY_CD
,      BR82.MISE_CD
,      BM01.MISE_NAME_KJ
,      BR82.SHU_DT_STA
,      BR82.SHU_DT_END
,      BR57.HAIS_RSLT_ST

FROM BR82RTSM BR82
LEFT JOIN BR56RTSH BR56 
  ON (BR82.COMPANY_CD = BR56.COMPANY_CD
  AND BR82.SHU_DT_STA = BR56.HAIS_SIJI_DT
  AND BR82.MISE_CD = BR56.MISE_CD)
LEFT JOIN BR57RTST BR57
  ON (BR82.COMPANY_CD = BR57.COMPANY_CD
  AND BR82.SHU_DT_STA = BR57.HAIS_SIJI_DT
  AND BR82.MISE_CD = BR57.MISE_CD)
,    BM01TENM BM01

WHERE BR82.COMPANY_CD = /*companyCd*/'00'
AND   BR82.SHU_DT_END >= /*sysDate*/'20101119'
AND   BR82.COMPANY_CD = BM01.COMPANY_CD
AND   BR82.MISE_CD = BM01.MISE_CD 

GROUP BY BR82.SHU_DT_STA 
,        BR82.COMPANY_CD
,        BR82.MISE_CD
,        BM01.MISE_NAME_KJ
,        BR82.SHU_DT_STA
,        BR82.SHU_DT_END
,        BR57.HAIS_RSLT_ST
ORDER BY
    BR82.SHU_DT_STA,
    BR82.SHU_DT_END,
    BR82.MISE_CD,
    BR57.HAIS_RSLT_ST
    