select 
	   MAX(BD03.CAMP_ID) AS CAMP_ID
,      BN01.EIGYO_DT AS EIGYO_DT
/*IF !hyojiTaisho.equals("ALL") */
,      MAX(BM01.MISE_NAME_KJ) AS MISE_NAME_KJ
,      MAX(CASE WHEN BN01.TENKO_KBN IS NULL THEN 0 ELSE BN01.TENKO_KBN END) AS TENKO_KBN
,      MAX(CASE WHEN BN01.TENKO_KBN_ZEN IS NULL THEN 0 ELSE BN01.TENKO_KBN_ZEN END)  AS TENKO_KBN_ZEN
/*END*/
,      COUNT(DISTINCT (CASE WHEN BN01.OPEN_KBN = 1 THEN BM01.MISE_CD ELSE null END)) TAISHO_TENPO_CNT
,	   SUM(CASE WHEN BD03.KAZU_KEI IS NULL THEN 0 ELSE BD03.KAZU_KEI END) AS KAZU_KEI
,	   SUM(CASE WHEN BD03.MENU_URIAGE IS NULL THEN 0 ELSE BD03.MENU_URIAGE END) AS MENU_URIAGE
,      SUM(CASE WHEN BN01.URIAGE IS NULL THEN 0 ELSE BN01.URIAGE END) AS URIAGE
,      SUM(CASE WHEN BN01.KYAKUSU IS NULL THEN 0 ELSE BN01.KYAKUSU END)  AS KYAKUSU
,      SUM(CASE WHEN BN01.URIAGE_ZEN IS NULL THEN 0 ELSE BN01.URIAGE_ZEN END)   AS URIAGE_ZEN
,      SUM(CASE WHEN BN01.KYAKUSU_ZEN IS NULL THEN 0 ELSE BN01.KYAKUSU_ZEN END)  AS KYAKUSU_ZEN
/*IF zenDataShubetu.equals("DOGETUHOSEI") */
,      SUM(CASE WHEN BN01.URIAGE_NET IS NULL THEN 0 ELSE BN01.URIAGE_NET END) AS URIAGE_NET
,      SUM(CASE WHEN BN01.KYAKUSU_NET IS NULL THEN 0 ELSE BN01.KYAKUSU_NET END)  AS KYAKUSU_NET

,      SUM(CASE WHEN BN01.URIAGE_ZEN_NET IS NULL THEN 0 ELSE BN01.URIAGE_ZEN_NET END)   AS URIAGE_ZEN_NET
,      SUM(CASE WHEN BN01.KYAKUSU_ZEN_NET IS NULL THEN 0 ELSE BN01.KYAKUSU_ZEN_NET END)  AS KYAKUSU_ZEN_NET
/*END*/
FROM 
( 
      SELECT SUBBM01.COMPANY_CD
      ,      SUBBM01.SIBU_CD 
      ,      SUBBM01.MISE_CD
      ,      SUBBM01.ONER_CD
      ,      SUBBM01.MISE_NAME_KJ
      FROM BM01TENM SUBBM01
      ,    BM10GSIB BM10
      WHERE SUBBM01.COMPANY_CD = /*companyCd*/'00'
/*IF !hyojiTaisho.equals("ALL") */
      AND   SUBBM01.MISE_CD = /*hyojiTaisho*/'02001'
/*END*/
/*IF hyojiTaisho.equals("ALL") */
      AND   SUBBM01.ONER_CD = /*onerCd*/'36478'
/*END*/
      AND    BM10.COMPANY_CD  = SUBBM01.COMPANY_CD
      AND    BM10.SIBU_CD     = SUBBM01.SIBU_CD
      GROUP BY SUBBM01.COMPANY_CD
      ,        SUBBM01.SIBU_CD 
      ,        SUBBM01.MISE_CD
      ,        SUBBM01.ONER_CD
      ,        SUBBM01.MISE_NAME_KJ
) BM01
,(
       SELECT DISTINCT
                BN01.EIGYO_DT
         ,      BN01.MISE_CD
         ,      BT60.OPEN_KBN
         ,      BT60.URIAGE
         ,      BT60.KYAKUSU
         ,      BT60.TENKO_KBN
/*IF zenDataShubetu.equals("DOGETU") */
         ,      BT60.URIAGE_ZEN_DOGETU     AS URIAGE_ZEN
         ,      BT60.TENKO_KBN_ZEN_DOGETU  AS TENKO_KBN_ZEN
         ,      BT60.KYAKUSU_ZEN_DOGETU    AS KYAKUSU_ZEN
/*END*/
/*IF zenDataShubetu.equals("DOJITU") */
         ,      BT60.URIAGE_ZEN_DOJITU     AS URIAGE_ZEN
         ,      BT60.TENKO_KBN_ZEN_DOJITU  AS TENKO_KBN_ZEN
         ,      BT60.KYAKUSU_ZEN_DOJITU    AS KYAKUSU_ZEN
/*END*/
/*IF zenDataShubetu.equals("DOYO") */
         ,      BT60.URIAGE_ZEN_DOYO     AS URIAGE_ZEN
         ,      BT60.TENKO_KBN_ZEN_DOYO  AS TENKO_KBN_ZEN
         ,      BT60.KYAKUSU_ZEN_DOYO    AS KYAKUSU_ZEN
/*END*/
/*IF zenDataShubetu.equals("DOGETUHOSEI") */
         ,      BT60.URIAGE_ZEN_DOGETU     AS URIAGE_ZEN
         ,      BT60.TENKO_KBN_ZEN_DOGETU  AS TENKO_KBN_ZEN
         ,      BT60.KYAKUSU_ZEN_DOGETU    AS KYAKUSU_ZEN
         ,      (CASE WHEN BT60.OPEN_KBN =1 AND BT60.OPEN_KBN_ZEN_DOGETU = 1 AND BT60.URIAGE_ZEN_DOGETU > 0
                      THEN BT60.URIAGE ELSE 0 END) AS URIAGE_NET
         ,      (CASE WHEN BT60.OPEN_KBN =1 AND BT60.OPEN_KBN_ZEN_DOGETU = 1 AND BT60.URIAGE_ZEN_DOGETU > 0
                      THEN BT60.EIGYO_DAYS ELSE 0 END) AS KYAKUSU_NET
         ,      (CASE WHEN BT60.OPEN_KBN =1 AND BT60.OPEN_KBN_ZEN_DOGETU = 1 AND BT60.URIAGE > 0
                      THEN BT60.URIAGE_ZEN_DOGETU ELSE 0 END)  AS URIAGE_ZEN_NET
         ,      (CASE WHEN BT60.OPEN_KBN =1 AND BT60.OPEN_KBN_ZEN_DOGETU = 1 AND BT60.URIAGE > 0
                      THEN BT60.KYAKUSU_ZEN_DOGETU ELSE 0 END) AS KYAKUSU_ZEN_NET
/*END*/
       FROM BN01DTEN BN01
       ,    BT60ZNIP BT60 
       ,    BM65CPMS BM65
       WHERE  BN01.EIGYO_DT BETWEEN /*kikanFrom*/'20080301' AND /*kikanTo*/'20080331'
       AND    BN01.EIGYO_DT < /*sysDate*/'20080421'
       AND   BN01.COMPANY_CD = /*companyCd*/'00'
/*IF !hyojiTaisho.equals("ALL") */  
       AND   BN01.MISE_CD = /*hyojiTaisho*/'02001'
/*END*/
       AND   BN01.COMPANY_CD = BT60.COMPANY_CD
       AND   BN01.EIGYO_DT   = BT60.EIGYO_DT
       AND   BN01.MISE_CD    = BT60.MISE_CD
       AND   BT60.OLDM_FLG <> '1'
       AND   OPEN_KBN = 1
       AND   BM65.CAMP_ID = /*campId*/'200806'
       AND   BM65.COMPANY_CD = BN01.COMPANY_CD
       AND   BM65.MISE_CD = BN01.MISE_CD
) BN01
LEFT OUTER JOIN
(
         SELECT BM61.CAMP_ID
         ,		BD03.MENU_DT 
         ,      BD03.MISE_CD
         ,      SUM(BD03.URIAGE) AS MENU_URIAGE
/*IF totaledKbn == "TANPIN" */
         ,      SUM(BD03.KAZU_KEI) AS KAZU_KEI
/*END*/
/*IF (totaledKbn == "SHUYAKU" || totaledKbn == "TOTAL")*/
		 ,      SUM(BD03.KAZU_KEI * (case when bm62.conv_value is null then 1 else bm62.conv_value end)) AS KAZU_KEI
/*END*/
         FROM BD03CPML BD03
         ,    BM65CPMS BM65
         ,    BM61CPMN BM61
/*IF totaledKbn.equals("SHUYAKU") || totaledKbn.equals("TOTAL")*/
		 left outer join BM62SYMM BM62 on (BM61.MENU_CD = BM62.MENU_CD) 
/*END*/
         WHERE BD03.COMPANY_CD = /*companyCd*/'00'
         AND   BD03.MENU_DT >=/*kikanFrom*/'20080301' 
         AND   BD03.MENU_DT <=/*kikanTo*/'20080331'
         AND   BD03.MENU_DT < /*sysDate*/'20080421'
/*IF !hyojiTaisho.equals("ALL") */  
         AND   BD03.MISE_CD = /*hyojiTaisho*/'02001'
/*END*/
/*IF totaledKbn.equals("TANPIN") */
		 AND   BD03.MENU_CD = /*menuCd*/'220001'
/*END*/
         AND   BM61.CAMP_ID = /*campId*/'200806'
         AND   BM61.MENU_CD = BD03.MENU_CD
         AND   BD03.MISE_CD = BM65.MISE_CD
         AND   BM65.CAMP_ID = BM61.CAMP_ID
         AND   BM65.COMPANY_CD = BD03.COMPANY_CD
/*IF totaledKbn.equals("SHUYAKU")*/
		 AND   (case when bm62.sum_menu_cd is null then bm61.menu_cd else bm62.sum_menu_cd end) = /*menuCd*/'220001'
/*END*/
         GROUP BY BM61.CAMP_ID
         ,        BD03.MENU_DT
         ,        BD03.MISE_CD
) BD03 ON (BN01.EIGYO_DT = BD03.MENU_DT AND BN01.MISE_CD = BD03.MISE_CD)
WHERE BN01.MISE_CD  = BM01.MISE_CD
GROUP BY ROLLUP (BN01.EIGYO_DT)
ORDER BY BN01.EIGYO_DT