SELECT RTRIM(BM03.USER_ID) as USER_ID
,      RTRIM(BC02.R_COMPANY_CD) as R_COMPANY_CD
,      RTRIM(CASE WHEN BC02.R_COMPANY_CD = BC05.COMPANY_CD THEN BC05.COMPANY_NAME ELSE BC02.COMPANY_NAME END) as R_COMPANY_NAME
,	   BM03.ZOKUSEI_KBN
,      RTRIM(BM03.FIRST_USER) as FIRST_USER
,      RTRIM(BM03.FIRST_PGM) as FIRST_PGM
,      BM03.FIRST_TMSP
,      RTRIM(BM03.LAST_USER) as LAST_USER
,      RTRIM(BM03.LAST_PGM) as LAST_PGM
,      BM03.LAST_TMSP
,      CASE WHEN BM03.ZOKUSEI_KBN = '0' THEN '999'
            ELSE BM03.ZOKUSEI_KBN END ZOKUSEI_SEQ
,      BC05.COMPANY_CD
,      BC05.COMPANY_NAME

FROM      BC02COMP BC02
LEFT JOIN BM03USCP BM03
   ON (BM03.USER_ID = /*userId*/'99990002'
       AND  BM03.R_COMPANY_CD = BC02.R_COMPANY_CD)
,     BC05KCOM BC05
,     BC06COMM BC06

WHERE BC06.R_COMPANY_CD = BC02.R_COMPANY_CD
AND   BC06.COMPANY_CD   = BC05.COMPANY_CD
/*IF miseFlg == true */
AND     BC02.MISE_FLG = '1'
/*END*/
/*IF  isForeignIn==false */
AND   BC05.FOREIGN_FLG <> '1'
/*END*/

ORDER BY BC02.SORT_SEQ
,        R_COMPANY_CD
,        ZOKUSEI_SEQ	