SELECT BR17.ENTRY_CD
,      BR17.ENTRY_YEAR
,      BR17.ENTRY_KAI
,      ENTRY.FROM_DT AS KAISAI_DT
,      BR17.ENTRY_TITLE AS ENTRY_TITLE
,      HONBU.FROM_DT AS HONBU_FROM_DT
,      HONBU.TO_DT AS HONBU_TO_DT
,      ONER.FROM_DT AS ONER_FROM_DT
,      ONER.TO_DT AS ONER_TO_DT
,      DECIMAL(CASE WHEN BT46.J_ATTEND_CNT IS NULL THEN 0 ELSE BT46.J_ATTEND_CNT END, 6,0) AS J_ATTEND_CNT
,      DECIMAL(CASE WHEN BT46.J_ABSENT_CNT IS NULL THEN 0 ELSE BT46.J_ABSENT_CNT END, 6,0) AS J_ABSENT_CNT
,      DECIMAL(CASE WHEN BT46.KON_ATTEND_CNT IS NULL THEN 0 ELSE BT46.KON_ATTEND_CNT END, 6,0) AS KON_ATTEND_CNT
,      DECIMAL(CASE WHEN BT46.KON_ABSENT_CNT IS NULL THEN 0 ELSE BT46.KON_ABSENT_CNT END, 6,0) AS KON_ABSENT_CNT
,      DECIMAL(CASE WHEN BT46.KYO_ATTEND_CNT IS NULL THEN 0 ELSE BT46.KYO_ATTEND_CNT END, 6,0) AS KYO_ATTEND_CNT
,      DECIMAL(CASE WHEN BT46.KYO_ABSENT_CNT IS NULL THEN 0 ELSE BT46.KYO_ABSENT_CNT END, 6,0) AS KYO_ABSENT_CNT

FROM BR17ENTL BR17
     
JOIN (SELECT * FROM BR18ENTD WHERE USERTYPE_CD = '99' AND DAY_KBN = '01') ENTRY
  ON (ENTRY.ENTRY_CD = BR17.ENTRY_CD AND ENTRY.ENTRY_YEAR = BR17.ENTRY_YEAR AND ENTRY.ENTRY_KAI = BR17.ENTRY_KAI)

JOIN (SELECT * FROM BR18ENTD WHERE USERTYPE_CD = '01' AND DAY_KBN = '04') HONBU
  ON (HONBU.ENTRY_CD = BR17.ENTRY_CD AND HONBU.ENTRY_YEAR = BR17.ENTRY_YEAR AND HONBU.ENTRY_KAI = BR17.ENTRY_KAI)

JOIN (SELECT * FROM BR18ENTD WHERE USERTYPE_CD = '02' AND DAY_KBN = '04') ONER
  ON (ONER.ENTRY_CD = BR17.ENTRY_CD AND ONER.ENTRY_YEAR = BR17.ENTRY_YEAR AND ONER.ENTRY_KAI = BR17.ENTRY_KAI)

LEFT JOIN (
          SELECT BT46.ENTRY_CD
          ,      BT46.ENTRY_YEAR
          ,      BT46.ENTRY_KAI
          ,      SUM(CASE WHEN JIGYO_FLG = '0' THEN 1 ELSE 0 END) AS J_ATTEND_CNT
          ,      SUM(CASE WHEN JIGYO_FLG = '1' THEN 1 ELSE 0 END) AS J_ABSENT_CNT
          ,      SUM(CASE WHEN KONSHIN_FLG = '0' THEN 1 ELSE 0 END) AS KON_ATTEND_CNT
          ,      SUM(CASE WHEN KONSHIN_FLG = '1' THEN 1 ELSE 0 END) AS KON_ABSENT_CNT
          ,      SUM(CASE WHEN KYOEI_FLG = '0' THEN 1 ELSE 0 END) AS KYO_ATTEND_CNT
          ,      SUM(CASE WHEN KYOEI_FLG = '1' THEN 1 ELSE 0 END) AS KYO_ABSENT_CNT
          FROM BT46KENS BT46
          ,    BT21ENOJ BT21
          ,    (SELECT MISE.SIBU_CD
                  ,      MISE.ONER_CD 
                  FROM BM11ONER ONER
                  ,    BM01TENM MISE
                  WHERE ONER.COMPANY_CD   = /*companyCd*/'00'
                  AND   ONER.ONER_CD     != '39999' 
                  AND   ONER.KEIYAKU_STA <= /*sysDate*/'20061213'
                  AND   ONER.KEIYAKU_END >= /*sysDate*/'20061213'
                  AND   MISE.COMPANY_CD   = ONER.COMPANY_CD
                  AND   MISE.ONER_CD   = ONER.ONER_CD
                  GROUP BY MISE.SIBU_CD
                  ,        MISE.ONER_CD 
               ) BM11
          ,    BM01TENM BM01

          WHERE BM01.COMPANY_CD   = /*companyCd*/'00'
          AND   BT46.ENTRY_CD     = /*entryCd*/'25'
          AND   BT46.ENTRY_YEAR   = /*entryYear*/'2005'
          AND   BT46.ENTRY_KAI    = /*entryKai*/'001'
          AND   BT21.ENTRY_CD     = BT46.ENTRY_CD 
          AND   BT21.ENTRY_YEAR   = BT46.ENTRY_YEAR
          AND   BT21.ENTRY_KAI    = BT46.ENTRY_KAI
          AND   BT46.COMPANY_CD   = BM01.COMPANY_CD 
          AND   BT21.COMPANY_CD   = BT46.COMPANY_CD 
          AND   BT46.ONER_CD      = BM11.ONER_CD
          AND   BT21.ONER_CD      = BT46.ONER_CD
          AND   BT21.ATESAKI_KBN  = '00'
          AND   BM01.SIBU_CD      = BM11.SIBU_CD
          AND   BT46.MISE_CD      = BM01.MISE_CD
          GROUP BY BT46.ENTRY_CD
          ,        BT46.ENTRY_YEAR
          ,        BT46.ENTRY_KAI
          ) BT46
  ON (BT46.ENTRY_CD = BR17.ENTRY_CD AND BT46.ENTRY_YEAR = BR17.ENTRY_YEAR AND BT46.ENTRY_KAI = BR17.ENTRY_KAI)

WHERE SAKUJO_FLG <> '1'
  and BR17.ENTRY_CD = /*entryCd*/'25'
  and BR17.ENTRY_YEAR = /*entryYear*/'2006'
  and BR17.ENTRY_KAI = /*entryKai*/'012'