SELECT  BT32.STAFF_ID as STAFF_ID
  ,     BT32.TOTAL_LAST_YEAR as TOTAL_LAST_YEAR
  ,     BT32.TOTAL_LAST_KAI as TOTAL_LAST_KAI
  ,     BT32.LICENSE_KBN as LICENSE_KBN
FROM    BT32MLKR as BT32
WHERE   BT32.EXAM_NO = /*examNo*/'03044' AND
        CONCAT(BT32.TOTAL_LAST_YEAR, bt32.TOTAL_LAST_KAI) = (
        SELECT MAX(CONCAT(TOTAL_LAST_YEAR, TOTAL_LAST_KAI))
        FROM   BT32MLKR 
        WHERE  TOTAL_LAST_YEAR  in (/*entryYear*/'2006',/*lastYear*/'2005')
        AND EXAM_NO = /*examNo*/'03044')