SELECT
    BM11ONER.COMPANY_CD,
    BM11ONER.ONER_CD,
    BM11ONER.ONER_NAME_KJ,
    BM11ONER.ONER_NAME_KNA
FROM
    BM11ONER 
WHERE
    BM11ONER.COMPANY_CD = '00'
AND BM11ONER.ONER_CD = /*ONER_CD*/'00000'
       