SELECT DISTINCT
    BM06UONR.USER_ID,
    BM06UONR.COMPANY_CD,
    BM06UONR.ONER_CD,
    BM11ONER.ONER_NAME_KJ
FROM 
    BM06UONR
    INNER JOIN BM11ONER ON BM06UONR.COMPANY_CD = BM11ONER.COMPANY_CD
                        AND BM06UONR.ONER_CD = BM11ONER.ONER_CD
WHERE
    BM06UONR.USER_ID = /*USER_ID*/'99990003'
AND BM06UONR.COMPANY_CD = '00'
