select
    BT17.PL_TYPE,
    BT17.PL_YM,
    BT17.COMPANY_CD,
    BT17.ONER_CD,
    BT17.MISE_CD,
    BT17.URIAGEDAKA,
    BT17.URIAGEGENKA,
    BT17.URIAGE_SO_RIEKI,
    BT17.SALARY,
    BT17.YACHIN,
    BT17.SUIKOU_HI,
    BT17.ROYALTY,
    BT17.TESURYO,
    BT17.KOUKOKU,
    BT17.SHOUMOU,
    BT17.HOUTEI_FUKURI,
    BT17.FUKURI_KOUSEI,
    BT17.KOUSAI,
    BT17.RYOHI,
    BT17.TUSIN,
    BT17.LEASE,
    BT17.SHARYO,
    BT17.SOZEI,
    BT17.HOKEN,
    BT17.UNCHIN,
    BT17.SHUZEN,
    BT17.YOBI,
    BT17.ZAPPI,
    BT17.KEIHI_SHOKEI,
    BT17.SHOKYAKU_RIEKI,
    BT17.GENKA_SHOKYAKU,
    BT17.EIGAI_SHUEKI,
    BT17.EIGAI_HIYO,
    BT17.HONSHAHI_HAI,
    BT17.RIEKI,
    BT17.URIAGE,
    BT17.BUPPAN,
    BT17.URI_UCHIWAKE,
    BT17.ELEC,
    BT17.GAS,
    BT17.WATER,
    BT17.SONOTA,
    BT17.SUIKOU_UCHIWAKE,
    BT17.GENZAIRYO_KEI,
    BT17.GENZAIRYO_SHIRE,
    BT17.GENZAIRYO_ZAIKO,
    BT17.YASAI_KEI,
    BT17.YASAI_SHIRE,
    BT17.YASAI_ZAIKO,
    BT17.HOUZAI_KEI,
    BT17.HOUZAI_SHIRE,
    BT17.HOUZAI_ZAIKO,
    BT17.BUPPAN_KEI,
    BT17.BUPPAN_SHIRE,
    BT17.BUPPAN_ZAIKO,
    BT17.TOU_SIIRE_KEI,
    BT17.TOU_ZAIKO_KEI,
    BT17.SASHIHIKI_KEI,
    BT17.YAKUIN_SALARY,
    BT17.YAKUIN_BONUS,
    BT17.YAKUIN_RETIRE,
    BT17.YAKUIN_KEI,
    BT17.SALARY_SALARY,
    BT17.SALARY_BONUS,
    BT17.SALARY_RETIRE,
    BT17.SALARY_KEI,
    BT17.ZAKKYU_SALARY,
    BT17.ZAKKYU_BONUS,
    BT17.ZAKKYU_RETIRE,
    BT17.ZAKKYU_KEI,
    BT17.KYURYO_KEI,
    BT17.BONUS_KEI,
    BT17.RETIRE_KEI,
    BT17.SALARY_UTI_KEI,
    BT17.KASHIIRE_UP,
    BT17.KASHIIRE_DOWN,
    BT17.KASHIIRE_ZANDAKA,
    BT17.KAPPU_UP,
    BT17.KAPPU_DOWN,
    BT17.KAPPU_ZANDAKA,
    BT17.LEASE_UP,
    BT17.LEASE_DOWN,
    BT17.LEASE_ZANDAKA,
    BT17.TOU_ZOUKA_KEI,
    BT17.TOU_GENSHO_KEI,
    BT17.TOU_ZANDAKA_KEI,
    rtrim(BT17.MEMO) as MEMO,
    BT17.LAST_DT,
    BT17.AUTHOR_NAME,
    BT17.AUTH_DT,
    BT17.AUTH_PHONE_NUM,
    BT17.AUTH_OTHER,
    BT17.ERR_FLG,
    BT17.FIRST_USER,
    BT17.FIRST_PGM,
    BT17.FIRST_TMSP,
    BT17.LAST_USER,
    BT17.LAST_PGM,
    BT17.LAST_TMSP,
    rtrim(
    case
    when BT17.PL_TYPE = '0' then
        (select
            BM11.ONER_NAME_KJ
        from
            BM11ONER as BM11
        where
            BM11.COMPANY_CD = BT17.COMPANY_CD and
            BM11.ONER_CD = BT17.MISE_CD)
    when BT17.PL_TYPE = '1' then
        (select
            BM01.MISE_NAME_KJ
        from
            BM01TENM as BM01
        where
            BM01.COMPANY_CD = BT17.COMPANY_CD and
            BM01.MISE_CD = BT17.MISE_CD)
    else
        null
    end) as MISE_NAME_KJ
from
    BT17PLDT as BT17
    left outer join BM01TENM as BM01 on BM01.COMPANY_CD = BT17.COMPANY_CD and BM01.MISE_CD = BT17.MISE_CD
where
    BT17.PL_YM = /*plYm*/'200601' and
    BT17.COMPANY_CD = '00' and
    BT17.ONER_CD = /*onerCd*/'36961'
/*IF !closeMiseFlg */
    and (BT17.PL_TYPE = '0' OR BM01.CLOSE_DT >= /*plYm*/'200605') 
/*END*/
order by
    BT17.PL_TYPE,
    BT17.MISE_CD,
    BT17.ERR_FLG
