SELECT DISTINCT
	BM11ONER.ONER_NAME_KJ,
    (CASE
        WHEN BT17PLDT.PL_TYPE = '0' THEN
            (SELECT
                ONER_NAME_KJ
            FROM
                BM11ONER
            WHERE
                ONER_CD = BT17PLDT.MISE_CD
            AND COMPANY_CD = BT17PLDT.COMPANY_CD)
        WHEN BT17PLDT.PL_TYPE = '1' THEN
            (SELECT
                MISE_NAME_KJ
            FROM
                BM01TENM
            WHERE
                MISE_CD = BT17PLDT.MISE_CD
            AND COMPANY_CD = BT17PLDT.COMPANY_CD)
        ELSE
            NULL
    END) AS MISE_NAME_KJ,
	BT17PLDT.PL_TYPE,
	BT17PLDT.PL_YM,
	BT17PLDT.COMPANY_CD,
	BT17PLDT.ONER_CD,
	BT17PLDT.MISE_CD,
	BT17PLDT.URIAGEDAKA,
	BT17PLDT.URIAGEGENKA,
	BT17PLDT.URIAGE_SO_RIEKI,
	BT17PLDT.SALARY,
	BT17PLDT.YACHIN,
	BT17PLDT.SUIKOU_HI,
	BT17PLDT.ROYALTY,
	BT17PLDT.TESURYO,
	BT17PLDT.KOUKOKU,
	BT17PLDT.SHOUMOU,
	BT17PLDT.HOUTEI_FUKURI,
	BT17PLDT.FUKURI_KOUSEI,
	BT17PLDT.KOUSAI,
	BT17PLDT.RYOHI,
	BT17PLDT.TUSIN,
	BT17PLDT.LEASE,
	BT17PLDT.SHARYO,
	BT17PLDT.SOZEI,
	BT17PLDT.HOKEN,
	BT17PLDT.UNCHIN,
	BT17PLDT.SHUZEN,
	BT17PLDT.YOBI,
	BT17PLDT.ZAPPI,
	BT17PLDT.KEIHI_SHOKEI,
	BT17PLDT.SHOKYAKU_RIEKI,
	BT17PLDT.GENKA_SHOKYAKU,
	BT17PLDT.EIGAI_SHUEKI,
	BT17PLDT.EIGAI_HIYO,
	BT17PLDT.HONSHAHI_HAI,
	BT17PLDT.RIEKI,
	BT17PLDT.URIAGE,
	BT17PLDT.BUPPAN,
	BT17PLDT.URI_UCHIWAKE,
	BT17PLDT.ELEC,
	BT17PLDT.GAS,
	BT17PLDT.WATER,
	BT17PLDT.SONOTA,
	BT17PLDT.SUIKOU_UCHIWAKE,
	BT17PLDT.GENZAIRYO_KEI,
	BT17PLDT.GENZAIRYO_SHIRE,
	BT17PLDT.GENZAIRYO_ZAIKO,
	BT17PLDT.YASAI_KEI,
	BT17PLDT.YASAI_SHIRE,
	BT17PLDT.YASAI_ZAIKO,
	BT17PLDT.HOUZAI_KEI,
	BT17PLDT.HOUZAI_SHIRE,
	BT17PLDT.HOUZAI_ZAIKO,
	BT17PLDT.BUPPAN_KEI,
	BT17PLDT.BUPPAN_SHIRE,
	BT17PLDT.BUPPAN_ZAIKO,
	BT17PLDT.TOU_SIIRE_KEI,
	BT17PLDT.TOU_ZAIKO_KEI,
	BT17PLDT.SASHIHIKI_KEI,
	BT17PLDT.YAKUIN_SALARY,
	BT17PLDT.YAKUIN_BONUS,
	BT17PLDT.YAKUIN_RETIRE,
	BT17PLDT.YAKUIN_KEI,
	BT17PLDT.SALARY_SALARY,
	BT17PLDT.SALARY_BONUS,
	BT17PLDT.SALARY_RETIRE,
	BT17PLDT.SALARY_KEI,
	BT17PLDT.ZAKKYU_SALARY,
	BT17PLDT.ZAKKYU_BONUS,
	BT17PLDT.ZAKKYU_RETIRE,
	BT17PLDT.ZAKKYU_KEI,
	BT17PLDT.KYURYO_KEI,
	BT17PLDT.BONUS_KEI,
	BT17PLDT.RETIRE_KEI,
	BT17PLDT.SALARY_UTI_KEI,
	BT17PLDT.KASHIIRE_UP,
	BT17PLDT.KASHIIRE_DOWN,
	BT17PLDT.KASHIIRE_ZANDAKA,
	BT17PLDT.KAPPU_UP,
	BT17PLDT.KAPPU_DOWN,
	BT17PLDT.KAPPU_ZANDAKA,
	BT17PLDT.LEASE_UP,
	BT17PLDT.LEASE_DOWN,
	BT17PLDT.LEASE_ZANDAKA,
	BT17PLDT.TOU_ZOUKA_KEI,
	BT17PLDT.TOU_GENSHO_KEI,
	BT17PLDT.TOU_ZANDAKA_KEI,
	RTRIM(BT17PLDT.MEMO) AS MEMO,
	BT17PLDT.LAST_DT,
	BT17PLDT.AUTHOR_NAME,
	BT17PLDT.AUTH_DT,
	BT17PLDT.AUTH_PHONE_NUM,
	BT17PLDT.AUTH_OTHER,
	BT17PLDT.FIRST_USER,
	BT17PLDT.FIRST_PGM,
	BT17PLDT.FIRST_TMSP,
	BT17PLDT.LAST_USER,
	BT17PLDT.LAST_PGM,
	BT17PLDT.LAST_TMSP
FROM
	BT17PLDT
	INNER JOIN BM01TENM ON BT17PLDT.COMPANY_CD = BM01TENM.COMPANY_CD
	INNER JOIN BM11ONER ON BT17PLDT.COMPANY_CD = BM11ONER.COMPANY_CD
WHERE
	BT17PLDT.COMPANY_CD = '00'
AND BT17PLDT.MISE_CD = /*MISE_CD*/'00000'
AND BT17PLDT.PL_YM = /*PL_YM*/'200602'
AND BT17PLDT.PL_TYPE = /*PL_TYPE*/'0'
