SELECT 
    RTRIM(AUTHOR_NAME) AS AUTHOR_NAME,
    RTRIM(AUTH_DT) AS AUTH_DT,
    RTRIM(AUTH_PHONE_NUM) AS AUTH_PHONE_NUM,
    RTRIM(AUTH_OTHER) AS AUTH_OTHER,
    LAST_USER,
    LAST_PGM,
    LAST_TMSP,
    RTRIM(KESSAN_DT) AS KESSAN_DT
FROM 
    BT18PLAU
WHERE
    COMPANY_CD = '00'
AND ONER_CD = /*ONER_CD*/'00000'
