SELECT DISTINCT
    BT17PLDT.GENZAIRYO_ZAIKO,
    BT17PLDT.YASAI_ZAIKO,
    BT17PLDT.HOUZAI_ZAIKO,
    BT17PLDT.BUPPAN_ZAIKO,
    BT17PLDT.KASHIIRE_ZANDAKA,
    BT17PLDT.KAPPU_ZANDAKA,
    BT17PLDT.LEASE_ZANDAKA,
    BT17PLDT.TOU_ZAIKO_KEI,
    BT17PLDT.TOU_ZANDAKA_KEI
FROM
    BT17PLDT
	INNER JOIN BM01TENM ON BT17PLDT.COMPANY_CD = BM01TENM.COMPANY_CD
	INNER JOIN BM11ONER ON BT17PLDT.COMPANY_CD = BM11ONER.COMPANY_CD
WHERE
	BT17PLDT.COMPANY_CD = '00'
AND BT17PLDT.MISE_CD = /*MISE_CD*/'00000'
AND BT17PLDT.PL_YM = /*PL_YM*/'200602'
AND BT17PLDT.PL_TYPE = /*PL_TYPE*/'0'
