SELECT
	BM76.TOUROKU_NO,
	BM76.DATA_VER,
	RTRIM(BM76.PLAN_NAME) AS PLAN_NAME,
	BM76.G_RENDO_KEISU,
	BM76.G_RENDO_KEISU_YAKUIN,
	BM76.G_POINT_DATE,
      MIN(BM77.NENDO) AS startNendo,
      MAX(BM77.NENDO) AS endNendo
FROM
	BM76SEID BM76
  INNER JOIN BM77HUYP BM77
    ON (BM76.TOUROKU_NO = BM77.TOUROKU_NO)

WHERE
    BM76.SAKUJO_FLG = '0'
    AND BM77.SAKUJO_FLG = '0'

GROUP BY BM76.TOUROKU_NO,
    BM76.DATA_VER,
    BM76.PLAN_NAME,
    BM76.G_RENDO_KEISU,
    BM76.G_RENDO_KEISU_YAKUIN,
    BM76.G_POINT_DATE

ORDER BY BM76.TOUROKU_NO DESC