SELECT DISTINCT
       ONERDATA.SIBU_CD
,      ONERDATA.SIBU_NAME
,      ONERDATA.ONER_CD
,      ONERDATA.ONER_NAME_KJ
,      STAFFDATA.SEQ_NO
,      STAFFDATA.MISE_CD
,      STAFFDATA.MISE_NAME_KJ
,      ONERDATA.NAME
,      ONERDATA.TEL
,      STAFFDATA.L_NAME_KJ
,      STAFFDATA.F_NAME_KJ
,      STAFFDATA.L_NAME_kna
,      STAFFDATA.F_NAME_kna
,      STAFFDATA.SEX
,      STAFFDATA.BIRTHDAY
,      STAFFDATA.AGE
,      STAFFDATA.JOB_TYPE AS JOB_TYPE
,      STAFFDATA.PROPOSE_KBN
,      STAFFDATA.PROPOSE_NAME
,      STAFFDATA.OPTIONAL1
,      STAFFDATA.OPTIONAL2
,      STAFFDATA.OPTIONAL3
,      STAFFDATA.OPTIONAL4
,      STAFFDATA.OPTIONAL5
,      STAFFDATA.OPTIONAL6
,      STAFFDATA.OPTIONAL7
,      STAFFDATA.OPTIONAL8
,      STAFFDATA.OPTIONAL9
,      STAFFDATA.OPTIONAL10
,      STAFFDATA.OPTIONAL11
,      STAFFDATA.OPTIONAL12
,      STAFFDATA.OPTIONAL13
,      STAFFDATA.OPTIONAL14
,      STAFFDATA.OPTIONAL15
,      STAFFDATA.OPTIONAL16
,      STAFFDATA.OPTIONAL21
,      STAFFDATA.OPTIONAL22
,      STAFFDATA.OPTIONAL23
,      STAFFDATA.OPTIONAL24
,      STAFFDATA.OPTIONAL25
,      STAFFDATA.OPTIONAL26
,      STAFFDATA.OPTIONAL27
,      STAFFDATA.OPTIONAL28
,      STAFFDATA.OPTIONAL29
,      STAFFDATA.OPTIONAL30
,      STAFFDATA.NOTE1
,      STAFFDATA.NOTE
,      STAFFDATA.LAST_USER
,      STAFFDATA.USER_NAME_KJ
,      ONERDATA.KEIYAKU_END
FROM (
     SELECT DISTINCT
            BT20.ENTRY_CD
     ,      BT20.ENTRY_YEAR
     ,      BT20.ENTRY_KAI
     ,      BM11.COMPANY_CD
     ,      BM11.SIBU_CD
     ,      BM10.SIBU_NAME
     ,      BM11.ONER_CD
     ,      BM11.ONER_NAME_KJ
     ,      BT21.NAME
     ,      BT21.TEL
     ,      BM11.KEIYAKU_END
     FROM BM10GSIB BM10
     ,    BM11ONER BM11
     ,    BT20ENON BT20
     ,    BT21ENOJ BT21
/*IF limit*/
     ,    BM51SVSB as BM51
/*END*/
     WHERE BM11.COMPANY_CD   = /*companyCd*/'00'
     AND   BM11.ONER_CD     != '39999'
     AND   BM11.KEIYAKU_STA <= /*sysDate*/'20061213'
     AND   BM11.KEIYAKU_END >= /*sysDate*/'20061213'
     AND   BT20.ENTRY_CD     = /*entryCd*/'15'
     AND   BT20.ENTRY_YEAR   = /*entryYear*/'2006'
     AND   BT20.ENTRY_KAI    = /*entryKai*/'001'
     AND   BT20.ENTRY_FLG = /*attendKbn*/'0'
     AND   BT21.ATESAKI_KBN  = '00'
     AND   BT21.ENTRY_CD     = BT20.ENTRY_CD
     AND   BT21.ENTRY_YEAR   = BT20.ENTRY_YEAR
     AND   BT21.ENTRY_KAI    = BT20.ENTRY_KAI
     AND   BT21.COMPANY_CD   = BM10.COMPANY_CD

     AND   BM10.SIBU_CD      = BM11.SIBU_CD
     AND   BT21.ONER_CD      = BM11.ONER_CD
     AND   BT20.ONER_CD      = BT21.ONER_CD
/*IF limit*/
     AND   BM51.COMPANY_CD = BM10.COMPANY_CD
     AND   BM51.SIBU_CD    = BM10.SIBU_CD
     AND   BM51.SV_CD = /*userId*/'99990003'
/*END*/
) ONERDATA
LEFT JOIN (
     SELECT BT48.ENTRY_CD
     ,      BT48.ENTRY_YEAR
     ,      BT48.ENTRY_KAI
     ,      BT48.COMPANY_CD
     ,      BT48.ONER_CD
     ,      BT48.SEQ_NO
     ,      BM01.SIBU_CD
     ,      BT48.MISE_CD
     ,      BM01.MISE_NAME_KJ
     ,      BT48.L_NAME_KJ
     ,      BT48.F_NAME_KJ
     ,      BT48.L_NAME_kna
     ,      BT48.F_NAME_kna
     ,      BT48.SEX
	 ,      BT48.BIRTHDAY
     ,      BT48.AGE
     ,      BT48.JOB_TYPE AS JOB_TYPE
     ,      BR53_PROPOSE.SELECTION_INDEX AS PROPOSE_KBN
     ,      BR53_PROPOSE.SELECTION_NAME AS PROPOSE_NAME
     ,      CASE WHEN BT48.OPTIONAL1  = '1' THEN BT48.OPTIONAL1 ELSE '' END AS OPTIONAL1
     ,      CASE WHEN BT48.OPTIONAL2  = '1' THEN BT48.OPTIONAL2 ELSE '' END AS OPTIONAL2
     ,      CASE WHEN BT48.OPTIONAL3  = '1' THEN BT48.OPTIONAL3 ELSE '' END AS OPTIONAL3
     ,      CASE WHEN BT48.OPTIONAL4  = '1' THEN BT48.OPTIONAL4 ELSE '' END AS OPTIONAL4
     ,      CASE WHEN BT48.OPTIONAL5  = '1' THEN BT48.OPTIONAL5 ELSE '' END AS OPTIONAL5
     ,      CASE WHEN BT48.OPTIONAL6  = '1' THEN BT48.OPTIONAL6 ELSE '' END AS OPTIONAL6
     ,      CASE WHEN BT48.OPTIONAL7  = '1' THEN BT48.OPTIONAL7 ELSE '' END AS OPTIONAL7
     ,      CASE WHEN BT48.OPTIONAL8  = '1' THEN BT48.OPTIONAL8 ELSE '' END AS OPTIONAL8
     ,      CASE WHEN BT48.OPTIONAL9  = '1' THEN BT48.OPTIONAL9 ELSE '' END AS OPTIONAL9
     ,      CASE WHEN BT48.OPTIONAL10 = '1' THEN BT48.OPTIONAL10 ELSE '' END AS OPTIONAL10
     ,      CASE WHEN BT48.OPTIONAL11 = '1' THEN BT48.OPTIONAL11 ELSE '' END AS OPTIONAL11
     ,      CASE WHEN BT48.OPTIONAL12 = '1' THEN BT48.OPTIONAL12 ELSE '' END AS OPTIONAL12
     ,      CASE WHEN BT48.OPTIONAL13 = '1' THEN BT48.OPTIONAL13 ELSE '' END AS OPTIONAL13
     ,      CASE WHEN BT48.OPTIONAL14 = '1' THEN BT48.OPTIONAL14 ELSE '' END AS OPTIONAL14
     ,      CASE WHEN BT48.OPTIONAL15 = '1' THEN BT48.OPTIONAL15 ELSE '' END AS OPTIONAL15
     ,      CASE WHEN BT48.OPTIONAL16 = '1' THEN BT48.OPTIONAL16 ELSE '' END AS OPTIONAL16
     ,      CASE WHEN BT48.OPTIONAL21 = '1' THEN BT48.OPTIONAL21 ELSE '' END AS OPTIONAL21
     ,      CASE WHEN BT48.OPTIONAL22 = '1' THEN BT48.OPTIONAL22 ELSE '' END AS OPTIONAL22
     ,      CASE WHEN BT48.OPTIONAL23 = '1' THEN BT48.OPTIONAL23 ELSE '' END AS OPTIONAL23
     ,      CASE WHEN BT48.OPTIONAL24 = '1' THEN BT48.OPTIONAL24 ELSE '' END AS OPTIONAL24
     ,      CASE WHEN BT48.OPTIONAL25 = '1' THEN BT48.OPTIONAL25 ELSE '' END AS OPTIONAL25
     ,      CASE WHEN BT48.OPTIONAL26 = '1' THEN BT48.OPTIONAL26 ELSE '' END AS OPTIONAL26
     ,      CASE WHEN BT48.OPTIONAL27 = '1' THEN BT48.OPTIONAL27 ELSE '' END AS OPTIONAL27
     ,      CASE WHEN BT48.OPTIONAL28 = '1' THEN BT48.OPTIONAL28 ELSE '' END AS OPTIONAL28
     ,      CASE WHEN BT48.OPTIONAL29 = '1' THEN BT48.OPTIONAL29 ELSE '' END AS OPTIONAL29
     ,      CASE WHEN BT48.OPTIONAL30 = '1' THEN BT48.OPTIONAL30 ELSE '' END AS OPTIONAL30
     ,      CASE WHEN BT48.OPTIONAL1  = '1' THEN BR53_OP01.SELECTION_NAME ELSE '' END AS OPTIONAL1_NM
     ,      CASE WHEN BT48.OPTIONAL2  = '1' THEN BR53_OP02.SELECTION_NAME ELSE '' END AS OPTIONAL2_NM
     ,      CASE WHEN BT48.OPTIONAL3  = '1' THEN BR53_OP03.SELECTION_NAME ELSE '' END AS OPTIONAL3_NM
     ,      CASE WHEN BT48.OPTIONAL4  = '1' THEN BR53_OP04.SELECTION_NAME ELSE '' END AS OPTIONAL4_NM
     ,      CASE WHEN BT48.OPTIONAL5  = '1' THEN BR53_OP05.SELECTION_NAME ELSE '' END AS OPTIONAL5_NM
     ,      CASE WHEN BT48.OPTIONAL6  = '1' THEN BR53_OP06.SELECTION_NAME ELSE '' END AS OPTIONAL6_NM
     ,      CASE WHEN BT48.OPTIONAL7  = '1' THEN BR53_OP07.SELECTION_NAME ELSE '' END AS OPTIONAL7_NM
     ,      CASE WHEN BT48.OPTIONAL8  = '1' THEN BR53_OP08.SELECTION_NAME ELSE '' END AS OPTIONAL8_NM
     ,      CASE WHEN BT48.OPTIONAL9  = '1' THEN BR53_OP09.SELECTION_NAME ELSE '' END AS OPTIONAL9_NM
     ,      CASE WHEN BT48.OPTIONAL10 = '1' THEN BR53_OP10.SELECTION_NAME ELSE '' END AS OPTIONAL10_NM
     ,      CASE WHEN BT48.OPTIONAL11 = '1' THEN BR53_OP11.SELECTION_NAME ELSE '' END AS OPTIONAL11_NM
     ,      CASE WHEN BT48.OPTIONAL12 = '1' THEN BR53_OP12.SELECTION_NAME ELSE '' END AS OPTIONAL12_NM
     ,      CASE WHEN BT48.OPTIONAL13 = '1' THEN BR53_OP13.SELECTION_NAME ELSE '' END AS OPTIONAL13_NM
     ,      CASE WHEN BT48.OPTIONAL14 = '1' THEN BR53_OP14.SELECTION_NAME ELSE '' END AS OPTIONAL14_NM
     ,      CASE WHEN BT48.OPTIONAL15 = '1' THEN BR53_OP15.SELECTION_NAME ELSE '' END AS OPTIONAL15_NM
     ,      CASE WHEN BT48.OPTIONAL16 = '1' THEN BR53_OP16.SELECTION_NAME ELSE '' END AS OPTIONAL16_NM
     ,      CASE WHEN BT48.OPTIONAL21 = '1' THEN BR53_OP21.SELECTION_NAME ELSE '' END AS OPTIONAL21_NM
     ,      CASE WHEN BT48.OPTIONAL22 = '1' THEN BR53_OP22.SELECTION_NAME ELSE '' END AS OPTIONAL22_NM
     ,      CASE WHEN BT48.OPTIONAL23 = '1' THEN BR53_OP23.SELECTION_NAME ELSE '' END AS OPTIONAL23_NM
     ,      CASE WHEN BT48.OPTIONAL24 = '1' THEN BR53_OP24.SELECTION_NAME ELSE '' END AS OPTIONAL24_NM
     ,      CASE WHEN BT48.OPTIONAL25 = '1' THEN BR53_OP25.SELECTION_NAME ELSE '' END AS OPTIONAL25_NM
     ,      CASE WHEN BT48.OPTIONAL26 = '1' THEN BR53_OP26.SELECTION_NAME ELSE '' END AS OPTIONAL26_NM
     ,      CASE WHEN BT48.OPTIONAL27 = '1' THEN BR53_OP27.SELECTION_NAME ELSE '' END AS OPTIONAL27_NM
     ,      CASE WHEN BT48.OPTIONAL28 = '1' THEN BR53_OP28.SELECTION_NAME ELSE '' END AS OPTIONAL28_NM
     ,      CASE WHEN BT48.OPTIONAL29 = '1' THEN BR53_OP29.SELECTION_NAME ELSE '' END AS OPTIONAL29_NM
     ,      CASE WHEN BT48.OPTIONAL30 = '1' THEN BR53_OP30.SELECTION_NAME ELSE '' END AS OPTIONAL30_NM
	 ,      BT48.NOTE1
     ,      BT48.NOTE
     ,      BT48.LAST_USER
     ,      br01.USER_NAME_KJ
     FROM BM01TENM BM01
     ,    BT48NATI BT48
     LEFT JOIN BR53ENTS BR53_PROPOSE
          ON (      BR53_PROPOSE.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_PROPOSE.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_PROPOSE.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_PROPOSE.SELECTION_KBN  = '1'
              AND   BR53_PROPOSE.SELECTION_INDEX = BT48.PROPOSE_KBN
              )
     LEFT JOIN BR53ENTS BR53_OP01
          ON (      BR53_OP01.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP01.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP01.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP01.SELECTION_KBN  = '2'
              AND   BR53_OP01.SELECTION_INDEX = '01'
              )
     LEFT JOIN BR53ENTS BR53_OP02
          ON (      BR53_OP02.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP02.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP02.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP02.SELECTION_KBN  = '2'
              AND   BR53_OP02.SELECTION_INDEX = '02'
              )
     LEFT JOIN BR53ENTS BR53_OP03
          ON (      BR53_OP03.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP03.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP03.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP03.SELECTION_KBN  = '2'
              AND   BR53_OP03.SELECTION_INDEX = '03'
              )
     LEFT JOIN BR53ENTS BR53_OP04
          ON (      BR53_OP04.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP04.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP04.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP04.SELECTION_KBN  = '2'
              AND   BR53_OP04.SELECTION_INDEX = '04'
              )
     LEFT JOIN BR53ENTS BR53_OP05
          ON (      BR53_OP05.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP05.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP05.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP05.SELECTION_KBN  = '2'
              AND   BR53_OP05.SELECTION_INDEX = '05'
              )
     LEFT JOIN BR53ENTS BR53_OP06
          ON (      BR53_OP06.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP06.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP06.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP06.SELECTION_KBN  = '2'
              AND   BR53_OP06.SELECTION_INDEX = '06'
              )
     LEFT JOIN BR53ENTS BR53_OP07
          ON (      BR53_OP07.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP07.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP07.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP07.SELECTION_KBN  = '2'
              AND   BR53_OP07.SELECTION_INDEX = '07'
              )
     LEFT JOIN BR53ENTS BR53_OP08
          ON (      BR53_OP08.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP08.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP08.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP08.SELECTION_KBN  = '2'
              AND   BR53_OP08.SELECTION_INDEX = '08'
              )
     LEFT JOIN BR53ENTS BR53_OP09
          ON (      BR53_OP09.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP09.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP09.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP09.SELECTION_KBN  = '2'
              AND   BR53_OP09.SELECTION_INDEX = '09'
              )
     LEFT JOIN BR53ENTS BR53_OP10
          ON (      BR53_OP10.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP10.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP10.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP10.SELECTION_KBN  = '2'
              AND   BR53_OP10.SELECTION_INDEX = '10'
              )
     LEFT JOIN BR53ENTS BR53_OP11
          ON (      BR53_OP11.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP11.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP11.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP11.SELECTION_KBN  = '2'
              AND   BR53_OP11.SELECTION_INDEX = '11'
              )
     LEFT JOIN BR53ENTS BR53_OP12
          ON (      BR53_OP12.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP12.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP12.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP12.SELECTION_KBN  = '2'
              AND   BR53_OP12.SELECTION_INDEX = '12'
              )
     LEFT JOIN BR53ENTS BR53_OP13
          ON (      BR53_OP13.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP13.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP13.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP13.SELECTION_KBN  = '2'
              AND   BR53_OP13.SELECTION_INDEX = '13'
              )
     LEFT JOIN BR53ENTS BR53_OP14
          ON (      BR53_OP14.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP14.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP14.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP14.SELECTION_KBN  = '2'
              AND   BR53_OP14.SELECTION_INDEX = '14'
              )
     LEFT JOIN BR53ENTS BR53_OP15
          ON (      BR53_OP15.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP15.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP15.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP15.SELECTION_KBN  = '2'
              AND   BR53_OP15.SELECTION_INDEX = '15'
              )
     LEFT JOIN BR53ENTS BR53_OP16
          ON (      BR53_OP16.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP16.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP16.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP16.SELECTION_KBN  = '2'
              AND   BR53_OP16.SELECTION_INDEX = '16'
              )
     LEFT JOIN BR53ENTS BR53_OP21
          ON (      BR53_OP21.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP21.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP21.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP21.SELECTION_KBN  = '2'
              AND   BR53_OP21.SELECTION_INDEX = '21'
              )
     LEFT JOIN BR53ENTS BR53_OP22
          ON (      BR53_OP22.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP22.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP22.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP22.SELECTION_KBN  = '2'
              AND   BR53_OP22.SELECTION_INDEX = '22'
              )
     LEFT JOIN BR53ENTS BR53_OP23
          ON (      BR53_OP23.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP23.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP23.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP23.SELECTION_KBN  = '2'
              AND   BR53_OP23.SELECTION_INDEX = '23'
              )
     LEFT JOIN BR53ENTS BR53_OP24
          ON (      BR53_OP24.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP24.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP24.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP24.SELECTION_KBN  = '2'
              AND   BR53_OP24.SELECTION_INDEX = '24'
              )
     LEFT JOIN BR53ENTS BR53_OP25
          ON (      BR53_OP25.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP25.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP25.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP25.SELECTION_KBN  = '2'
              AND   BR53_OP25.SELECTION_INDEX = '25'
              )
     LEFT JOIN BR53ENTS BR53_OP26
          ON (      BR53_OP26.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP26.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP26.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP26.SELECTION_KBN  = '2'
              AND   BR53_OP26.SELECTION_INDEX = '26'
              )
     LEFT JOIN BR53ENTS BR53_OP27
          ON (      BR53_OP27.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP27.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP27.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP27.SELECTION_KBN  = '2'
              AND   BR53_OP27.SELECTION_INDEX = '27'
              )
     LEFT JOIN BR53ENTS BR53_OP28
          ON (      BR53_OP28.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP28.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP28.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP28.SELECTION_KBN  = '2'
              AND   BR53_OP28.SELECTION_INDEX = '28'
              )
     LEFT JOIN BR53ENTS BR53_OP29
          ON (      BR53_OP29.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP29.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP29.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP29.SELECTION_KBN  = '2'
              AND   BR53_OP29.SELECTION_INDEX = '29'
              )
     LEFT JOIN BR53ENTS BR53_OP30
          ON (      BR53_OP30.ENTRY_CD     = BT48.ENTRY_CD
              AND   BR53_OP30.ENTRY_YEAR   = BT48.ENTRY_YEAR
              AND   BR53_OP30.ENTRY_KAI    = BT48.ENTRY_KAI
              AND   BR53_OP30.SELECTION_KBN  = '2'
              AND   BR53_OP30.SELECTION_INDEX = '30'
              )
     ,    BR01USER BR01
     WHERE BM01.COMPANY_CD = /*companyCd*/'00'
     AND   BT48.ENTRY_CD   = /*entryCd*/'15'
     AND   BT48.ENTRY_YEAR = /*entryYear*/'2006'
     AND   BT48.ENTRY_KAI  = /*entryKai*/'001'
     AND   BT48.COMPANY_CD = BM01.COMPANY_CD
     AND   BT48.LAST_USER  = BR01.USER_ID
     AND   BT48.MISE_CD    = BM01.MISE_CD
) STAFFDATA
 ON (      STAFFDATA.ENTRY_CD     = ONERDATA.ENTRY_CD
     AND   STAFFDATA.ENTRY_YEAR   = ONERDATA.ENTRY_YEAR
     AND   STAFFDATA.ENTRY_KAI    = ONERDATA.ENTRY_KAI
     AND   STAFFDATA.COMPANY_CD   = ONERDATA.COMPANY_CD
     AND   STAFFDATA.ONER_CD      = ONERDATA.ONER_CD
 )
ORDER BY ONER_CD
,        SEQ_NO
,        SIBU_CD
