SELECT DISTINCT
    BC05KCOM.COMPANY_CD,
    BC05KCOM.COMPANY_NAME
FROM 
    BM03USCP 
    inner join BC05KCOM on BM03USCP.R_COMPANY_CD = BC05KCOM.COMPANY_CD
WHERE
    BM03USCP.USER_ID = /*USER_ID*/'99990003'
ORDER BY
    BC05KCOM.COMPANY_CD

