SELECT DISTINCT
    BR38OLNK.O_LINK_ID,
    BR38OLNK.MENU_NAME,
    BR38OLNK.SUB_MENU_NAME,
    BR38OLNK.SITE_KBN,
    BR38OLNK.URL,
    BR38OLNK.PARAM,
    BR38OLNK.README,
    BR38OLNK.SORT
FROM 
    BR38OLNK
    INNER JOIN BR39OLAC ON BR39OLAC.O_LINK_ID = BR38OLNK.O_LINK_ID  
    INNER JOIN BR04USRL ON BR04USRL.ROLE_CD = BR39OLAC.ROLE_CD
WHERE
    BR04USRL.USER_ID = /*USER_ID*/'99990003'
AND BR38OLNK.ENABLE_FLG != '' 
ORDER BY BR38OLNK.SORT
