SELECT
    BM11ONER.COMPANY_CD,
    BM11ONER.ONER_CD,
    BM11ONER.ONER_KBN,
    BC21AITE.AITE_NAME,
    BM11ONER.SIBU_CD,
    BM11ONER.ONER_NAME_KJ,
    BM11ONER.ONER_NAME_KNA,
    BM11ONER.ONER_POST_NO,
    BM11ONER.ONER_KEN_NAME,
    BM11ONER.ONER_ADRS1,
    BM11ONER.ONER_ADRS2,
    BM11ONER.ONER_ADRS3,
    BM11ONER.ONER_TEL,
    BM11ONER.ONER_FAX,
    BM11ONER.KESSAN_M AS KESSAN_DT,
    BM11ONER.BIRTH_ONER,
    BM11ONER.KEIYAKU_STA,
    BM11ONER.KEIYAKU_END,
    BM11ONER.UNEI_CD,
    KC11UNEI.UNEI,
    BM11ONER.KEIYAKU_NAME,
    BM11ONER.MISE_FIRST,
    (SELECT BM01TENM.MISE_NAME_KJ 
     FROM BM01TENM 
     WHERE BM01TENM.COMPANY_CD = BM11ONER.COMPANY_CD 
           and BM01TENM.MISE_CD = BM11ONER.MISE_FIRST) AS MISE_FIRST_NAME,
    BM11ONER.ONER_TEL2,
    BM11ONER.OTHER_BUSINESS,
    KM16OREL.REL_NAME_KJ as TANTO_NAME,
    KM16OREL.REL_TEL as TANTO_TEL,
    BM11ONER.CAPITAL,
    BM11ONER.MOS_RATE,
    BM11ONER.GYOMU,
    BM11ONER.SEX
FROM 
    BM11ONER    
    LEFT OUTER JOIN BM01TENM  ON BM11ONER.COMPANY_CD = BM01TENM.COMPANY_CD
                             AND BM11ONER.ONER_CD    = BM01TENM.ONER_CD
                             AND BM11ONER.MISE_FIRST = BM01TENM.MISE_CD
    LEFT OUTER JOIN BC21AITE  ON BM11ONER.ONER_KBN   = BC21AITE.AITE_KBN
    LEFT OUTER JOIN KC11UNEI  ON BM11ONER.UNEI_CD = KC11UNEI.UNEI_CD
    LEFT OUTER JOIN BT18PLAU  ON BM11ONER.COMPANY_CD = BT18PLAU.COMPANY_CD
                             AND BM11ONER.ONER_CD    = BT18PLAU.ONER_CD
    LEFT OUTER JOIN KM16OREL ON  BM11ONER.COMPANY_CD = KM16OREL.COMPANY_CD
                             AND BM11ONER.ONER_CD = KM16OREL.ONER_CD 
                             AND KM16OREL.REL_CD = '03'
    /*IF IS_LIMIT == true */
		, BM51SVSB 
	/*END*/
WHERE
BM11ONER.COMPANY_CD = /*COMPANY_CD*/'00'
AND BM11ONER.ONER_CD = /*ONER_CD*/'36231'

/*IF IS_LIMIT == true */
	AND BM11ONER.COMPANY_CD = BM51SVSB.COMPANY_CD 
	AND BM11ONER.SIBU_CD = BM51SVSB.SIBU_CD 
	AND BM51SVSB.SV_CD = /*USER_ID*/'00000921' 
/*END*/