SELECT
	BM01.COMPANY_CD      as COMPANY_CD,
	BM01.MISE_CD         as MISE_CD,
    rtrim(BM01.MISE_NAME_KJ)    as MISE_NAME_KJ,
    rtrim(BM01.SIBU_CD)         as SIBU_CD,
    rtrim(BM10.SIBU_NAME)       as SIBU_NAME,
    rtrim(BC23.BLOCK_NAME)      as BLOCK_NAME,
	rtrim(BM23.YOBI_KBN_1)      as YOBI_KBN_1,
	rtrim(GAS_SHU_NAME)         as GAS_SHU_NAME,
	rtrim(BM23.YOBI_KBN_2)      as YOBI_KBN_2,
	rtrim(AIR_CON_SHU_NAME)     as AIR_CON_SHU_NAME
FROM
	(SELECT CNT_DATE FROM BR33CDAY WHERE DAY_KBN = '02') BR33,
	BM01TENM BM01 
        LEFT JOIN BM10GSIB BM10 on (BM01.COMPANY_CD = BM10.COMPANY_CD AND BM01.SIBU_CD  = BM10.SIBU_CD) 
		LEFT JOIN BC23BLCK BC23 on (BM01.BLOCK_CD = BC23.BLOCK_CD)
	    LEFT JOIN BM23MIYO BM23 ON (BM23.COMPANY_CD = BM01.COMPANY_CD AND BM23.MISE_CD    = BM01.MISE_CD)
        LEFT JOIN BC32GASS BC32 ON (BM23.YOBI_KBN_1 = BC32.GAS_SHU)
        LEFT JOIN BC33AIRS BC33 ON (BM23.YOBI_KBN_2 = BC33.AIR_CON_SHU)

WHERE BM01.COMPANY_CD = /*companyCd*/'00'
/*IF sibuCd != null */AND BM01.SIBU_CD = /*sibuCd*/'081'/*END*/
/*IF closeFlg != null */AND BM01.CLOSE_DT >= BR33.CNT_DATE/*END*/
ORDER BY 
    BM01.SIBU_CD,
    BM01.BLOCK_CD,
    BM01.MISE_CD
