select
	rtrim(BM26.COMPANY_CD)       as COMPANY_CD,
	rtrim(BM26.MISE_CD)          as MISE_CD,
    rtrim(BM01.MISE_NAME_KJ)     as MISE_NAME_KJ,
    rtrim(BM01.SIBU_CD)          as SIBU_CD,
    rtrim(BM10.SIBU_NAME)        as SIBU_NAME,
    rtrim(BM01.BLOCK_CD)         as BLOCK_CD,
    rtrim(BC23.BLOCK_NAME)       as BLOCK_NAME,
	rtrim(BM26.INSENTIVE_1)      as INSENTIVE_1,
	rtrim(BC17_1.INSENTIVE_NAME) as INSENTIVE_NAME_1,
	rtrim(BM26.INSENTIVE_1_STA)  as INSENTIVE_1_STA,
	rtrim(BM26.INSENTIVE_1_END)  as INSENTIVE_1_END,
	rtrim(BM26.INSENTIVE_1_NOTE) as INSENTIVE_1_NOTE,
	rtrim(BM26.INSENTIVE_2)      as INSENTIVE_2,
	rtrim(BC17_2.INSENTIVE_NAME) as INSENTIVE_NAME_2,
	rtrim(BM26.INSENTIVE_2_STA)  as INSENTIVE_2_STA,
	rtrim(BM26.INSENTIVE_2_END)  as INSENTIVE_2_END,
	rtrim(BM26.INSENTIVE_2_NOTE) as INSENTIVE_2_NOTE,
	rtrim(BM26.INSENTIVE_3)      as INSENTIVE_3,
	rtrim(BC17_3.INSENTIVE_NAME) as INSENTIVE_NAME_3,
	rtrim(BM26.INSENTIVE_3_STA)  as INSENTIVE_3_STA,
	rtrim(BM26.INSENTIVE_3_END)  as INSENTIVE_3_END,
	rtrim(BM26.INSENTIVE_3_NOTE) as INSENTIVE_3_NOTE,
	rtrim(BM26.INSENTIVE_4)      as INSENTIVE_4,
	rtrim(BC17_4.INSENTIVE_NAME) as INSENTIVE_NAME_4,
	rtrim(BM26.INSENTIVE_4_STA)  as INSENTIVE_4_STA,
	rtrim(BM26.INSENTIVE_4_END)  as INSENTIVE_4_END,
	rtrim(BM26.INSENTIVE_4_NOTE) as INSENTIVE_4_NOTE,
	rtrim(BM26.INSENTIVE_5)      as INSENTIVE_5,
	rtrim(BC17_5.INSENTIVE_NAME) as INSENTIVE_NAME_5,
	rtrim(BM26.INSENTIVE_5_STA)  as INSENTIVE_5_STA,
	rtrim(BM26.INSENTIVE_5_END)  as INSENTIVE_5_END,
	rtrim(BM26.INSENTIVE_5_NOTE) as INSENTIVE_5_NOTE
from
    (SELECT CNT_DATE FROM BR33CDAY WHERE DAY_KBN = '02') BR33,
    BM01TENM BM01
        left join BM10GSIB BM10 on (BM01.COMPANY_CD = BM10.COMPANY_CD and BM01.SIBU_CD = BM10.SIBU_CD) 
		left join BC23BLCK BC23 on (BM01.BLOCK_CD = BC23.BLOCK_CD) ,
	BM26INSR BM26
        left join BC17INSE BC17_1 on (BM26.COMPANY_CD = BC17_1.COMPANY_CD and BM26.INSENTIVE_1 = BC17_1.INSENTIVE_CD)
        left join BC17INSE BC17_2 on (BM26.COMPANY_CD = BC17_2.COMPANY_CD and BM26.INSENTIVE_2 = BC17_2.INSENTIVE_CD)
        left join BC17INSE BC17_3 on (BM26.COMPANY_CD = BC17_3.COMPANY_CD and BM26.INSENTIVE_3 = BC17_3.INSENTIVE_CD)
        left join BC17INSE BC17_4 on (BM26.COMPANY_CD = BC17_4.COMPANY_CD and BM26.INSENTIVE_4 = BC17_4.INSENTIVE_CD)
        left join BC17INSE BC17_5 on (BM26.COMPANY_CD = BC17_5.COMPANY_CD and BM26.INSENTIVE_5 = BC17_5.INSENTIVE_CD)
where
	BM26.COMPANY_CD = BM01.COMPANY_CD
and BM26.MISE_CD    = BM01.MISE_CD
and BM26.COMPANY_CD = /*companyCd*/'00'
/*IF sibuCd != null */AND BM01.SIBU_CD = /*sibuCd*/'081'/*END*/
/*IF closeFlg != null */
and BM01.CLOSE_DT >= BR33.CNT_DATE
/*END*/
order by 
    BM01.SIBU_CD,
    BM01.BLOCK_CD,
    BM26.MISE_CD,
	BM26.MISE_M_DATE