select
	rtrim(BM23.COMPANY_CD)      as COMPANY_CD,
	rtrim(BM23.MISE_CD)         as MISE_CD,
    rtrim(BM01.MISE_NAME_KJ)    as MISE_NAME_KJ,
    rtrim(BM01.SIBU_CD)         as SIBU_CD,
    rtrim(BM10.SIBU_NAME)       as SIBU_NAME,
    rtrim(BC23.BLOCK_NAME)      as BLOCK_NAME,
	rtrim(BM23.EMERGENCE_TEL1)  as EMERGENCE_TEL1,
	rtrim(BM23.EMERGENCE_TEL2)  as EMERGENCE_TEL2,
	rtrim(BM23.EMERGENCE_TEL3)  as EMERGENCE_TEL3,
	rtrim(BM23.EMERGENCE_NAME1) as EMERGENCE_NAME1,
	rtrim(BM23.EMERGENCE_NAME2) as EMERGENCE_NAME2,
	rtrim(BM23.EMERGENCE_NAME3) as EMERGENCE_NAME3,
	rtrim(BM23.YOBI_FREE_1)     as YOBI_FREE_1,
	rtrim(BM23.YOBI_FREE_2)     as YOBI_FREE_2,
	rtrim(BM23.YOBI_FREE_3)     as YOBI_FREE_3,
	rtrim(BM23.YOBI_FREE_4)     as YOBI_FREE_4,
	rtrim(BM23.YOBI_FREE_5)     as YOBI_FREE_5
from
	BM23MIYO BM23,
	(SELECT CNT_DATE FROM BR33CDAY WHERE DAY_KBN = '02') BR33,
	BM01TENM BM01 
        left join BM10GSIB BM10 on (BM01.COMPANY_CD = BM10.COMPANY_CD and BM01.SIBU_CD  = BM10.SIBU_CD) 
		left join BC23BLCK BC23 on (BM01.BLOCK_CD = BC23.BLOCK_CD)
where
	BM23.COMPANY_CD = BM01.COMPANY_CD
and BM23.MISE_CD    = BM01.MISE_CD
and BM23.COMPANY_CD = /*companyCd*/'00'
/*IF sibuCd != null */AND BM01.SIBU_CD = /*sibuCd*/'081'/*END*/
/*IF closeFlg != null */
and BM01.CLOSE_DT >= BR33.CNT_DATE
/*END*/
order by 
    BM01.SIBU_CD,
    BM01.BLOCK_CD,
    BM23.MISE_CD
