select * from (
select
    rtrim(BM12.STAFF_ID)       as STAFF_ID,
    rtrim(BM12.COMPANY_CD)      as COMPANY_CD,
    rtrim(BM12.ONER_CD)         as ONER_CD,
    rtrim(BM11.ONER_NAME_KJ)    as ONER_NAME_KJ,
    rtrim(BM12.MISE_CD_1)       as MISE_CD_1,
    rtrim(BM01.MISE_NAME_KJ)    as MISE_NAME_KJ,
    rtrim(BM01.SIBU_CD)         as SIBU_CD,
    rtrim(BM10.SIBU_NAME)       as SIBU_NAME,
    COUNT(BM12.STAFF_ID) OVER( partition by BM01.SIBU_CD) AS SIBU_STAFF_CNT,
    rtrim(BM12.STAFF_L_NAME_KJ) as STAFF_L_NAME_KJ,
    rtrim(BM12.STAFF_F_NAME_KJ) as STAFF_F_NAME_KJ,
    rtrim(VBT32.EXAM_NO)        as EXAM_NO,
    rtrim(VBT32.TOTAL_LAST_YEAR)as TOTAL_LAST_YEAR,
    rtrim(VBT32.TOTAL_LAST_KAI) as TOTAL_LAST_KAI,
    rtrim(VBT32.TOTAL_RESULT)   as TOTAL_RESULT,
    rtrim(VBT32.SUB1_RESULT)    as SUB1_RESULT,
    rtrim(VBT32.SUB2_RESULT)    as SUB2_RESULT,
    rtrim(VBT32.SUB3_RESULT)    as SUB3_RESULT,
    rtrim(BT30ZENTEI.COURSE_STATUS)  as COURSE_STATUS,
    rtrim(BM12.SITUATION_KBN)   as SITUATION_KBN,	
    rtrim(BT26.LICENSE_NO)      as LICENSE_NO,
    rtrim(BT26.LICENSE_DT)      as LICENSE_DT,
    VBT32.STAFF_ID AS BT32_STAFF_ID,
    BT26.EXPIRE_FLG
from BM01TENM BM01
     LEFT JOIN BM10GSIB BM10 
          ON (BM10.COMPANY_CD = /*companyCd*/'00' and BM01.SIBU_CD = BM10.SIBU_CD)
,    BM11ONER  BM11
,    (SELECT CNT_DATE FROM BR33CDAY WHERE DAY_KBN = '02') BR33
,    BM12STAF BM12
     LEFT JOIN VBT32MLKR VBT32 ON (BM12.STAFF_ID = VBT32.STAFF_ID )
     LEFT JOIN BT26UPJK  BT26  ON (BM12.STAFF_ID = BT26.STAFF_ID)
LEFT JOIN (SELECT STAFF_ID 
           ,      (CASE WHEN MAX(CASE WHEN COURSE_STATUS ='1' THEN '3' ELSE COURSE_STATUS END) ='3' THEN '1' 
                        ELSE MAX(CASE WHEN COURSE_STATUS ='1' THEN '3' ELSE COURSE_STATUS END) 
                   END) AS COURSE_STATUS 
           FROM BT30ENKJ 
           WHERE ENTRY_CD IN ('01', '05') 
           GROUP BY STAFF_ID
          ) BT30ZENTEI ON (BT30ZENTEI.STAFF_ID = BM12.STAFF_ID)
where BM12.COMPANY_CD = /*companyCd*/'00'
/*IF sibuCd != null */
AND BM01.SIBU_CD = /*sibuCd*/'081'
/*END*/
/*IF closeFlg != null */
and   BM01.CLOSE_DT >= BR33.CNT_DATE
/*END*/
and   BM12.COMPANY_CD = BM01.COMPANY_CD
and   BM12.COMPANY_CD = BM11.COMPANY_CD
and   BM12.MISE_CD_1  = BM01.MISE_CD
and   BM12.ONER_CD    = BM11.ONER_CD
) SUB 
WHERE (BT32_STAFF_ID IS NOT NULL OR EXPIRE_FLG='0')
order by SIBU_CD
,        ONER_CD
,        MISE_CD_1
,        TOTAL_LAST_YEAR
,        TOTAL_LAST_KAI
