SELECT PC25.SYUKEI_CD
    ,  RTRIM(PC25.SYUKEI_NAME) AS SYUKEI_NAME
    ,  COUNT(PM25.KKBN_CD) KKBN_CNT
FROM PC25KKSK PC25
    ,PM25KKBN PM25
WHERE 
    PC25.SYUKEI_CD = PM25.SYUKEI_CD
    /*IF birdDisFlg != null*/
    AND   PM25.BIRD_DISP_FLG = /*birdDisFlg*/'1'
    /*END*/
GROUP BY PC25.SYUKEI_CD
    ,    PC25.SYUKEI_NAME
ORDER BY SYUKEI_CD
