SELECT CASE WHEN TM_ELEM IS NULL THEN 'TOTAL'

            WHEN TIME_KBN IS NOT NULL THEN ''

            ELSE 'TIMESLOT'  END AS ROW_TYPE
,      TAISHO.COMPANY_CD
,      TAISHO.TARGET_NAME_KJ
,      TAISHO.TENPO_CNT

,      CASE WHEN TM_ELEM IS NULL THEN '00' ELSE TM_ELEM  END AS TM_ELEM
,      SUBSTR(TM_KBN,1,2) AS TM_KBN
,      KYAKUSU_EAT
,      KINGAKU_EAT
,      KYAKUSU_TAKE
,      KINGAKU_TAKE
,      KYAKUSU_TEL
,      KINGAKU_TEL
,      KYAKUSU_DRIVE
,      KINGAKU_DRIVE
,      KYAKUSU_TAKUHAI
,      KINGAKU_TAKUHAI
,      KYAKUSU_GAIHAN
,      KINGAKU_GAIHAN
,      KYAKUSU_SYUBETSU_07
,      KINGAKU_SYUBETSU_07
,      KYAKUSU_SYUBETSU_08
,      KINGAKU_SYUBETSU_08
,      KYAKUSU_SYUBETSU_09
,      KINGAKU_SYUBETSU_09
,      KYAKUSU_SYUBETSU_10
,      KINGAKU_SYUBETSU_10
,      KYAKUSU_NET_TAKE
,      KINGAKU_NET_TAKE
,      KYAKUSU_NET_TAKUHAI
,      KINGAKU_NET_TAKUHAI
,      KYAKUSU_SYUBETSU_13
,      KINGAKU_SYUBETSU_13
,      KYAKUSU_SYUBETSU_14
,      KINGAKU_SYUBETSU_14
,      KYAKUSU_SYUBETSU_15
,      KINGAKU_SYUBETSU_15
,      KYAKUSU_ETC
,      KINGAKU_ETC
,      KYAKUSU_ALL
,      KINGAKU_ALL
FROM (
SELECT B1470.TM_ELEM
,      B1470.TM_KBN AS TIME_KBN
,      MIN(B1470.TM_KBN) AS TM_KBN
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_EAT END) AS KYAKUSU_EAT 
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_EAT END) AS KINGAKU_EAT
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_TAKE END) AS KYAKUSU_TAKE
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_TAKE END) AS KINGAKU_TAKE
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_TEL END) AS KYAKUSU_TEL
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_TEL END) AS KINGAKU_TEL
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_DRIVE END) AS KYAKUSU_DRIVE
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_DRIVE END) AS KINGAKU_DRIVE
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_TAKUHAI END) AS KYAKUSU_TAKUHAI
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_TAKUHAI END) AS KINGAKU_TAKUHAI
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_GAIHAN END) AS KYAKUSU_GAIHAN
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_GAIHAN END) AS KINGAKU_GAIHAN
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_07 END) AS KYAKUSU_SYUBETSU_07
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_07 END) AS KINGAKU_SYUBETSU_07
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_08 END) AS KYAKUSU_SYUBETSU_08
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_08 END) AS KINGAKU_SYUBETSU_08
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_09 END) AS KYAKUSU_SYUBETSU_09
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_09 END) AS KINGAKU_SYUBETSU_09
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_10 END) AS KYAKUSU_SYUBETSU_10
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_10 END) AS KINGAKU_SYUBETSU_10
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_NET_TAKE END) AS KYAKUSU_NET_TAKE
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_NET_TAKE END) AS KINGAKU_NET_TAKE
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_NET_TAKUHAI END) AS KYAKUSU_NET_TAKUHAI
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_NET_TAKUHAI END) AS KINGAKU_NET_TAKUHAI
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_13 END) AS KYAKUSU_SYUBETSU_13
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_13 END) AS KINGAKU_SYUBETSU_13
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_14 END) AS KYAKUSU_SYUBETSU_14
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_14 END) AS KINGAKU_SYUBETSU_14
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_SYUBETSU_15 END) AS KYAKUSU_SYUBETSU_15
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_SYUBETSU_15 END) AS KINGAKU_SYUBETSU_15
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_ETC END) AS KYAKUSU_ETC
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_ETC END) AS KINGAKU_ETC
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KYAKUSU_ALL END) AS KYAKUSU_ALL
,      SUM(CASE WHEN BD18.COMPANY_CD IS NULL THEN 0 ELSE KINGAKU_ALL END) AS KINGAKU_ALL
FROM (
	SELECT 
	       BM70.TM_ELEM
	,      BM70.TM_KBN
	FROM   
	      BM70JTNM BM70
	GROUP BY 
	       BM70.TM_ELEM
	,      BM70.TM_KBN
	) B1470
LEFT JOIN (
	SELECT BD18.COMPANY_CD
	,      BD18.TM_KBN
	,      DECIMAL(SUM(BD18.URI_KEN_01)+0.5, 8,0) AS KYAKUSU_EAT
	,      DECIMAL(SUM(BD18.URI_KIN_01)+0.5, 14,0) AS KINGAKU_EAT
	,      DECIMAL(SUM(BD18.URI_KEN_02)+0.5, 8,0) AS KYAKUSU_TAKE
	,      DECIMAL(SUM(BD18.URI_KIN_02)+0.5, 14,0) AS KINGAKU_TAKE
	,      DECIMAL(SUM(BD18.URI_KEN_03)+0.5, 8,0) AS KYAKUSU_TEL
	,      DECIMAL(SUM(BD18.URI_KIN_03)+0.5, 14,0) AS KINGAKU_TEL
	,      DECIMAL(SUM(BD18.URI_KEN_04)+0.5, 8,0) AS KYAKUSU_DRIVE
	,      DECIMAL(SUM(BD18.URI_KIN_04)+0.5, 14,0) AS KINGAKU_DRIVE
	,      DECIMAL(SUM(BD18.URI_KEN_05)+0.5, 8,0) AS KYAKUSU_TAKUHAI
	,      DECIMAL(SUM(BD18.URI_KIN_05)+0.5, 14,0) AS KINGAKU_TAKUHAI
	,      DECIMAL(SUM(BD18.URI_KEN_06)+0.5, 8,0) AS KYAKUSU_GAIHAN
	,      DECIMAL(SUM(BD18.URI_KIN_06)+0.5, 14,0) AS KINGAKU_GAIHAN
	,      DECIMAL(SUM(BD18.URI_KEN_07)+0.5, 8,0) AS KYAKUSU_SYUBETSU_07
	,      DECIMAL(SUM(BD18.URI_KIN_07)+0.5, 14,0) AS KINGAKU_SYUBETSU_07
	,      DECIMAL(SUM(BD18.URI_KEN_08)+0.5, 8,0) AS KYAKUSU_SYUBETSU_08
	,      DECIMAL(SUM(BD18.URI_KIN_08)+0.5, 14,0) AS KINGAKU_SYUBETSU_08
	,      DECIMAL(SUM(BD18.URI_KEN_09)+0.5, 8,0) AS KYAKUSU_SYUBETSU_09
	,      DECIMAL(SUM(BD18.URI_KIN_09)+0.5, 14,0) AS KINGAKU_SYUBETSU_09
	,      DECIMAL(SUM(BD18.URI_KEN_10)+0.5, 8,0) AS KYAKUSU_SYUBETSU_10
	,      DECIMAL(SUM(BD18.URI_KIN_10)+0.5, 14,0) AS KINGAKU_SYUBETSU_10
	,      DECIMAL(SUM(BD18.URI_KEN_11)+0.5, 8,0) AS KYAKUSU_NET_TAKE
	,      DECIMAL(SUM(BD18.URI_KIN_11)+0.5, 14,0) AS KINGAKU_NET_TAKE
	,      DECIMAL(SUM(BD18.URI_KEN_12)+0.5, 8,0) AS KYAKUSU_NET_TAKUHAI
	,      DECIMAL(SUM(BD18.URI_KIN_12)+0.5, 14,0) AS KINGAKU_NET_TAKUHAI
	,      DECIMAL(SUM(BD18.URI_KEN_13)+0.5, 8,0) AS KYAKUSU_SYUBETSU_13
	,      DECIMAL(SUM(BD18.URI_KIN_13)+0.5, 14,0) AS KINGAKU_SYUBETSU_13
	,      DECIMAL(SUM(BD18.URI_KEN_14)+0.5, 8,0) AS KYAKUSU_SYUBETSU_14
	,      DECIMAL(SUM(BD18.URI_KIN_14)+0.5, 14,0) AS KINGAKU_SYUBETSU_14
	,      DECIMAL(SUM(BD18.URI_KEN_15)+0.5, 8,0) AS KYAKUSU_SYUBETSU_15
	,      DECIMAL(SUM(BD18.URI_KIN_15)+0.5, 14,0) AS KINGAKU_SYUBETSU_15	
	,      DECIMAL(SUM(BD18.URI_KEN_06+BD18.URI_KEN_07+BD18.URI_KEN_08+BD18.URI_KEN_09+BD18.URI_KEN_10
	                   +BD18.URI_KEN_11+BD18.URI_KEN_12+BD18.URI_KEN_13+BD18.URI_KEN_14+BD18.URI_KEN_15)+0.5, 8,0) AS KYAKUSU_ETC
	,      DECIMAL(SUM(BD18.URI_KIN_06+BD18.URI_KIN_07+BD18.URI_KIN_08+BD18.URI_KIN_09+BD18.URI_KIN_10
	                   +BD18.URI_KIN_11+BD18.URI_KIN_12+BD18.URI_KIN_13+BD18.URI_KIN_14+BD18.URI_KIN_15)+0.5, 14,0) AS KINGAKU_ETC
	,      DECIMAL(SUM(BD18.URI_KEN_KEI)+0.5, 8,0) AS KYAKUSU_ALL
	,      DECIMAL(SUM(BD18.URI_KIN_KEI)+0.5, 14,0) AS KINGAKU_ALL
	FROM BD18JSSL BD18
	,    (
		SELECT BM01.COMPANY_CD
		,      BM01.MISE_CD
		,      BM01.MISE_NAME_KJ
		FROM BM01TENM BM01
		,   (
			SELECT MISE_CD
			FROM BN01DTEN
			WHERE COMPANY_CD = /*companyCd*/'00'
			AND   EIGYO_YM BETWEEN /*kiknFromYM*/'200812' and /*kikanToYM*/'200902'
		
		
			GROUP BY MISE_CD
		) BN01
		WHERE BM01.COMPANY_CD = /*companyCd*/'00'
  
		AND   BM01.MISE_CD = /*hyojiTaisho*/'02001'


		AND   BN01.MISE_CD    = BM01.MISE_CD
	
	
		GROUP BY BM01.COMPANY_CD
		,        BM01.MISE_CD
		,        BM01.MISE_NAME_KJ
	) BM01
	WHERE BD18.COMPANY_CD = /*companyCd*/'00'
	AND   BD18.SYS_DT BETWEEN /*kikanSitei*/'20090201' and /*kikanSiteiTo*/'20090209'
  
	AND   BD18.MISE_CD = /*hyojiTaisho*/'02001'

	AND   BD18.COMPANY_CD = BM01.COMPANY_CD
	AND   BD18.MISE_CD    = BM01.MISE_CD
	GROUP BY BD18.COMPANY_CD
	,        BD18.TM_KBN
 	
) BD18 ON (
             BD18.TM_KBN= B1470.TM_KBN
          )
GROUP BY ROLLUP(
        B1470.TM_ELEM
    ,    B1470.TM_KBN
)
)SUB
,(
	SELECT BD18.COMPANY_CD
  
    ,      BM01.MISE_NAME_KJ AS TARGET_NAME_KJ


	,      COUNT(DISTINCT BD18.MISE_CD) AS TENPO_CNT
	FROM BD18JSSL BD18
	,    (
		SELECT BM01.COMPANY_CD
		,      BM01.MISE_CD
		,      BM01.MISE_NAME_KJ
		FROM BM01TENM BM01
		
		
		,   (
			SELECT MISE_CD
			FROM BN01DTEN
			WHERE COMPANY_CD = /*companyCd*/'00'
			AND   EIGYO_YM BETWEEN /*kiknFromYM*/'200812' and /*kikanToYM*/'200902' 
		
		
			GROUP BY MISE_CD
		) BN01
		WHERE BM01.COMPANY_CD = '00'
  
		AND   BM01.MISE_CD = /*hyojiTaisho*/'02001'


		AND   BN01.MISE_CD    = BM01.MISE_CD
	
	
		GROUP BY BM01.COMPANY_CD
		,        BM01.MISE_CD
		,        BM01.MISE_NAME_KJ
	) BM01
	WHERE BD18.COMPANY_CD = /*companyCd*/'00'
	AND   BD18.SYS_DT BETWEEN /*kikanSitei*/'20090201' and /*kikanSiteiTo*/'20090209'
	AND   BD18.COMPANY_CD = BM01.COMPANY_CD
	AND   BD18.MISE_CD    = BM01.MISE_CD
	GROUP BY BD18.COMPANY_CD
  
    ,      BM01.MISE_NAME_KJ

) TAISHO

ORDER BY COMPANY_CD    
,        ROW_TYPE DESC
,        TM_ELEM
,        TM_KBN


