SELECT DISTINCT
       BM41.MENU_CD as MENU_CD
  ,    rtrim(MENU_NAME_KJ) as MENU_NAME_KJ
  ,    BM41.MENU_GROUP
  ,    BM41.SUM_GROUP
FROM BM41CMNU BM41
 INNER JOIN (SELECT MENU_CD
                 ,  MENU_NAME_KJ
             FROM BM38MMNU 
             WHERE MISE_CD = /*miseCd*/'01057'
             AND   COMPANY_CD = /*companyCd*/'00') BM38
  ON (BM41.MENU_CD = BM38.MENU_CD) 
 INNER JOIN (SELECT MENU_GROUP 
             FROM   BM40CMGP
             WHERE  CKANRI_NO = /*ckanriNo*/'200601')BM40
  ON (BM41.MENU_GROUP = BM40.MENU_GROUP) 
WHERE BM41.CKANRI_NO = /*ckanriNo*/'200601'
ORDER BY BM41.MENU_GROUP
    ,    BM41.SUM_GROUP
   ,     BM41.MENU_CD