SELECT DISTINCT
       BT71.MENU_CD as MENU_CD
  ,    rtrim(BM38.MENU_NAME_KJ) as MENU_NAME_KJ
  ,    BT71.RESERVE_AMT
  ,    BT71.SEQ_NO
  ,    BT71.LAST_TMSP
  ,    BT70.RESERVE_DT
FROM BT71CRSD BT71
INNER JOIN (SELECT MENU_NAME_KJ
              ,    MENU_CD
             FROM  BM38MMNU
            WHERE  COMPANY_CD = /*companyCd*/'00'
             AND   MISE_CD = /*miseCd*/'01057') BM38
  ON (BT71.MENU_CD = BM38.MENU_CD) 
, BT70CRSV BT70
WHERE BT71.CKANRI_NO = /*ckanriNo*/'200604'
AND   BT71.COMPANY_CD = /*companyCd*/'00'
AND   BT71.MISE_CD = /*miseCd*/'01057'
AND   BT71.SEQ_NO = /*seqNo*/1
AND   BT71.CKANRI_NO = BT70.CKANRI_NO 
AND   BT71.COMPANY_CD = BT70.COMPANY_CD 
AND   BT71.MISE_CD = BT70.MISE_CD 
AND   BT71.SEQ_NO = BT70.SEQ_NO 
ORDER BY BT71.MENU_CD 
