SELECT
  MAX(BD59.NENDO) AS NENDO,
  RTRIM(BD59.USER_ID) AS USER_ID,
  SUM(BD59.POINT)*-1 AS POINT,
  MAXINFO.KB_COMPANY_CD AS KB_COMPANY_CD,
  MAXINFO.RANK_CD AS RANK_CD
FROM BD59HPRI BD59
  LEFT OUTER JOIN (
       SELECT
            DISTINCT(BD59.USER_ID),
            BD59.KB_COMPANY_CD,
            BD59.RANK_CD
        FROM (SELECT
            USER_ID,
            MAX(NENDO || POINT_SHU) AS NENDO1
            FROM BD59HPRI
            GROUP BY USER_ID
        ) B59MAXN
        LEFT JOIN
            BD59HPRI BD59
        ON (BD59.USER_ID = B59MAXN.USER_ID
            AND BD59.NENDO = LEFT(B59MAXN.NENDO1,4)
            AND BD59.POINT_SHU = RIGHT(B59MAXN.NENDO1,1))
    ) MAXINFO
    ON (BD59.USER_ID = MAXINFO.USER_ID)
WHERE BD59.USER_ID = /*userId*/'00000020'
  AND BD59.KAIGAI_FLG <> '1'
  AND BD59.POINT_SHU <>'9'
  AND BD59.NENDO <= /*nendo*/'2017'

GROUP BY BD59.USER_ID,MAXINFO.KB_COMPANY_CD,MAXINFO.RANK_CD
