SELECT DISTINCT
	BT17PLDT.PL_YM,
	count(*) as ROW_COUNT, 
	AVG(BT17PLDT.URIAGEDAKA) as URIAGEDAKA,
	AVG(BT17PLDT.URIAGEGENKA) as URIAGEGENKA,
	AVG(BT17PLDT.URIAGE_SO_RIEKI) as URIAGE_SO_RIEKI,
	AVG(BT17PLDT.SALARY) as SALARY,
	AVG(BT17PLDT.YACHIN) as YACHIN,
	AVG(BT17PLDT.SUIKOU_HI) as SUIKOU_HI,
	AVG(BT17PLDT.ROYALTY) as ROYALTY,
	AVG(BT17PLDT.TESURYO) as TESURYO,
	AVG(BT17PLDT.KOUKOKU) as KOUKOKU,
	AVG(BT17PLDT.SHOUMOU) as SHOUMOU,
	AVG(BT17PLDT.HOUTEI_FUKURI) as HOUTEI_FUKURI,
	AVG(BT17PLDT.FUKURI_KOUSEI) as FUKURI_KOUSEI,
	AVG(BT17PLDT.KOUSAI) as KOUSAI,
	AVG(BT17PLDT.RYOHI) as RYOHI,
	AVG(BT17PLDT.TUSIN) as TUSIN,
	AVG(BT17PLDT.LEASE) as LEASE,
	AVG(BT17PLDT.SHARYO) as SHARYO,
	AVG(BT17PLDT.SOZEI) as SOZEI,
	AVG(BT17PLDT.HOKEN) as HOKEN,
	AVG(BT17PLDT.UNCHIN) as UNCHIN,
	AVG(BT17PLDT.SHUZEN) as SHUZEN,
	AVG(BT17PLDT.YOBI) as YOBI,
	AVG(BT17PLDT.ZAPPI) as ZAPPI,
	AVG(BT17PLDT.KEIHI_SHOKEI) as KEIHI_SHOKEI,
	AVG(BT17PLDT.SHOKYAKU_RIEKI) as SHOKYAKU_RIEKI,
	AVG(BT17PLDT.GENKA_SHOKYAKU) as GENKA_SHOKYAKU,
	AVG(BT17PLDT.EIGAI_SHUEKI) as EIGAI_SHUEKI,
	AVG(BT17PLDT.EIGAI_HIYO) as EIGAI_HIYO,
	AVG(BT17PLDT.HONSHAHI_HAI) as HONSHAHI_HAI,
	AVG(BT17PLDT.RIEKI) as RIEKI,
	AVG(BT17PLDT.URIAGE) as URIAGE,
	AVG(BT17PLDT.BUPPAN) as BUPPAN,
	AVG(BT17PLDT.URI_UCHIWAKE) as URI_UCHIWAKE,
	AVG(BT17PLDT.ELEC) as ELEC,
	AVG(BT17PLDT.GAS) as GAS,
	AVG(BT17PLDT.WATER) as WATER,
	AVG(BT17PLDT.SONOTA) as SONOTA,
	AVG(BT17PLDT.SUIKOU_UCHIWAKE) as SUIKOU_UCHIWAKE,
	AVG(BT17PLDT.GENZAIRYO_KEI) as GENZAIRYO_KEI,
	AVG(BT17PLDT.GENZAIRYO_SHIRE) as GENZAIRYO_SHIRE,
	AVG(BT17PLDT.GENZAIRYO_ZAIKO) as GENZAIRYO_ZAIKO,
	AVG(BT17PLDT.YASAI_KEI) as YASAI_KEI,
	AVG(BT17PLDT.YASAI_SHIRE) as YASAI_SHIRE,
	AVG(BT17PLDT.YASAI_ZAIKO) as YASAI_ZAIKO,
	AVG(BT17PLDT.HOUZAI_KEI) as HOUZAI_KEI,
	AVG(BT17PLDT.HOUZAI_SHIRE) as HOUZAI_SHIRE,
	AVG(BT17PLDT.HOUZAI_ZAIKO) as HOUZAI_ZAIKO,
	AVG(BT17PLDT.BUPPAN_KEI) as BUPPAN_KEI,
	AVG(BT17PLDT.BUPPAN_SHIRE) as BUPPAN_SHIRE,
	AVG(BT17PLDT.BUPPAN_ZAIKO) as BUPPAN_ZAIKO,
	AVG(BT17PLDT.TOU_SIIRE_KEI) as TOU_SIIRE_KEI,
	AVG(BT17PLDT.TOU_ZAIKO_KEI) as TOU_ZAIKO_KEI,
	AVG(BT17PLDT.SASHIHIKI_KEI) as SASHIHIKI_KEI,
	AVG(BT17PLDT.YAKUIN_SALARY) as YAKUIN_SALARY,
	AVG(BT17PLDT.YAKUIN_BONUS) as YAKUIN_BONUS,
	AVG(BT17PLDT.YAKUIN_RETIRE) as YAKUIN_RETIRE,
	AVG(BT17PLDT.YAKUIN_KEI) as YAKUIN_KEI,
	AVG(BT17PLDT.SALARY_SALARY) as SALARY_SALARY,
	AVG(BT17PLDT.SALARY_BONUS) as SALARY_BONUS,
	AVG(BT17PLDT.SALARY_RETIRE) as SALARY_RETIRE,
	AVG(BT17PLDT.SALARY_KEI) as SALARY_KEI,
	AVG(BT17PLDT.ZAKKYU_SALARY) as ZAKKYU_SALARY,
	AVG(BT17PLDT.ZAKKYU_BONUS) as ZAKKYU_BONUS,
	AVG(BT17PLDT.ZAKKYU_RETIRE) as ZAKKYU_RETIRE,
	AVG(BT17PLDT.ZAKKYU_KEI) as ZAKKYU_KEI,
	AVG(BT17PLDT.KYURYO_KEI) as KYURYO_KEI,
	AVG(BT17PLDT.BONUS_KEI) as BONUS_KEI,
	AVG(BT17PLDT.RETIRE_KEI) as RETIRE_KEI,
	AVG(BT17PLDT.SALARY_UTI_KEI) as SALARY_UTI_KEI,
	AVG(BT17PLDT.KASHIIRE_UP) as KASHIIRE_UP,
	AVG(BT17PLDT.KASHIIRE_DOWN) as KASHIIRE_DOWN,
	AVG(BT17PLDT.KASHIIRE_ZANDAKA) as KASHIIRE_ZANDAKA,
	AVG(BT17PLDT.KAPPU_UP) as KAPPU_UP,
	AVG(BT17PLDT.KAPPU_DOWN) as KAPPU_DOWN,
	AVG(BT17PLDT.KAPPU_ZANDAKA) as KAPPU_ZANDAKA,
	AVG(BT17PLDT.LEASE_UP) as LEASE_UP,
	AVG(BT17PLDT.LEASE_DOWN) as LEASE_DOWN,
	AVG(BT17PLDT.LEASE_ZANDAKA) as LEASE_ZANDAKA,
	AVG(BT17PLDT.TOU_ZOUKA_KEI) as TOU_ZOUKA_KEI,
	AVG(BT17PLDT.TOU_GENSHO_KEI) as TOU_GENSHO_KEI,
	AVG(BT17PLDT.TOU_ZANDAKA_KEI) as TOU_ZANDAKA_KEI 
FROM
	BT17PLDT 
/*IF isLimit */
, BM01TENM
, BM51SVSB 
/*END*/
WHERE
    BT17PLDT.PL_TYPE = /*plType*/'1' 
and BT17PLDT.COMPANY_CD = /*companyCd*/'00'
and BT17PLDT.ONER_CD = /*onerCd*/'36478' 
and BT17PLDT.PL_YM between /*plYmZen*/'200501' and /*plYm*/'200601' 
and BT17PLDT.ERR_FLG = '0' 
/*IF isLimit */
and BT17PLDT.COMPANY_CD = BM01TENM.COMPANY_CD 
and BT17PLDT.MISE_CD = BM01TENM.MISE_CD 
and BM01TENM.COMPANY_CD = BM51SVSB.COMPANY_CD
and BM01TENM.SIBU_CD = BM51SVSB.SIBU_CD
and BM51SVSB.SV_CD = /*userId*/'00000921' 
/*END*/
/*IF isUriage == true */
and BT17PLDT.URIAGEDAKA > 0
/*END*/
GROUP BY
	BT17PLDT.PL_YM
ORDER BY 
	BT17PLDT.PL_YM