SELECT 
    RTRIM(BR01USER.USER_ID) as USER_ID,
    RTRIM(BR01USER.USER_NAME_KJ) as USER_NAME_KJ,
    RTRIM(BR01USER.USER_NAME_KANA) as USER_NAME_KANA,
    RTRIM(BR01USER.USER_ID) || 'ÅF' || RTRIM(BR01USER.USER_NAME_KJ) as USER_CD_NAME_KJ,
    RTRIM(BR01USER.BUMON_CD) as BUMON_CD,
    RTRIM(BC08CBMN.BUMON_NAME) as BUMON_NAME,
    RTRIM(BR01USER.BUMON_CD) || 'ÅF' || RTRIM(BC08CBMN.BUMON_NAME) as BUMON_CD_NAME,
    RTRIM(VIR51USER.STOP_FLG) as STOP_FLG,
    RTRIM(VIR51USER.TAISHOKU_dt) as TAISHOKU_DT
FROM  
    BR01USER LEFT OUTER JOIN BC08CBMN 
    on (BR01USER.BUMON_CD = BC08CBMN.BUMON_CD)
    INNER JOIN VIR51USER
    on (BR01USER.USER_ID = VIR51USER.USER_ID)
WHERE
    UPPER(BR01USER.USER_ID) like /*USER_ID*/
ORDER BY
    BR01USER.USER_ID