SELECT
    RTRIM(BM03USCP.USER_ID) as USER_ID,
    CASE WHEN BM03USCP.ZOKUSEI_KBN = '1' THEN 0 ELSE 1 END AS SHOZOKU_FLG,
	RTRIM(BM03USCP.ZOKUSEI_KBN) as ZOKUSEI_KBN,
    RTRIM(BC02COMP.COMPANY_NAME) as R_COMPANY_NAME,
    RTRIM(BM03USCP.R_COMPANY_CD) as R_COMPANY_CD,
    RTRIM(BM03USCP.FIRST_USER) as FIRST_USER,
    RTRIM(BM03USCP.FIRST_PGM) as FIRST_PGM,
    BM03USCP.FIRST_TMSP,
    RTRIM(BM03USCP.LAST_USER) as LAST_USER,
    RTRIM(BM03USCP.LAST_PGM) as LAST_PGM,
    BM03USCP.LAST_TMSP
FROM
    BM03USCP LEFT JOIN
    BC02COMP ON (BM03USCP.R_COMPANY_CD = BC02COMP.R_COMPANY_CD)

WHERE
	BM03USCP.USER_ID = /*user_id*/'XM000044'

ORDER BY BM03USCP.USER_ID
,        SHOZOKU_FLG