SELECT RTRIM(BC05.COMPANY_CD) as COMPANY_CD
,      RTRIM(BC05.COMPANY_NAME) as COMPANY_NAME

FROM  BC05KCOM BC05
/*IF  isForeignIn==false */
WHERE   BC05.FOREIGN_FLG <> '1'
/*END*/

ORDER BY BC05.SORT_SEQ