SELECT AITE_2
FROM BC21AITE
,    (SELECT MISE_CD,MISE_KBN,COMPANY_CD
      FROM BM01TENM
      ,   (SELECT R_COMPANY_CD
           FROM BC02COMP
           WHERE R_COMPANY_CD=/*companyCd*/'00'
           )AS BC02COMP
      WHERE MISE_CD = /*miseCd*/'02001'
      AND   COMPANY_CD = R_COMPANY_CD) BM01TENM
WHERE MISE_KBN = AITE_KBN
