SELECT
    RTRIM(COMPANY_CD) as COMPANY_CD,
    RTRIM(MISE_CD) as MISE_CD,
    RTRIM(MISE_NAME_KJ) as MISE_NAME_KJ,
    RTRIM(GYOTAI_KBN) as GYOTAI_KBN,
    RTRIM(MISE_KBN) as MISE_KBN,
    RTRIM(ONER_CD) as ONER_CD
FROM 
    BM01TENM
WHERE
    MISE_CD = /*miseCd*/
AND COMPANY_CD = /*companyCd*/ 
