SELECT DISTINCT
       RTRIM(BM06.USER_ID) as USER_ID
,      BC05.COMPANY_CD
,      RTRIM(BC05.COMPANY_NAME) as COMPANY_NAME
,      RTRIM(BM11.ONER_NAME_KJ) as ONER_NAME_KJ
,      RTRIM(BM06.ONER_CD) as ONER_CD
,      RTRIM(BM06.FIRST_USER) as FIRST_USER
,      RTRIM(BM06.FIRST_PGM) as FIRST_PGM
,      BM06.FIRST_TMSP
,      RTRIM(BM06.LAST_USER) as LAST_USER
,      RTRIM(BM06.LAST_PGM) as LAST_PGM
,      BM06.LAST_TMSP
,      CASE WHEN BM06.USER_ID IS NOT NULL THEN 'CHECKED' ELSE null END CHECK_STATUS
,      BC05.SORT_SEQ

FROM  BC02COMP BC02
    LEFT JOIN BM03USCP BM03
     ON (BM03.USER_ID = /*userId*/'99990003' AND BM03.R_COMPANY_CD= BC02.R_COMPANY_CD)
,             BC05KCOM BC05
    LEFT JOIN BM06UONR BM06
     ON (BM06.USER_ID = /*userId*/'99990001' AND BM06.COMPANY_CD= BC05.COMPANY_CD)
    LEFT JOIN BM11ONER BM11 
     ON (BM11.COMPANY_CD= BM06.COMPANY_CD AND BM11.ONER_CD= BM06.ONER_CD)
 ,     BC06COMM BC06

WHERE BC06.R_COMPANY_CD = BC02.R_COMPANY_CD
AND   BC06.COMPANY_CD   = BC05.COMPANY_CD
/*IF zokuseiKbn != null */
AND   BM03.ZOKUSEI_KBN = /*zokuseiKbn*/'2'
/*END*/
/*IF  isForeignIn==false */
AND   BC05.FOREIGN_FLG <> '1'
/*END*/

ORDER BY BC05.SORT_SEQ
