SELECT
	RTRIM(BM07.USER_ID) as USER_ID,
	RTRIM(BM07.COMPANY_CD) as COMPANY_CD,
	RTRIM(BC05.COMPANY_NAME) as COMPANY_NAME,
	RTRIM(BM07.MISE_CD) as MISE_CD,
	RTRIM(BM01.MISE_NAME_KJ) as MISE_NAME_KJ,
	RTRIM(BM07.FIRST_USER) as FIRST_USER,
	RTRIM(BM07.FIRST_PGM) as FIRST_PGM,
	BM07.FIRST_TMSP,
	RTRIM(BM07.LAST_USER) as LAST_USER,
	RTRIM(BM07.LAST_PGM) as LAST_PGM,
	BM07.LAST_TMSP

FROM BC05KCOM BC05
,    BM07UTEN BM07
LEFT JOIN BM01TENM BM01
     ON (BM07.COMPANY_CD = BM01.COMPANY_CD
         AND BM07.MISE_CD = BM01.MISE_CD )
	
WHERE BM07.USER_ID = /*user_id*/'99990003'
AND   BM07.COMPANY_CD = BC05.COMPANY_CD