SELECT
	RTRIM(BM05USGT.USER_ID) as USER_ID,
	RTRIM(BM05USGT.GYOTAI_KBN) as GYOTAI_KBN,
	RTRIM(BC09GTAI.GYOTAI_KBN_NAME) as GYOTAI_KBN_NAME,
	RTRIM(BM05USGT.FIRST_USER) as FIRST_USER,
	RTRIM(BM05USGT.FIRST_PGM) as FIRST_PGM,
	BM05USGT.FIRST_TMSP,
	RTRIM(BM05USGT.LAST_USER) as LAST_USER,
	RTRIM(BM05USGT.LAST_PGM) as LAST_PGM,
	BM05USGT.LAST_TMSP

FROM 
    BM05USGT LEFT JOIN 
    BC09GTAI ON (BM05USGT.GYOTAI_KBN= BC09GTAI.GYOTAI_KBN)

WHERE
	BM05USGT .USER_ID = /*userId*/'99990002'
ORDER BY 
	BM05USGT .USER_ID