SELECT BR67.URI_SOKU_YM
,      BR67.FRAME_KBN
,      BR67.SEQ_NO
,      RTRIM(BR67.MENU_CD) AS MENU_CD
,      RTRIM(PC10.MENU_NAME_KJ) AS MENU_NAME_KJ
,      BR67.DATA_KBN
,      RTRIM(BR67.DISP_WORD) AS DISP_WORD
,      BR67.FIRST_USER
,      BR67.FIRST_PGM
,      BR67.FIRST_TMSP
,      BR67.LAST_USER
,      BR67.LAST_PGM
,      BR67.LAST_TMSP
FROM BR67SGRP BR67
LEFT JOIN PC10SMNU PC10 ON (BR67.MENU_CD = PC10.MENU_CD)
WHERE URI_SOKU_YM = /*uriSokuYm*/'200808'
/*IF frameKbn != null */
AND FRAME_KBN = /*frameKbn*/'01'
/*END*/
ORDER BY FRAME_KBN
,      BR67.SEQ_NO