select 
	BM12.STAFF_ID,
	BM12.JOB,
	BM12.COMPANY_CD,
	BM12.ONER_CD,
	BM12.MISE_CD_1,
	rtrim(BM12.SITUATION_KBN) as SITUATION_KBN,
	rtrim(BM12.STAFF_L_NAME_KJ) as STAFF_L_NAME_KJ,
	rtrim(BM12.STAFF_F_NAME_KJ) as STAFF_F_NAME_KJ,
	rtrim(BM12.STAFF_L_NAME_KNA) as STAFF_L_NAME_KNA,
	rtrim(BM12.STAFF_F_NAME_KNA) as STAFF_F_NAME_KNA,
	rtrim(BM12.SEX) as SEX,
	rtrim(BM12.NOTE) as NOTE,
    BM12.LAST_USER,
    BM12.LAST_TMSP,
    BM12.LAST_PGM  
from
	BM12STAF BM12
where 
	BM12.STAFF_ID = /*staffId*/'36478001' 