SELECT CKANRI_NO
   ,   rtrim(TITLE) as TITLE
   ,   TARGET_FROM
   ,   TARGET_TO
FROM   BM39CPRD
WHERE  /*sysDate*/'20060920' BETWEEN TARGET_FROM AND TARGET_TO
order by TARGET_FROM DESC
   ,     CKANRI_NO DESC
