SELECT DISTINCT
       MASTER_FLG
  ,    BT71.MENU_CD 
  ,    rtrim(MENU_NAME_KJ) as MENU_NAME_KJ
  ,    RESERVE_AMT
  ,    SEQ_NO
FROM BT71CRSD BT71
,    (
    SELECT CASE WHEN BM41.CKANRI_NO IS NOT NULL THEN BM41.CKANRI_NO ELSE /*ckanriNo*/'200632' END AS CKANRI_NO
    ,      CASE WHEN BM38.MENU_CD IS NOT NULL THEN BM38.MISE_CD ELSE /*miseCd*/'00080' END AS MISE_CD 
    ,      CASE WHEN BM38.MENU_CD IS NOT NULL THEN BM38.MENU_CD ELSE BM41.MENU_CD END AS MENU_CD
    ,      CASE WHEN BM38.MENU_CD IS NOT NULL THEN BM38.MENU_NAME_KJ ELSE '' END AS MENU_NAME_KJ
    ,      CASE WHEN BM41.MENU_CD IS NOT NULL THEN '1' ELSE '0' END AS MASTER_FLG
    ,      MENU_GROUP
    ,      SUM_GROUP
    FROM (
        SELECT MISE_CD 
        ,    MENU_CD
        ,    MENU_NAME_KJ
        FROM BM38MMNU
        WHERE  COMPANY_CD =/*companyCd*/'00'
        AND    MISE_CD  = /*miseCd*/'00080'
         ) BM38
    FULL OUTER JOIN (
        SELECT MENU_CD
        ,      CKANRI_NO
        ,      MENU_GROUP
        ,      SUM_GROUP
        FROM BM41CMNU
        WHERE CKANRI_NO = /*ckanriNo*/'200632'
        ) BM41
        ON (BM38.MENU_CD = BM41.MENU_CD)
) SUB
WHERE BT71.CKANRI_NO = SUB.CKANRI_NO
AND   BT71.COMPANY_CD = '00'
AND   BT71.MISE_CD = SUB.MISE_CD
AND   BT71.MENU_CD = SUB.MENU_CD
AND   BT71.SEQ_NO = /*seqNo*/51
AND   BT71.RESERVE_AMT > 0
ORDER BY MASTER_FLG DESC
      ,  BT71.MENU_CD
