select   mise_cd
,        oner_cd
,        pl_ym
,        uriagedaka
,        uriagegenka
,        uriage_so_rieki
,        salary
,        yachin
,        suikou_hi
,        royalty
,        tesuryo
,        koukoku 
,        shoumou
,        houtei_fukuri
,        fukuri_kousei
,        kousai
,        ryohi
,        tusin
,        lease
,        sharyo
,        sozei
,        hoken
,        unchin
,        shuzen
,        yobi
,        zappi
,        keihi_shokei
,        shokyaku_rieki
,        genka_shokyaku
,        eigai_shueki
,        eigai_hiyo
,        honshahi_hai
,        rieki
,        uriage
,        buppan
,        uri_uchiwake
,        elec
,        gas
,        water
,        sonota
,        suikou_uchiwake
,        genzairyo_kei
,        genzairyo_shire
,        genzairyo_zaiko
,        yasai_kei
,        yasai_shire
,        yasai_zaiko
,        houzai_kei
,        houzai_shire
,        houzai_zaiko
,        buppan_kei
,        buppan_shire
,        buppan_zaiko
,        tou_siire_kei
,        tou_zaiko_kei
,        sashihiki_kei
,        yakuin_salary
,        yakuin_bonus
,        yakuin_retire
,        yakuin_kei
,        salary_salary
,        salary_bonus
,        salary_retire
,        salary_kei
,        zakkyu_salary
,        zakkyu_bonus
,        zakkyu_retire
,        zakkyu_kei
,        kyuryo_kei
,        bonus_kei
,        retire_kei
,        salary_uti_kei
,        kashiire_up
,        kashiire_down
,        kashiire_zandaka
,        kappu_up
,        kappu_down
,        kappu_zandaka
,        lease_up
,        lease_down
,        lease_zandaka
,        tou_zouka_kei
,        tou_gensho_kei
,        tou_zandaka_kei
from     bt17pldt
where    oner_cd = /*onerCd*/'36378'
and      company_cd = /*companyCd*/'00'
and      pl_ym between /*fromDt*/'200601' and /*toDt*/'200603'
and      err_flg = '0'
order by oner_cd
,        mise_cd
,        pl_ym