select   pl_ym
,        round(avg(uriagedaka),2) as uriagedaka
,        round(avg(uriagegenka),2) as uriagegenka
,        round(avg(uriage_so_rieki),2) as uriage_so_rieki
,        round(avg(salary),2) as salary
,        round(avg(yachin),2) as yachin
,        round(avg(suikou_hi),2) as suikou_hi
,        round(avg(royalty),2) as royalty
,        round(avg(tesuryo),2) as tesuryo
,        round(avg(koukoku ),2) as koukoku 
,        round(avg(shoumou),2) as shoumou
,        round(avg(houtei_fukuri),2) as houtei_fukuri
,        round(avg(fukuri_kousei),2) as fukuri_kousei
,        round(avg(kousai),2) as kousai
,        round(avg(ryohi),2) as ryohi
,        round(avg(tusin),2) as tusin
,        round(avg(lease),2) as lease
,        round(avg(sharyo),2) as sharyo
,        round(avg(sozei),2) as sozei
,        round(avg(hoken),2) as hoken
,        round(avg(unchin),2) as unchin
,        round(avg(shuzen),2) as shuzen
,        round(avg(yobi),2) as yobi
,        round(avg(zappi),2) as zappi
,        round(avg(keihi_shokei),2) as keihi_shokei
,        round(avg(shokyaku_rieki),2) as shokyaku_rieki
,        round(avg(genka_shokyaku),2) as genka_shokyaku
,        round(avg(eigai_shueki),2) as eigai_shueki
,        round(avg(eigai_hiyo),2) as eigai_hiyo
,        round(avg(honshahi_hai),2) as honshahi_hai
,        round(avg(rieki),2) as rieki
,        round(avg(uriage),2) as uriage
,        round(avg(buppan),2) as buppan
,        round(avg(uri_uchiwake),2) as uri_uchiwake
,        round(avg(elec),2) as elec
,        round(avg(gas),2) as gas
,        round(avg(water),2) as water
,        round(avg(sonota),2) as sonota
,        round(avg(suikou_uchiwake),2) as suikou_uchiwake
,        round(avg(genzairyo_kei),2) as genzairyo_kei
,        round(avg(genzairyo_shire),2) as genzairyo_shire
,        round(avg(genzairyo_zaiko),2) as genzairyo_zaiko
,        round(avg(yasai_kei),2) as yasai_kei
,        round(avg(yasai_shire),2) as yasai_shire
,        round(avg(yasai_zaiko),2) as yasai_zaiko
,        round(avg(houzai_kei),2) as houzai_kei
,        round(avg(houzai_shire),2) as houzai_shire
,        round(avg(houzai_zaiko),2) as houzai_zaiko
,        round(avg(buppan_kei),2) as buppan_kei
,        round(avg(buppan_shire),2) as buppan_shire
,        round(avg(buppan_zaiko),2) as buppan_zaiko
,        round(avg(tou_siire_kei),2) as tou_siire_kei
,        round(avg(tou_zaiko_kei),2) as tou_zaiko_kei
,        round(avg(sashihiki_kei),2) as sashihiki_kei
,        round(avg(yakuin_salary),2) as yakuin_salary
,        round(avg(yakuin_bonus),2) as yakuin_bonus
,        round(avg(yakuin_retire),2) as yakuin_retire
,        round(avg(yakuin_kei),2) as yakuin_kei
,        round(avg(salary_salary),2) as salary_salary
,        round(avg(salary_bonus),2) as salary_bonus
,        round(avg(salary_retire),2) as salary_retire
,        round(avg(salary_kei),2) as salary_kei
,        round(avg(zakkyu_salary),2) as zakkyu_salary
,        round(avg(zakkyu_bonus),2) as zakkyu_bonus
,        round(avg(zakkyu_retire),2) as zakkyu_retire
,        round(avg(zakkyu_kei),2) as zakkyu_kei
,        round(avg(kyuryo_kei),2) as kyuryo_kei
,        round(avg(bonus_kei),2) as bonus_kei
,        round(avg(retire_kei),2) as retire_kei
,        round(avg(salary_uti_kei),2) as salary_uti_kei
,        round(avg(kashiire_up),2) as kashiire_up
,        round(avg(kashiire_down),2) as kashiire_down
,        round(avg(kashiire_zandaka),2) as kashiire_zandaka
,        round(avg(kappu_up),2) as kappu_up
,        round(avg(kappu_down),2) as kappu_down
,        round(avg(kappu_zandaka),2) as kappu_zandaka
,        round(avg(lease_up),2) as lease_up
,        round(avg(lease_down),2) as lease_down
,        round(avg(lease_zandaka),2) as lease_zandaka
,        round(avg(tou_zouka_kei),2) as tou_zouka_kei
,        round(avg(tou_gensho_kei),2) as tou_gensho_kei
,        round(avg(tou_zandaka_kei),2) as tou_zandaka_kei
from     bm01tenm as bm01
,        bt17pldt as bt17
where    bm01.mise_cd = bt17.mise_cd
and      bm01.company_cd = bt17.company_cd
and      bm01.company_cd = /*companyCd*/'00'
and      bm01.gyotai_kbn in /*gyotaiKbnList*/('010','013')
and      pl_ym between /*fromDt*/'200601' and /*toDt*/'200603'
and      err_flg = '0'
group by pl_ym
order by pl_ym