SELECT BR17.ENTRY_CD
,      BR17.ENTRY_YEAR
,      BR17.ENTRY_KAI
,      ENTRY.FROM_DT AS KAISAI_FROM_DT
,      ENTRY.TO_DT AS KAISAI_TO_DT
,      BR17.ENTRY_TITLE AS ENTRY_TITLE
,      HONBU.FROM_DT AS HONBU_FROM_DT
,      HONBU.TO_DT AS HONBU_TO_DT
,      ONER.FROM_DT AS ONER_FROM_DT
,      ONER.TO_DT AS ONER_TO_DT
,      DECIMAL(CASE WHEN BT20.ATTEND_CNT IS NULL THEN 0 ELSE BT20.ATTEND_CNT END, 6,0) AS ONER_ATTEND_CNT
,      DECIMAL(CASE WHEN BT20.ABSENT_CNT IS NULL THEN 0 ELSE BT20.ABSENT_CNT END, 6,0) AS ONER_ABSENT_CNT

FROM BR17ENTL BR17
     
JOIN (SELECT * FROM BR18ENTD WHERE USERTYPE_CD = '99' AND DAY_KBN = '01') ENTRY
  ON (ENTRY.ENTRY_CD = BR17.ENTRY_CD AND ENTRY.ENTRY_YEAR = BR17.ENTRY_YEAR AND ENTRY.ENTRY_KAI = BR17.ENTRY_KAI)

JOIN (SELECT * FROM BR18ENTD WHERE USERTYPE_CD = '01' AND DAY_KBN = '04') HONBU
  ON (HONBU.ENTRY_CD = BR17.ENTRY_CD AND HONBU.ENTRY_YEAR = BR17.ENTRY_YEAR AND HONBU.ENTRY_KAI = BR17.ENTRY_KAI)

JOIN (SELECT * FROM BR18ENTD WHERE USERTYPE_CD = '02' AND DAY_KBN = '04') ONER
  ON (ONER.ENTRY_CD = BR17.ENTRY_CD AND ONER.ENTRY_YEAR = BR17.ENTRY_YEAR AND ONER.ENTRY_KAI = BR17.ENTRY_KAI)

LEFT JOIN (
          SELECT ENTRY_CD
          ,      ENTRY_YEAR
          ,      ENTRY_KAI
          ,      SUM(CASE WHEN ENTRY_FLG = '1' THEN 1 ELSE 0 END) AS ATTEND_CNT
          ,      SUM(CASE WHEN ENTRY_FLG != '1' THEN 1 ELSE 0 END) AS ABSENT_CNT
          FROM BT20ENON BT20
          ,    (SELECT MISE.COMPANY_CD
                  ,    MISE.ONER_CD 
                  FROM BM11ONER ONER
                  ,    BM01TENM MISE
                  WHERE ONER.ONER_CD     != '39999' 
                  AND   ONER.KEIYAKU_STA <= /*sysDate*/'20061213'
                  AND   ONER.KEIYAKU_END >= /*sysDate*/'20061213'
                  AND   MISE.COMPANY_CD   = ONER.COMPANY_CD
                  AND   MISE.ONER_CD   = ONER.ONER_CD
                  GROUP BY MISE.COMPANY_CD
                  ,        MISE.ONER_CD 
               ) BM11
          WHERE BT20.ENTRY_CD     = /*entryCd*/'25'
          AND   BT20.ENTRY_YEAR   = /*entryYear*/'2005'
          AND   BT20.ENTRY_KAI    = /*entryKai*/'001'
          AND   BT20.COMPANY_CD   = BM11.COMPANY_CD 
          AND   BT20.ONER_CD      = BM11.ONER_CD
          GROUP BY ENTRY_CD
          ,        ENTRY_YEAR
          ,        ENTRY_KAI
          ) BT20
  ON (BT20.ENTRY_CD   = BR17.ENTRY_CD 
  AND BT20.ENTRY_YEAR = BR17.ENTRY_YEAR 
  AND BT20.ENTRY_KAI  = BR17.ENTRY_KAI)

WHERE SAKUJO_FLG <> '1'
AND   BR17.ENTRY_CD   = /*entryCd*/'25'
AND   BR17.ENTRY_YEAR = /*entryYear*/'2006'
AND   BR17.ENTRY_KAI  = /*entryKai*/'012'
