SELECT
	BT49LONG.ENTRY_CD,
	BT49LONG.ENTRY_YEAR,
	BT49LONG.ENTRY_KAI,
	BT49LONG.COMPANY_CD,
	BT49LONG.ONER_CD,
	BT49LONG.SEQ_NO,
	BT49LONG.MISE_CD,
	BT49LONG.L_NAME_KJ,
	BT49LONG.F_NAME_KJ,
	BT49LONG.L_NAME_RM,
	BT49LONG.F_NAME_RM,
	BT49LONG.SEX,
	BT49LONG.BIRTHDAY,
	BT49LONG.AGE,
	BT49LONG.ENTRY_DATE,
	BT49LONG.EXP_KBN,
	BT49LONG.NOTE,
	BT49LONG.FIRST_USER,
	BT49LONG.FIRST_PGM,
	BT49LONG.FIRST_TMSP,
	BT49LONG.LAST_USER,
	BT49LONG.LAST_PGM,
	BT49LONG.LAST_TMSP
,   SUBSTR(BT49LONG.EXP_KBN, 1,1) AS STAFF_TYPE
,	CASE WHEN SUBSTR(BT49LONG.EXP_KBN, 1,1) = 'E' THEN SUBSTR(BT49LONG.EXP_KBN, 2,2) ELSE '' END AS EMPLOYEE_YEARS
,	CASE WHEN SUBSTR(BT49LONG.EXP_KBN, 1,1) = 'P' THEN SUBSTR(BT49LONG.EXP_KBN, 2,2) ELSE '' END AS PARTTIMER_YEARS
FROM
    BT49LONG
WHERE 
	BT49LONG.ENTRY_CD = /*entryCd*/'20' AND
    BT49LONG.ENTRY_YEAR = /*entryYear*/'2009' AND
    BT49LONG.ENTRY_KAI = /*entryKai*/'001' AND
    BT49LONG.COMPANY_CD = /*companyCd*/'00' AND
    BT49LONG.ONER_CD = /*onerCd*/'36907'   
ORDER BY
	BT49LONG.SEQ_NO
