select 
BT51POSD.CRE_DT,
BT51POSD.MISE_CD,
BT51POSD.DATA_KBN,
BT51POSD.DATA_NO,
BT51POSD.DATA 
, BM01TENM.SIBU_CD
from 
BT51POSD join BM01TENM on (
BM01TENM.COMPANY_CD = /*companyCd*/ and 
BM01TENM.ONER_CD = /*onerId*/ 
) 
where 
BT51POSD.COMPANY_CD = /*companyCd*/ and 
BT51POSD.CRE_DT = /*dataDt*/ and 
BT51POSD.MISE_CD = BM01TENM.MISE_CD 
ORDER BY 
BT51POSD.CRE_DT,
BT51POSD.MISE_CD,
BT51POSD.DATA_KBN,
BT51POSD.DATA_NO
