SELECT
    BM12.COMPANY_CD,
    BM12.MISE_CD_1,
    BM01.MISE_NAME_KJ,
    BM01.CLOSE_DT,
    BM12.STAFF_ID,
    BM12.ONER_CD,
    BM12.OLD_ONER_CD,
    BM12.STAFF_L_NAME_KJ,
    BM12.STAFF_F_NAME_KJ,
    BM12.STAFF_L_NAME_KNA,
    BM12.STAFF_F_NAME_KNA,
    BM12.SITUATION_KBN,
    BM12.MOVE_DT,
    BM12.LAST_USER,
    BM12.LAST_PGM,
    BM12.LAST_TMSP,
    BT26.LICENSE_NO

FROM
    BM12STAF as BM12 
    inner join BM01TENM as BM01 on BM12.COMPANY_CD = BM01.COMPANY_CD and
                                   BM12.ONER_CD = BM01.ONER_CD
    left join BT26UPJK as BT26 on BM12.STAFF_ID = BT26.STAFF_ID

WHERE
    BM12.COMPANY_CD = /*companyCd*/'00' AND
    BM12.ONER_CD = /*onerCd*/'36478'AND
    BM12.MISE_CD_1 = BM01.MISE_CD

ORDER BY
    BM12.MISE_CD_1, 
    HEX(BM12.STAFF_L_NAME_KNA),
    HEX(BM12.STAFF_F_NAME_KNA),
    BT26.LICENSE_NO
