SELECT 
    COMPANY_CD
   ,SEGMENT_TYPE AS HYOJITAISHO_CD
   ,RTRIM(SEGMENT_NAME) AS HYOJITAISHO_NAME
   ,DESCRIPTION
   ,SORT_SEQ
FROM 
    BM08SGTP
WHERE 
    COMPANY_CD =/*companyCd*/'00'
ORDER BY 
    SORT_SEQ
