SELECT    MISE_MST.COMPANY_CD
,         MISE_MST.SIBU_CD
,         MISE_MST.SIBU_NAME
,         MISE_MST.BLOCK_CD
,         MISE_MST.BLOCK_NAME
,         MISE_MST.MISE_CD
,         MISE_MST.MISE_NAME_KJ
,         DATA.KBN1
/*IF taishoKikan.equals("DAY1")*/
,         DATA.TENKO_KBN
,         DATA.TENKO_KBN_ZEN
/*END*/
,         BM50.SV_CD
,         BM50.USERNAMEKJ
,         DATA.URIAGE
,         DATA.URIAGE_ZEN
,         DATA.YOSAN
,         DATA.KYAKUSU
,         DATA.KYAKUSU_ZEN
,         DATA.OPEN_KBN
,         DATA.OPEN_KBN_ZEN
,         DATA.EIGYO_DAYS
,         DATA.ISSUE_CNT
,         DATA.CHARGE_KIN
,         DATA.CHARGE_KEN
,         DATA.KESSAI_KIN
,         DATA.KESSAI_KEN
,         DATA.CHARGE_KIN_CANCEL
,         DATA.CHARGE_KEN_CANCEL
,         DATA.USE_KIN_CANCEL
,         DATA.USE_KEN_CANCEL
,         DATA.BONUS_V_ISSUE
,         DATA.BONUS_V_USE
,         DATA.COUPON_V_ISSUE
,         DATA.COUPON_V_USE
,         DATA.ZANDAKA
,         DATA.EIGYO_DAYS_ZEN
,         DATA.ZEN_ISSUE_CNT
,         DATA.ZEN_CHARGE_KIN
,         DATA.ZEN_CHARGE_KEN
,         DATA.ZEN_KESSAI_KIN
,         DATA.ZEN_KESSAI_KEN
FROM (
	SELECT    BM01.COMPANY_CD
	,         BM10.SIBU_CD
	,         BM10.SIBU_NAME
	,         (CASE WHEN length(ltrim(rtrim(BM01.BLOCK_CD))) = 0 then '001' else BM01.BLOCK_CD END) AS BLOCK_CD
	,         (CASE WHEN length(ltrim(rtrim(BM01.BLOCK_CD))) = 0 then '' else BC23.BLOCK_NAME END) AS BLOCK_NAME
	,         BM01.MISE_CD
	,         BM01.MISE_NAME_KJ
	FROM BM01TENM AS BM01
	LEFT JOIN BC23BLCK AS BC23
	          ON (BM01.BLOCK_CD = BC23.BLOCK_CD)
	,    BM10GSIB AS BM10
	WHERE  BM01.COMPANY_CD = /*companyCd*/'00'
	AND    BM01.COMPANY_CD = BM10.COMPANY_CD
/*IF userType == "02" */
    AND    BM01.ONER_CD IN (
                SELECT ONER_CD 
                FROM BM06UONR
                WHERE COMPANY_CD = /*companyCd*/'00'
                AND   USER_ID = /*userId*/'99990002'
                )
/*END*/
/*IF areaDaiFlg.equals("AREA_DAI_CD")*/
  AND       BM01.AREA_DAI= BM10.SIBU_CD
-- ELSE
  AND       BM01.SIBU_CD = BM10.SIBU_CD
/*END*/

/*IF areaDaiFlg.equals("AREA_DAI_CD")*/
  AND       BM10.AREA_DAI_FLG = '1'
/*END*/
/*IF taishoJoken.equals("SLAREA")*/
  AND       BM10.slarea_CD = /*hyojiTaisho*/'10001'
/*END*/
/*IF taishoJoken.equals("JIGYOU")*/
  AND       BM10.jigyou_CD = /*hyojiTaisho*/'11000'
/*END*/
/*IF taishoJoken.equals("HONBU")*/
  AND       BM10.HONBU_CD = /*hyojiTaisho*/'10000'
/*END*/

/*IF taishoJoken.equals("SIBU")*/
  AND       BM10.SIBU_CD = /*hyojiTaisho*/'022'
/*END*/

/*IF taishoJoken.equals("GYOTAI")*/
	AND       BM01.GYOTAI_KBN IN (
	                SELECT GYOTAI_KBN
	                FROM   BM09GTSG
	                WHERE  SEGMENT_TYPE =/*hyojiTaisho*/'M'
                              )
/*END*/
/*IF limitFlg == true*/
	AND       BM01.SIBU_CD IN (
	                SELECT   BM51.SIBU_CD
	                FROM     BM51SVSB AS BM51
	                WHERE    BM51.COMPANY_CD = /*companyCd*/'00'
	                AND      BM51.SV_CD      = /*userId*/'00000921'
	                GROUP BY BM51.SIBU_CD
	                          )
/*END*/

/*IF areaDaiFlg.equals("SV_CD")*/
	AND       BM01.MISE_CD IN (
	                SELECT   BM50.MISE_CD
	                FROM     BM50TANM AS BM50
	                WHERE    BM50.COMPANY_CD = /*companyCd*/'00'
	                AND      BM50.SV_CD      = /*svCd*/'00000921'
	                          )                         
/*END*/

/*IF !taishoTenpo.equals("ALL")*/
       /*IF taishoTenpo.equals("FC")*/
	AND       BM01.MISE_KBN like '_1_'
       -- ELSE
	AND       BM01.MISE_KBN like '_2_'
       /*END*/
/*END*/
) AS MISE_MST
,    (
	SELECT (CASE WHEN URIAGE60.COMPANY_CD IS NOT NULL THEN URIAGE60.COMPANY_CD
	             ELSE YOSAN45.COMPANY_CD END) AS COMPANY_CD
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.MISE_CD
	             ELSE YOSAN45.MISE_CD END) AS MISE_CD
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.KBN1
	             ELSE YOSAN45.TENPO_SHU END) AS KBN1
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.URIAGE ELSE 0 END) AS URIAGE
	,      (CASE WHEN YOSAN45.MISE_CD IS NOT NULL THEN YOSAN45.YOSAN
	             ELSE 0 END) AS YOSAN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.URIAGE_ZEN ELSE 0 END) AS URIAGE_ZEN
/*IF taishoKikan.equals("DAY1")*/
/*END*/
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.KYAKUSU ELSE 0 END) AS KYAKUSU
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.KYAKUSU_ZEN ELSE 0 END) AS KYAKUSU_ZEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.OPEN_KBN ELSE 0 END) AS OPEN_KBN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.OPEN_KBN_ZEN ELSE 0 END) AS OPEN_KBN_ZEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.TENKO_KBN ELSE 0 END) AS TENKO_KBN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.EIGYO_DAYS ELSE 0 END) AS EIGYO_DAYS
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.ISSUE_CNT ELSE 0 END) AS ISSUE_CNT
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.CHARGE_KIN ELSE 0 END) AS CHARGE_KIN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.CHARGE_KEN ELSE 0 END) AS CHARGE_KEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.KESSAI_KIN ELSE 0 END) AS KESSAI_KIN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.KESSAI_KEN ELSE 0 END) AS KESSAI_KEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.TENKO_KBN_ZEN ELSE 0 END) AS TENKO_KBN_ZEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.EIGYO_DAYS_ZEN ELSE 0 END) AS EIGYO_DAYS_ZEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.ZEN_ISSUE_CNT ELSE 0 END) AS ZEN_ISSUE_CNT
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.CHARGE_KIN_CANCEL ELSE 0 END) AS CHARGE_KIN_CANCEL
    ,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.CHARGE_KEN_CANCEL ELSE 0 END) AS CHARGE_KEN_CANCEL
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.USE_KIN_CANCEL ELSE 0 END) AS USE_KIN_CANCEL
    ,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.USE_KEN_CANCEL ELSE 0 END) AS USE_KEN_CANCEL	    
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.BONUS_V_ISSUE ELSE 0 END) AS BONUS_V_ISSUE
    ,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.BONUS_V_USE ELSE 0 END) AS BONUS_V_USE
    ,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.COUPON_V_ISSUE ELSE 0 END) AS COUPON_V_ISSUE
    ,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.COUPON_V_USE ELSE 0 END) AS COUPON_V_USE
    ,      (CASE WHEN URIAGE60.ZANDAKA IS NOT NULL THEN URIAGE60.ZANDAKA ELSE 0 END) AS ZANDAKA
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.ZEN_CHARGE_KIN ELSE 0 END) AS ZEN_CHARGE_KIN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.ZEN_CHARGE_KEN ELSE 0 END) AS ZEN_CHARGE_KEN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.ZEN_KESSAI_KIN ELSE 0 END) AS ZEN_KESSAI_KIN
	,      (CASE WHEN URIAGE60.MISE_CD IS NOT NULL THEN URIAGE60.ZEN_KESSAI_KEN ELSE 0 END) AS ZEN_KESSAI_KEN
	FROM   (
		SELECT BT45.COMPANY_CD
		,      BT45.MISE_CD
		,      MIN(BT45.TENPO_SHU) AS TENPO_SHU
		,      SUM(BT45.YOSAN) AS YOSAN
		FROM  BT45DSJY AS BT45
		WHERE BT45.COMPANY_CD = /*companyCd*/'00'
		AND   BT45.YOSAN <> 0
	/*IF !taishoTenpo.equals("ALL")*/
   	    /*IF taishoTenpo.equals("FC")*/
		AND       BT45.FC_RC = '1'
       -- ELSE
		AND       BT45.FC_RC = '2'
       /*END*/
	/*END*/
	/*IF taishoJoken.equals("SIBU")*/
/*IF areaDaiFlg.equals("AREA_DAI_CD")*/
  AND       BT45.AREA_DAI= /*hyojiTaisho*/'022'
-- ELSE
  AND       BT45.SIBU_CD = /*hyojiTaisho*/'022'
/*END*/
	/*END*/
	/*IF taishoKikan.equals("DAY1")*/ 
		AND   BT45.YOSAN_DT = /*kikanFrom*/'20060405'
	/*END*/

	/*IF taishoKikan.equals("DAYS") || taishoKikan.equals("APPMONTH") */ 
		AND   BT45.YOSAN_DT between /*kikanFrom*/'20060401' AND /*kikanTo*/'20060430'
	/*END*/

	/*IF limitFlg == true*/
		AND   BT45.SIBU_CD in (
		         SELECT   BM51.SIBU_CD
		         FROM     BM51SVSB BM51
		         WHERE  BM51.COMPANY_CD = /*companyCd*/'00'
		         AND    BM51.SV_CD      = /*userId*/'9999000a'
		         GROUP BY BM51.SIBU_CD
		    )
	/*END*/
	
	/*IF areaDaiFlg.equals("SV_CD")*/
	    AND   BT45.MISE_CD IN (
	             SELECT   BM50.MISE_CD
	             FROM     BM50TANM AS BM50
	             WHERE    BM50.COMPANY_CD = /*companyCd*/'00'
	             AND      BM50.SV_CD      = /*svCd*/'00000921'
	        )
    /*END*/

	/*IF !tenpoShu.equals("ALL")*/
	   /*IF tenpoShu.equals("2")*/
		AND   (BT45.TENPO_SHU = '1' or BT45.TENPO_SHU = '2')
	   -- ELSE
		AND   BT45.TENPO_SHU = /*tenpoShu*/'1'
	   /*END*/
	/*END*/
		GROUP BY BT45.COMPANY_CD
		,      BT45.MISE_CD

	/*END*/
	) YOSAN45
	full outer join (
		select  bd35.COMPANY_CD
		,       bd35.MISE_CD
		,       MAX(BN01.KBN1) AS KBN1
		,       MAX(bd35.TENKO_KBN) AS TENKO_KBN
		,       SUM(bd35.URIAGE) AS URIAGE
		,       SUM(bd35.CHARGE_KIN_CANCEL) AS CHARGE_KIN_CANCEL
		,       SUM(bd35.CHARGE_KEN_CANCEL) AS CHARGE_KEN_CANCEL
		,       SUM(bd35.USE_KIN_CANCEL) AS USE_KIN_CANCEL
		,       SUM(bd35.USE_KEN_CANCEL) AS USE_KEN_CANCEL
		,       SUM(bd35.BONUS_V_ISSUE) AS BONUS_V_ISSUE
		,       SUM(bd35.BONUS_V_USE) AS BONUS_V_USE
		,       SUM(bd35.COUPON_V_ISSUE) AS COUPON_V_ISSUE
		,       SUM(bd35.COUPON_V_USE) AS COUPON_V_USE
		,       SUM(bd35.ISSUE_CNT) AS ISSUE_CNT
		,       SUM(bd35.CHARGE_KIN) AS CHARGE_KIN
		,       SUM(bd35.CHARGE_KEN) AS CHARGE_KEN
		,       SUM(bd35.KESSAI_KIN) AS KESSAI_KIN
		,       SUM(bd35.KESSAI_KEN) AS KESSAI_KEN
	/*IF userType.equals("01") */
		,       SUM(bd35.URI_YOSAN) AS YOSAN
	--ELSE
		,       SUM(bd35.ONER_YOSAN) AS YOSAN
	/*END*/
		,       SUM(bd35.KYAKUSU) AS KYAKUSU
		,       MAX(bd35.OPEN_KBN) AS OPEN_KBN
		,       SUM(bd35.EIGYO_DAYS) AS EIGYO_DAYS
	/*IF dataShu.equals("HOSEI")*/
		,       SUM(bd35.DOGETU_ZEN_URIAGE)     AS URIAGE_ZEN
		,       SUM(bd35.DOGETU_ZEN_KYAKUSU)    AS KYAKUSU_ZEN
		,       SUM(bd35.DOGETU_ZEN_EIGYO_DAYS) AS EIGYO_DAYS_ZEN
		,       MAX(bd35.DOGETU_ZEN_TENKO_KBN)  AS TENKO_KBN_ZEN
		,       MAX(bd35.DOGETU_ZEN_OPEN_KBN)   AS OPEN_KBN_ZEN
		,       SUM(bd35.DOGETU_ZEN_ISSUE_CNT)  AS ZEN_ISSUE_CNT
		,       SUM(bd35.DOGETU_ZEN_CHARGE_KIN) AS ZEN_CHARGE_KIN
		,       SUM(bd35.DOGETU_ZEN_CHARGE_KEN) AS ZEN_CHARGE_KEN
		,       SUM(bd35.DOGETU_ZEN_KESSAI_KIN) AS ZEN_KESSAI_KIN
		,       SUM(bd35.DOGETU_ZEN_KESSAI_KEN) AS ZEN_KESSAI_KEN
	--ELSE
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_URIAGE)     AS URIAGE_ZEN
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_KYAKUSU)    AS KYAKUSU_ZEN
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_EIGYO_DAYS) AS EIGYO_DAYS_ZEN
		,       MAX(bd35./*$dataShu*/'DOGETU'_ZEN_TENKO_KBN)  AS TENKO_KBN_ZEN
		,       MAX(bd35./*$dataShu*/'DOGETU'_ZEN_OPEN_KBN)   AS OPEN_KBN_ZEN
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_ISSUE_CNT)  AS ZEN_ISSUE_CNT
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_CHARGE_KIN) AS ZEN_CHARGE_KIN
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_CHARGE_KEN) AS ZEN_CHARGE_KEN
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_KESSAI_KIN) AS ZEN_KESSAI_KIN
		,       SUM(bd35./*$dataShu*/'DOGETU'_ZEN_KESSAI_KEN) AS ZEN_KESSAI_KEN
	/*END*/
	    ,       (CASE WHEN MAXDT.ZANDAKA IS NOT NULL THEN MAXDT.ZANDAKA ELSE 0 END) AS ZANDAKA
		FROM    bd35znmc AS bd35
	    LEFT JOIN (
	         SELECT MAX3.EIGYO_DT
	         ,      MAX3.COMPANY_CD
	         ,      MAX3.MISE_CD
	         ,      MAX3.ZANDAKA
	         FROM (SELECT MAX(BD3.EIGYO_DT) AS EIGYO_DT
	               ,      BD3.COMPANY_CD
	               ,      BD3.MISE_CD
	               FROM BD35ZNMC BD3
	/*IF taishoKikan.equals("DAYS") || taishoKikan.equals("APPMONTH") */
	               WHERE BD3.EIGYO_DT between /*kikanFrom*/'20060530' and /*kikanTo*/'20060601'
	--ELSE
	               WHERE BD3.EIGYO_DT = /*kikanFrom*/'201303'
	/*END*/
	               AND   BD3.COMPANY_CD = /*companyCd*/'00'
	               AND   BD3.OPEN_KBN   =1
	               AND   BD3.oldm_flg   = '0'
	               GROUP BY BD3.COMPANY_CD
	               ,      BD3.MISE_CD
	           ) GETMT
	        ,    BD35ZNMC MAX3
	        WHERE MAX3.EIGYO_DT   = GETMT.EIGYO_DT
	        AND   MAX3.COMPANY_CD = GETMT.COMPANY_CD
	        AND   MAX3.MISE_CD    = GETMT.MISE_CD
		    GROUP BY MAX3.EIGYO_DT
	        ,        MAX3.COMPANY_CD
	        ,        MAX3.MISE_CD
	        ,        MAX3.ZANDAKA
	        ) MAXDT  
	        ON (     MAXDT.COMPANY_CD = bd35.COMPANY_CD
                AND MAXDT.MISE_CD    = bd35.MISE_CD)
		,       BN01DTEN AS BN01
	    
	    WHERE   bd35.COMPANY_CD = /*companyCd*/'00'
		AND     bd35.COMPANY_CD = BN01.COMPANY_CD
		AND     bd35.MISE_CD    = BN01.MISE_CD
		AND     bd35.OLDM_FLG   = '0'
	/*IF taishoKikan.equals("DAY1")*/ 
		AND     bd35.EIGYO_DT   = /*kikanFrom*/'20060704'
	/*END*/
	/*IF taishoKikan.equals("DAYS") || taishoKikan.equals("APPMONTH") */ 
		AND     bd35.EIGYO_DT between /*kikanFrom*/'20060401' AND /*kikanTo*/'20060430'
	/*END*/
		AND     bd35.EIGYO_DT   = BN01.EIGYO_DT

	/*IF tenpoShu.equals("ALL")*/
		AND     (bd35.OPEN_KBN = 1 or bd35.DOGETU_ZEN_OPEN_KBN = 1)
	-- ELSE
		AND     bd35.OPEN_KBN = 1
	/*END*/

	/*IF dataShu.equals("HOSEI")*/
		AND     (bd35.URIAGE > 0 AND bd35.DOGETU_ZEN_URIAGE > 0)
	/*END*/
	/*IF !tenpoShu.equals("ALL")*/
	    /*IF tenpoShu.equals("2")*/
		AND     (BN01.KBN1 = '1' or BN01.KBN1 = '2')
	    -- ELSE
		AND     BN01.KBN1 = /*tenpoShu*/'1'
	    /*END*/
	/*END*/
	    AND      bd35.honbu_kbn = '0'
		GROUP BY bd35.COMPANY_CD
		,        bd35.MISE_CD
		,        (CASE WHEN MAXDT.ZANDAKA IS NOT NULL THEN MAXDT.ZANDAKA ELSE 0 END)
	) AS URIAGE60
	ON (        URIAGE60.COMPANY_CD = YOSAN45.COMPANY_CD
			AND URIAGE60.MISE_CD    = YOSAN45.MISE_CD
	   )
    ) DATA left join 
        (select BM50.COMPANY_CD, BM50.MISE_CD , BM50.sv_cd , rtrim(BR01.user_name_kj) as usernamekj
         from BM50TANM as BM50, BR01USER as BR01
         where BM50.sv_cd = BR01.USER_ID ) BM50

     on (DATA.COMPANY_CD = BM50.COMPANY_CD
     and DATA.MISE_CD = BM50.MISE_CD)
WHERE DATA.COMPANY_CD = MISE_MST.COMPANY_CD
AND   DATA.MISE_CD    = MISE_MST.MISE_CD
/*IF areaDaiFlg.equals("AREA_DAI_CD")*/
order by  MISE_MST.COMPANY_CD
,         MISE_MST.MISE_CD
-- ELSE
order by  MISE_MST.COMPANY_CD
,         MISE_MST.SIBU_CD
,         MISE_MST.BLOCK_CD
,         MISE_MST.MISE_CD
/*END*/
