select 
	BT22.ENTRY_CD,
	BT22.ENTRY_YEAR,
	BT22.ENTRY_KAI,
	BT22.STAFF_ID,
	rtrim(BT22.ONER_CD) as ONER_CD,
	rtrim(BT22.COURSE_CD) as COURSE_CD, 
	rtrim(BT22.EMP_EXP_YEAR) as EMP_EXP_YEAR,
	rtrim(BT22.EMP_EXP_MONTH) as EMP_EXP_MONTH,
	rtrim(BT22.PA_EXP_YEAR) as PA_EXP_YEAR,
	rtrim(BT22.PA_EXP_MONTH) as PA_EXP_MONTH,
	rtrim(BT22.JOB) as JOB,
	rtrim(BT22.GUIDE_KBN) as GUIDE_KBN,
	rtrim(BT22.GUIDE_NAME) as GUIDE_NAME,
	rtrim(BT22.GUIDE_ZIP) as GUIDE_ZIP,
	rtrim(BT22.GUIDE_ADRS1) as GUIDE_ADRS1,
	rtrim(BT22.GUIDE_ADRS2) as GUIDE_ADRS2,
	rtrim(BT22.GUIDE_ADRS3) as GUIDE_ADRS3,
	rtrim(BT22.OTHER_FLG1) as OTHER_FLG1,
	rtrim(BT22.OTHER_FLG2) as OTHER_FLG2,
	rtrim(BT22.OTHER_FLG3) as OTHER_FLG3,
	rtrim(BT22.OTHER_FLG4) as OTHER_FLG4,
	rtrim(BT22.OTHER_FLG5) as OTHER_FLG5,
	rtrim(BT22.BOSS_NAME) as BOSS_NAME,
	rtrim(BT22.BOSS_GROUP) as BOSS_GROUP,
	rtrim(BT22.BOSS_JOB_TYPE) as BOSS_JOB_TYPE,
	rtrim(BT22.BOSS_COMMENT) as BOSS_COMMENT,
	rtrim(BT22.FIRST_USER) as FIRST_USER,
	rtrim(BT22.FIRST_PGM) as FIRST_PGM,
	BT22.FIRST_TMSP,
	rtrim(BT22.LAST_USER) as LAST_USER,
	rtrim(BT22.LAST_PGM) as LAST_PGM,
	BT22.LAST_TMSP,
	rtrim(BM12.STAFF_L_NAME_KJ)
		concat '  ' 
		concat rtrim(BM12.STAFF_F_NAME_KJ) 
		concat 'Åi' 
		concat rtrim(BM01.MISE_NAME_KJ) 
        concat 'Åj' as STAFF_SELECT ,
	rtrim(BM12.STAFF_L_NAME_KNA) concat '  ' concat rtrim(BM12.STAFF_F_NAME_KNA) as NAME_KNA_INPUT,
	BM12.SEX
from
	BT22ENKN BT22, 
	BM12STAF BM12 
	  left join BM01TENM BM01 on (BM12.COMPANY_CD = BM01.COMPANY_CD and BM12.MISE_CD_1 = BM01.MISE_CD)  
where 
	BT22.ENTRY_CD = /*entryCd*/'05'
and BT22.ENTRY_YEAR = /*entryYear*/'2006'
and BT22.ENTRY_KAI = /*entryKai*/'047'
and BT22.STAFF_ID = BM12.STAFF_ID 
and BM12.COMPANY_CD =/*companyCd*/'00'
and BM12.ONER_CD = /*onerCd*/'36478'
order by
	BT22.STAFF_ID