SELECT COMPANY_CD
,      ONER_CD       AS TARGET_CD
,      RTRIM(CHAR(REPLACE(ONER_NAME_KJ, '  ', '  '), 40))  AS TARGET_NAME_KJ
,      RTRIM(CHAR(REPLACE(ONER_NAME_KNA, '  ', '  '), 40)) AS TARGET_NAME_KNA

FROM   BM11ONER 

WHERE COMPANY_CD = /*companyCd*/'00'
AND   ONER_CD    = /*taishoCd*/'36000'

GROUP BY COMPANY_CD
,        ONER_CD
,        ONER_NAME_KJ
,        ONER_NAME_KNA