SELECT KM32.COMPANY_CD
,      KM32.SIBU_CD
,      KM32.SV_CD
,      KM32.SV_NAME_KJ
,      KM32.SV_NAME_KNA
FROM
    BM11ONER 
    LEFT OUTER JOIN 
        BM01TENM
    ON 
        BM11ONER.COMPANY_CD = BM01TENM.COMPANY_CD 
    AND BM11ONER.ONER_CD = BM01TENM.ONER_CD

    LEFT OUTER JOIN KM31TANM on (KM31TANM.MISE_CD = BM01TENM.MISE_CD) 
    LEFT OUTER JOIN KM32SVCD KM32 on (KM31TANM.SV_CD = KM32.SV_CD) 
WHERE
1=1
/*IF COMPANY_CD_0 != null */AND BM11ONER.COMPANY_CD = /*COMPANY_CD_0*/'00000000000'/*END*/
/*IF SIBU_CD != null */AND KM32.SIBU_CD = /*SIBU_CD*/'00000000000'/*END*/
/*IF ONER_NAME_KJ != null */AND BM11ONER.ONER_NAME_KJ like /*ONER_NAME_KJ*/'abc'/*END*/
/*IF ONER_CD != null */AND BM11ONER.ONER_CD = /*ONER_CD*/'00000'/*END*/
/*IF MISE_NAME_KJ_0 != null */AND BM01TENM.MISE_NAME_KJ like /*MISE_NAME_KJ_0*/'abc'/*END*/
/*IF MISE_CD_0 != null */AND BM01TENM.MISE_CD = /*MISE_CD_0*/'00000'/*END*/
/*IF IN_END != null */AND BM11ONER.KEIYAKU_END >= BR33.CNT_DATE /*END*/
AND (1 = 1
/*IF SV_NAME_KNA_1 != null */AND KM32.SV_NAME_KNA like /*SV_NAME_KNA_1*/'abc'/*END*/
/*IF SV_NAME_KNA_2 != null */OR KM32.SV_NAME_KNA like /*SV_NAME_KNA_2*/'abc'/*END*/
/*IF SV_NAME_KNA_3 != null */OR KM32.SV_NAME_KNA like /*SV_NAME_KNA_3*/'abc'/*END*/
)
GROUP BY KM32.COMPANY_CD
,        KM32.SIBU_CD
,        KM32.SV_CD
,        KM32.SV_NAME_KJ
,        KM32.SV_NAME_KNA

/*IF SORT_TYPE == null */
ORDER BY KM32.SV_CD
/*END*/

/*IF SORT_TYPE != null */
ORDER BY Hex(KM32.SV_NAME_KNA)
/*END*/
       