SELECT distinct EIGYO_DT
,      ZEN_DOGETU_DT AS DOGETU_DT
,      SUBSTR(ZEN_DOGETU_DT, 1,4) AS DOGETU_YEAR
,      SUBSTR(ZEN_DOGETU_DT, 5,2) AS DOGETU_MONTH
,      ZEN_DOYO_DT AS DOYO_DT
,      SUBSTR(ZEN_DOYO_DT, 1,4) AS DOYO_YEAR
,      SUBSTR(ZEN_DOYO_DT, 5,2) AS DOYO_MONTH
,      ZEN_DOJITU_DT AS DOJITU_DT
,      SUBSTR(ZEN_DOJITU_DT, 1,4) AS DOJITU_YEAR
,      SUBSTR(ZEN_DOJITU_DT, 5,2) AS DOJITU_MONTH
FROM BM45ZDAY BM45
WHERE COMPANY_CD =/*companyCd*/'00'
AND   EIGYO_DT = /*eigyoDt*/'20070707'