SELECT (CASE WHEN BD11.MENU_BUNRUI IS NULL  THEN 1
        ELSE 2 END) AS ROW_RANK
,      (CASE WHEN BD11.MENU_BUNRUI IS NULL  THEN 'TOTAL' 
        ELSE '' END) AS ROW_TYPE
,      BD11.COMPANY_CD
,      BD11.MENU_BUNRUI
,      BD11.MENU_CD
,      (CASE WHEN BD11.MENU_BUNRUI IS NULL THEN '‡Œv' 
        ELSE RTRIM(BD11.MENU_NAME_KJ) END) AS MENU_NAME_KJ
,      (CASE WHEN BD11.MENU_BUNRUI IS NULL THEN null ELSE BD11.TANKA END) AS TANKA
,      BD11.TENPO_CNT
,      BD11.KOSU
,      BD11.KINGAKU
,      DECIMAL(CASE WHEN BD11.KINGAKU IS NULL OR SUM(CASE WHEN BD11.MENU_CD IS NOT NULL THEN BD11.KINGAKU ELSE 0 END) OVER(partition by BD11.COMPANY_CD)=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KINGAKU)/DOUBLE(SUM(CASE WHEN BD11.MENU_CD IS NOT NULL THEN BD11.KINGAKU ELSE 0 END) OVER(partition by BD11.COMPANY_CD)))*100+0.005
                    END,11,2)  AS KINGAKU_KOUSEI_HI
,      BD11.KOSU_EAT
,      BD11.KINGAKU_EAT
,      BD11.KOSU_TAKE
,      BD11.KINGAKU_TAKE
,      BD11.KOSU_TEL
,      BD11.KINGAKU_TEL
,      BD11.KOSU_DRIVE
,      BD11.KINGAKU_DRIVE
,      BD11.KOSU_TAKUHAI
,      BD11.KINGAKU_TAKUHAI
,      BD11.KOSU_ETC
,      BD11.KINGAKU_ETC
FROM (
        SELECT BD22.COMPANY_CD
        ,      PC10.MENU_BUNRUI 
        ,      BD22.MENU_CD 
        ,      PC10.MENU_NAME_KJ
        ,      CASE WHEN (SUM(BD22.KAZU_KEI))=0 THEN null
                    WHEN COUNT(DISTINCT BD22.TANKA) = 1 THEN MAX(BD22.TANKA) 
                    WHEN SUM(BD22.URIAGE) >= 0 THEN DECIMAL(DOUBLE(SUM(BD22.URIAGE)) / DOUBLE(SUM(BD22.KAZU_KEI))+0.5, 11, 0) 
                    ELSE DECIMAL(DOUBLE(SUM(BD22.URIAGE)) / DOUBLE(SUM(BD22.KAZU_KEI))-0.5, 11, 0) 
               END AS TANKA
		,      SUM(BD22.TAISHO_TENPOSU) TENPO_CNT
		,      SUM(BD22.KAZU_KEI) AS KOSU
		,      SUM(DECIMAL(BD22.URIAGE,11,0))  AS KINGAKU
		,      SUM(BD22.KAZU_EAT) AS KOSU_EAT
		,      SUM(DECIMAL(CASE WHEN BD22.KAZU_EAT IS NULL THEN 0
		                    ELSE (DOUBLE(BD22.KAZU_EAT)*DOUBLE(BD22.TANKA))
		                    END,11,0))  AS KINGAKU_EAT
		,      SUM(BD22.KAZU_TAKE) AS KOSU_TAKE
		,      SUM(DECIMAL(CASE WHEN BD22.KAZU_TAKE IS NULL THEN 0
		                    ELSE (DOUBLE(BD22.KAZU_TAKE)*DOUBLE(BD22.TANKA))
		                    END,11,0))  AS KINGAKU_TAKE
		,      SUM(BD22.KAZU_TEL) AS KOSU_TEL
		,      SUM(DECIMAL(CASE WHEN BD22.KAZU_TEL IS NULL THEN 0
		                    ELSE (DOUBLE(BD22.KAZU_TEL)*DOUBLE(BD22.TANKA))
		                    END,11,0))  AS KINGAKU_TEL
		,      SUM(BD22.KAZU_DRIVE) AS KOSU_DRIVE
		,      SUM(DECIMAL(CASE WHEN BD22.KAZU_DRIVE IS NULL THEN 0
		                    ELSE (DOUBLE(BD22.KAZU_DRIVE)*DOUBLE(BD22.TANKA))
		                    END,11,0))  AS KINGAKU_DRIVE
		,      SUM(BD22.KAZU_TAKUHAI) AS KOSU_TAKUHAI
		,      SUM(DECIMAL(CASE WHEN BD22.KAZU_TAKUHAI IS NULL THEN 0
		                    ELSE (DOUBLE(BD22.KAZU_TAKUHAI)*DOUBLE(BD22.TANKA))
		                    END,11,0))  AS KINGAKU_TAKUHAI
		,      SUM(BD22.KAZU_GAIHAN + BD22.KAZU_TAKUHAI
		          + BD22.KAZU_OTHER_1+BD22.KAZU_OTHER_2+BD22.KAZU_OTHER_3+BD22.KAZU_OTHER_4
		          + BD22.KAZU_OTHER_5+BD22.KAZU_OTHER_6+BD22.KAZU_OTHER_7+BD22.KAZU_OTHER_8
		          + BD22.KAZU_OTHER_9) AS KOSU_ETC
		,      SUM(DECIMAL(CASE WHEN (BD22.KAZU_GAIHAN + BD22.KAZU_TAKUHAI
		          + BD22.KAZU_OTHER_1+BD22.KAZU_OTHER_2+BD22.KAZU_OTHER_3+BD22.KAZU_OTHER_4
		          + BD22.KAZU_OTHER_5+BD22.KAZU_OTHER_6+BD22.KAZU_OTHER_7+BD22.KAZU_OTHER_8
		          + BD22.KAZU_OTHER_9) IS NULL THEN 0
		                    ELSE (DOUBLE(BD22.KAZU_GAIHAN + BD22.KAZU_TAKUHAI
		          + BD22.KAZU_OTHER_1+BD22.KAZU_OTHER_2+BD22.KAZU_OTHER_3+BD22.KAZU_OTHER_4
		          + BD22.KAZU_OTHER_5+BD22.KAZU_OTHER_6+BD22.KAZU_OTHER_7+BD22.KAZU_OTHER_8
		          + BD22.KAZU_OTHER_9)*DOUBLE(BD22.TANKA))
		                    END,11,0))  AS KINGAKU_ETC
        FROM BD22NMSR BD22
        LEFT JOIN BM62SYMM BM62 ON (BD22.MENU_CD = BM62.MENU_CD)
        ,    PC10SMNU PC10
        WHERE BD22.COMPANY_CD = /*companyCd*/'00'
        AND   BD22.MENU_YM = /*kikanSitei*/'200805'
/*IF taishoJoken.equals("SIBU") || taishoJoken.equals("AREADAI") */  
        AND   BD22.SIBU_CD = /*hyojiTaisho*/'031'
/*END*/
	    AND   BD22.MENU_CD = PC10.MENU_CD
        GROUP BY ROLLUP (
		(BD22.COMPANY_CD, PC10.MENU_BUNRUI , BD22.MENU_CD, PC10.MENU_NAME_KJ)
		)
) BD11
ORDER BY MENU_BUNRUI
,        MENU_CD
,        TANKA