SELECT (CASE WHEN BD11.MENU_BUNRUI IS NULL  THEN 1
        ELSE 2 END) AS ROW_RANK
,      (CASE WHEN BD11.MENU_BUNRUI IS NULL  THEN 'TOTAL' 
             WHEN BD11.MENU_BUNRUI IS NOT NULL AND BD11.MENU_CD IS NULL THEN 'MBUNRUI' 
        ELSE '' END) AS ROW_TYPE
,      BD11.COMPANY_CD
/*IF taishoJoken.equals("MISE") */  
,      BD11.TARGET_NAME_KJ
/*END*/
,      BD11.MENU_BUNRUI
,      BD11.MBUNRUI_NAME_KJ
,      BD11.MENU_CD
,      (CASE WHEN BD11.MENU_BUNRUI IS NULL  THEN '‡Œv' 
			 WHEN BD11.MENU_BUNRUI IS NOT NULL AND BD11.MENU_CD IS NULL THEN CONCAT(RTRIM(BD11.MBUNRUI_NAME_KJ) ,'Œv')
        ELSE RTRIM(BD11.MENU_NAME_KJ) END) AS MENU_NAME_KJ
,      BD11.TENPO_CNT
,      BD11.KOSU_EAT
,      DECIMAL(CASE WHEN BD11.KOSU_EAT IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_EAT)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_EAT
,      BD11.KOSU_TAKE
,      DECIMAL(CASE WHEN BD11.KOSU_TAKE IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_TAKE)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_TAKE
,      BD11.KOSU_TEL
,      DECIMAL(CASE WHEN BD11.KOSU_TEL IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_TEL)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_TEL
,      BD11.KOSU_DRIVE
,      DECIMAL(CASE WHEN BD11.KOSU_DRIVE IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_DRIVE)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_DRIVE
,      BD11.KOSU_TAKUHAI
,      DECIMAL(CASE WHEN BD11.KOSU_TAKUHAI IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_TAKUHAI)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_TAKUHAI
,      BD11.KOSU_GAIHAN
,      DECIMAL(CASE WHEN BD11.KOSU_GAIHAN IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_GAIHAN)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_GAIHAN
,      BD11.KOSU_SYUBETSU_07
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_07 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_07)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_07
,      BD11.KOSU_SYUBETSU_08
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_08 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_08)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_08
,      BD11.KOSU_SYUBETSU_09
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_09 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_09)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_09
,      BD11.KOSU_SYUBETSU_10
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_10 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_10)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_10
,      BD11.KOSU_NET_TAKE
,      DECIMAL(CASE WHEN BD11.KOSU_NET_TAKE IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_NET_TAKE)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_NET_TAKE
,      BD11.KOSU_NET_TAKUHAI
,      DECIMAL(CASE WHEN BD11.KOSU_NET_TAKUHAI IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_NET_TAKUHAI)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_NET_TAKUHAI
,      BD11.KOSU_SYUBETSU_13
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_13 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_13)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_13
,      BD11.KOSU_SYUBETSU_14
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_14 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_14)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_14
,      BD11.KOSU_SYUBETSU_15
,      DECIMAL(CASE WHEN BD11.KOSU_SYUBETSU_15 IS NULL OR BD11.KOSU_ALL=0 THEN 0.00
                    ELSE (DOUBLE(BD11.KOSU_SYUBETSU_15)/DOUBLE(BD11.KOSU_ALL))*100+0.005
                    END,11,2)  AS KOSU_KOUSEI_HI_SYUBETSU_15
FROM (
        SELECT BD10orBD11.COMPANY_CD
/*IF taishoJoken.equals("MISE") */  
        ,      BM01.MISE_NAME_KJ AS TARGET_NAME_KJ
/*END*/

        ,      PC10.MENU_BUNRUI 
        ,      PC11.MBUNRUI_NAME_KJ 
        ,      BD10orBD11.MENU_CD 
        ,      PC10.MENU_NAME_KJ
		,      0 TENPO_CNT
		,      SUM(BD10orBD11.KAZU_EAT) AS KOSU_EAT
		,      SUM(BD10orBD11.KAZU_TAKE) AS KOSU_TAKE
		,      SUM(BD10orBD11.KAZU_TEL) AS KOSU_TEL
		,      SUM(BD10orBD11.KAZU_DRIVE) AS KOSU_DRIVE
		,      SUM(BD10orBD11.KAZU_TAKUHAI) AS KOSU_TAKUHAI
		,      SUM(BD10orBD11.KAZU_GAIHAN) AS KOSU_GAIHAN
		,      SUM(BD10orBD11.KAZU_OTHER_1) AS KOSU_SYUBETSU_07
		,      SUM(BD10orBD11.KAZU_OTHER_2) AS KOSU_SYUBETSU_08
		,      SUM(BD10orBD11.KAZU_OTHER_3) AS KOSU_SYUBETSU_09
		,      SUM(BD10orBD11.KAZU_OTHER_4) AS KOSU_SYUBETSU_10
		,      SUM(BD10orBD11.KAZU_OTHER_5) AS KOSU_NET_TAKE
		,      SUM(BD10orBD11.KAZU_OTHER_6) AS KOSU_NET_TAKUHAI
		,      SUM(BD10orBD11.KAZU_OTHER_7) AS KOSU_SYUBETSU_13
		,      SUM(BD10orBD11.KAZU_OTHER_8) AS KOSU_SYUBETSU_14
		,      SUM(BD10orBD11.KAZU_OTHER_9) AS KOSU_SYUBETSU_15
		,      SUM(BD10orBD11.KAZU_EAT + BD10orBD11.KAZU_TAKE 
				   + BD10orBD11.KAZU_TEL + BD10orBD11.KAZU_DRIVE
				   + BD10orBD11.KAZU_TAKUHAI
		           + BD10orBD11.KAZU_GAIHAN
		           + BD10orBD11.KAZU_OTHER_1+BD10orBD11.KAZU_OTHER_2+BD10orBD11.KAZU_OTHER_3+BD10orBD11.KAZU_OTHER_4
		           + BD10orBD11.KAZU_OTHER_5+BD10orBD11.KAZU_OTHER_6+BD10orBD11.KAZU_OTHER_7+BD10orBD11.KAZU_OTHER_8
		           + BD10orBD11.KAZU_OTHER_9) AS KOSU_ALL
        FROM (
        	SELECT DISTINCT BM10.SIBU_CD 
            ,      BM10.SIBU_NAME
            ,      BM01.MISE_CD
            ,      BM01.MISE_NAME_KJ
            FROM BM01TENM BM01
            ,    BM10GSIB BM10
		/*IF userTypeCd == "02" */
		    ,    BM06UONR BM06
		/*END*/
		/*IF userTypeCd == "03" */
		    ,    BM07UTEN BM07
		/*END*/
            ,   (
		             SELECT MISE_CD
		             FROM BN01DTEN
		             WHERE COMPANY_CD = /*companyCd*/'00'
	    /*IF "DAY".equals(taishoKikan) */
                     AND   EIGYO_DT = /*kikanSitei*/'20080515'
	    --ELSE
		             AND   EIGYO_YM = /*kikanSitei*/'' 
		/*END*/
		/*IF tenpoShubetu == "1" || tenpoShubetu == "3"*/
		             AND   KBN1 = /*tenpoShubetu*/''
		/*END*/
		/*IF tenpoShubetu == "2" */
		             AND   KBN1 IN ('1', '2')
		/*END*/
		             GROUP BY MISE_CD
		           ) BN01
            WHERE BM01.COMPANY_CD = /*companyCd*/'00'
/*IF taishoJoken.equals("SIBU") || taishoJoken.equals("AREADAI") */  
            AND   BM10.SIBU_CD = /*hyojiTaisho*/''
/*END*/
/*IF taishoJoken.equals("MISE") */  
            AND   BM01.MISE_CD = /*hyojiTaisho*/
/*END*/
            AND   BM10.COMPANY_CD  = BM01.COMPANY_CD
            AND   BM10.SIBU_CD     = BM01.SIBU_CD
/*IF userTypeCd == "01" && limitFlg == true */
            AND    BM10.SIBU_CD IN (
                SELECT   BM51.SIBU_CD
                FROM     BM51SVSB BM51
                WHERE  BM51.COMPANY_CD = /*companyCd*/'00'
                AND    BM51.SV_CD      = /*userId*/'9999000a'
                GROUP BY BM51.SIBU_CD
                )
/*END*/
/*IF userTypeCd == "02" */
	        AND   BM06.USER_ID    = /*userId*/'99990002'
	        AND   BM06.COMPANY_CD = BM01.COMPANY_CD
	        AND   BM06.ONER_CD    = BM01.ONER_CD
/*END*/
/*IF userTypeCd == "03" */
	        AND   BM07.USER_ID    = /*userId*/'99990003'
	        AND   BM07.COMPANY_CD = BM01.COMPANY_CD
	        AND   BM07.MISE_CD    = BM01.MISE_CD
/*END*/
	        AND   BN01.MISE_CD    = BM01.MISE_CD
	    ) BM01
	    /*IF "DAY".equals(taishoKikan) */
	    ,   BD10NMSL/*$targetMonth*/ BD10orBD11
	    --ELSE
	    ,   BD11NMRI BD10orBD11
	    /*END*/
        LEFT JOIN PC10SMNU PC10 ON (BD10orBD11.MENU_CD = PC10.MENU_CD)
        LEFT JOIN PC11MBUN PC11 ON (PC11.MENU_BUNRUI = PC10.MENU_BUNRUI)
        WHERE BD10orBD11.COMPANY_CD = /*companyCd*/'00'
	    /*IF "DAY".equals(taishoKikan) */
        AND   BD10orBD11.MENU_DT = /*kikanSitei*/'20080515'
	    --ELSE
        AND   BD10orBD11.MENU_YM = /*kikanSitei*/'20080515'
	    /*END*/
	    /*IF !"DAY".equals(taishoKikan) */
	    AND   BD10orBD11.URIAGE_FLG = '1'
	    --ELSE
	    AND   BD10orBD11.KAZU_KEI > 0
	    /*END*/
        AND   BD10orBD11.MISE_CD    = BM01.MISE_CD
        GROUP BY ROLLUP (
               (BD10orBD11.COMPANY_CD
/*IF taishoJoken.equals("MISE") */  
        ,      BM01.MISE_NAME_KJ
/*END*/
               )
        ,      (BD10orBD11.COMPANY_CD, PC10.MENU_BUNRUI , PC11.MBUNRUI_NAME_KJ
              , BD10orBD11.MENU_CD, PC10.MENU_NAME_KJ)
        )
) BD11
WHERE COMPANY_CD IS NOT NULL
ORDER BY COMPANY_CD
,        ROW_RANK
,        MENU_BUNRUI
,        MENU_CD
