select
	MISE.SIBU_CD,
	rtrim(MISE.SIBU_NAME) as SIBU_NAME,
	rtrim(MISE.ONER_NAME_KJ) as ONER_NAME_KJ,
	rtrim(MISE.MISE_NAME_KJ) as MISE_NAME_KJ,
	COALESCE(MISE.PL_TYPE, '0') as PL_TYPE,
	COALESCE(BT17.PL_YM, /*plYm*/'200609') as PL_YM,
	MISE.CLOSE_DT,
	MISE.COMPANY_CD,
	MISE.ONER_CD,
	MISE.MISE_CD,
	BT17.URIAGEDAKA,
	BT17.URIAGEGENKA,
	BT17.URIAGE_SO_RIEKI,
	BT17.SALARY,
	BT17.YACHIN,
	BT17.SUIKOU_HI,
	BT17.ROYALTY,
	BT17.TESURYO,
	BT17.KOUKOKU,
	BT17.SHOUMOU,
	BT17.HOUTEI_FUKURI,
	BT17.FUKURI_KOUSEI,
	BT17.KOUSAI,
	BT17.RYOHI,
	BT17.TUSIN,
	BT17.LEASE,
	BT17.SHARYO,
	BT17.SOZEI,
	BT17.HOKEN,
	BT17.UNCHIN,
	BT17.SHUZEN,
	BT17.YOBI,
	BT17.ZAPPI,
	BT17.KEIHI_SHOKEI,
	BT17.SHOKYAKU_RIEKI,
	BT17.GENKA_SHOKYAKU,
	BT17.EIGAI_SHUEKI,
	BT17.EIGAI_HIYO,
	BT17.HONSHAHI_HAI,
	BT17.RIEKI,
	BT17.URIAGE,
	BT17.BUPPAN,
	BT17.URI_UCHIWAKE,
	BT17.ELEC,
	BT17.GAS,
	BT17.WATER,
	BT17.SONOTA,
	BT17.SUIKOU_UCHIWAKE,
	BT17.GENZAIRYO_KEI,
	BT17.GENZAIRYO_SHIRE,
	BT17.GENZAIRYO_ZAIKO,
	BT17.YASAI_KEI,
	BT17.YASAI_SHIRE,
	BT17.YASAI_ZAIKO,
	BT17.HOUZAI_KEI,
	BT17.HOUZAI_SHIRE,
	BT17.HOUZAI_ZAIKO,
	BT17.BUPPAN_KEI,
	BT17.BUPPAN_SHIRE,
	BT17.BUPPAN_ZAIKO,
	BT17.TOU_SIIRE_KEI,
	BT17.TOU_ZAIKO_KEI,
	BT17.SASHIHIKI_KEI,
	BT17.YAKUIN_SALARY,
	BT17.YAKUIN_BONUS,
	BT17.YAKUIN_RETIRE,
	BT17.YAKUIN_KEI,
	BT17.SALARY_SALARY,
	BT17.SALARY_BONUS,
	BT17.SALARY_RETIRE,
	BT17.SALARY_KEI,
	BT17.ZAKKYU_SALARY,
	BT17.ZAKKYU_BONUS,
	BT17.ZAKKYU_RETIRE,
	BT17.ZAKKYU_KEI,
	BT17.KYURYO_KEI,
	BT17.BONUS_KEI,
	BT17.RETIRE_KEI,
	BT17.SALARY_UTI_KEI,
	BT17.KASHIIRE_UP,
	BT17.KASHIIRE_DOWN,
	BT17.KASHIIRE_ZANDAKA,
	BT17.KAPPU_UP,
	BT17.KAPPU_DOWN,
	BT17.KAPPU_ZANDAKA,
	BT17.LEASE_UP,
	BT17.LEASE_DOWN,
	BT17.LEASE_ZANDAKA,
	BT17.TOU_ZOUKA_KEI,
	BT17.TOU_GENSHO_KEI,
	BT17.TOU_ZANDAKA_KEI,
	rtrim(BT17.MEMO) as MEMO,
	rtrim(BT17.LAST_DT) as LAST_DT,
	rtrim(BT17.AUTHOR_NAME) as AUTHOR_NAME,
	rtrim(BT17.AUTH_DT) as AUTH_DT,
	rtrim(BT17.AUTH_PHONE_NUM) as AUTH_PHONE_NUM,
	rtrim(BT17.AUTH_OTHER) as AUTH_OTHER,
	rtrim(BT17.ERR_FLG) as ERR_FLG,
	rtrim(BT17.FIRST_USER) as FIRST_USER,
	rtrim(BT17.FIRST_PGM) as FIRST_PGM,
	BT17.FIRST_TMSP,
	rtrim(BT17.LAST_USER) as LAST_USER,
	rtrim(BT17.LAST_PGM) as LAST_PGM,
	BT17.LAST_TMSP

from (
    select
        BM11.COMPANY_CD as COMPANY_CD,
        BM11.SIBU_CD as SIBU_CD,
        rtrim(BM10.SIBU_NAME) as SIBU_NAME,
        BM11.ONER_CD as ONER_CD,
        rtrim(BM11.ONER_NAME_KJ) as ONER_NAME_KJ,
        '' as MISE_CD,
        '' as MISE_NAME_KJ,
        '' as CLOSE_DT,
        '0' as PL_TYPE
    from
        BM11ONER BM11,
        BM10GSIB BM10
    where
        BM11.ONER_CD in 
        (select
            distinct rtrim(BM01.ONER_CD) as ONER_CD
        from 
            BM01TENM BM01
        where 
            BM01.MISE_KBN like '_1_' 
        and BM01.COMPANY_CD = /*companyCd*/'00'
        /*IF !closeMiseFlg */and BM01.CLOSE_DT > /*plYm*/'200609'/*END*/
        order by
            ONER_CD
        )
    and BM11.COMPANY_CD = /*companyCd*/'00'
    /*IF !closeMiseFlg */and BM11.KEIYAKU_END > /*plYm*/'200609'/*END*/
    and BM11.COMPANY_CD = BM10.COMPANY_CD
    and BM11.SIBU_CD = BM10.SIBU_CD

    union all
    
    select
        BM01.COMPANY_CD as COMPANY_CD,
        BM01.SIBU_CD as SIBU_CD,
        rtrim(BM10.SIBU_NAME) as SIBU_NAME,
        BM01.ONER_CD as ONER_CD,
        rtrim(BM11.ONER_NAME_KJ) as ONER_NAME_KJ,
        BM01.MISE_CD as MISE_CD,
        rtrim(BM01.MISE_NAME_KJ) as MISE_NAME_KJ,
        (case when BM01.CLOSE_DT = '99991231' then '' else BM01.CLOSE_DT end) as CLOSE_DT,
        '1' as PL_TYPE
    from 
        BM01TENM BM01,
        BM10GSIB BM10,
        BM11ONER BM11
    where
        BM01.MISE_KBN like '_1_'
    and BM01.COMPANY_CD = /*companyCd*/'00'
    /*IF !closeMiseFlg */and BM01.CLOSE_DT > /*plYm*/'200609'/*END*/
    and BM01.COMPANY_CD = BM10.COMPANY_CD
    and BM01.SIBU_CD = BM10.SIBU_CD
    and BM01.ONER_CD in (
        select rtrim(ONER_CD)
          from BM11ONER
         where COMPANY_CD = /*companyCd*/'00'
    /*IF !closeMiseFlg */and KEIYAKU_END > /*plYm*/'200609'/*END*/
    )
    and BM01.COMPANY_CD = BM11.COMPANY_CD
    and BM01.ONER_CD = BM11.ONER_CD
    order by
        SIBU_CD,
        ONER_CD,
        MISE_CD
)MISE
left join BT17PLDT as BT17 on
BT17.PL_TYPE = MISE.PL_TYPE and
BT17.PL_YM = /*plYm*/'200609' and
BT17.COMPANY_CD = MISE.COMPANY_CD and
BT17.MISE_CD = MISE.MISE_CD