SELECT PM25.KKBN_CD
    ,  PM25.MST_DT
    ,  RTRIM(PM25.KKBN_NAME) AS KKBN_NAME
    ,  PM25.KKBN_ZOK
    ,  PM25.KKBN_TANKA
    ,  PM25.DISP_FLG
    ,  PM25.SYUKEI_CD
    ,  PC25.SYUKEI_NAME
    ,  PM25.COUPON_FLG
    ,  PM25.COUPON_ID
    ,  PM25.TICKET_CD
FROM PM25KKBN PM25
    ,PC25KKSK PC25
WHERE
    PC25.SYUKEI_CD = PM25.SYUKEI_CD
    /*IF birdDisFlg != null*/
    AND  PM25.BIRD_DISP_FLG = /*birdDisFlg*/'1'
    /*END*/
    AND  PM25.COMPANY_CD = /*companyCd*/
ORDER BY SYUKEI_CD
    ,    KKBN_CD
