SELECT PC25.SYUKEI_CD
    ,  RTRIM(PC25.SYUKEI_NAME) AS SYUKEI_NAME
    ,  COUNT(PM25.KKBN_CD) KKBN_CNT
FROM PC25KKSK PC25
LEFT JOIN PM25KKBN PM25 ON (PM25.SYUKEI_CD = PC25.SYUKEI_CD)
GROUP BY PC25.SYUKEI_CD
    ,    PC25.SYUKEI_NAME
ORDER BY SYUKEI_CD
