SELECT BD25.COMPANY_CD
,      BD25.URIKAKE_CD
,      RTRIM(TM11.ONER_NAME_KJ) AS URIKAKE_NAME
,      BD25.KEISAN_YM
,      BD25.KEI_CATEGORY
,      BD25.KEI_SHU
,      BD25.SEQ
,      BD25.HAKKO_DT
,      RTRIM(BD25.FILE_NAME) AS FILE_NAME
,      RTRIM(BC28.SAVE_DIR) AS SAVE_DIR
,      BD25.FIRST_USER
,      BD25.FIRST_TMSP
,      BD25.FIRST_PGM
,      BD25.LAST_USER
,      BD25.LAST_TMSP
,      BD25.LAST_PGM
FROM TM11ONER TM11
,    BM11ONER BM11
,    BM01TENM BM01
,    BC28KEIS BC28
,    BD25MEIR BD25
WHERE BC28.KEI_CATEGORY = '03'
AND   BC28.KEI_SHU = '01'
AND   BD25.COMPANY_CD = /*companyCd*/'00'
/*IF miseCd != null && miseCd !='' */
AND   BD25.URIKAKE_CD = /*miseCd*/'020'
/*END*/
/*IF taishoYm != null && taishoYm !='' */
AND   BD25.KEISAN_YM = /*taishoYm*/'200906'
/*END*/
/*IF kaisuu != null && kaisuu !='' */
AND   BD25.SEQ = /*kaisuu*/'01'
/*END*/
AND   BM01.COMPANY_CD = BD25.COMPANY_CD
AND   BM11.COMPANY_CD = BM01.COMPANY_CD
AND   TM11.COMPANY_CD = BM11.COMPANY_CD
AND   BD25.URIKAKE_CD = TM11.ONER_CD
AND   BM01.MISE_CD    = BD25.URIKAKE_CD
AND   BM01.ONER_CD    = BM11.ONER_CD
AND   BD25.KEI_CATEGORY    = BC28.KEI_CATEGORY
AND   BD25.KEI_SHU    = BC28.KEI_SHU

ORDER BY BD25.URIKAKE_CD
,        BD25.KEISAN_YM DESC
,        BD25.SEQ
