SELECT 
	TM17SOKO.KANRI_MOTO , 
	sokonam.SOKO_NAME_KJ
FROM
	TM17SOKO 
	JOIN 
		TM02MPTN ON (HAI_SHUKKA_KBN = '008')
	JOIN 
		TM17SOKO as sokonam on (TM17SOKO.KANRI_MOTO = sokonam.SOKO_CD ) 
 WHERE 
 	TM17SOKO.SOKO_CD = TM02MPTN.HAI_SOKO_CD 
 GROUP BY 
 	TM17SOKO.KANRI_MOTO , 
 	sokonam.SOKO_NAME_KJ
 ORDER BY 
 	TM17SOKO.KANRI_MOTO