SELECT 
    TM17SOKO.KANRI_MOTO, 
    sokonam.SOKO_NAME_KJ AS KANRI_MOTO_KJ, 
    TM17SOKO.SOKO_CD,
    TM17SOKO.SOKO_NAME_KJ,
    BM54BSET.SHO_CD_DAI,
    BM54BSET.SHO_NISUGATA,
    TM22SCHU.SHO_NAME_KJ,
    BM54BSET.FIRST_USER,
    BM54BSET.FIRST_PGM,
    BM54BSET.FIRST_TMSP,
    BM54BSET.LAST_USER,
    BM54BSET.LAST_PGM,
    BM54BSET.LAST_TMSP
FROM
    TM17SOKO 
        JOIN TM17SOKO as sokonam on 
                (TM17SOKO.KANRI_MOTO = sokonam.SOKO_CD ) 
        JOIN TM02MPTN ON (HAI_SHUKKA_KBN = '008')
        LEFT OUTER JOIN BM54BSET ON (TM17SOKO.SOKO_CD = BM54BSET.SOKO_CD)
        LEFT OUTER JOIN TM22SCHU ON (TM22SCHU.SHO_CD_DAI = BM54BSET.SHO_CD_DAI)
 WHERE 
    TM17SOKO.SOKO_CD = TM02MPTN.HAI_SOKO_CD  
   	AND TM17SOKO.KANRI_MOTO = /*kanriMoto*/'00001'
 GROUP BY 
    (TM17SOKO.KANRI_MOTO,
     sokonam.SOKO_NAME_KJ,
     TM17SOKO.SOKO_CD,
     TM17SOKO.SOKO_NAME_KJ),
    (BM54BSET.SHO_CD_DAI,
     BM54BSET.SHO_NISUGATA,
     TM22SCHU.SHO_NAME_KJ,
	 BM54BSET.FIRST_USER,
	 BM54BSET.FIRST_PGM,
     BM54BSET.FIRST_TMSP,
     BM54BSET.LAST_USER,
     BM54BSET.LAST_PGM,
     BM54BSET.LAST_TMSP)
 ORDER BY 
     TM17SOKO.SOKO_CD,
     BM54BSET.SHO_CD_DAI