SELECT BC05.COMPANY_CD
,      RTRIM(BC05.COMPANY_NAME) AS COMPANY_NAME
,      BC05.FOREIGN_FLG 

FROM   BC05KCOM BC05
/*IF  isForeignIn==false */
    WHERE FOREIGN_FLG <> '1'
/*END*/
ORDER BY BC05.SORT_SEQ
