select
    BC09GTAI.GYOTAI_KBN,
    BC09GTAI.GYOTAI_KBN_NAME
from
    BC09GTAI inner join BM04GTCP on BC09GTAI.GYOTAI_KBN = BM04GTCP.GYOTAI_KBN
where
    BM04GTCP.COMPANY_CD = /*companyCd*/'01'
order by
    BC09GTAI.GYOTAI_KBN
