SELECT DISTINCT
    BM06UONR.USER_ID,
    BM06UONR.COMPANY_CD,
    BM06UONR.ONER_CD,
    BM11ONER.ONER_NAME_KJ
FROM 
    BM06UONR
    INNER JOIN BM11ONER ON BM06UONR.COMPANY_CD = BM11ONER.COMPANY_CD
                        AND BM06UONR.ONER_CD = BM11ONER.ONER_CD
WHERE
    BM06UONR.USER_ID = /*userId*/'99990002'
/* IF null != companyCd */
AND BM06UONR.COMPANY_CD = /*companyCd*/'00'
/*END*/
