select BC05.COMPANY_CD
,      rtrim(BC05.COMPANY_NAME) AS COMPANY_NAME
,      BC05.FOREIGN_FLG
,      BC05.CURRENCY_TYPE
,      RTRIM(BC35.CURRENCY_NAME) AS CURRENCY_NAME
,      (CASE WHEN DISP_FORMAT IS NOT NULL THEN RTRIM(BC35.DISP_FORMAT) ELSE '0' END) AS DISP_FORMAT
,      BC35.RATE
,      rtrim(BC35.RATE_LABEL) AS RATE_LABEL

from   BC05KCOM BC05
LEFT JOIN BC35CRCY BC35 
               ON (BC35.CURRENCY_TYPE = BC05.CURRENCY_TYPE)
,      BC06COMM BC06
,      BM03USCP BM03
where  BM03.USER_ID = /*birdUserInfo.userID*/'99990003'
/*IF ( birdUserInfo.mstUser.userTypeCd=="01" && birdUserInfo.limit ) || isForeignIn==false */
    AND FOREIGN_FLG <> '1'
/*END*/
and    BC05.COMPANY_CD = BC06.COMPANY_CD
and    BM03.R_COMPANY_CD = BC06.R_COMPANY_CD
order by    BC05.sort_seq