SELECT
    RTRIM(BM49TCKT.TCKT_CD) AS TCKT_CD,
    RTRIM(BM49TCKT.TCKT_NAME) AS TCKT_NAME
FROM
    BM49TCKT
WHERE
    BM49TCKT.COMPANY_CD = /*companyCd*/'00' AND 
    BM49TCKT.MISE_CD    = /*miseCd*/'00000'
ORDER BY 
    BM49TCKT.TCKT_CD
