select 
    sum(BS02.KAZEI_GAKU + BS02.SHO_TAX + BS02.HIZEI_GAKU) as KINGAKU,
    substr(BS02.SEIKYUSHO_ID,1,6) as NENGETU,
    BM11.ONER_NAME_KJ
from 
    BS02SEKR BS02 INNER JOIN (
        BM33ONUR BM33 LEFT OUTER JOIN BM11ONER BM11 ON BM33.COMPANY_CD = BM11.COMPANY_CD and BM33.URIKAKE_CD = BM11.ONER_CD )
    ON BS02.COMPANY_CD = BM33.COMPANY_CD AND BS02.URIKAKE_CD = BM33.URIKAKE_CD
where 
    BS02.URIKAKE_CD = /*urikakeCd*/ and
    substr(BS02.SEIKYUSHO_ID,1,6) >= /*startYM*/ and
    substr(BS02.SEIKYUSHO_ID,1,6) <= /*endYM*/ and
    BM33.COMPANY_CD = /*companyCd*/ and 
    BM33.ONER_CD = /*ownerCd*/
group by
    substr(BS02.SEIKYUSHO_ID,1,6),ONER_NAME_KJ
order by 
    NENGETU
