SELECT 
    BT37.URIKAKE_CD
   ,rtrim(TM11.ONER_NAME_KJ) as URIKAKE_NAME
   ,BT37.URIKAKE_YM
   ,BT37.MISE_CD
   ,rtrim(BM01.MISE_NAME_KJ) as MISE_NAME_KJ
   ,BT37.SEIKYU_ID
   ,BT37.U_KANRI_NO
   ,BT37.DENPYO_NO
   ,BT37.DATA_SHU
   ,BT37.DENPYO_KBN
   ,BT37.SHO_CD_JITU
   ,rtrim(TM20.SHO_NAME_KJ) as SHO_NAME_KJ
   ,BT37.NOHIN_UNIT
   ,BT37.SHO_AMOUNT
   ,BT37.NOHIN_SAKI
   ,BT37.NOHIN_TANKA
   ,BT37.URI_KIN
   ,BT37.MUSHOU_URI
   ,BT37.STAX_URI
   ,BT37.TAX_CD
   ,BT37.SOTO_TAX
   ,BT37.UCHI_TAX
   ,BT37.NOHIN_DT_J
   ,BT37.KENSHU_DT
   ,rtrim(BT37.TEKIYOU) as TEKIYOU
   ,BT37.SEIKYU_DT
   ,BM32.SHO_CD_DAI
   ,rtrim(TC26.SE_BNR_NAME) as SE_BNR_NAME 
   ,rtrim(TC03.NISU_NAME) as NISU_NAME
FROM 
    BT37URTR BT37 
        LEFT OUTER JOIN BM01TENM BM01 ON (BT37.COMPANY_CD = BM01.COMPANY_CD AND BT37.MISE_CD = BM01.MISE_CD)
        LEFT OUTER JOIN TM20SHOM TM20 ON (BT37.SHO_CD_JITU = TM20.SHO_CD_JITU) 
        LEFT OUTER JOIN BM32JDAI BM32 ON (BT37.SHO_CD_JITU = BM32.SHO_CD_JITU) 
        LEFT OUTER JOIN TC26SEIK TC26 ON (TM20.SEIKYU_BNRUI = TC26.SEIKYU_BNRUI) 
        LEFT OUTER JOIN TM21SHOK TM21 ON (BT37.SHO_CD_JITU = TM21.SHO_CD_JITU AND BT37.NOHIN_UNIT = TM21.UNIT_KBN) 
        LEFT OUTER JOIN TC03NISU TC03 ON (TM21.SHO_NISUGATA = TC03.SHO_NISUGATA)
   ,TM11ONER TM11
   ,(
     SELECT
        U.COMPANY_CD
       ,U.URIKAKE_CD
       ,U.URIKAKE_YM
       ,U.MISE_CD
       ,U.SEIKYU_ID
       ,U.SEIKYUSHO_ID
     FROM
        BS02SEKR S,
        BS01URSR U
     WHERE
        S.URIKAKE_CD   = /*urikakeCd*/'36056' AND
        substr(S.SEIKYUSHO_ID,1,6) = /*seikyuId*/'200607' AND
        S.COMPANY_CD   = U.COMPANY_CD AND
        S.URIKAKE_CD   = U.URIKAKE_CD AND
        S.SEIKYUSHO_ID = U.SEIKYUSHO_ID
    ) SUB1
WHERE 
      BT37.COMPANY_CD = TM11.COMPANY_CD
  AND BT37.URIKAKE_CD = TM11.ONER_CD
  AND BT37.URIKAKE_CD = /*urikakeCd*/'36056' 
  AND BT37.COMPANY_CD = /*companyCd*/'00'
  AND BT37.COMPANY_CD = SUB1.COMPANY_CD
  AND BT37.URIKAKE_CD = SUB1.URIKAKE_CD
  AND BT37.MISE_CD    = SUB1.MISE_CD
  AND BT37.SEIKYU_ID  = SUB1.SEIKYU_ID
ORDER BY 
/*IF sort.equals("0")*/
    BT37.MISE_CD
   ,BT37.NOHIN_DT_J
   ,BT37.DENPYO_NO
/*END*/

/*IF sort.equals("1")*/
    BT37.URIKAKE_YM
   ,BT37.MISE_CD
   ,BT37.SHUKKA_KBN
   ,BT37.SHO_BNRUI1
   ,BT37.SIWAKE_CD
   ,BT37.SHO_RYAK_KNA
   ,BT37.SHO_CD_DAI
/*END*/
