SELECT DISTINCT 
       BM01.COMPANY_CD
,      BC05.COMPANY_NAME
,      BM01.MISE_CD 
,      BM01.MISE_NAME_KJ
,      BM01.SIBU_CD 
,      BM10.SIBU_NAME 
,      (CASE WHEN MISEBLOCKLIST.BLOCK_CD IS NULL THEN '000' ELSE MISEBLOCKLIST.BLOCK_CD END) AS BLOCK_CD
,      (CASE WHEN MISEBLOCKLIST.BLOCK_CD IS NULL THEN 'ñ¢ê›íË'
             ELSE MISEBLOCKLIST.BLOCK_NAME END) AS BLOCK_NAME
,      (CASE WHEN MISEBLOCKLIST.BLOCK_CD IS NULL THEN '0' 
             WHEN MISEBLOCKLIST.CHANGE_FLG <> '1' THEN '0' 
             ELSE MISEBLOCKLIST.CHANGE_FLG END) AS CHANGE_FLG
,      '0' AS SELECT_FLG
,      MISEBLOCKLIST.FIRST_USER
,      MISEBLOCKLIST.FIRST_PGM
,      MISEBLOCKLIST.FIRST_TMSP
,      MISEBLOCKLIST.LAST_USER
,      MISEBLOCKLIST.LAST_PGM
,      MISEBLOCKLIST.LAST_TMSP
,      BM01.CLOSE_MJ

FROM BC05KCOM BC05
,    BM10GSIB BM10
,    (
	SELECT DISTINCT 
	       COMPANY_CD
	,      MISE_CD
	,      RTRIM(CHAR(REPLACE(BM01.MISE_NAME_KJ , '  ', '  '), 40)) AS MISE_NAME_KJ
	,      BM01.SIBU_CD
	,      BM01.GYOTAI_KBN
	,      BM01.OPEN_DT
	,      BM01.CLOSE_DT
	,      CASE WHEN CLOSE_DT <= /*sysDate*/'20100406' THEN '(CLOSE)'
	            ELSE ''
	       END  AS CLOSE_MJ
	
	FROM   BM01TENM as BM01
	
	WHERE COMPANY_CD = /*companyCd*/'00'
	AND   SIBU_CD    = /*sibuCd*/'075'
	) BM01
LEFT JOIN (
     SELECT BC13.MISE_CD
     ,      BC23.BLOCK_CD
     ,      BC23.BLOCK_NAME
     ,      BC23.CHANGE_FLG
     ,      BC13.FIRST_USER
     ,      BC13.FIRST_PGM
     ,      BC13.FIRST_TMSP
     ,      BC13.LAST_USER
     ,      BC13.LAST_PGM
     ,      BC13.LAST_TMSP
     FROM   BC13MBLK BC13
     LEFT JOIN  BC23BLCK BC23
     ON (  BC13.BLOCK_CD = BC23.BLOCK_CD )
     WHERE BC13.COMPANY_CD =/*companyCd*/'00'
     ) MISEBLOCKLIST
ON (MISEBLOCKLIST.MISE_CD = BM01.MISE_CD)

WHERE BM01.COMPANY_CD = /*companyCd*/'00'
AND   BM01.SIBU_CD    = /*sibuCd*/'075'
AND   BM01.COMPANY_CD = BC05.COMPANY_CD
AND   BM10.COMPANY_CD = BM01.COMPANY_CD
AND   BM10.SIBU_CD    = BM01.SIBU_CD

ORDER BY CHANGE_FLG
,        BLOCK_CD
,        MISE_CD 