select
	rtrim(BM23.COMPANY_CD) as COMPANY_CD,
	rtrim(BM23.MISE_CD) as MISE_CD,
	rtrim(BM23.EMERGENCE_TEL1) as EMERGENCE_TEL1,
    rtrim(BM23.EMERGENCE_TEL2) as EMERGENCE_TEL2,
	rtrim(BM23.EMERGENCE_TEL3) as EMERGENCE_TEL3,
	rtrim(BM23.EMERGENCE_NAME1) as EMERGENCE_NAME1,
	rtrim(BM23.EMERGENCE_NAME2) as EMERGENCE_NAME2,
	rtrim(BM23.EMERGENCE_NAME3) as EMERGENCE_NAME3,
	rtrim(BM23.YOBI_KBN_1) as YOBI_KBN_1,
	rtrim(GAS_SHU_NAME) as GAS_SHU_NAME,
	rtrim(BM23.YOBI_KBN_2) as YOBI_KBN_2,
	rtrim(AIR_CON_SHU_NAME) as AIR_CON_SHU_NAME,
	rtrim(BM23.YOBI_FREE_1) as YOBI_FREE_1,
	rtrim(BM23.YOBI_FREE_2) as YOBI_FREE_2,
	rtrim(BM23.YOBI_FREE_3) as YOBI_FREE_3,
	rtrim(BM23.YOBI_FREE_4) as YOBI_FREE_4,
	rtrim(BM23.YOBI_FREE_5) as YOBI_FREE_5,
	rtrim(BM23.FIRST_USER) as FIRST_USER,
	rtrim(BM23.FIRST_PGM) as FIRST_PGM,
	BM23.FIRST_TMSP,
	rtrim(BM23.LAST_USER) as LAST_USER,
	rtrim(BM23.LAST_PGM) as LAST_PGM,
	BM23.LAST_TMSP
from
	BM23MIYO BM23
LEFT JOIN BC32GASS BC32 ON (BM23.YOBI_KBN_1 = BC32.GAS_SHU)
LEFT JOIN BC33AIRS BC33 ON (BM23.YOBI_KBN_2 = BC33.AIR_CON_SHU)

where
	  COMPANY_CD = /*companyCd*/'00'
and   MISE_CD = /*miseCd*/'01776' 