SELECT DISTINCT RTRIM(BC05.COMPANY_CD) as COMPANY_CD
,      RTRIM(BC05.COMPANY_NAME) as COMPANY_NAME
,      BC05.SORT_SEQ
FROM  BC05KCOM BC05
,     BC06COMM BC06
WHERE BC05.COMPANY_CD = BC06.COMPANY_CD
AND   BC06.R_COMPANY_CD NOT IN (SELECT R_COMPANY_CD FROM BC29NCOM)
ORDER BY SORT_SEQ