select 
	CASE 
	WHEN SUB1.SALE_DT is null THEN  SUB2.RESERVE_DT
 	ELSE SUB1.SALE_DT
 	END as DT,
	CASE 
	WHEN SUB1.SALE_MENU_CD is null THEN  SUB2.RESERVE_MENU_CD
 	ELSE SUB1.SALE_MENU_CD
 	END as MENU_CD,
	CASE 
	WHEN SUB1.SALE_MENU_NM is null THEN  SUB2.RESERVE_MENU_NM
 	ELSE SUB1.SALE_MENU_NM
 	END as MENU_NM, 
	CASE
	WHEN SUB1.KAZU_KEI is null THEN  0
 	ELSE SUB1.KAZU_KEI
 	END as KAZU_KEI,
	CASE
	WHEN SUB2.RESERVE_AMT is null THEN  0
 	ELSE SUB2.RESERVE_AMT
 	END as RESERVE_AMT,
	CASE
	WHEN SUB1.SUM_GROUP is null THEN  SUB2.SUM_GROUP
 	ELSE SUB1.SUM_GROUP
 	END as SUM_GROUP 	
from
	(select
		BM41.MENU_CD as SALE_MENU_CD,
		BM38.MENU_NAME_KJ as SALE_MENU_NM,
		BT66.MENU_DT as SALE_DT,
		sum(BT66.KAZU_KEI) as KAZU_KEI,
		BM41.SUM_GROUP
	from
		BM41CMNU as BM41 
		left outer join BT66CMSL as BT66 
		on  BT66.COMPANY_CD = '00' and 
		   	BT66.MISE_CD = /*miseCd*/'01776' and
			BT66.MENU_DT between /*taishoKikanFr*/'20060801' and /*taishoKikanTo*/'20060930' and
			BT66.MENU_CD = BM41.MENU_CD 
		, BM38MMNU as BM38
	where
	 	BM41.CKANRI_NO =  /*ckanriNo*/'200619' and
	 	BM41.MENU_GROUP =  /*menuGroup*/'01' and
	 	BM41.MENU_CD = BM38.MENU_CD and
		BM38.COMPANY_CD ='00' and
		BM38.MISE_CD = /*miseCd*/'01776'
	group by BM41.MENU_CD,BT66.MENU_DT,BM38.MENU_NAME_KJ, BM41.SUM_GROUP		
	order by BM41.SUM_GROUP,BM41.MENU_CD
	) SUB1 full outer join 
	(select
		BM41.MENU_CD as RESERVE_MENU_CD,
		BM38.MENU_NAME_KJ as RESERVE_MENU_NM,
		SUB3.RESERVE_DT as RESERVE_DT,
		sum(SUB3.RESERVE_AMT) as RESERVE_AMT,
		BM41.SUM_GROUP
	from
		BM41CMNU as BM41 left outer join
		(select 
			BT70.CKANRI_NO,
			BT71.MENU_CD ,	
			BT70.RESERVE_DT ,
			BT71.RESERVE_AMT
		 from 
		  		BT70CRSV as BT70,
				BT71CRSD as BT71
		 where 
		BT70.COMPANY_CD = '00' and
		BT70.CKANRI_NO = /*ckanriNo*/'123456' and
		BT70.CANCEL_FLG = '0' and
		BT70.MISE_CD = /*miseCd*/'21235' and
		BT70.RESERVE_DT between /*taishoKikanFr*/'20061201' and /*taishoKikanTo*/'20061231' and
		BT70.CKANRI_NO = BT71.CKANRI_NO and
		BT70.COMPANY_CD = BT71.COMPANY_CD and
		BT70.MISE_CD = BT71.MISE_CD and
		BT70.SEQ_NO = BT71.SEQ_NO
		) SUB3
		on BM41.CKANRI_NO = SUB3.CKANRI_NO 
		and BM41.MENU_CD = SUB3.MENU_CD
		, BM38MMNU as BM38
	where 
		BM41.CKANRI_NO =  /*ckanriNo*/'123456' and
		BM41.MENU_GROUP =  /*menuGroup*/'123456' and
		BM38.COMPANY_CD = '00' and
		BM38.MISE_CD =  /*miseCd*/'21235' and	 	
		BM41.MENU_CD = BM38.MENU_CD 
	group by BM41.MENU_CD , SUB3.RESERVE_DT ,BM38.MENU_NAME_KJ ,BM41.SUM_GROUP	
	order by BM41.SUM_GROUP, BM41.MENU_CD
	) SUB2 on SUB1.SALE_MENU_CD = SUB2.RESERVE_MENU_CD and SUB1.SALE_DT = SUB2.RESERVE_DT
order by SUM_GROUP, MENU_CD, DT
