SELECT
    BM03.USER_ID,
    BC02COMP .COMPANY_NAME,
    BM03.R_COMPANY_CD,
    BM03.ZOKUSEI_KBN,
    BM03.FIRST_USER,
    BM03.FIRST_PGM,
    BM03.FIRST_TMSP,
    BM03.LAST_USER,
    BM03.LAST_PGM,
    BM03.LAST_TMSP
FROM
    BM03USCP BM03
LEFT JOIN 
    BC02COMP ON (BM03.R_COMPANY_CD = BC02COMP.R_COMPANY_CD)

WHERE 
	BM03.USER_ID = /*userId*/'99990002'
/*IF zokuseiKbn != null*/
AND BM03.ZOKUSEI_KBN = /*zokuseiKbn*/'1'
/*END*/
ORDER BY BM03.USER_ID