SELECT DISTINCT 
       BM10.HONBU_CD 
,      BM10.JIGYOU_CD 
,      BM10.SLAREA_CD
,      rtrim(BM10.SIBU_CD) AS SIBU_CD
,      rtrim(BM10.SIBU_NAME) as SIBU_NAME

FROM  BM10GSIB BM10
,     BM01TENM BM01

WHERE BM10.COMPANY_CD = '00'
/*IF sysDate != null */
AND   BM01.CLOSE_DT >= /*sysDate*/'20110802'
/*END*/
AND   BM10.COMPANY_CD = BM01.COMPANY_CD
/*IF areaDai*/
AND   BM10.AREA_DAI_FLG = '1'
AND   BM10.SIBU_CD = BM01.AREA_DAI
--ELSE
AND   BM10.SIBU_CD = BM01.SIBU_CD
/*END*/

ORDER BY BM10.HONBU_CD
,        BM10.JIGYOU_CD 
,        BM10.SLAREA_CD
,        SIBU_CD