select distinct
	rtrim(BT04.REG_DATE) as REG_DATE,
	rtrim(BT04.SEQ) as SEQ,  
	rtrim(BT04.CATE_ID) as CATE_ID,  
	rtrim(BM02IFCT.CATE_NAME) as CATE_NAME, 
	rtrim(BT04.SUB_CATE_ID) as SUB_CATE_ID,
	rtrim(BM17SBCT.SUB_CATE_NAME) as SUB_CATE_NAME, 
	rtrim(BT04.TITLE) as TITLE, 
	rtrim(BT04.DISCRIPTION) as DISCRIPTION, 
	rtrim(BT04.PUB_DATE_FROM) as PUB_DATE_FROM, 
	rtrim(BT04.PUB_DATE_TO) as PUB_DATE_TO, 
	rtrim(BT04.PUB_USER) as PUB_USER, 
	rtrim(BR01USER.USER_NAME_KJ) as USER_NAME_KJ, 
	rtrim(BT04.PUB_ORG) as PUB_ORG, 
	rtrim(BT04.PUB_ORG_NAME) as PUB_ORG_NAME, 
	rtrim(BT04.FILE_NAME) as FILE_NAME, 
	rtrim(BT04.ATTACH_NAME1) as ATTACH_NAME1, 
	rtrim(BT04.ATTACH_NAME2) as ATTACH_NAME2, 
	rtrim(BT04.ATTACH_NAME3) as ATTACH_NAME, 
	rtrim(BT04.ATTACH_FL1) as ATTACH_FL1, 
	rtrim(BT04.ATTACH_FL2) as ATTACH_FL2, 
	rtrim(BT04.ATTACH_FL3) as ATTACH_FL3, 
	rtrim(BT04.LIMIT_KBN) as LIMIT_KBN, 
	rtrim(BT04.SORT_SEQ) as SORT_SEQ, 
	rtrim(BT04.SAKUJO_FLG) as SAKUJO_FLG, 
	rtrim(BT14.GYOTAI_KBN) as GYOTAI_KBN,
	rtrim(BT14.KOBETSU_FLG) as KOBETSU_FLG, 
	rtrim(BT14.MISE_FLG) as MISE_FLG,
	BM02IFCT.SORT_KEY as CATE_SORT_KEY,
	BM17SBCT.SORT_KEY as SUB_CATE_SORT_KEY
from 
 	BT04FRMM BT04
    inner join BM02IFCT on BT04.CATE_ID = BM02IFCT.CATE_ID 
                      and BM02IFCT.INFO_SHU = /*infoShu*/'04'
    inner join BM17SBCT on BT04.CATE_ID = BM17SBCT.CATE_ID 
                      and BT04.SUB_CATE_ID = BM17SBCT.SUB_CATE_ID 
                      and BM17SBCT.INFO_SHU = /*infoShu*/'04'
    left join BR01USER on BT04.PUB_USER = BR01USER.USER_ID
   ,BT12IACP BT12
   ,BT13IASZ BT13
   ,BT14IAGT BT14
   ,BM03USCP BM03
   ,BM05USGT BM05
   ,BM13SHKM BM13
where
    BT04.SAKUJO_FLG <> '1'
and BM03.USER_ID = /*userId*/'99990003'
and BM13.USER_ID = /*userId*/'99990003'
and BM05.USER_ID = /*userId*/'99990003'
and BT04.PUB_DATE_FROM <= /*sysDate*/'20060101'
and BT04.PUB_DATE_TO >= /*sysDate*/'20060101'    
and BT12.INFO_SHU = /*infoShu*/'04' 
and BT04.REG_DATE = BT12.REG_DATE
and BT04.SEQ = BT12.SEQ
and BT13.INFO_SHU = /*infoShu*/'04' 
and BT04.REG_DATE = BT13.REG_DATE
and BT04.SEQ = BT13.SEQ
and BT14.INFO_SHU = /*infoShu*/'04' 
and BT04.REG_DATE = BT14.REG_DATE
and BT04.SEQ = BT14.SEQ
and BT12.R_COMPANY_CD = BM03.R_COMPANY_CD
and BT13.SHOZOKU_KBN = BM13.SHOZOKU_KBN
and BT14.GYOTAI_KBN = BM05.GYOTAI_KBN
order by
    rtrim(BT04.CATE_ID),
    rtrim(BT04.SUB_CATE_ID),
    rtrim(BT04.REG_DATE),
    rtrim(BT04.SEQ)
    
    
    