SELECT SUBSTR((CASE WHEN BT4YOSAN.YOSAN_DT IS NULL THEN BD35.EIGYO_DT ELSE BT4YOSAN.YOSAN_DT END), 1,6) AS EIGYO_YM
,      (CASE WHEN BT4YOSAN.YOSAN_DT IS NOT NULL THEN BT4YOSAN.YOSAN_DT ELSE BD35.EIGYO_DT END) AS EIGYO_DT 
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.URIAGE END) AS URIAGE
,      (CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END) AS YOSAN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.URIAGE_ZEN END)   AS URIAGE_ZEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.KYAKUSU END)  AS KYAKUSU
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.KYAKUSU_ZEN END)  AS KYAKUSU_ZEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.EIGYO_DAYS END) AS EIGYO_DAYS
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.TENKO_KBN END) AS TENKO_KBN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.EIGYO_DAYS_ZEN END)  AS EIGYO_DAYS_ZEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.TENKO_KBN_ZEN END)  AS TENKO_KBN_ZEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.CHARGE_KIN_CANCEL END) AS CHARGE_KIN_CANCEL
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.CHARGE_KEN_CANCEL END) AS CHARGE_KEN_CANCEL
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.USE_KIN_CANCEL END) AS USE_KIN_CANCEL
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.USE_KEN_CANCEL END) AS USE_KEN_CANCEL
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.BONUS_V_ISSUE END) AS BONUS_V_ISSUE
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.BONUS_V_USE END) AS BONUS_V_USE
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.COUPON_V_ISSUE END) AS COUPON_V_ISSUE
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.COUPON_V_USE END) AS COUPON_V_USE
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ZANDAKA END) AS ZANDAKA
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ISSUE_CNT END)  AS ISSUE_CNT
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.CHARGE_KIN END) AS CHARGE_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.CHARGE_KEN END) AS CHARGE_KEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.KESSAI_KIN END) AS KESSAI_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.KESSAI_KEN END) AS KESSAI_KEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ZEN_ISSUE_CNT END)  AS ZEN_ISSUE_CNT
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ZEN_CHARGE_KIN END) AS ZEN_CHARGE_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ZEN_CHARGE_KEN END) AS ZEN_CHARGE_KEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ZEN_KESSAI_KIN END) AS ZEN_KESSAI_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.ZEN_KESSAI_KEN END) AS ZEN_KESSAI_KEN

/*IF paramsDto.selectHosei==true */
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_URIAGE END) AS NET_URIAGE
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_URIAGE_ZEN END) AS NET_URIAGE_ZEN      
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_KYAKUSU END) AS NET_KYAKUSU
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_KYAKUSU_ZEN END) AS NET_KYAKUSU_ZEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_ISSUE_CNT END) AS NET_ISSUE_CNT
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_CHARGE_KIN END) AS NET_CHARGE_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_CHARGE_KEN END) AS NET_CHARGE_KEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_KESSAI_KIN END) AS NET_KESSAI_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_KESSAI_KEN END) AS NET_KESSAI_KEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_ZEN_ISSUE_CNT END) AS NET_ZEN_ISSUE_CNT
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_ZEN_CHARGE_KIN END) AS NET_ZEN_CHARGE_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_ZEN_CHARGE_KEN END) AS NET_ZEN_CHARGE_KEN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_ZEN_KESSAI_KIN END) AS NET_ZEN_KESSAI_KIN
,      (CASE WHEN BD35.EIGYO_DT IS NULL THEN 0 ELSE BD35.NET_ZEN_KESSAI_KEN END) AS NET_ZEN_KESSAI_KEN
/*END*/
from (SELECT YOSANTBL.YOSAN_DT
      ,      SUM(YOSANTBL.YOSAN) AS YOSAN
      FROM (SELECT BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */  
             , BM01.MISE_CD 
/*END*/
             FROM BM01TENM BM01
             WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
             AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
    /*IF "SIBU".equals(paramsDto.taishoJoken) */
            AND   BM01.SIBU_CD = /*paramsDto.hyojiTaisho*/'004'
        /*IF paramsDto.existsBlockCd */  
            AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
        /*END*/
    /*END*/
    /*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
             AND   EXISTS (SELECT * FROM BM10GSIB BM10
                           WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                           AND   BM10./*$paramsDto.taishoJoken*/'SIBU'_CD = /*paramsDto.hyojiTaisho*/'031'
                           AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
    /*END*/         
    /*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM09GTSG BM09
                      WHERE BM09.SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                      AND   BM09.GYOTAI_KBN = BM01.GYOTAI_KBN)
    /*END*/
    /*IF birdUserInfo.limit*/
            AND   EXISTS (SELECT * FROM BM51SVSB AS BM51
                      WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                      AND   BM51.SV_CD      = /*birdUserInfo.userID*/'00000921'
                      AND   BM51.SIBU_CD    = BM01.SIBU_CD)
    /*END*/
/*END*/
		    GROUP BY BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */  
            ,        BM01.MISE_CD 
/*END*/
     ) BM01
     ,      BT45DSJY YOSANTBL
      WHERE YOSANTBL.YOSAN_DT < /*birdDateInfo.sysDate*/'20110228'
      AND   YOSANTBL.YOSAN_DT BETWEEN /*paramsDto.focusTabFromAddDay*/ AND /*paramsDto.focusTabToAddDay*/
/*IF "SIBU".equals(paramsDto.taishoJoken) */  
      AND   YOSANTBL.SIBU_CD = /*paramsDto.hyojiTaisho*/'031'
/*END*/
/*IF "MISE".equals(paramsDto.taishoJoken) */  
      AND   YOSANTBL.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "1".equals(paramsDto.tenpoShubetu) || "3".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU = /*paramsDto.tenpoShubetu*/'1'
/*END*/
/*IF "2".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU IN ('1', '2')
/*END*/
      AND   YOSANTBL.SIBU_CD    = BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */
      AND   YOSANTBL.MISE_CD = BM01.MISE_CD
/*END*/
      group by YOSANTBL.YOSAN_DT
      ) BT4YOSAN
FULL OUTER JOIN ( 
      SELECT BD35.EIGYO_DT
      ,      SUM(BD35.URIAGE) AS URIAGE
      ,      SUM(BD35.ONER_YOSAN) AS ONER_YOSAN
      ,      SUM(BD35.EIGYO_DAYS) AS EIGYO_DAYS
      ,      MAX(BD35.TENKO_KBN) AS TENKO_KBN
      ,      SUM(BD35.KYAKUSU) AS KYAKUSU
      ,      SUM(BD35.CHARGE_KIN_CANCEL) AS CHARGE_KIN_CANCEL
      ,      SUM(BD35.CHARGE_KEN_CANCEL) AS CHARGE_KEN_CANCEL
      ,      SUM(BD35.USE_KIN_CANCEL) AS USE_KIN_CANCEL
      ,      SUM(BD35.USE_KEN_CANCEL) AS USE_KEN_CANCEL
      ,      SUM(BD35.BONUS_V_ISSUE) AS BONUS_V_ISSUE
      ,      SUM(BD35.BONUS_V_USE) AS BONUS_V_USE
      ,      SUM(BD35.COUPON_V_ISSUE) AS COUPON_V_ISSUE
      ,      SUM(BD35.COUPON_V_USE) AS COUPON_V_USE
      ,      SUM(CASE WHEN BD35.OPEN_KBN = 1 THEN BD35.ZANDAKA ELSE 0 END) AS ZANDAKA
      ,      SUM(BD35.ISSUE_CNT) AS ISSUE_CNT
      ,      SUM(BD35.CHARGE_KIN) AS CHARGE_KIN
      ,      SUM(BD35.CHARGE_KEN) AS CHARGE_KEN
      ,      SUM(BD35.KESSAI_KIN) AS KESSAI_KIN
      ,      SUM(BD35.KESSAI_KEN) AS KESSAI_KEN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_URIAGE) AS URIAGE_ZEN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_EIGYO_DAYS) AS EIGYO_DAYS_ZEN
      ,      MAX(BD35./*$zdsColmunName*/'DOGETU'_ZEN_TENKO_KBN) AS TENKO_KBN_ZEN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_KYAKUSU) AS KYAKUSU_ZEN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_ISSUE_CNT) AS ZEN_ISSUE_CNT
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_CHARGE_KIN) AS ZEN_CHARGE_KIN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_CHARGE_KEN) AS ZEN_CHARGE_KEN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_KESSAI_KIN) AS ZEN_KESSAI_KIN
      ,      SUM(BD35./*$zdsColmunName*/'DOGETU'_ZEN_KESSAI_KEN) AS ZEN_KESSAI_KEN
/*IF paramsDto.selectHosei==true */
       ,     SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.URIAGE ELSE 0 END) AS NET_URIAGE
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.EIGYO_DAYS ELSE 0 END) AS NET_EIGYO_DAYS
      ,      MAX(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.TENKO_KBN ELSE 0 END) AS NET_TENKO_KBN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.KYAKUSU ELSE 0 END) AS NET_KYAKUSU
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_URIAGE ELSE 0 END) AS NET_URIAGE_ZEN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_EIGYO_DAYS ELSE 0 END) AS NET_EIGYO_DAYS_ZEN
      ,      MAX(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_TENKO_KBN ELSE 0 END) AS NET_TENKO_KBN_ZEN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_KYAKUSU ELSE 0 END) AS NET_KYAKUSU_ZEN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.ISSUE_CNT ELSE 0 END) AS NET_ISSUE_CNT
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.CHARGE_KIN ELSE 0 END) AS NET_CHARGE_KIN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.CHARGE_KEN ELSE 0 END) AS NET_CHARGE_KEN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.KESSAI_KIN ELSE 0 END) AS NET_KESSAI_KIN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.KESSAI_KEN ELSE 0 END) AS NET_KESSAI_KEN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_ISSUE_CNT ELSE 0 END) AS NET_ZEN_ISSUE_CNT
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_CHARGE_KIN ELSE 0 END) AS NET_ZEN_CHARGE_KIN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_CHARGE_KEN ELSE 0 END) AS NET_ZEN_CHARGE_KEN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_KESSAI_KIN ELSE 0 END) AS NET_ZEN_KESSAI_KIN
      ,      SUM(CASE WHEN BD35.URIAGE > 0 AND BD35.DOGETU_ZEN_URIAGE > 0 THEN BD35.DOGETU_ZEN_KESSAI_KEN ELSE 0 END) AS NET_ZEN_KESSAI_KEN
/*END*/ 
      FROM (SELECT BM01.MISE_CD FROM BM01TENM BM01
            WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
            AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
    /*IF "SIBU".equals(paramsDto.taishoJoken) */
            AND   BM01.SIBU_CD = /*paramsDto.hyojiTaisho*/'004'
        /*IF paramsDto.existsBlockCd */  
            AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
        /*END*/
    /*END*/
    /*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM10GSIB BM10
                          WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM10./*$paramsDto.taishoJoken*/'JIGYOU'_CD = /*paramsDto.hyojiTaisho*/'031'
                          AND   BM10.COMPANY_CD = BM01.COMPANY_CD
                          AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
    /*END*/         
    /*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM09GTSG BM09
                          WHERE SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                          AND BM09.GYOTAI_KBN = BM01.GYOTAI_KBN)
    /*END*/
    /*IF birdUserInfo.limit */
            AND   EXISTS (SELECT * FROM BM51SVSB AS BM51
                          WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM51.SV_CD = /*birdUserInfo.userID*/'00000921'
                          AND   BM51.SIBU_CD = BM01.SIBU_CD)
    /*END*/
    /*IF "ALL".equals(paramsDto.taishoJoken) */
		UNION ALL 
            SELECT CAST('00000' AS CHAR(5)) AS MISE_CD FROM BM01TENM BM01
            WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
            GROUP BY CAST('00000' AS CHAR(5))  
    /*END*/
/*END*/
        ) BM01 
      ,     BD35ZNMC BD35 
      WHERE BD35.EIGYO_DT BETWEEN /*paramsDto.focusTabFromAddDay*/ AND /*paramsDto.focusTabToAddDay*/
      AND   BD35.EIGYO_DT < /*birdDateInfo.sysDate*/'20130520'
      AND   BD35.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
      AND   BD35.MISE_CD = /*paramsDto.hyojiTaisho*/'02001'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) && "ALL".equals(paramsDto.tenpoShubetu) */
      AND   (BD35.OPEN_KBN + BD35.DOGETU_ZEN_OPEN_KBN) > 0
--ELSE
      AND   BD35.OPEN_KBN   = 1
/*END*/
      AND   BD35.OLDM_FLG   = '0'
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) && "ALL".equals(paramsDto.tenpoShubetu) ==false */
      AND   (EXISTS (
         SELECT * FROM BN01DTEN BN01
         WHERE BN01.COMPANY_CD = /*paramsDto.companyCd*/'00'
		/*IF paramsDto.tenpoShubetu == "2" */
         AND   BN01.KBN1 IN ('1', '2')
		--ELSE
         AND   BN01.KBN1 = /*paramsDto.tenpoShubetu*/'1'
		/*END*/
         AND   BD35.EIGYO_DT   = BN01.EIGYO_DT
         AND   BD35.MISE_CD    = BN01.MISE_CD 
	  )
	/*IF "ALL".equals(paramsDto.taishoJoken) */
		OR BD35.MISE_CD = '00000'
	/*END*/
	)
/*END*/
      AND   BD35.MISE_CD    = BM01.MISE_CD
      GROUP BY BD35.EIGYO_DT
) BD35 ON (BD35.EIGYO_DT = BT4YOSAN.YOSAN_DT)
ORDER BY EIGYO_DT
