SELECT BR66.URI_SOKU_YM
,      CAMPMST.CAMP_ID
,      CASE WHEN BR66.TITLE_FLG IS NOT NULL THEN BR66.TITLE_FLG ELSE '0' END AS TITLE_FLG
,      CASE WHEN BR66.JISSEKI_FLG IS NOT NULL THEN BR66.JISSEKI_FLG ELSE '0' END AS JISSEKI_FLG
,      CAMPMST.SEQ_NO
,      CAMPMST.CAMP_TITLE
,      CAMPMST.CAMP_FROM
,      CAMPMST.CAMP_TO
,      MAX(SUMMENU.MENU_SEQ_NO) OVER (partition by CAMPMST.CAMP_ID) AS MENU_CNT
,      ROW_NUMBER() OVER(partition by CAMPMST.CAMP_ID order by SUMMENU.MENU_CD) AS MENU_SEQ_NO
,      SUMMENU.MENU_CD
,      RTRIM(PC10.MENU_NAME_KJ) AS MENU_NAME_KJ
,      BR66.FIRST_USER
,      BR66.FIRST_PGM
,      BR66.FIRST_TMSP
,      BR66.LAST_USER
,      BR66.LAST_PGM
,      BR66.LAST_TMSP

FROM (
	SELECT ROW_NUMBER() OVER(order by BM60.CAMP_FROM DESC, BM60.CAMP_ID DESC) AS SEQ_NO
	,      BM60.CAMP_ID
	,      BM60.COMPANY_CD
	,      RTRIM(BM60.CAMP_TITLE) AS CAMP_TITLE
	,      BM60.CAMP_FROM
	,      BM60.CAMP_TO
	,      BM60.DISP_FROM
	,      BM60.DISP_TO
	,      BM60.YOBI_FROM
	,      BM60.YOBI_TO
	FROM BM60CPDT BM60
	WHERE BM60.COMPANY_CD = /*companyCd*/'00'
	AND   (BM60.CAMP_ID IN (SELECT CAMP_ID FROM BR66SKCP
	                       WHERE URI_SOKU_YM = /*taishoYm*/'200805'
	                       AND (TITLE_FLG = '1' OR JISSEKI_FLG = '1')
	                       )
	       OR    (SUBSTR(BM60.CAMP_FROM, 1,6) <= /*taishoYm*/'200805'
	              AND   SUBSTR(BM60.CAMP_TO, 1,6) >= /*taishoYm*/'200805')
	      )
	GROUP BY BM60.CAMP_ID
	,      BM60.COMPANY_CD
	,      RTRIM(BM60.CAMP_TITLE)
	,      BM60.CAMP_FROM
	,      BM60.CAMP_TO
	,      BM60.DISP_FROM
	,      BM60.DISP_TO
	,      BM60.YOBI_FROM
	,      BM60.YOBI_TO
) CAMPMST
LEFT JOIN BR66SKCP BR66
     ON (BR66.URI_SOKU_YM = /*taishoYm*/'200805' AND BR66.CAMP_ID = CAMPMST.CAMP_ID)
,   (
      SELECT CAMP_ID 
	,      ROW_NUMBER() OVER(partition by CAMP_ID) AS MENU_SEQ_NO
      ,      MENU_CD
      FROM (
	SELECT DISTINCT BM61.CAMP_ID
	,      (CASE WHEN BM69.SUM_MENU_CD IS NOT NULL THEN BM69.SUM_MENU_CD 
	             WHEN BM62.SUM_MENU_CD IS NOT NULL THEN BM62.SUM_MENU_CD 
	        ELSE BM61.MENU_CD END) AS MENU_CD
	FROM BM61CPMN BM61
	LEFT JOIN BM69SYMP BM69
	     ON (BM69.CAMP_ID = BM61.CAMP_ID AND BM69.MENU_CD = BM61.MENU_CD)
	LEFT JOIN BM62SYMM BM62
	     ON (BM62.MENU_CD = BM61.MENU_CD)
      )SUB

	) SUMMENU
LEFT JOIN PC10SMNU PC10 ON (PC10.MENU_CD = SUMMENU.MENU_CD)	
	
WHERE SUMMENU.CAMP_ID = CAMPMST.CAMP_ID

ORDER BY CAMP_FROM DESC
,        CAMP_ID DESC
,        MENU_SEQ_NO
