SELECT (CASE WHEN BT4YOSAN.YOSAN_DT IS NULL THEN BD53.EIGYO_DT ELSE BT4YOSAN.YOSAN_DT END) AS EIGYO_DT 
,      (CASE WHEN BD53.URIAGE IS NULL THEN 0 ELSE BD53.URIAGE END) AS URIAGE
,      (CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END) AS YOSAN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_ZEN END) AS URIAGE_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.EIGYO_DAYS END) AS EIGYO_DAYS
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.EIGYO_DAYS_ZEN END) AS EIGYO_DAYS_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU END) AS KYAKUSU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_ZEN END) AS KYAKUSU_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.EIGYO_DAYS_NSUM END) AS EIGYO_DAYS_NSUM
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.MISECNT_NSUM END) AS MISECNT_KBN_NSUM
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_NSUM END) AS URIAGE_NSUM
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_NSUM END) AS KYAKUSU_NSUM
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_NSUM_ZEN END) AS URIAGE_NSUM_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_NSUM_ZEN END) AS KYAKUSU_NSUM_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.EIGYO_DAYS_NTAKE END) AS EIGYO_DAYS_NTAKE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.MISECNT_NTAKE END) AS MISECNT_KBN_NTAKE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_NTAKE END) AS URIAGE_NTAKE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_NTAKE END) AS KYAKUSU_NTAKE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_NTAKE_ZEN END) AS URIAGE_NTAKE_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_NTAKE_ZEN END) AS KYAKUSU_NTAKE_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.EIGYO_DAYS_NTAKU END) AS EIGYO_DAYS_NTAKU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.MISECNT_NTAKU END) AS MISECNT_KBN_NTAKU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_NTAKU END) AS URIAGE_NTAKU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_NTAKU END)  AS KYAKUSU_NTAKU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_NTAKU_ZEN END) AS URIAGE_NTAKU_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_NTAKU_ZEN END) AS KYAKUSU_NTAKU_ZEN
/*IF paramsDto.selectHosei */
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI END) AS NET_URIAGE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_ZEN END) AS NET_URIAGE_ZEN      
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI END) AS NET_KYAKUSU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_ZEN END) AS NET_KYAKUSU_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_NSUM END) AS NET_URIAGE_NSUM
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_NSUM_ZEN END) AS NET_URIAGE_NSUM_ZEN      
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_NSUM END) AS NET_KYAKUSU_NSUM
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_NSUM_ZEN END) AS NET_KYAKUSU_NSUM_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_NTAKE END) AS NET_URIAGE_NTAKE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_NTAKE_ZEN END) AS NET_URIAGE_NTAKE_ZEN      
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_NTAKE END) AS NET_KYAKUSU_NTAKE
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_NTAKE_ZEN END) AS NET_KYAKUSU_NTAKE_ZEN
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_NTAKU END) AS NET_URIAGE_NTAKU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.URIAGE_HOSEI_NTAKU_ZEN END) AS NET_URIAGE_NTAKU_ZEN      
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_NTAKU END) AS NET_KYAKUSU_NTAKU
,      (CASE WHEN BD53.EIGYO_DT IS NULL THEN 0 ELSE BD53.KYAKUSU_HOSEI_NTAKU_ZEN END) AS NET_KYAKUSU_NTAKU_ZEN
/*END*/
from (SELECT YOSANTBL.YOSAN_DT
      ,      SUM(YOSANTBL.YOSAN) AS YOSAN
      FROM   (SELECT BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */
            ,      BM01.MISE_CD 
/*END*/
            FROM BM01TENM BM01
            WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF paramsDto.taishoJoken.equals("MISE") */  
            AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
	/*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM10GSIB BM10
                          WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM10./*$paramsDto.taishoJoken*/'SIBU'_CD = /*paramsDto.hyojiTaisho*/'031'
		/*IF "SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd */  
                          AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
		/*END*/
                          AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
	/*END*/
	/*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM09GTSG BM09
                          WHERE SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                          AND BM09.GYOTAI_KBN = BM01.GYOTAI_KBN)
	/*END*/
	/*IF birdUserInfo.limit*/
            AND EXISTS (SELECT * FROM BM51SVSB AS BM51
                          WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM51.SV_CD      = /*birdUserInfo.userID*/'00000921'
                          AND   BM51.SIBU_CD    = BM01.SIBU_CD)
	/*END*/
/*END*/
/*IF (("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken))==false */
        GROUP BY BM01.SIBU_CD
/*END*/
     ) BM01
,    BT44MSJY YOSANTBL
      WHERE YOSANTBL.YOSAN_DT BETWEEN /*kikanFrom*/'201203' AND /*kikanTo*/'201304'
      AND   YOSANTBL.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "1".equals(paramsDto.tenpoShubetu) || "3".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU = /*paramsDto.tenpoShubetu*/'1'
/*END*/
/*IF "2".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU IN ('1', '2')
/*END*/
      AND   YOSANTBL.SIBU_CD = BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.blockCd != null) || "MISE".equals(paramsDto.taishoJoken) */
      AND   YOSANTBL.MISE_CD = BM01.MISE_CD
/*END*/
      
/*END*/
      group by YOSANTBL.YOSAN_DT
      ) BT4YOSAN
FULL OUTER JOIN    (
      SELECT SUB.EIGYO_DT
      ,      SUM(URIAGE) AS URIAGE
      ,      SUM(ONER_YOSAN) AS ONER_YOSAN
      ,      SUM(EIGYO_DAYS) AS EIGYO_DAYS
      ,      SUM(KYAKUSU) AS KYAKUSU
      ,      SUM(EIGYO_DAYS_ZEN) AS EIGYO_DAYS_ZEN
      ,      SUM(URIAGE_ZEN) AS URIAGE_ZEN
      ,      SUM(KYAKUSU_ZEN) AS KYAKUSU_ZEN
      ,      SUM(EIGYO_DAYS_NSUM) AS EIGYO_DAYS_NSUM
      ,      SUM(MISECNT_NSUM) AS MISECNT_NSUM
      ,      SUM(URIAGE_NSUM) AS URIAGE_NSUM
      ,      SUM(KYAKUSU_NSUM) AS KYAKUSU_NSUM
      ,      SUM(URIAGE_NSUM_ZEN) AS URIAGE_NSUM_ZEN
      ,      SUM(KYAKUSU_NSUM_ZEN) AS KYAKUSU_NSUM_ZEN
      ,      SUM(EIGYO_DAYS_NTAKE) AS EIGYO_DAYS_NTAKE
      ,      SUM(MISECNT_NTAKE) AS MISECNT_NTAKE
      ,      SUM(URIAGE_NTAKE) AS URIAGE_NTAKE
      ,      SUM(KYAKUSU_NTAKE) AS KYAKUSU_NTAKE
      ,      SUM(URIAGE_NTAKE_ZEN) AS URIAGE_NTAKE_ZEN
      ,      SUM(KYAKUSU_NTAKE_ZEN) AS KYAKUSU_NTAKE_ZEN
      ,      SUM(EIGYO_DAYS_NTAKU) AS EIGYO_DAYS_NTAKU
      ,      SUM(MISECNT_NTAKU) AS MISECNT_NTAKU
      ,      SUM(URIAGE_NTAKU) AS URIAGE_NTAKU
      ,      SUM(KYAKUSU_NTAKU) AS KYAKUSU_NTAKU
      ,      SUM(URIAGE_NTAKU_ZEN) AS URIAGE_NTAKU_ZEN
      ,      SUM(KYAKUSU_NTAKU_ZEN) AS KYAKUSU_NTAKU_ZEN
/*IF paramsDto.selectHosei */
      ,      SUM(URIAGE_HOSEI)          AS URIAGE_HOSEI
      ,      SUM(ONER_YOSAN_HOSEI)      AS ONER_YOSAN_HOSEI
      ,      SUM(EIGYO_DAYS_HOSEI)      AS EIGYO_DAYS_HOSEI
      ,      SUM(KYAKUSU_HOSEI)         AS KYAKUSU_HOSEI
      ,      SUM(URIAGE_HOSEI_ZEN)      AS URIAGE_HOSEI_ZEN
      ,      SUM(EIGYO_DAYS_HOSEI_ZEN)  AS EIGYO_DAYS_HOSEI_ZEN
      ,      SUM(KYAKUSU_HOSEI_ZEN)     AS KYAKUSU_HOSEI_ZEN
      ,      SUM(EIGYO_DAYS_HOSEI_NSUM) AS EIGYO_DAYS_HOSEI_NSUM
      ,      SUM(MISECNT_DOGETU_NSUM)   AS MISECNT_DOGETU_NSUM
      ,      SUM(URIAGE_HOSEI_NSUM)     AS URIAGE_HOSEI_NSUM
      ,      SUM(KYAKUSU_HOSEI_NSUM)    AS KYAKUSU_HOSEI_NSUM
      ,      SUM(URIAGE_HOSEI_NSUM_ZEN) AS URIAGE_HOSEI_NSUM_ZEN
      ,      SUM(KYAKUSU_HOSEI_NSUM_ZEN) AS KYAKUSU_HOSEI_NSUM_ZEN
      ,      SUM(EIGYO_DAYS_HOSEI_NTAKE) AS EIGYO_DAYS_HOSEI_NTAKE
      ,      SUM(MISECNT_DOGETU_NTAKE)   AS MISECNT_DOGETU_NTAKE
      ,      SUM(URIAGE_HOSEI_NTAKE)     AS URIAGE_HOSEI_NTAKE
      ,      SUM(KYAKUSU_HOSEI_NTAKE)    AS KYAKUSU_HOSEI_NTAKE
      ,      SUM(URIAGE_HOSEI_NTAKE_ZEN) AS URIAGE_HOSEI_NTAKE_ZEN
      ,      SUM(KYAKUSU_HOSEI_NTAKE_ZEN) AS KYAKUSU_HOSEI_NTAKE_ZEN
      ,      SUM(EIGYO_DAYS_HOSEI_NTAKU) AS EIGYO_DAYS_HOSEI_NTAKU
      ,      SUM(MISECNT_DOGETU_NTAKU)   AS MISECNT_DOGETU_NTAKU
      ,      SUM(URIAGE_HOSEI_NTAKU)     AS URIAGE_HOSEI_NTAKU
      ,      SUM(KYAKUSU_HOSEI_NTAKU)    AS KYAKUSU_HOSEI_NTAKU
      ,      SUM(URIAGE_HOSEI_NTAKU_ZEN) AS URIAGE_HOSEI_NTAKU_ZEN
      ,      SUM(KYAKUSU_HOSEI_NTAKU_ZEN) AS KYAKUSU_HOSEI_NTAKU_ZEN
/*END*/
      FROM ( 
      SELECT BD53.EIGYO_DT
      ,      BD53.MISE_CD
      ,      SUM(BD53.URIAGE_/*$zdsColmunName*/'DOGETU') AS URIAGE
      ,      SUM(BD53.ONER_YOSAN_/*$zdsColmunName*/'DOGETU') AS ONER_YOSAN
      ,      SUM(BD53.EIGYO_DAYS_/*$zdsColmunName*/'DOGETU') AS EIGYO_DAYS
      ,      SUM(BD53.KYAKUSU_/*$zdsColmunName*/'DOGETU') AS KYAKUSU
      ,      SUM(BD53.EIGYO_DAYS_ZEN_/*$zdsColmunName*/'DOGETU') AS EIGYO_DAYS_ZEN
      ,      SUM(BD53.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU') AS URIAGE_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU') AS KYAKUSU_ZEN
      ,      SUM(BD53.EIGYO_DAYS_/*$zdsColmunName*/'DOGETU'_NSUM) AS EIGYO_DAYS_NSUM
      ,      MAX(BD53.MISECNT_/*$zdsColmunName*/'DOGETU'_NSUM) AS MISECNT_NSUM
      ,      SUM(BD53.URIAGE_/*$zdsColmunName*/'DOGETU'_NSUM) AS URIAGE_NSUM
      ,      SUM(BD53.KYAKUSU_/*$zdsColmunName*/'DOGETU'_NSUM) AS KYAKUSU_NSUM
      ,      SUM(BD53.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU'_NSUM) AS URIAGE_NSUM_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU'_NSUM) AS KYAKUSU_NSUM_ZEN
      ,      SUM(BD53.EIGYO_DAYS_/*$zdsColmunName*/'DOGETU'_NTAKE) AS EIGYO_DAYS_NTAKE
      ,      MAX(BD53.MISECNT_/*$zdsColmunName*/'DOGETU'_NTAKE) AS MISECNT_NTAKE
      ,      SUM(BD53.URIAGE_/*$zdsColmunName*/'DOGETU'_NTAKE) AS URIAGE_NTAKE
      ,      SUM(BD53.KYAKUSU_/*$zdsColmunName*/'DOGETU'_NTAKE) AS KYAKUSU_NTAKE
      ,      SUM(BD53.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKE) AS URIAGE_NTAKE_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKE) AS KYAKUSU_NTAKE_ZEN
      ,      SUM(BD53.EIGYO_DAYS_/*$zdsColmunName*/'DOGETU'_NTAKU) AS EIGYO_DAYS_NTAKU
      ,      MAX(BD53.MISECNT_/*$zdsColmunName*/'DOGETU'_NTAKU) AS MISECNT_NTAKU
      ,      SUM(BD53.URIAGE_/*$zdsColmunName*/'DOGETU'_NTAKU) AS URIAGE_NTAKU
      ,      SUM(BD53.KYAKUSU_/*$zdsColmunName*/'DOGETU'_NTAKU) AS KYAKUSU_NTAKU
      ,      SUM(BD53.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKU) AS URIAGE_NTAKU_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKU) AS KYAKUSU_NTAKU_ZEN
/*IF paramsDto.selectHosei */
      ,      SUM(BD53.URIAGE_HOSEI)          AS URIAGE_HOSEI
      ,      SUM(BD53.ONER_YOSAN_HOSEI)      AS ONER_YOSAN_HOSEI
      ,      SUM(BD53.EIGYO_DAYS_HOSEI)      AS EIGYO_DAYS_HOSEI
      ,      SUM(BD53.KYAKUSU_HOSEI)         AS KYAKUSU_HOSEI
      ,      SUM(BD53.EIGYO_DAYS_ZEN_HOSEI)  AS EIGYO_DAYS_HOSEI_ZEN
      ,      SUM(BD53.URIAGE_ZEN_HOSEI)      AS URIAGE_HOSEI_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_HOSEI)     AS KYAKUSU_HOSEI_ZEN
      ,      SUM(BD53.EIGYO_DAYS_HOSEI_NSUM) AS EIGYO_DAYS_HOSEI_NSUM
      ,      MAX(BD53.MISECNT_DOGETU_NSUM)   AS MISECNT_DOGETU_NSUM
      ,      SUM(BD53.URIAGE_HOSEI_NSUM)     AS URIAGE_HOSEI_NSUM
      ,      SUM(BD53.KYAKUSU_HOSEI_NSUM)    AS KYAKUSU_HOSEI_NSUM
      ,      SUM(BD53.URIAGE_ZEN_HOSEI_NSUM) AS URIAGE_HOSEI_NSUM_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_HOSEI_NSUM) AS KYAKUSU_HOSEI_NSUM_ZEN
      ,      SUM(BD53.EIGYO_DAYS_HOSEI_NTAKE) AS EIGYO_DAYS_HOSEI_NTAKE
      ,      MAX(BD53.MISECNT_DOGETU_NTAKE)   AS MISECNT_DOGETU_NTAKE
      ,      SUM(BD53.URIAGE_HOSEI_NTAKE)     AS URIAGE_HOSEI_NTAKE
      ,      SUM(BD53.KYAKUSU_HOSEI_NTAKE)    AS KYAKUSU_HOSEI_NTAKE
      ,      SUM(BD53.URIAGE_ZEN_HOSEI_NTAKE) AS URIAGE_HOSEI_NTAKE_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_HOSEI_NTAKE) AS KYAKUSU_HOSEI_NTAKE_ZEN
      ,      SUM(BD53.EIGYO_DAYS_HOSEI_NTAKU) AS EIGYO_DAYS_HOSEI_NTAKU
      ,      MAX(BD53.MISECNT_DOGETU_NTAKU)   AS MISECNT_DOGETU_NTAKU
      ,      SUM(BD53.URIAGE_HOSEI_NTAKU)     AS URIAGE_HOSEI_NTAKU
      ,      SUM(BD53.KYAKUSU_HOSEI_NTAKU)    AS KYAKUSU_HOSEI_NTAKU
      ,      SUM(BD53.URIAGE_ZEN_HOSEI_NTAKU) AS URIAGE_HOSEI_NTAKU_ZEN
      ,      SUM(BD53.KYAKUSU_ZEN_HOSEI_NTAKU) AS KYAKUSU_HOSEI_NTAKU_ZEN
/*END*/

      FROM BD53NGEP BD53
      WHERE BD53.EIGYO_DT BETWEEN /*kikanFrom*/'201203' AND /*kikanTo*/'201304'
      AND   BD53.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF paramsDto.taishoJoken.equals("MISE") */  
      AND   BD53.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) && "ALL".equals(paramsDto.tenpoShubetu) */
      AND   (BD53.OPEN_KBN + BD53.OPEN_KBN_ZEN)>0
 --ELSE
      AND   BD53.OPEN_KBN  = 1
/*END*/
      AND   BD53.OLDM_FLG = '0'
      AND   EXISTS (
      		SELECT * FROM (
                SELECT COMPANY_CD, MISE_CD FROM BM01TENM BM01
                WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
                AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
	/*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
                AND   EXISTS (SELECT * FROM BM10GSIB BM10
                              WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                              AND   BM10./*$paramsDto.taishoJoken*/'SIBU'_CD = /*paramsDto.hyojiTaisho*/'031'
		/*IF "SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd */  
                              AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
		/*END*/
                              AND   BM10.COMPANY_CD = BM01.COMPANY_CD
                              AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
	/*END*/         
	/*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
                AND   EXISTS (SELECT * FROM BM09GTSG BM09
                              WHERE BM09.SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                              AND   BM09.GYOTAI_KBN   = BM01.GYOTAI_KBN)
	/*END*/
	/*IF birdUserInfo.limit*/
                AND   EXISTS (SELECT * FROM BM51SVSB AS BM51
                              WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                              AND   BM51.SV_CD = /*birdUserInfo.userID*/'00000921'
                              AND   BM51.COMPANY_CD = BM01.COMPANY_CD 
                              AND   BM51.SIBU_CD    = BM01.SIBU_CD)
	/*END*/
	/*IF "ALL".equals(paramsDto.taishoJoken) */
      		UNION ALL 
            SELECT CAST(/*paramsDto.companyCd*/'00' AS CHAR(2)) AS COMPANY_CD, CAST('00000' AS CHAR(5)) AS MISE_CD FROM BM01TENM
	/*END*/
/*END*/
        ) BM01 
        WHERE BD53.MISE_CD    = BM01.MISE_CD)
      GROUP BY BD53.EIGYO_DT
      ,        BD53.MISE_CD
      ) SUB
/*IF "ALL".equals(paramsDto.tenpoShubetu) ==false */
      WHERE EXISTS (
         SELECT * FROM BN01DTEN BN01
         WHERE BN01.COMPANY_CD = /*paramsDto.companyCd*/'00'
		/*IF paramsDto.tenpoShubetu == "2" */
         AND   BN01.KBN1 IN ('1', '2')
		--ELSE
         AND   BN01.KBN1 = /*paramsDto.tenpoShubetu*/'1'
		/*END*/
         AND   SUB.EIGYO_DT   = BN01.EIGYO_YM
         AND   SUB.MISE_CD    = BN01.MISE_CD 
	  )
	/*IF "ALL".equals(paramsDto.taishoJoken) */
		OR SUB.MISE_CD = '00000'
	/*END*/
/*END*/
      GROUP BY SUB.EIGYO_DT
) BD53
ON (BD53.EIGYO_DT = BT4YOSAN.YOSAN_DT)
order by EIGYO_DT
