SELECT DISTINCT CASE WHEN BR80.MENU_ID IS NULL THEN BR02.MENU_ID ELSE BR80.MENU_ID_MOTO END AS MOTO_MENU
   ,CASE WHEN BR80.MENU_ID IS NULL THEN BR02.SUB_MENU_ID ELSE BR80.SUB_MENU_ID_MOTO END AS MOTO_SUB_MENU
   ,BR02.MENU_name 
   ,BR02.MENU_ID 
   ,BR02.SUB_MENU_ID 
   ,BR02.SUB_MENU_name 
   ,BR02.SORT_SEQ
   ,MAX(BR05.ENABLE_FLG)  OVER( partition by BR02.MENU_name 
       ,BR02.MENU_ID 
       ,BR02.SUB_MENU_ID 
       ,BR02.SUB_MENU_name ) ENABLE_FLG 
   ,BR05.EXTRA_FLG 
   ,CASE WHEN BR80.MENU_ID IS NULL THEN '0' ELSE '1' END AS HIDDEN_FLG
   ,MIN(customize_flg) OVER( partition by BR02.MENU_name 
       ,BR02.MENU_ID 
       ,BR02.SUB_MENU_ID 
       ,BR02.SUB_MENU_name ) CUSTOMIZE_FLG
   ,BR04.USER_ID
   ,BR54.FIRST_USER
   ,BR54.FIRST_PGM
   ,BR54.FIRST_TMSP
   ,BR54.LAST_USER
   ,BR54.LAST_PGM
   ,BR54.LAST_TMSP
FROM
    BR02bmnu as BR02 
LEFT JOIN BR54usac BR54
      ON (user_ID = /*userId*/'99990002'
             and BR02.MENU_ID = BR54.MENU_ID 
             AND BR02.SUB_MENU_ID = BR54.SUB_MENU_ID)
   ,BR04usrl as BR04 
   ,BR05actr as BR05
   LEFT JOIN BR80AGMS BR80
    ON ( BR80.MENU_ID = BR05.MENU_ID 
         AND  BR80.SUB_MENU_ID = BR05.SUB_MENU_ID )
WHERE  BR02.MENU_ID = BR05.MENU_ID 
  AND  BR02.SUB_MENU_ID = BR05.SUB_MENU_ID 
  AND  BR05.ROLE_CD = BR04.role_cd 
  AND  BR05.EXTRA_FLG = '1' 

  AND  BR04.USER_ID = /*userId*/'99990002'
ORDER BY MENU_ID
,        HIDDEN_FLG
,        BR02.SORT_SEQ