INSERT INTO BM76SEID (TOUROKU_NO,
DATA_VER,
PLAN_NAME,
G_RENDO_KEISU,
G_RENDO_KEISU_YAKUIN,
G_POINT_DATE,
BIKOU,
SAKUJO_FLG,
FIRST_USER,
FIRST_PGM,
FIRST_TMSP,
LAST_USER,
LAST_PGM,
LAST_TMSP) values
(/*urSeidoMst.tourokuNo*/'0001' ,
/*urSeidoMst.dataVer*/'001',
/*urSeidoMst.planName*/'',
/*gRendoKeisu*/,
/*gRendoKeisuYakuin*/'',
/*urSeidoMst.gPointDate*/'' ,
/*urSeidoMst.bikou*/,
'0' ,
/*urSeidoMst.firstUser*/'' ,
'BBS036' ,
current timestamp ,
/*urSeidoMst.lastUser*/'' ,
'BBS036',
current timestamp)

