SELECT (CASE WHEN ALL.METER_YM IS NULL THEN '”N“x—ÝŒv' ELSE ALL.METER_YM END) AS METER_YM
,      (CASE WHEN (ALL.URIAGE              =0 OR ALL.URIAGE              IS NULL) THEN 0 ELSE ALL.URIAGE              END) AS URIAGE              
,      (CASE WHEN (ALL.ZENNEN_URIAGE       =0 OR ALL.ZENNEN_URIAGE       IS NULL) THEN 0 ELSE ALL.ZENNEN_URIAGE       END) AS ZEN_URIAGE       
,      (CASE WHEN (ALL.EIGYO_DAYS          =0 OR ALL.EIGYO_DAYS          IS NULL) THEN 0 ELSE DECIMAL(ALL.EIGYO_DAYS)          END) AS EIGYO_DAYS          
,      (CASE WHEN (ALL.ZENNEN_EIGYO_DAYS   =0 OR ALL.ZENNEN_EIGYO_DAYS   IS NULL) THEN 0 ELSE DECIMAL(ALL.ZENNEN_EIGYO_DAYS)   END) AS ZEN_EIGYO_DAYS   
,      (CASE WHEN (ALL.ELECTRIC_AMT        =0 OR ALL.ELECTRIC_AMT        IS NULL) THEN 0 ELSE ALL.ELECTRIC_AMT        END) AS ELECTRIC_AMT        
,      (CASE WHEN (ALL.ZENNEN_ELECTRIC_AMT =0 OR ALL.ZENNEN_ELECTRIC_AMT IS NULL) THEN 0 ELSE ALL.ZENNEN_ELECTRIC_AMT END) AS ELECTRIC_AMT_ZENNEN 
,      (CASE WHEN (ALL.POWER_AMT           =0 OR ALL.POWER_AMT           IS NULL) THEN 0 ELSE ALL.POWER_AMT           END) AS POWER_AMT           
,      (CASE WHEN (ALL.ZENNEN_POWER_AMT    =0 OR ALL.ZENNEN_POWER_AMT    IS NULL) THEN 0 ELSE ALL.ZENNEN_POWER_AMT    END) AS POWER_AMT_ZENNEN    
,      (CASE WHEN (ALL.GAS_AMT             =0 OR ALL.GAS_AMT             IS NULL) THEN 0 ELSE ALL.GAS_AMT             END) AS GAS_AMT             
,      (CASE WHEN (ALL.ZENNEN_GAS_AMT      =0 OR ALL.ZENNEN_GAS_AMT      IS NULL) THEN 0 ELSE ALL.ZENNEN_GAS_AMT      END) AS GAS_AMT_ZENNEN      
,      (CASE WHEN (ALL.WATER_AMT           =0 OR ALL.WATER_AMT           IS NULL) THEN 0 ELSE ALL.WATER_AMT           END) AS WATER_AMT           
,      (CASE WHEN (ALL.ZENNEN_WATER_AMT    =0 OR ALL.ZENNEN_WATER_AMT    IS NULL) THEN 0 ELSE ALL.ZENNEN_WATER_AMT    END) AS WATER_AMT_ZENNEN    
,      (CASE WHEN (ALL.ELECTRIC_AMT = 0 OR ALL.URIAGE =0 OR ALL.URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.ELECTRIC_AMT)) / (DOUBLE(((DOUBLE(ALL.URIAGE))/1000000))))+0.005, 16, 2) END) AS ELECTRIC_AMT_URIAGEHI 
,      (CASE WHEN (ALL.ZENNEN_ELECTRIC_AMT = 0 OR ALL.ZENNEN_ELECTRIC_AMT IS NULL OR ALL.ZENNEN_URIAGE =0 OR ALL.ZENNEN_URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.ZENNEN_ELECTRIC_AMT)) / (DOUBLE(((DOUBLE(ALL.ZENNEN_URIAGE))/1000000))))+0.005,16, 2) END) AS ELECTRIC_AMT_URIAGEHI_ZENNEN 
,      (CASE WHEN (ALL.POWER_AMT = 0 OR ALL.URIAGE =0 OR ALL.URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.POWER_AMT)) / (DOUBLE(((DOUBLE(ALL.URIAGE))/1000000))))+0.005, 16, 2) END) AS POWER_AMT_URIAGEHI 
,      (CASE WHEN (ALL.ZENNEN_POWER_AMT = 0 OR ALL.ZENNEN_POWER_AMT IS NULL OR ALL.ZENNEN_URIAGE =0 OR ALL.ZENNEN_URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.ZENNEN_POWER_AMT)) / (DOUBLE(((DOUBLE(ALL.ZENNEN_URIAGE))/1000000))))+0.005, 16, 2) END) AS POWER_AMT_URIAGEHI_ZENNEN 
,      (CASE WHEN (ALL.GAS_AMT = 0 OR ALL.URIAGE =0 OR ALL.URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.GAS_AMT)) / (DOUBLE(((DOUBLE(ALL.URIAGE))/1000000))))+0.005, 16, 2) END) AS GAS_AMT_URIAGEHI
,      (CASE WHEN (ALL.ZENNEN_GAS_AMT = 0 OR ALL.ZENNEN_GAS_AMT IS NULL OR ALL.ZENNEN_URIAGE =0 OR ALL.ZENNEN_URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.ZENNEN_GAS_AMT)) / (DOUBLE(((DOUBLE(ALL.ZENNEN_URIAGE))/1000000))))+0.005, 16, 2) END) AS GAS_AMT_URIAGEHI_ZENNEN 
,      (CASE WHEN (ALL.WATER_AMT = 0 OR ALL.URIAGE =0 OR ALL.URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.WATER_AMT)) / (DOUBLE(((DOUBLE(ALL.URIAGE))/1000000))))+0.005, 16, 2) END) AS WATER_AMT_URIAGEHI
,      (CASE WHEN (ALL.ZENNEN_WATER_AMT = 0 OR ALL.ZENNEN_WATER_AMT IS NULL OR ALL.ZENNEN_URIAGE =0 OR ALL.ZENNEN_URIAGE IS NULL) THEN 0 ELSE DECIMAL(((DOUBLE(ALL.ZENNEN_WATER_AMT)) / (DOUBLE(((DOUBLE(ALL.ZENNEN_URIAGE))/1000000))))+0.005, 16, 2) END) AS WATER_AMT_URIAGEHI_ZENNEN 
FROM   (SELECT BD08.METER_YM          AS METER_YM          
        ,      SUM(BD08.ELECTRIC_AMT)      AS ELECTRIC_AMT      
        ,      SUM(BD08.POWER_AMT)         AS POWER_AMT         
        ,      SUM(BD08.GAS_AMT)           AS GAS_AMT           
        ,      SUM(BD08.WATER_AMT)         AS WATER_AMT         
        ,      SUM(BT64.URIAGE_DOGETU)     AS URIAGE            
        ,      SUM(BT64.EIGYO_DAYS_DOGETU) AS EIGYO_DAYS        
        ,      SUM(BT64.URIAGE_ZEN_DOGETU)     AS ZENNEN_URIAGE     
        ,      SUM(BT64.EIGYO_DAYS_ZEN_DOGETU) AS ZENNEN_EIGYO_DAYS 
        ,      SUM(ZENNEN_BD08.ELECTRIC_AMT) AS ZENNEN_ELECTRIC_AMT 
        ,      SUM(ZENNEN_BD08.POWER_AMT)    AS ZENNEN_POWER_AMT    
        ,      SUM(ZENNEN_BD08.GAS_AMT)      AS ZENNEN_GAS_AMT      
        ,      SUM(ZENNEN_BD08.WATER_AMT)    AS ZENNEN_WATER_AMT    
        FROM   BD08ENGY BD08           
               LEFT JOIN BT64ZGEP BT64 
                  ON (BD08.COMPANY_CD = BT64.COMPANY_CD AND BD08.METER_YM = BT64.EIGYO_DT AND BD08.MISE_CD = BT64.MISE_CD)  
               LEFT JOIN (SELECT * FROM   BD08ENGY BD08 
                          WHERE  METER_YM BETWEEN /*zennenFrom*/'200704' AND /*zennenTo*/'200803'  
                            AND  METER_KBN = /*meterKbn*/'0'  
               ) ZENNEN_BD08   
                  ON (BD08.COMPANY_CD = ZENNEN_BD08.COMPANY_CD AND RIGHT(BD08.METER_YM, 2) = RIGHT(ZENNEN_BD08.METER_YM, 2) AND BD08.MISE_CD=ZENNEN_BD08.MISE_CD)  
              ,BM01TENM BM01
        WHERE  BM01.COMPANY_CD   = BD08.COMPANY_CD  
        AND    BM01.MISE_CD   = BD08.MISE_CD  
        AND    BD08.METER_YM BETWEEN /*kikanFrom*/'200804' AND /*kikanTo*/'200903'
        AND    BD08.METER_KBN = /*meterKbn*/'0'  
/*IF userTypeCd == "01" */
    /*IF sibuCd != null && !sibuCd.equals("ALL")*/
        AND    BM01.SIBU_CD      = /*sibuCd*/'031'   
    /*END*/
    /*IF sibuCd.equals("ALL") && limitFlg == true */
		AND    BM01.SIBU_CD IN (
		         SELECT   BM51.SIBU_CD
		         FROM     BM51SVSB BM51
		         WHERE  BM51.COMPANY_CD = /*companyCd*/'00'
		         AND    BM51.SV_CD      = /*userId*/'99990001'
		         GROUP BY BM51.SIBU_CD
				)                    
    /*END*/
/*END*/
    /*IF userTypeCd == "02" */
        and  bm01.mise_cd in (
             select mise_cd 
             from bm01tenm 
             where company_cd = /*companyCd*/'00' 
             and   oner_cd in (select oner_cd from bm06uonr 
                               where  USER_ID = /*userId*/'99990002'   
                               AND   COMPANY_CD = bm01tenm.company_cd)
             )
    /*END*/
    /*IF userTypeCd == "03" */
             and  bm01.mise_cd in (
                       select mise_cd 
                       from bm07uten 
                       where USER_ID = /*userId*/'99990003' and COMPANY_CD = /*companyCd*/'00'
             )
    /*END*/
        GROUP BY ROLLUP (BD08.METER_YM)
)ALL 
order by ALL.METER_YM