select
    BM01.MISE_CD,
    CASE WHEN CLOSE_DT   > /*sysDate*/'20060823'  THEN MISE_NAME_KJ  
 	ELSE (RTRIM (CHAR (REPLACE (MISE_NAME_KJ,'',''), 40 ) ) CONCAT '(CLOSE)') END AS MISE_NAME_KJ,
 	BM11.ONER_NAME_KJ
from
    BM01TENM as BM01,
    BM11ONER as BM11
where
    BM01.COMPANY_CD = '00' and
    BM01.ONER_CD = /*onerCd*/'36711' and
    BM01.COMPANY_CD = BM11.COMPANY_CD and 
    BM01.ONER_CD = BM11.ONER_CD
order by
    BM01.MISE_CD
