select
	BS03.URIKAKE_YM,
	sum(BS03.SHO_AMOUNT) SHO_AMOUNT,
	SUB.NISU_NAME,
	BS03.NOHIN_TANKA,
	sum(BS03.URI_KIN) URI_KIN
from
    BS03USSR as BS03 left join 
		(SELECT NISU_NAME
		     , S.SHO_NISUGATA AS SHO_NISUGATA
	         , S.SHO_CD_JITU AS SHO_CD_JITU
	         , S.UNIT_KBN
	 	 FROM TM21SHOK S
	     	left join TC03NISU N on (S.SHO_NISUGATA = N.SHO_NISUGATA)
	     ) SUB on BS03.SHO_CD_JITU = SUB.SHO_CD_JITU and BS03.NOHIN_UNIT = SUB.UNIT_KBN
where
    BS03.COMPANY_CD = '00' and 
    BS03.MISE_CD = /*miseCd*/'01962' and
    BS03.SHO_CD_JITU = /*shoJituCd*/'05751' and
    BS03.URIKAKE_YM between /*condYMStr*/'200506' and /*condYMEnd*/'200608'
group by
	BS03.URIKAKE_YM, SUB.NISU_NAME, BS03.NOHIN_TANKA
order by
	BS03.URIKAKE_YM
