SELECT
     BC18_SRC.MISE_LEASE_SHU   AS MISE_LEASE_SHU
    ,BC18_SRC.MISE_LEASE_NAME  AS MISE_LEASE_NAME
    ,(CASE WHEN BC18_MAX.MAX_LEASE_SHU_COUNT IS NULL THEN 1 ELSE BC18_MAX.MAX_LEASE_SHU_COUNT END) AS MAX_LEASE_SHU_COUNT
FROM
    BC18CHIT BC18_SRC
LEFT JOIN
  (
    SELECT
      BC18_COUNT.MISE_LEASE_SHU  AS MISE_LEASE_SHU
      ,MAX(LEASE_SHU_COUNT)      AS MAX_LEASE_SHU_COUNT
    FROM
      (
        SELECT
           MM24.MISE_M_DATE        AS MISE_M_DATE
          ,MM24.MISE_LEASE_SHU     AS MISE_LEASE_SHU
          ,COUNT(MM24.MISE_LEASE_SHU)   AS LEASE_SHU_COUNT
        FROM
           MM24CHIT MM24
           ,BM74MMRI BM74
           ,BC18CHIT BC18
        WHERE
          BM74.COMPANY_CD='00'
          AND BM74.MISE_CD = /*miseCd*/'00000'
          AND MM24.COMPANY_CD = BM74.COMPANY_CD
          AND MM24.MISE_CD = BM74.MISE_CD
          AND MM24.MISE_M_DATE = BM74.MISE_M_DATE
          AND MM24.COMPANY_CD = BC18.COMPANY_CD
          AND MM24.MISE_LEASE_SHU = BC18.MISE_LEASE_SHU
        GROUP BY
           MM24.MISE_M_DATE
          ,MM24.MISE_LEASE_SHU
      ) BC18_COUNT
    GROUP BY
      BC18_COUNT.MISE_LEASE_SHU
  )  BC18_MAX ON (BC18_SRC.MISE_LEASE_SHU = BC18_MAX.MISE_LEASE_SHU)
WHERE
    BC18_SRC.COMPANY_CD='00'
 ORDER BY BC18_SRC.MISE_LEASE_SHU ASC