SELECT BM31.BNR_L 
,      BM31.BNR_L_NAME 
,      BM31.BNR_M 
,      BM31.BNR_M_NAME 
,      BM31.KOUMOKU_NO 
,      BM31.KOUMOKU_SUB  
,      BM31.KOUMOKU_NAME 
,      BM31.LIMIT_U AS LIMITMAX 
,      BM31.LIMIT_U AS LIMIT_U_100 
,      TENPO_DATA.ZEN_AVG  AS ZEN_AVG_100
,      TENPO_DATA.SIBU_AVG AS SIBU_AVG_100
,      0 AS SV_SIBU_AVG_100 
,      TENPO_DATA.COMPANY_CD 
,      TENPO_DATA.ONER_CD 
,      TENPO_DATA.ONER_NAME 
,      TENPO_DATA.TENPO_POINT_DATA AS TOKUTEN_100 

FROM BM31MSPM BM31 
LEFT JOIN ( 
	SELECT BS04.NENDO     
	,      BS04.KAI     
	,      BS04.COMPANY_CD     
	,      BS04.ONER_CD     
	,      BM11.ONER_NAME_KJ AS ONER_NAME 
	,      BS04.KOUMOKU_NO     
	,      BS04.KOUMOKU_SUB     
	,      BS04.BNR_L     
	,      BS04.BNR_M     
	,      BS04.ZEN_AVG    
	,      DECIMAL(AVG(BS04.SIBU_AVG), 5,2) AS SIBU_AVG 
	,      DECIMAL(AVG(BS04.ONER_SIBU_AVG), 5,2) AS TENPO_POINT_DATA 
	FROM BS04MSPS BS04     
	,    BM11ONER BM11
	,    BM01TENM BM01
	WHERE BS04.NENDO = /*nendo*/''     
	AND   BS04.KAI = /*kai*/''     
	AND   BS04.COMPANY_CD = /*companyCd*/'' 
	AND   BM01.SIBU_CD in /*sibuCd*/('')  
	AND   BS04.HYOUKA_KBN = '1'    
	AND   BS04.BNR_L <> '99'     
    AND   BM01.COMPANY_CD = BS04.COMPANY_CD
    AND   BM11.COMPANY_CD = BS04.COMPANY_CD
	AND   BM11.ONER_CD = BS04.ONER_CD     
	AND   BS04.MISE_CD = BM01.MISE_CD  

	GROUP BY BS04.NENDO     
	,        BS04.KAI     
	,        BS04.COMPANY_CD     
	,        BS04.ONER_CD     
	,        BM11.ONER_NAME_KJ 
	,        BS04.KOUMOKU_NO     
	,        BS04.KOUMOKU_SUB     
	,        BS04.BNR_L     
	,        BS04.BNR_M     
	,        BS04.ZEN_AVG    
) TENPO_DATA
ON (    TENPO_DATA.NENDO = BM31.NENDO
    AND TENPO_DATA.KAI = BM31.KAI
    AND TENPO_DATA.BNR_L = BM31.BNR_L
    AND TENPO_DATA.BNR_M =BM31.BNR_M
    AND TENPO_DATA.KOUMOKU_NO = BM31.KOUMOKU_NO
    AND TENPO_DATA.KOUMOKU_SUB = BM31.KOUMOKU_SUB
)
WHERE BM31.NENDO = /*nendo*/'' 
AND   BM31.KAI = /*kai*/'' 
AND   BM31.COMPANY_CD = /*companyCd*/'' 
AND   BM31.HYOUKA_KBN = '1' 
AND   BM31.BNR_L <> '99' 
ORDER BY BM31.BNR_L 
,        BM31.BNR_L_NAME 
,        BM31.BNR_M 
,        BM31.BNR_M_NAME 
,        BM31.KOUMOKU_NO 
,        BM31.KOUMOKU_SUB  
,        TENPO_DATA.ONER_CD 
