SELECT
     JIGYOU_CD              AS  JIGYOU_CD,
     JIGYOU_NAME            AS  JIGYOU_NAME,
     SLAREA_CD              AS  SLAREA_CD,
     SLAREA_NAME            AS  SLAREA_NAME,
     SIBU_CD                AS  SIBU_CD,
     SIBU_NAME              AS  SIBU_NAME,
     AREA_DAI               AS  AREA_DAI,
     AREA_NAME              AS  AREA_NAME,
     MISE_CD                AS  MISE_CD,
     MISE_NAME_KJ           AS  MISE_NAME_KJ,
     ONER_CD                AS  ONER_CD,
     ONER_NAME_KJ           AS  ONER_NAME_KJ,
     SUM(OTHER_KIN_7)       AS  OTHER_KIN_7,
     SUM(OTHER_KIN_8)       AS  OTHER_KIN_8,
     SUM(EAT_KIN)           AS  EAT_KIN,
     SUM(TAKE_KIN)          AS  TAKE_KIN,
     SUM(TEL_KIN)           AS  TEL_KIN,
     SUM(DRIVE_KIN)         AS  DRIVE_KIN,
     SUM(OTHER_KIN_1)       AS  OTHER_KIN_1,
     SUM(OTHER_KIN_2)       AS  OTHER_KIN_2,
     SUM(OTHER_KEN_7)       AS  OTHER_KEN_7,
     SUM(OTHER_KEN_8)       AS  OTHER_KEN_8,
     SUM(EAT_KEN)           AS  EAT_KEN,
     SUM(TAKE_KEN)          AS  TAKE_KEN,
     SUM(TEL_KEN)           AS  TEL_KEN,
     SUM(DRIVE_KEN)         AS  DRIVE_KEN,
     SUM(OTHER_KEN_1)       AS  OTHER_KEN_1,
     SUM(OTHER_KEN_2)       AS  OTHER_KEN_2,
     SUM(ZEN_OTHER_KIN_7)   AS  ZEN_OTHER_KIN_7,
     SUM(ZEN_OTHER_KIN_8)   AS  ZEN_OTHER_KIN_8,
     SUM(ZEN_EAT_KIN)       AS  ZEN_EAT_KIN,
     SUM(ZEN_TAKE_KIN)      AS  ZEN_TAKE_KIN,
     SUM(ZEN_TEL_KIN)       AS  ZEN_TEL_KIN,
     SUM(ZEN_DRIVE_KIN)     AS  ZEN_DRIVE_KIN,
     SUM(ZEN_OTHER_KIN_1)   AS  ZEN_OTHER_KIN_1,
     SUM(ZEN_OTHER_KIN_2)   AS  ZEN_OTHER_KIN_2,
     SUM(ZEN_OTHER_KEN_7)   AS  ZEN_OTHER_KEN_7,
     SUM(ZEN_OTHER_KEN_8)   AS  ZEN_OTHER_KEN_8,
     SUM(ZEN_EAT_KEN)       AS  ZEN_EAT_KEN,
     SUM(ZEN_TAKE_KEN)      AS  ZEN_TAKE_KEN,
     SUM(ZEN_TEL_KEN)       AS  ZEN_TEL_KEN,
     SUM(ZEN_DRIVE_KEN)     AS  ZEN_DRIVE_KEN,
     SUM(ZEN_OTHER_KEN_1)   AS  ZEN_OTHER_KEN_1,
     SUM(ZEN_OTHER_KEN_2)   AS  ZEN_OTHER_KEN_2
FROM
     (SELECT
           A1.EIGYO_DT,
           BM01TENM.COMPANY_CD,
           BM10GSIB.JIGYOU_CD,
           BM10GSIB.JIGYOU_NAME,
           BM10GSIB.SLAREA_CD,
           BM10GSIB.SLAREA_NAME,
           BM01TENM.SIBU_CD,
           BM10GSIB.SIBU_NAME,
           BM01TENM.AREA_DAI,
           BM10GSIB_AREA.SIBU_NAME AS AREA_NAME,
           A1.MISE_CD,
           BM01TENM.MISE_NAME_KJ,
           BM01TENM.ONER_CD,
           BM11ONER.ONER_NAME_KJ,
           BT63SNIP.OTHER_KIN_7,
           BT63SNIP.OTHER_KIN_8,
           BT63SNIP.EAT_KIN,
           BT63SNIP.TAKE_KIN,
           BT63SNIP.TEL_KIN,
           BT63SNIP.DRIVE_KIN,
           BT63SNIP.OTHER_KIN_1,
           BT63SNIP.OTHER_KIN_2,
           BT63SNIP.OTHER_KEN_7,
           BT63SNIP.OTHER_KEN_8,
           BT63SNIP.EAT_KEN,
           BT63SNIP.TAKE_KEN,
           BT63SNIP.TEL_KEN,
           BT63SNIP.DRIVE_KEN,
           BT63SNIP.OTHER_KEN_1,
           BT63SNIP.OTHER_KEN_2,
           0 AS ZEN_OTHER_KIN_7,
           0 AS ZEN_OTHER_KIN_8,
           0 AS ZEN_EAT_KIN,
           0 AS ZEN_TAKE_KIN,
           0 AS ZEN_TEL_KIN,
           0 AS ZEN_DRIVE_KIN,
           0 AS ZEN_OTHER_KIN_1,
           0 AS ZEN_OTHER_KIN_2,
           0 AS ZEN_OTHER_KEN_7,
           0 AS ZEN_OTHER_KEN_8,
           0 AS ZEN_EAT_KEN,
           0 AS ZEN_TAKE_KEN,
           0 AS ZEN_TEL_KEN,
           0 AS ZEN_DRIVE_KEN,
           0 AS ZEN_OTHER_KEN_1,
           0 AS ZEN_OTHER_KEN_2
         FROM
            BM11ONER
            INNER JOIN BM01TENM ON (BM01TENM.COMPANY_CD=BM11ONER.COMPANY_CD AND BM01TENM.ONER_CD=BM11ONER.ONER_CD)
            INNER JOIN BM10GSIB ON (BM01TENM.COMPANY_CD=BM10GSIB.COMPANY_CD AND BM01TENM.SIBU_CD=BM10GSIB.SIBU_CD)
            INNER JOIN BM10GSIB AS BM10GSIB_AREA ON (BM01TENM.COMPANY_CD=BM10GSIB_AREA.COMPANY_CD AND BM01TENM.AREA_DAI=BM10GSIB_AREA.SIBU_CD)
            ,BT63SNIP
            LEFT OUTER JOIN BM45ZDAY A1 ON (A1.EIGYO_DT = BT63SNIP.EIGYO_DT AND A1.COMPANY_CD = BT63SNIP.COMPANY_CD AND  A1.MISE_CD = BT63SNIP.MISE_CD )
         WHERE
            BM01TENM.COMPANY_CD = '00'
            AND  A1.COMPANY_CD = BM01TENM.COMPANY_CD AND A1.MISE_CD=BM01TENM.MISE_CD
            AND (A1.COMPANY_CD,A1.MISE_CD) NOT IN (SELECT COMPANY_CD,MISE_CD FROM BM82NOJT)
            AND A1.EIGYO_DT  BETWEEN /*staDate*/'20170907' AND  /*endDate*/'20180906'
            AND A1.OLDM_FLG='0' AND ( A1.OPEN_KBN=1 OR A1.OP_KBN_ZEN_DOGETU=1)
    UNION ALL
    SELECT
           A2.EIGYO_DT,
           BM01TENM.COMPANY_CD,
           BM10GSIB.JIGYOU_CD,
           BM10GSIB.JIGYOU_NAME,
           BM10GSIB.SLAREA_CD,
           BM10GSIB.SLAREA_NAME,
           BM01TENM.SIBU_CD,
           BM10GSIB.SIBU_NAME,
           BM01TENM.AREA_DAI,
           BM10GSIB_AREA.SIBU_NAME AS AREA_NAME,
           A2.MISE_CD,
           BM01TENM.MISE_NAME_KJ,
           BM01TENM.ONER_CD,
           BM11ONER.ONER_NAME_KJ,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           0,
           BT63SNIP.OTHER_KIN_7,
           BT63SNIP.OTHER_KIN_8,
           BT63SNIP.EAT_KIN,
           BT63SNIP.TAKE_KIN,
           BT63SNIP.TEL_KIN,
           BT63SNIP.DRIVE_KIN,
           BT63SNIP.OTHER_KIN_1,
           BT63SNIP.OTHER_KIN_2,
           BT63SNIP.OTHER_KEN_7,
           BT63SNIP.OTHER_KEN_8,
           BT63SNIP.EAT_KEN,
           BT63SNIP.TAKE_KEN,
           BT63SNIP.TEL_KEN,
           BT63SNIP.DRIVE_KEN,
           BT63SNIP.OTHER_KEN_1,
           BT63SNIP.OTHER_KEN_2
         FROM
            BM11ONER
            INNER JOIN BM01TENM ON (BM01TENM.COMPANY_CD=BM11ONER.COMPANY_CD AND BM01TENM.ONER_CD=BM11ONER.ONER_CD)
            INNER JOIN BM10GSIB ON (BM01TENM.COMPANY_CD=BM10GSIB.COMPANY_CD AND BM01TENM.SIBU_CD=BM10GSIB.SIBU_CD)
            INNER JOIN BM10GSIB AS BM10GSIB_AREA ON (BM01TENM.COMPANY_CD=BM10GSIB.COMPANY_CD AND BM01TENM.AREA_DAI=BM10GSIB_AREA.SIBU_CD)
            ,BT63SNIP
            LEFT OUTER JOIN BM45ZDAY A2 ON (A2.ZEN_DOGETU_DT = BT63SNIP.EIGYO_DT AND A2.COMPANY_CD = BT63SNIP.COMPANY_CD AND A2.ZEN_DOGETU_MISE = BT63SNIP.MISE_CD )
         WHERE
            BM01TENM.COMPANY_CD = '00'
            AND  A2.COMPANY_CD = BM01TENM.COMPANY_CD AND A2.MISE_CD=BM01TENM.MISE_CD
            AND (A2.COMPANY_CD,A2.MISE_CD) NOT IN (SELECT COMPANY_CD,MISE_CD FROM BM82NOJT)
            AND A2.EIGYO_DT  BETWEEN /*staDate*/'20170907' AND /*endDate*/'20180906'
            AND A2.OLDM_FLG='0' AND ( A2.OPEN_KBN=1 OR A2.OP_KBN_ZEN_DOGETU=1)
    )
GROUP BY
     JIGYOU_CD,
     JIGYOU_NAME,
     SLAREA_CD,
     SLAREA_NAME,
     SIBU_CD,
     SIBU_NAME,
     AREA_DAI,
     AREA_NAME,
     MISE_CD,
     MISE_NAME_KJ,
     ONER_CD,
     ONER_NAME_KJ
ORDER BY
/*IF orderByCd.equals("data")*/
    JIGYOU_CD,
    SLAREA_CD,
    SIBU_CD,
    AREA_DAI,
    MISE_CD
/*END*/
/*IF orderByCd.equals("data_area_dai")*/
    AREA_DAI,
    MISE_CD
/*END*/
