SELECT
	NENDO,
	RTRIM(USER_ID) AS USER_ID,
	POINT,
	POINT_SHU,
	RTRIM(POINT_SHU_NAME) AS POINT_SHU_NAME,
	KB_COMPANY_CD,
	RTRIM(BIKOU) AS BIKOU,
	FIRST_USER,
	FIRST_PGM,
	FIRST_TMSP,
	LAST_USER,
	LAST_PGM,
	LAST_TMSP

FROM
    BD60YPRI

WHERE NENDO = /*nendo*/'2017'
	AND USER_ID = /*userId*/'00000020'
	AND POINT_SHU_NAME = /*pointShuName*/''