SELECT
	RTRIM(BD60.USER_ID) AS USER_ID,
	COALESCE(SUM(BD60.POINT),0) AS POINT,
    MAXINFO.KB_COMPANY_CD
FROM
    BD60YPRI BD60
   LEFT OUTER JOIN (
        SELECT
            BD60.USER_ID,
            BD60.KB_COMPANY_CD
        FROM
            BD60YPRI BD60
        INNER JOIN (
        SELECT
            USER_ID,
            MAX(NENDO) AS NENDO
        FROM BD60YPRI
        GROUP BY
        	USER_ID) BD60MAXN
        ON (BD60.USER_ID = BD60MAXN.USER_ID
            AND BD60.NENDO = BD60MAXN.NENDO
        )
    ) MAXINFO
    ON (BD60.USER_ID = MAXINFO.USER_ID)

WHERE BD60.NENDO >= /*minNendo*/'2016'
    AND BD60.NENDO <= /*maxNendo*/'2019'

GROUP BY
		BD60.USER_ID,
		MAXINFO.KB_COMPANY_CD