SELECT
	NENDO,
	RTRIM(USER_ID) AS USER_ID,
	POINT_RUIKEI,
	KB_COMPANY_CD,
	NYUSYA_DT,
	TAISHOKU_DT,
	KINZOKU_YEAR,
	RETIRE_CD,
	SIKYU_RATE,
	T_SEISAN_POINT,
	RTRIM(BIKOU) AS BIKOU,
	FIRST_USER,
	FIRST_PGM,
	FIRST_TMSP,
	LAST_USER,
	LAST_PGM,
	LAST_TMSP

FROM
    BD61TSES BD61
WHERE USER_ID = /*userId*/'00000020'

/*IF nendo != null*/
	AND NENDO = /*nendo*/'2017'
/*END*/

/*IF nyusyaDt != null*/
	AND NYUSYA_DT = /*nyusyaDt*/'20170223'
/*END*/