SELECT
	NENDO,
	RTRIM(USER_ID) AS USER_ID,
	POINT,
	POINT_SHU,
	KB_COMPANY_CD,
	RANK_CD,
	RTRIM(KAIGAI_FLG) AS KAIGAI_FLG,
	RTRIM(BIKOU) AS BIKOU,
	FIRST_USER,
	FIRST_PGM,
	FIRST_TMSP,
	LAST_USER,
	LAST_PGM,
	LAST_TMSP

FROM
    BD59HPRI BD59

WHERE NENDO = /*nendo*/'2017'
	AND USER_ID = /*userId*/'00000020'
	AND POINT_SHU = /*pointShu*/'1'