SELECT
	DISTINCT(BD59.USER_ID) AS USER_ID,
	COALESCE(SUMPOINT.POINT,0) AS POINT,
    COALESCE(BD59KG.KAIGAI_FLG,'') as KAIGAI_FLG,
    COALESCE(MAXINFO.KB_COMPANY_CD,'') as KB_COMPANY_CD,
    COALESCE(MAXINFO.RANK_CD,'') as RANK_CD
FROM
    BD59HPRI BD59
    LEFT OUTER JOIN (
         SELECT
            BD59.USER_ID,
            BD59.KAIGAI_FLG
        FROM
        (SELECT
            USER_ID,
            MAX(NENDO || POINT_SHU) AS NENDO1
            FROM BD59HPRI
            GROUP BY USER_ID
        ) B59MAXN
        inner JOIN BD59HPRI BD59
        ON (BD59.USER_ID = B59MAXN.USER_ID
            AND BD59.NENDO = LEFT(B59MAXN.NENDO1,4)
            AND BD59.POINT_SHU = RIGHT(B59MAXN.NENDO1,1)
            AND BD59.KAIGAI_FLG = '1')
    ) BD59KG
    ON (BD59.USER_ID = BD59KG.USER_ID)
   LEFT OUTER JOIN (
        SELECT
            DISTINCT(BD59.USER_ID),
            BD59.KB_COMPANY_CD,
            BD59.RANK_CD
        FROM
        (SELECT
            USER_ID,
            MAX(NENDO || POINT_SHU) AS NENDO1
            FROM BD59HPRI
            GROUP BY USER_ID
        ) B59MAXN
        inner JOIN BD59HPRI BD59
        ON (BD59.USER_ID = B59MAXN.USER_ID
            AND BD59.NENDO = LEFT(B59MAXN.NENDO1,4)
            AND BD59.POINT_SHU = RIGHT(B59MAXN.NENDO1,1))
    ) MAXINFO
    ON (BD59.USER_ID = MAXINFO.USER_ID)
    LEFT JOIN (
    	SELECT SUM(POINT) AS POINT,USER_ID
    	FROM BD59HPRI
    	WHERE NENDO >= /*minNendo*/'2017'
    	AND NENDO <= /*maxNendo*/'2019'
    	AND POINT_SHU <> '2'
    	GROUP BY USER_ID
    ) SUMPOINT
    ON (BD59.USER_ID = SUMPOINT.USER_ID)

LEFT JOIN BD61TSES BD61 ON BD61.USER_ID = BD59.USER_ID
WHERE BD61.USER_ID IS NULL
