SELECT 
	ENTRY_CD,
	ENTRY_YEAR,
	ENTRY_KAI,
	rtrim(ENTRY_TITLE) as ENTRY_TITLE,
	rtrim(ENTRY_PLACE) as ENTRY_PLACE,
	NUMBER_LIMIT,
	PLACE_LIMIT,
	rtrim(NOTE) as NOTE,
	SPARE_FLG1,
	SPARE_FLG2,
	rtrim(SAKUJO_FLG) as SAKUJO_FLG,
	SAKUJO_FLG,
	FIRST_USER,
	FIRST_PGM,
	FIRST_TMSP,
	LAST_USER,
	LAST_PGM,
	LAST_TMSP
FROM
	BR17ENTL
WHERE 
    CONCAT(ENTRY_CD, CONCAT(ENTRY_YEAR, ENTRY_KAI)) IN /*joinCharacterList*/('052006001', '052006002')
ORDER BY ENTRY_CD, ENTRY_YEAR, ENTRY_KAI