SELECT 
	BR18ENTD.ENTRY_CD,
	BR18ENTD.ENTRY_YEAR,
	BR18ENTD.ENTRY_KAI,
	BR18ENTD.USERTYPE_CD,
	BR18ENTD.DAY_KBN,
	BR18ENTD.FROM_DT,
	BR18ENTD.TO_DT,
	BR18ENTD.FIRST_USER,
	BR18ENTD.FIRST_PGM,
	BR18ENTD.FIRST_TMSP,
	BR18ENTD.LAST_USER,
	BR18ENTD.LAST_PGM,
	BR18ENTD.LAST_TMSP
FROM
    BR18ENTD
WHERE
    CONCAT(ENTRY_CD, CONCAT(ENTRY_YEAR, ENTRY_KAI)) IN /*joinCharacterList*/('052006001')
AND (DAY_KBN = '01' 
    OR DAY_KBN = '03'
    OR DAY_KBN = '04'
    OR DAY_KBN = '06')
ORDER BY 
    ENTRY_CD,
    ENTRY_YEAR,
    ENTRY_KAI,
    USERTYPE_CD,
    DAY_KBN,
    FROM_DT,
    TO_DT
