SELECT  ENTRY_KAI,
        ENTRY_YEAR,
        ENTRY_CD,
        NOTICE1,
        NOTICE2,
        NOTICE3,
	    FIRST_USER,
    	FIRST_PGM,
    	FIRST_TMSP,
    	LAST_USER,
    	LAST_PGM,
    	LAST_TMSP
FROM BR51ENCI
WHERE 
    CONCAT(ENTRY_CD, CONCAT(ENTRY_YEAR, ENTRY_KAI)) IN /*joinCharacterList*/('052006001', '052006002')
ORDER BY ENTRY_CD, ENTRY_YEAR, ENTRY_KAI
