select
    BR03ROLE.ROLE_CD as ROLE_CD,
    BR03ROLE.ROLE_NAME as ROLE_NAME,
    BR03ROLE.BUNRUI_CD as BUNRUI_CD,
    BR03ROLE.DESCRIPTION as DESCRIPTION,
    BR03ROLE.SORT_SEQ as ROLE_SORT_SEQ,
    BC03RLBR.BUNRUI_NAME as BUNRUI_NAME,
    BC03RLBR.SORT_SEQ as BUNRUI_SORT_SEQ
from
    BR03ROLE inner join BC03RLBR on BR03ROLE.BUNRUI_CD = BC03RLBR.BUNRUI_CD
where
    BR03ROLE.BUNRUI_CD = /*bunruiCd*/'01'
order by
    BC03RLBR.SORT_SEQ,
    BR03ROLE.SORT_SEQ
