SELECT BM39.CKANRI_NO
,      RTRIM(BM39.TITLE) AS TITLE
,      BM39.TARGET_FROM
,      BM39.TARGET_TO
,      BM39.DEFAULT_FROM
,      BM39.DEFAULT_TO
,      BM39.YOBI_FROM
,      BM39.YOBI_TO
,      BM39.FIRST_USER
,      BM39.FIRST_PGM
,      BM39.FIRST_TMSP
,      BM39.LAST_USER
,      BM39.LAST_PGM
,      BM39.LAST_TMSP
FROM BM39CPRD BM39
WHERE BM39.CKANRI_NO = /*ckanriNo*/''

