SELECT SUBSTR(BD14.EIGYO_DT, 1,6) EIGYO_YM
,      SUM(CASE WHEN THREE_KBN='1' THEN 1 ELSE 0 END) AS WEEK_CNT
,      SUM(CASE WHEN THREE_KBN='2' THEN 1 ELSE 0 END) AS SAT_CNT
,      SUM(CASE WHEN THREE_KBN='3' THEN 1 ELSE 0 END) AS HOLI_CNT
FROM BD14ACAL BD14
WHERE SUBSTR(BD14.EIGYO_DT, 1,6) IN (/*targetYM*/'200903', /*targetLastYM*/'200803')
GROUP BY SUBSTR(BD14.EIGYO_DT, 1,6)
ORDER BY SUBSTR(BD14.EIGYO_DT, 1,6) DESC