SELECT BC02.R_COMPANY_CD AS COMPANY_CD
,      BC02.COMPANY_NAME
,      CASE WHEN BM03.ZOKUSEI_KBN = '1' THEN 0 ELSE 1 END AS SHOZOKU_FLG
,      BM03.ZOKUSEI_KBN
from BM03USCP BM03 
,    BC02COMP BC02   
WHERE BM03.USER_ID = /*userId*/'99990001'
AND   BC02.MISE_FLG = '1'
AND   BM03.R_COMPANY_CD = BC02.R_COMPANY_CD
ORDER BY SHOZOKU_FLG
,        COMPANY_CD
,        BM03.ZOKUSEI_KBN