INSERT INTO BR05ACTR 
SELECT BR05.ROLE_CD
,      '00' AS MENU_ID 
,      BR02.MENU_ID AS SUB_MENU_ID
,      MAX(ENABLE_FLG) AS ENABLE_FLG
,      MAX(EXTRA_FLG) AS EXTRA_FLG
,      BR01.USER_ID AS FIRST_USER
,      'BSA007L' AS FIRST_PGM
,      current timestamp AS FIRST_TMSP
,      BR01.USER_ID AS LAST_USER
,      'BSA007L' AS LAST_PGM
,      current timestamp AS LAST_TMSP
FROM        BR02BMNU BR02
,           BR05ACTR BR05
,           (SELECT USER_ID FROM BR01USER 
             WHERE USER_ID = /*userId*/'99990001') BR01
WHERE BR02.MENU_ID != '00' 
AND   BR02.MENU_ID     = BR05.MENU_ID
AND   BR02.SUB_MENU_ID = BR05.SUB_MENU_ID
GROUP BY BR02.MENU_ID
,        BR02.MENU_NAME
,        BR05.ROLE_CD
,        BR01.USER_ID