UPDATE BT21ENOJ SET
  	NAME = /*uiOfferDutyPersonInfo.name*/''
  , TEL = /*uiOfferDutyPersonInfo.tel*/''
  , ZIP = /*uiOfferDutyPersonInfo.zip*/''
  , ADDRESS1 = /*uiOfferDutyPersonInfo.address1*/''
  , ADDRESS2 = /*uiOfferDutyPersonInfo.address2*/''
  , ADDRESS3 = /*uiOfferDutyPersonInfo.address3*/''
  , SOUFU_NAME = /*uiOfferDutyPersonInfo.soufuName*/''
  , JOB_TYPE = /*uiOfferDutyPersonInfo.jobType*/''
  , LAST_USER = /*uiOfferDutyPersonInfo.lastUser*/''
  , LAST_PGM = /*uiOfferDutyPersonInfo.lastPgm*/''
WHERE	ENTRY_CD = /*uiOfferDutyPersonInfo.entryCd*/''
  AND ENTRY_YEAR = /*uiOfferDutyPersonInfo.entryYear*/''
  AND ENTRY_KAI = /*uiOfferDutyPersonInfo.entryKai*/''
  AND COMPANY_CD = /*uiOfferDutyPersonInfo.companyCd*/''
  AND ONER_CD = /*uiOfferDutyPersonInfo.onerCd*/''
  AND ATESAKI_KBN = /*uiOfferDutyPersonInfo.atesakiKbn*/''
