select 
	LTRIM(RTRIM(ONER_NAME_KJ)) as ONER_NAME_KJ,
	LTRIM(RTRIM(ONER_TEL)) as ONER_TEL,
	LTRIM(RTRIM(SEIKYU_POST_NO)) as SEIKYU_POST_NO,
	LTRIM(RTRIM(SEIKYU_ADRS1)) as SEIKYU_ADRS1,
	LTRIM(RTRIM(SEIKYU_ADRS2)) as SEIKYU_ADRS2,
	LTRIM(RTRIM(SEIKYU_ADRS3)) as SEIKYU_ADRS3
from
	BM11ONER
where 
	COMPANY_CD = /*companyCd*/'00' AND
	ONER_CD = /*onerCd*/'36478'