select
	LTRIM(RTRIM(BT46.TAB_NO)) as TAB_NO,
	LTRIM(RTRIM(BT46.MISE_CD)) as MISE_CD,
	LTRIM(RTRIM(BT46.L_NAME_KJ)) as L_NAME_KJ,
	LTRIM(RTRIM(BT46.F_NAME_KJ)) as F_NAME_KJ,
	LTRIM(RTRIM(BT46.L_NAME_KNA)) as L_NAME_KNA,
	LTRIM(RTRIM(BT46.F_NAME_KNA)) as F_NAME_KNA,
	LTRIM(RTRIM(BT46.SEX)) as SEX,
	LTRIM(RTRIM(BT46.AGE)) as AGE,
	LTRIM(RTRIM(BT46.JIGYO_FLG)) as JIGYO_FLG,
	LTRIM(RTRIM(BT46.KONSHIN_FLG)) as KONSHIN_FLG,
	LTRIM(RTRIM(BT46.KYOEI_FLG)) as KYOEI_FLG,
	LTRIM(RTRIM(BT46.SHUKUHAKU_FLG)) as SHUKUHAKU_FLG,
	LTRIM(RTRIM(BT46.NOTE)) as NOTE,
	LTRIM(RTRIM(BT46.ABSENCE_REASON)) as ABSENCE_REASON,
	LTRIM(RTRIM(BT46.FIRST_USER)) as FIRST_USER,
	LTRIM(RTRIM(BT46.FIRST_PGM)) as FIRST_PGM,
	BT46.FIRST_TMSP,
	LTRIM(RTRIM(BT46.LAST_USER)) as LAST_USER,
	LTRIM(RTRIM(BT46.LAST_PGM)) as LAST_PGM,
	BT46.LAST_TMSP
from
    BT46KENS as BT46
where 
	BT46.ENTRY_CD = /*entryCd*/'25' and
	BT46.ENTRY_YEAR = /*entryYear*/'2006' and 
	BT46.ENTRY_KAI = /*entryKai*/'999' and 	
	BT46.COMPANY_CD = /*companyCd*/'00' and
	BT46.ONER_CD = /*onerCd*/'36478'