select
	LTRIM(RTRIM(BM11.ONER_NAME_KJ)) as ONER_NAME_KJ,
	LTRIM(RTRIM(BT21.SOUFU_NAME)) as SOUFU_NAME ,	
	LTRIM(RTRIM(BT21.NAME)) as NAME,
	LTRIM(RTRIM(BT21.TEL)) as TEL,
	LTRIM(RTRIM(BT21.ZIP)) as ZIP,
	LTRIM(RTRIM(BT21.JOB_TYPE)) as JOB_TYPE,
	LTRIM(RTRIM(BT21.ADDRESS1)) as ADDRESS1,
	LTRIM(RTRIM(BT21.ADDRESS2)) as ADDRESS2,
	LTRIM(RTRIM(BT21.ADDRESS3)) as ADDRESS3
from
	BT21ENOJ as BT21,
    BM11ONER as BM11
where 
	BT21.ENTRY_CD = /*entryCd*/'25' and
	BT21.ENTRY_YEAR = /*entryYear*/'2006' and 
	BT21.ENTRY_KAI = /*entryKai*/'999' and 
	BT21.COMPANY_CD = /*companyCd*/'00' and
	BT21.ONER_CD = /*onerCd*/'36478' and
	BT21.ATESAKI_KBN = '00' and
	BT21.COMPANY_CD = BM11.COMPANY_CD and
	BT21.ONER_CD = BM11.ONER_CD