SELECT CAMP_ID
,      COMPANY_CD
,      RTRIM(CAMP_TITLE) AS CAMP_TITLE
,      CAMP_FROM
,      CAMP_TO
,      DISP_FROM
,      DISP_TO
,      YOBI_FROM
,      YOBI_TO
FROM BM60CPDT
WHERE CAMP_ID= /*campId*/'000008'
ORDER BY CAMP_FROM
,        CAMP_TO