SELECT 
count(distinct BM01TENM.MISE_CD) AS COUNT,
BM01TENM.MISE_CD AS MISE_CD, 
BM01TENM.MISE_NAME_KJ AS MISE_NAME_KJ,
BN01DTEN.KBN1 AS TENPO_SHUBETU,
BN01DTEN.KBN16 AS MOSG_KBN, 
BM44YDMS.YAGO_DETAIL_NAME AS YAGO_DTL_NAME, 
sum(BT60ZNIP.URIAGE) as URIAGE , 
sum(BT60ZNIP.ONER_YOSAN) as URI_YOSAN, 
sum(BT60ZNIP.EIGYO_DAYS) as EIGYO_DAYS ,
sum(BT60ZNIP.KYAKUSU) as KYAKUSU , 

/*IF dataShu.equals("DOGETU")*/

	/*IF taishoKikan.equals("DAY1")*/
		BT60ZNIP.TENKO_KBN AS TENKO_KBN,
		BT60ZNIP.TENKO_KBN_ZEN_DOGETU as TENKO_KBN_ZEN,
	/*END*/
	
		sum(BT60ZNIP.URIAGE_ZEN_DOGETU) as URIAGE_ZEN, 
		sum(BT60ZNIP.KYAKUSU_ZEN_DOGETU) as KYAKUSU_ZEN, 
		sum(BT60ZNIP.EIGYO_DAYS_ZEN_DOGETU) as EIGYO_DAYS_ZEN
	
-- ELSE
		/*IF dataShu.equals("DOYO")*/
			/*IF taishoKikan.equals("DAY1")*/
				BT60ZNIP.TENKO_KBN AS TENKO_KBN,
				BT60ZNIP.TENKO_KBN_ZEN_DOYO as TENKO_KBN_ZEN,
			/*END*/
			
				sum(BT60ZNIP.URIAGE_ZEN_DOYO) as URIAGE_ZEN, 
				sum(BT60ZNIP.KYAKUSU_ZEN_DOYO) as KYAKUSU_ZEN, 
				sum(BT60ZNIP.EIGYO_DAYS_ZEN_DOYO) as EIGYO_DAYS_ZEN

		-- ELSE
			/*IF taishoKikan.equals("DAY1")*/
				BT60ZNIP.TENKO_KBN AS TENKO_KBN,
				BT60ZNIP.TENKO_KBN_ZEN_DOJITU as TENKO_KBN_ZEN,
			/*END*/	
			
				sum(BT60ZNIP.URIAGE_ZEN_DOJITU) as URIAGE_ZEN, 
				sum(BT60ZNIP.KYAKUSU_ZEN_DOJITU) as KYAKUSU_ZEN, 
				sum(BT60ZNIP.EIGYO_DAYS_ZEN_DOJITU) as EIGYO_DAYS_ZEN

		/*END*/
/*END*/

from (BM01TENM 
JOIN BN01DTEN on (
 BM01TENM.COMPANY_CD = BN01DTEN.COMPANY_CD AND 
 BM01TENM.MISE_CD = BN01DTEN.MISE_CD
/*IF taishoKikan.equals("DAY1")*/
 	AND BN01DTEN.EIGYO_DT = /*kikanFrom*/ 
/*END*/
/*IF taishoKikan.equals("DAYS")*/
	AND (BN01DTEN.EIGYO_DT between /*kikanFrom*/ AND /*kikanTo*/) 
/*END*/
)
JOIN BM44YDMS on (
 BM44YDMS.YAGO_DETAIL_CD = BN01DTEN.KBN16  )  
JOIN BT60ZNIP on (
 BT60ZNIP.COMPANY_CD = BM01TENM.COMPANY_CD AND
 BT60ZNIP.EIGYO_DT = BN01DTEN.EIGYO_DT AND
 BT60ZNIP.MISE_CD = BN01DTEN.MISE_CD AND 
 BT60ZNIP.OLDM_FLG = '0') 
 )
WHERE
 	BM01TENM.COMPANY_CD = /*companyCd*/ 
 	AND BM01TENM.ONER_CD = /*onerCd*/
 	AND BT60ZNIP.OPEN_KBN = 1 
GROUP BY rollup(
(BN01DTEN.KBN16,BM44YDMS.YAGO_DETAIL_NAME), 
(BM01TENM.MISE_CD,
BM01TENM.MISE_NAME_KJ, 
BN01DTEN.KBN1
/*IF taishoKikan.equals("DAY1")*/
	/*IF dataShu.equals("DOGETU")*/
,BT60ZNIP.TENKO_KBN
,BT60ZNIP.TENKO_KBN_ZEN_DOGETU
		-- ELSE
			/*IF dataShu.equals("DOYO")*/
,BT60ZNIP.TENKO_KBN
,BT60ZNIP.TENKO_KBN_ZEN_DOYO
			-- ELSE
,BT60ZNIP.TENKO_KBN
,BT60ZNIP.TENKO_KBN_ZEN_DOJITU
			/*END*/
	/*END*/	
/*END*/

))
ORDER BY BM01TENM.MISE_CD , BN01DTEN.KBN16
