SELECT
BM44YDMS.YAGO_DETAIL_CD AS YAGO_DETAIL_CD, 
BM44YDMS.YAGO_DETAIL_NAME AS YAGO_DETAIL_NAME,
BM43YMST.YAGO_CD AS YAGO_CD, 
BM43YMST.YAGO_NAME AS YAGO_NAME  
from BM44YDMS JOIN BM43YMST on (BM43YMST.YAGO_CD = BM44YDMS.YAGO_CD) 
ORDER BY BM44YDMS.SORT_DETAIL