SELECT
    BM01TENM.COMPANY_CD,
    BM01TENM.MISE_CD,
    BM01TENM.MISE_NAME_KJ,
    BM01TENM.MISE_NAME_KNA,
    (CASE WHEN BM01TENM.CLOSE_DT <= BR33.CNT_DATE THEN BM01TENM.CLOSE_DT ELSE '' END) AS CLOSE_KJ
FROM
    BM01TENM 
LEFT JOIN BM11ONER BM11 
     ON (BM11.COMPANY_CD = BM01TENM.COMPANY_CD 
          AND BM11.ONER_CD = BM01TENM.ONER_CD)
,   (SELECT CNT_DATE FROM BR33CDAY WHERE DAY_KBN = '02') BR33
WHERE BM01TENM.MISE_CD IS NOT NULL    
/*IF IN_CLOSE == null */
AND BM01TENM.CLOSE_DT >= BR33.CNT_DATE
/*END*/
/*IF COMPANY_CD != null */AND BM01TENM.COMPANY_CD = /*COMPANY_CD*/'01'/*END*/
/*IF SIBU_CD != null */AND BM01TENM.SIBU_CD = /*SIBU_CD*/'001'/*END*/
/*IF ONER_NAME_KJ_0 != null */AND ONER_NAME_KJ like /*ONER_NAME_KJ_0*/'abc'/*END*/
/*IF ONER_CD_0 != null */AND BM11.ONER_CD = /*ONER_CD_0*/'00001'/*END*/
/*IF MISE_NAME_KJ != null */AND MISE_NAME_KJ like /*MISE_NAME_KJ*/'abc'/*END*/
/*IF MISE_CD != null */AND MISE_CD = /*MISE_CD*/'00001'/*END*/
AND (1 = 1
/*IF MISE_NAME_KNA0 != null */AND MISE_NAME_KNA like /*MISE_NAME_KNA0*/'abc'/*END*/
/*IF MISE_NAME_KNA1 != null */OR MISE_NAME_KNA like /*MISE_NAME_KNA1*/'abc'/*END*/
/*IF MISE_NAME_KNA2 != null */OR MISE_NAME_KNA like /*MISE_NAME_KNA2*/'abc'/*END*/
/*IF MISE_NAME_KNA3 != null */OR MISE_NAME_KNA like /*MISE_NAME_KNA3*/'abc'/*END*/
)

/*IF SORT_SEQ != null */
ORDER BY MISE_CD
/*END*/

/*IF SORT_SEQ == null */
ORDER BY Hex(MISE_NAME_KNA)
/*END*/
       