select 
SUB1.MENU_GROUP, SUB1.SUM_GROUP,  SUB1.MENU_CD,
SUB1.RESERVE_TIME, SUB1.RESERVE_TOTAL 
from (
	select 
	BM40.MENU_GROUP, BM41.SUM_GROUP, BT71.MENU_CD,
	(BT70.RESERVE_HH || BT70.RESERVE_MM) as RESERVE_TIME, 
	sum(BT71.RESERVE_AMT * BM41.CONV_VALUE) as RESERVE_TOTAL ,
	GROUPING (BM40.MENU_GROUP) AS  MENU_GROUPS ,
	GROUPING (BM41.SUM_GROUP) AS  SUM_GROUPS
	from 
	BT70CRSV BT70, 
	BT71CRSD BT71,
	BM40CMGP BM40,
	BM41CMNU BM41
	where 
	BT70.CKANRI_NO = /*ckanriNo*/'200601' and 
	BT70.CANCEL_FLG = '0' and
	BT70.COMPANY_CD = /*companyCd*/'00' and
	BT70.MISE_CD =  /*miseCd*/'01776' and
	BT70.RESERVE_DT =  /*reservDt*/'20060502' and
	BT70.CKANRI_NO = BT71.CKANRI_NO and 
	BT70.COMPANY_CD = BT71.COMPANY_CD and
	BT70.MISE_CD = BT71.MISE_CD and
	BT70.SEQ_NO = BT71.SEQ_NO and
	BT70.CKANRI_NO = BM40.CKANRI_NO and 
	BM40.CKANRI_NO = BM41.CKANRI_NO and 
	BM40.MENU_GROUP = BM41.MENU_GROUP and 
	BT71.MENU_CD = BM41.MENU_CD
	GROUP BY CUBE  (BM40.MENU_GROUP, BM41.SUM_GROUP, BT71.MENU_CD,(BT70.RESERVE_HH || BT70.RESERVE_MM))
	order by BM40.MENU_GROUP,BM41.SUM_GROUP,BT71.MENU_CD,(BT70.RESERVE_HH || BT70.RESERVE_MM)
	) SUB1
where 
(SUB1.MENU_GROUP is not null and  
 SUB1.SUM_GROUP is not null and 
 SUB1.MENU_CD is null and 
 SUB1.RESERVE_TIME is not null) or 
(SUB1.MENU_GROUP is not null and 
 SUB1.SUM_GROUP is null and 
 SUB1.MENU_CD is null  and 
 SUB1.RESERVE_TIME is not null) 



