SELECT
	ENTRY_CD,
	ENTRY_YEAR,
	ENTRY_KAI,
	STAFF_ID,
	COMPANY_CD,
	ONER_CD,
	EXAM_NO,
	ENTRY_PLACE_CD,
	rtrim(NOTE) as NOTE,
	ABILITY_CHK,
	EXAM_CHK,
	INTERVIEW_CHK,
	OTHER_CHK1,
	OTHER_CHK2,
	EMP_EXP_YEAR,
	EMP_EXP_MONTH,
	PA_EXP_YEAR,
	PA_EXP_MONTH,
	rtrim(JOB) as JOB,
	FIRST_USER,
	FIRST_PGM,
	FIRST_TMSP,
	LAST_USER,
	LAST_PGM,
	LAST_TMSP
FROM
    BT23MLEJ
WHERE
    ENTRY_CD = '10' AND
    ENTRY_YEAR = /*entryYear*/'2007' AND
    ENTRY_KAI = /*entryKai*/'001' AND
    STAFF_ID = /*staffId*/'98000239'