SELECT
    BM11ONER.COMPANY_CD,
    BM11ONER.ONER_CD,
    BM11ONER.ONER_NAME_KJ,
    BM11ONER.ONER_NAME_KNA,
    (CASE WHEN BM11ONER.KEIYAKU_END <= BR33.CNT_DATE THEN BM11ONER.KEIYAKU_END ELSE '' END) AS KEIYAKU_END
FROM
    BM11ONER 
    LEFT OUTER JOIN 
        BM01TENM
    ON 
        BM11ONER.COMPANY_CD = BM01TENM.COMPANY_CD 
    AND BM11ONER.ONER_CD = BM01TENM.ONER_CD
    
    LEFT OUTER JOIN BM50TANM on (BM50TANM.MISE_CD = BM01TENM.MISE_CD) 
    LEFT OUTER JOIN BR01USER on (BM50TANM.SV_CD = BR01USER.USER_ID) 
    
,   (SELECT CNT_DATE FROM BR33CDAY WHERE DAY_KBN = '02') BR33
WHERE
1=1
/*IF COMPANY_CD_0 != null */AND BM11ONER.COMPANY_CD = /*COMPANY_CD_0*/'00000000000'/*END*/
/*IF SIBU_CD != null */AND BM11ONER.SIBU_CD = /*SIBU_CD*/'00000000000'/*END*/
/*IF ONER_NAME_KJ != null */AND BM11ONER.ONER_NAME_KJ like /*ONER_NAME_KJ*/'abc'/*END*/
/*IF ONER_CD != null */AND BM11ONER.ONER_CD = /*ONER_CD*/'00000'/*END*/
/*IF MISE_NAME_KJ_0 != null */AND BM01TENM.MISE_NAME_KJ like /*MISE_NAME_KJ_0*/'abc'/*END*/
/*IF MISE_CD_0 != null */AND BM01TENM.MISE_CD = /*MISE_CD_0*/'00000'/*END*/
/*IF SV_NAME_KJ != null */AND BR01USER.USER_NAME_KJ like /*SV_NAME_KJ*/'abc'/*END*/
/*IF SV_CD != null */AND BM50TANM.SV_CD = /*SV_CD*/'00000'/*END*/
/*IF IN_END != null */AND BM11ONER.KEIYAKU_END >= BR33.CNT_DATE /*END*/
AND (1 = 1
/*IF ONER_NAME_KNA_1 != null */AND BM11ONER.ONER_NAME_KNA like /*ONER_NAME_KNA_1*/'abc'/*END*/
/*IF ONER_NAME_KNA_2 != null */OR BM11ONER.ONER_NAME_KNA like /*ONER_NAME_KNA_2*/'abc'/*END*/
/*IF ONER_NAME_KNA_3 != null */OR BM11ONER.ONER_NAME_KNA like /*ONER_NAME_KNA_3*/'abc'/*END*/
/*IF ONER_NAME_KNA_4 != null */OR BM11ONER.ONER_NAME_KNA like /*ONER_NAME_KNA_4*/'abc'/*END*/
)
GROUP BY BM11ONER.COMPANY_CD, BM11ONER.ONER_CD, BM11ONER.ONER_NAME_KJ, BM11ONER.ONER_NAME_KNA, KEIYAKU_END, CNT_DATE

/*IF SORT_TYPE == null */
ORDER BY BM11ONER.ONER_CD
/*END*/

/*IF SORT_TYPE != null */
ORDER BY Hex(BM11ONER.ONER_NAME_KNA)
/*END*/
       