SELECT MAINMENU.MENU_ID
   ,MAINMENU.MENU_NAME
   ,MAINMENU.SUB_MENU_ID
   ,MAINMENU.SUB_MENU_NAME
   ,MAINMENU.VIEW_ID
   ,MAINMENU.INIT_VIEW_ID
   ,MAINMENU.SORT_SEQ
   ,MAINMENU.MENU_DISP_KBN 
   ,BR05.EXTRA_FLG
   ,MAX(BR05.ENABLE_FLG) AS ENABLE_FLG
   ,MIN(CASE WHEN kobetu.CUSTOMIZE_FLG IS NULL AND BR05.ENABLE_FLG='1'
                 THEN '' ELSE kobetu.CUSTOMIZE_FLG END) CUSTOMIZE_FLG

FROM
    BR05ACTR BR05
   ,BR04USRL BR04
   ,(SELECT BR02.MENU_ID
     ,      BR02.MENU_NAME
     ,      BR02.SUB_MENU_ID
     ,      BR02.SUB_MENU_NAME
     ,      BR02.VIEW_ID
     ,      BR02.INIT_VIEW_ID
     ,      BR02.SORT_SEQ
     ,      BR02.MENU_DISP_KBN 
     ,      BR05.EXTRA_FLG
     ,      BR05.ENABLE_FLG
     FROM BR02BMNU BR02
     ,    BR05ACTR BR05
     WHERE BR02.MENU_ID     = '00'
     AND   BR05.EXTRA_FLG   = '1' 
     AND   BR02.MENU_ID     = BR05.MENU_ID 
     AND   BR02.SUB_MENU_ID = BR05.SUB_MENU_ID 
     GROUP BY BR02.MENU_ID
     ,        BR02.MENU_NAME
     ,        BR02.SUB_MENU_ID
     ,        BR02.SUB_MENU_NAME
     ,        BR02.VIEW_ID
     ,        BR02.INIT_VIEW_ID
     ,        BR02.SORT_SEQ
     ,        BR02.MENU_DISP_KBN 
     ,        BR05.EXTRA_FLG
     ,        BR05.ENABLE_FLG
     ) MAINMENU
   ,BR02BMNU BR02
LEFT JOIN (
        SELECT USER_ID 
           ,MENU_ID 
           ,SUB_MENU_ID 
           ,CUSTOMIZE_FLG 
        FROM BR54USAC BR54
        WHERE BR54.USER_ID = /*userId*/'A0HT4724' 
        AND MENU_ID != '00'
        AND NOT EXISTS ( SELECT BR80.SUB_MENU_ID 
                         FROM BR80AGMS BR80
                         WHERE BR80.MENU_ID = BR54.MENU_ID
                         AND   BR80.SUB_MENU_ID = BR54.SUB_MENU_ID)
    ) as kobetu ON (kobetu.MENU_ID = BR02.MENU_ID AND kobetu.SUB_MENU_ID = BR02.SUB_MENU_ID)
WHERE
      BR02.MENU_ID     = BR05.MENU_ID 
  AND BR02.SUB_MENU_ID = BR05.SUB_MENU_ID 
  AND BR05.ROLE_CD     = BR04.ROLE_CD 
  AND BR02.MENU_ID     != '00' 
  AND BR05.EXTRA_FLG   = '1' 
  AND BR04.USER_ID     = /*userId*/'A0HT4724' 
  AND MAINMENU.SUB_MENU_ID = BR02.MENU_ID
  AND NOT EXISTS ( SELECT BR80.SUB_MENU_ID 
                         FROM BR80AGMS BR80
                         WHERE BR80.MENU_ID = BR02.MENU_ID
                         AND   BR80.SUB_MENU_ID = BR02.SUB_MENU_ID)
  
GROUP BY MAINMENU.MENU_ID
   ,MAINMENU.MENU_NAME
   ,MAINMENU.SUB_MENU_ID
   ,MAINMENU.SUB_MENU_NAME
   ,MAINMENU.VIEW_ID
   ,MAINMENU.INIT_VIEW_ID
   ,MAINMENU.SORT_SEQ
   ,MAINMENU.MENU_DISP_KBN 
   ,BR05.EXTRA_FLG

ORDER BY SORT_SEQ
