SELECT rtrim(MENU_NAME_KJ) as MENU_NAME_KJ
,      MENU_BUNRUI
,      MENU_CD
,      CAMP_FLG
,      CASE WHEN (SUM(KAZU))=0 THEN null
            WHEN COUNT(DISTINCT MENU_TANKA) = 1 THEN MAX(MENU_TANKA) 
            WHEN SUM(URIAGE) >= 0 THEN DECIMAL(DOUBLE(SUM(URIAGE)) / DOUBLE(SUM(KAZU))+0.5, 11, 0) 
            ELSE DECIMAL(DOUBLE(SUM(URIAGE)) / DOUBLE(SUM(KAZU))-0.5, 11, 0) 
            END AS MENU_TANKA
,      SUM(URIAGE) AS URIAGE
,      SUM(KAZU_EAT)   AS KAZU_EAT
,      SUM(KAZU_TAKE)  AS KAZU_TAKE
,      SUM(KAZU_TEL)   AS KAZU_TEL
,      SUM(KAZU_DRIVE) AS KAZU_DRIVE
,      SUM(KAZU_OTHER) AS KAZU_OTHER
,      SUM(KAZU) AS URIAGE_COUNT


FROM (
    SELECT PC10.MENU_NAME_KJ
    ,      PC10.MENU_BUNRUI
    ,      PC10.MENU_CD
    ,      CAMP_FLG
    ,      MENU_TANKA
    ,      (KAZU_EAT+KAZU_TAKE+KAZU_TEL+KAZU_DRIVE+KAZU_OTHER) AS KAZU
    ,      (MENU_TANKA * (KAZU_EAT+KAZU_TAKE+KAZU_TEL+KAZU_DRIVE+KAZU_OTHER)) AS URIAGE
    ,      KAZU_EAT
    ,      KAZU_TAKE
    ,      KAZU_TEL
    ,      KAZU_DRIVE
    ,      KAZU_OTHER

    FROM   BT77MRAL BT77
           INNER JOIN PC10SMNU PC10
                   ON (PC10.MENU_CD = BT77.MENU_CD)
           INNER JOIN BM01TENM BM01
                   ON (BT77.COMPANY_CD = BM01.COMPANY_CD
                  AND  BT77.MISE_CD = BM01.MISE_CD) 

    WHERE  DATA_NUM = '00'
    AND    BT77.MISE_CD = /*miseCd*/'01841'
    AND    SHU_SYS_DT = /*latestDate*/'20101125'
    AND    BT77.COMPANY_CD = /*companyCd*/'00'

) MENUBETU

GROUP BY rtrim(MENU_NAME_KJ)
,        MENU_BUNRUI
,        MENU_CD
,        CAMP_FLG

ORDER BY MENU_BUNRUI
,        MENU_CD
