SELECT COUNT(DISTINCT BM01.MISE_CD) MISE_CNT
/*IF "MISE".equals(taishoJoken)*/
,      BM01.MISE_CD 
,      RTRIM(MISE_NAME_KJ) AS MISE_NAME_KJ
,      (CASE WHEN BM01.CLOSE_DT < /*sysDate*/'20110304' THEN '1' ELSE '0' END) AS MISE_OPEN_FLG
/*END*/
FROM BM01TENM BM01
,    BT64ZGEP BT64
WHERE BT64.EIGYO_DT BETWEEN /*kikanFrom*/'201001' AND /*kikanTo*/'201012'
AND   BT64.COMPANY_CD = /*companyCd*/'00'
/*IF "MISE".equals(taishoJoken) */  
AND   BT64.MISE_CD = /*hyojiTaisho*/'04179'
/*END*/
/*IF "02".equals(userTypeCd) */
AND   BM01.ONER_CD = /*onerCd*/'37006'
/*END*/
AND   BT64.OPEN_KBN   = 1 AND BT64.OLDM_FLG <> '1'
AND   BM01.COMPANY_CD = BT64.COMPANY_CD
AND   BM01.MISE_CD    = BT64.MISE_CD
/*IF "MISE".equals(taishoJoken)*/
GROUP BY BM01.MISE_CD 
,        BM01.MISE_NAME_KJ 
,        BM01.CLOSE_DT
--ELSE
HAVING COUNT(DISTINCT BM01.MISE_CD) >0
/*END*/