select SUBSTR(DATA60.EIGYO_DT, 1,6) AS EIGYO_YM
,      DATA60.EIGYO_DT
,      DATA60.URIAGE AS URIAGE
,      DATA60.YOSAN AS YOSAN
,      DATA60.URIAGE_ZEN AS URIAGE_ZEN
,      DATA60.KYAKUSU AS KYAKUSU
,      DATA60.KYAKUSU_ZEN AS KYAKUSU_ZEN
/*IF taishoJoken.equals("MISE") */
,      DATA60.EIGYO_DAYS AS EIGYO_DAYS
,      DATA60.TENKO_KBN AS TENKO_KBN
,      DATA60.EIGYO_DAYS_ZEN AS EIGYO_DAYS_ZEN
,      DATA60.TENKO_KBN_ZEN AS TENKO_KBN_ZEN
,      CASE WHEN DATA60.TENKO_KBN = 1 THEN 'ê∞'
            WHEN DATA60.TENKO_KBN = 2 THEN 'ì‹'
            WHEN DATA60.TENKO_KBN = 3 THEN 'âJ'
            WHEN DATA60.TENKO_KBN = 4 THEN 'ê·'
            WHEN DATA60.TENKO_KBN = 5 THEN 'óí'
            ELSE '' END  AS TENKO_KBN_KJ
,      CASE WHEN DATA60.TENKO_KBN_ZEN = 1 THEN 'ê∞'
            WHEN DATA60.TENKO_KBN_ZEN = 2 THEN 'ì‹'
            WHEN DATA60.TENKO_KBN_ZEN = 3 THEN 'âJ'
            WHEN DATA60.TENKO_KBN_ZEN = 4 THEN 'ê·'
            WHEN DATA60.TENKO_KBN_ZEN = 5 THEN 'óí'
            ELSE '' END  AS TENKO_KBN_ZEN_KJ
/*END*/
from (
      SELECT BT60.EIGYO_DT
      ,      SUM(BT60.URIAGE) AS URIAGE
      ,      SUM(BT60.ONER_YOSAN) AS YOSAN
      ,      SUM(BT60.EIGYO_DAYS) AS EIGYO_DAYS
      ,      MAX(BT60.TENKO_KBN) AS TENKO_KBN
      ,      SUM(BT60.KYAKUSU) AS KYAKUSU

      ,      SUM(BT60.URIAGE_ZEN_/*$zennenDatashubetu*/'DOGETU')    AS URIAGE_ZEN
      ,      SUM(BT60.EIGYO_DAYS_ZEN_/*$zennenDatashubetu*/'DOGETU') AS EIGYO_DAYS_ZEN
      ,      MAX(BT60.TENKO_KBN_ZEN_/*$zennenDatashubetu*/'DOGETU')  AS TENKO_KBN_ZEN
      ,      SUM(BT60.KYAKUSU_ZEN_/*$zennenDatashubetu*/'DOGETU')    AS KYAKUSU_ZEN
FROM BT60ZNIP BT60
WHERE BT60.COMPANY_CD = /*companyCd*/'00'
AND   SUBSTR(BT60.EIGYO_DT, 1,6) = /*kikanYm*/'200902'
AND   BT60.EIGYO_DT < /*sysDate*/'20110228'
/*IF taishoJoken.equals("MISE") */  
AND   BT60.MISE_CD = /*hyojiTaisho*/'00108'
--ELSE
AND   EXISTS (SELECT COUNT(BM01.MISE_CD) FROM BM01TENM BM01
              WHERE BM01.COMPANY_CD = /*companyCd*/'00'
              AND   BM01.ONER_CD = /*onerCd*/'37006'
              AND   BM01.COMPANY_CD = BT60.COMPANY_CD
              AND   BM01.MISE_CD    = BT60.MISE_CD
              GROUP BY BM01.COMPANY_CD
)
/*END*/
	  AND   BT60.OLDM_FLG <> '1'
	  AND   BT60.OPEN_KBN = 1
      GROUP BY BT60.EIGYO_DT
  ) DATA60 

ORDER BY EIGYO_DT