SELECT
   MM24.MISE_M_DATE        AS MISE_M_DATE
  ,MM24.MISE_LEASE_SHU     AS MISE_LEASE_SHU
  ,MM24.MISE_LEASE_START   AS MISE_LEASE_START
  ,MM24.MISE_LEASE_END     AS MISE_LEASE_END
FROM
  MM24CHIT MM24
  ,BM74MMRI BM74
WHERE
  BM74.COMPANY_CD='00'
  AND BM74.MISE_CD = /*miseCd*/'00000'
  AND MM24.COMPANY_CD = BM74.COMPANY_CD
  AND MM24.MISE_CD = BM74.MISE_CD
  AND MM24.MISE_M_DATE = BM74.MISE_M_DATE
ORDER BY
   MM24.MISE_M_DATE DESC
  ,MM24.MISE_LEASE_SHU ASC