SELECT
  RTRIM(BM74.MISE_M_DATE)    AS MISE_M_DATE
  ,RTRIM(BM74.MISE_CD)    AS MISE_CD
  ,RTRIM(BM74.MISE_NAME_KJ)  AS MISE_NAME_KJ
  ,RTRIM(BM74.MISE_NAME_KNA)  AS MISE_NAME_KNA
  ,RTRIM(BM74.ONER_CD)    AS ONER_CD
  ,RTRIM(BM11.ONER_NAME_KJ)  AS ONER_NAME_KJ
  ,RTRIM(BM74.SIBU_CD)    AS SIBU_CD
  ,RTRIM(BM10.SIBU_NAME)    AS SIBU_NAME
  ,RTRIM(BM74.SIBU_TORI_CD)  AS SIBU_TORI_CD
  ,RTRIM(BM10_1.SIBU_NAME)  AS SIBU_TORI_NAME
  ,RTRIM(BM74.MISE_KBN)    AS MISE_KBN
  ,RTRIM(BC21.AITE_NAME)    AS AITE_NAME
  ,RTRIM(BM74.GYOTAI_KBN)    AS GYOTAI_KBN
  ,RTRIM(BC09.GYOTAI_KBN_NAME)AS GYOTAI_KBN_NAME
  ,RTRIM(BM50.SV_CD)      AS SV_CD
  ,RTRIM(BR01.USER_NAME_KJ)  AS USER_NAME_KJ
  ,RTRIM(BM74.OPEN_DT)    AS OPEN_DT
  ,RTRIM(BM74.CLOSE_DT)    AS CLOSE_DT
  ,RTRIM(BM74.MISE_CD_SAISHIN)AS MISE_CD_SAISHIN
  ,RTRIM(BM74.MISE_CD_SHINTEN)AS MISE_CD_SHINTEN
  ,RTRIM(BM74.KEN_CD)      AS KEN_CD
  ,RTRIM(BC38.KEN_NAME)    AS KEN_NAME
  ,RTRIM(BM74.MISE_POST_NO)  AS MISE_POST_NO
  ,RTRIM(BM74.MISE_ADRS1)    AS MISE_ADRS1
  ,RTRIM(BM74.MISE_ADRS2)    AS MISE_ADRS2
  ,RTRIM(BM74.MISE_ADRS3)    AS MISE_ADRS3
  ,RTRIM(BM74.MISE_TEL)    AS MISE_TEL
  ,RTRIM(BM74.M_TYPE_KBN)    AS M_TYPE_KBN
  ,RTRIM(MC23.M_TYPE_KBN_NAME)AS M_TYPE_KBN_NAME
  ,RTRIM(BM74.T_MISE_KEITAI)  AS T_MISE_KEITAI
  ,RTRIM(TC20.M_KEITAI_NAME)  AS M_KEITAI_NAME
  ,RTRIM(BM74.T_LOCATE_KBN)  AS T_LOCATE_KBN
  ,RTRIM(TC19.LOCATE_NAME)  AS LOCATE_NAME
  ,RTRIM(BM74.TENTAI)      AS TENTAI
  ,RTRIM(BM74.TENTAI_START_DT)AS TENTAI_START_DT
  ,RTRIM(BM74.TENTAI_END_DT)  AS TENTAI_END_DT
  ,RTRIM(BM74.TENTAI_INFO)  AS TENTAI_INFO
  ,RTRIM(BM74.MISE_LEASE_K_CD)AS MISE_LEASE_K_CD
FROM
  BM74MMRI BM74
LEFT JOIN
  BM11ONER BM11
    ON (BM74.COMPANY_CD = BM11.COMPANY_CD AND BM74.ONER_CD = BM11.ONER_CD)
LEFT JOIN
  BM10GSIB BM10
    ON (BM74.COMPANY_CD = BM10.COMPANY_CD AND BM74.SIBU_CD = BM10.SIBU_CD)
LEFT JOIN
  BM10GSIB BM10_1
    ON (BM74.COMPANY_CD = BM10_1.COMPANY_CD AND BM74.SIBU_TORI_CD = BM10_1.SIBU_CD)
LEFT JOIN
  BC21AITE BC21
    ON (BM74.MISE_KBN = BC21.AITE_KBN)
LEFT JOIN
  BC09GTAI BC09
    ON (BM74.GYOTAI_KBN = BC09.GYOTAI_KBN)
LEFT JOIN
  BM50TANM BM50
    ON (BM74.COMPANY_CD = BM50.COMPANY_CD AND BM74.MISE_CD = BM50.MISE_CD)
LEFT JOIN
  BR01USER BR01
    ON (BM50.SV_CD = BR01.USER_ID)
LEFT JOIN
  BC38TKEN BC38
    ON (BC38.KEN_CD = BM74.KEN_CD)
LEFT JOIN
  MC23MTYP MC23
    ON (BM74.M_TYPE_KBN = MC23.M_TYPE_KBN)
LEFT JOIN
  TC20MKTA TC20
    ON (BM74.COMPANY_CD = TC20.COMPANY_CD AND BM74.T_MISE_KEITAI = TC20.MISE_KEITAI)
LEFT JOIN
  TC19LOCT TC19
    ON (BM74.COMPANY_CD = TC19.COMPANY_CD AND BM74.T_LOCATE_KBN = TC19.LOCATE_KBN)
WHERE
  BM74.COMPANY_CD = '00'
  AND BM74.MISE_CD = /*miseCd*/'00000'
ORDER BY
  BM74.MISE_M_DATE DESC