SELECT DISTINCT BM02.SORT_KEY AS CATE_SORT_KEY
,      BM02.INFO_SHU
,      BM02.CATE_ID 
,      BM02.CATE_NAME

FROM (
    SELECT BT03or04.CATE_ID
    ,      BT03or04.SUB_CATE_ID
    FROM (SELECT CATE_ID, SUB_CATE_ID, REG_DATE,SEQ
/*IF "03".equals(infoShu)*/
          FROM BT03DOCM 
/*END*/
/*IF "04".equals(infoShu)*/
          FROM BT04FRMM 
/*END*/
     	  WHERE SAKUJO_FLG <> '1' 
     	  AND PUB_DATE_FROM <= /*sysDate*/'20110214'
     	  AND PUB_DATE_TO >= /*sysDate*/'20110214') BT03or04
    ,   (SELECT R_COMPANY_CD, REG_DATE,SEQ FROM BT12IACP WHERE INFO_SHU = /*infoShu*/'03') BT12
    ,   (SELECT SHOZOKU_KBN, REG_DATE,SEQ FROM BT13IASZ WHERE INFO_SHU = /*infoShu*/'03') BT13
    ,   (SELECT GYOTAI_KBN, REG_DATE,SEQ FROM BT14IAGT WHERE INFO_SHU = /*infoShu*/'03'
                                       AND   KOBETSU_FLG <> '1' AND MISE_FLG <> '1'
         ) BT14
    WHERE BT12.REG_DATE = BT03or04.REG_DATE
    AND   BT13.REG_DATE = BT12.REG_DATE
    AND   BT14.REG_DATE = BT13.REG_DATE
    AND   BT12.SEQ = BT03or04.SEQ
    AND   BT13.SEQ = BT12.SEQ
    AND   BT14.SEQ = BT13.SEQ
    AND   EXISTS(SELECT * FROM BM03USCP BM03
                 WHERE BM03.USER_ID = /*userId*/'99990003'
                 AND   BT12.R_COMPANY_CD = BM03.R_COMPANY_CD)
    AND   EXISTS(SELECT * FROM BM13SHKM BM13
                 WHERE BM13.USER_ID = /*userId*/'99990003'
                 AND   BT13.SHOZOKU_KBN = BM13.SHOZOKU_KBN)
    AND   EXISTS(SELECT * FROM BM05USGT BM05
                 WHERE BM05.USER_ID = /*userId*/'99990003'
                 AND   BT14.GYOTAI_KBN = BM05.GYOTAI_KBN)
    GROUP BY BT03or04.CATE_ID
    ,        BT03or04.SUB_CATE_ID
/*IF kobetsuFlg */
 UNION ALL 
    SELECT BT03or04.CATE_ID
    ,      BT03or04.SUB_CATE_ID
    FROM (SELECT CATE_ID, SUB_CATE_ID, REG_DATE,SEQ
    /*IF "03".equals(infoShu)*/
          FROM BT03DOCM 
    /*END*/
    /*IF "04".equals(infoShu)*/
          FROM BT04FRMM 
    /*END*/
     	  WHERE SAKUJO_FLG <> '1' 
     	  AND PUB_DATE_FROM <= /*sysDate*/'20110214'
     	  AND PUB_DATE_TO >= /*sysDate*/'20110214') BT03or04
    ,   (SELECT R_COMPANY_CD, REG_DATE,SEQ FROM BT12IACP WHERE INFO_SHU = /*infoShu*/'03') BT12
    ,   (SELECT SHOZOKU_KBN, REG_DATE,SEQ FROM BT13IASZ WHERE INFO_SHU = /*infoShu*/'03') BT13
    ,   (SELECT GYOTAI_KBN, REG_DATE,SEQ, KOBETSU_FLG, MISE_FLG
         FROM BT14IAGT WHERE INFO_SHU = /*infoShu*/'03'
                       AND   (KOBETSU_FLG = '1' OR MISE_FLG = '1')) BT14
    LEFT JOIN  (
    SELECT BT15.INFO_SHU
    ,      BT15.REG_DATE
    ,      BT15.SEQ
    ,      BT15.GYOTAI_KBN
    from BT15IAID BT15
    ,    BM04GTCP BM04
    ,    BM05USGT BM05
    ,    BM01TENM BM01
    /*IF "03".equals(userTypeCd) */
    ,    BM07UTEN USER
   --ELSE
    ,    BM06UONR USER
    /*END*/
    WHERE BT15.INFO_SHU    = /*infoShu*/'03'
    AND   BT15.KOBETSU_SHU = '01'
    AND   BM05.USER_ID     = /*userId*/'99990003'
    AND   BM01.CLOSE_DT > /*sysDate*/''
    AND   USER.USER_ID     = BM05.USER_ID
    AND   BM04.COMPANY_CD = USER.COMPANY_CD
    AND   BM01.COMPANY_CD = BM04.COMPANY_CD
    AND   BM05.GYOTAI_KBN = BM04.GYOTAI_KBN
    AND   BT15.GYOTAI_KBN = BM05.GYOTAI_KBN
    /*IF "03".equals(userTypeCd) */
    	AND BM01.MISE_CD = USER.MISE_CD
   --ELSE
    	AND BM01.ONER_CD = USER.ONER_CD
    /*END*/
    AND BT15.KOBETSU_CD = BM01.AREA_DAI
    group by
    BT15.INFO_SHU,
    BT15.REG_DATE,
    BT15.SEQ,
    BT15.GYOTAI_KBN
   ) KOBETSU ON (KOBETSU.REG_DATE = BT14.REG_DATE)
    LEFT JOIN  (
    SELECT BT16.INFO_SHU,
           BT16.REG_DATE,
           BT16.SEQ,
           BT16.GYOTAI_KBN
    FROM BT16IAST BT16,
         BM04GTCP BM04,
         BM05USGT BM05,
         BM01TENM BM01
    /*IF "03".equals(userTypeCd) */
    ,    BM07UTEN USER
    --ELSE
    ,    BM06UONR USER
    /*END*/
    WHERE BT16.INFO_SHU = /*infoShu*/'03'
    AND   BM05.USER_ID = /*userId*/'99990003'
    AND   BM01.CLOSE_DT > /*sysDate*/''
    AND   USER.USER_ID = BM05.USER_ID
    AND   BM04.COMPANY_CD = USER.COMPANY_CD
    AND   BM01.COMPANY_CD = BM04.COMPANY_CD
    AND   BT16.GYOTAI_KBN = BM05.GYOTAI_KBN
    AND   BT16.GYOTAI_KBN = BM04.GYOTAI_KBN
    AND   BT16.MISE_CD = BM01.MISE_CD
    /*IF "03".equals(userTypeCd) */
    	AND BM01.MISE_CD = USER.MISE_CD
    --ELSE
    	AND BM01.ONER_CD = USER.ONER_CD
    /*END*/
    group by
        BT16.INFO_SHU,
        BT16.REG_DATE,
        BT16.SEQ,
        BT16.GYOTAI_KBN
   ) MISEBETSU ON (MISEBETSU.REG_DATE = BT14.REG_DATE)
    
    WHERE BT12.REG_DATE = BT03or04.REG_DATE
    AND   BT13.REG_DATE = BT12.REG_DATE
    AND   BT14.REG_DATE = BT13.REG_DATE
    AND   BT12.SEQ = BT03or04.SEQ
    AND   BT13.SEQ = BT12.SEQ
    AND   BT14.SEQ = BT13.SEQ
    AND ((BT14.KOBETSU_FLG ='1' 
    	 AND BT14.REG_DATE   = KOBETSU.REG_DATE
    	 AND BT14.SEQ        = KOBETSU.SEQ
    	 AND BT14.GYOTAI_KBN = KOBETSU.GYOTAI_KBN
        ) 
        OR (BT14.MISE_FLG ='1' 
    	 AND BT14.REG_DATE   = MISEBETSU.REG_DATE
    	 AND BT14.SEQ        = MISEBETSU.SEQ
    	 AND BT14.GYOTAI_KBN = MISEBETSU.GYOTAI_KBN
        ))
    
    AND   EXISTS(SELECT * FROM BM03USCP BM03
                 WHERE BM03.USER_ID = /*userId*/'99990003'
                 AND   BT12.R_COMPANY_CD = BM03.R_COMPANY_CD)
    AND   EXISTS(SELECT * FROM BM13SHKM BM13
                 WHERE BM13.USER_ID = /*userId*/'99990003'
                 AND   BT13.SHOZOKU_KBN = BM13.SHOZOKU_KBN)
    AND   EXISTS(SELECT * FROM BM05USGT BM05
                 WHERE BM05.USER_ID = /*userId*/'99990003'
                 AND   BT14.GYOTAI_KBN = BM05.GYOTAI_KBN)
    GROUP BY BT03or04.CATE_ID
    ,      BT03or04.SUB_CATE_ID
/*END*/
) CATEDATA
,    (SELECT INFO_SHU, CATE_ID, CATE_NAME, SORT_KEY FROM BM02IFCT WHERE INFO_SHU = /*infoShu*/'03') BM02
,    (SELECT CATE_ID, SUB_CATE_ID, SUB_CATE_NAME, SORT_KEY FROM BM17SBCT WHERE BM17SBCT.INFO_SHU = /*infoShu*/'03') BM17
WHERE BM02.CATE_ID = CATEDATA.CATE_ID 
AND   BM17.CATE_ID = CATEDATA.CATE_ID 
AND   BM17.SUB_CATE_ID =CATEDATA.SUB_CATE_ID 
ORDER BY  BM02.SORT_KEY

 
    