SELECT 	BSTA.PGM_ID
	,  	BSTA.PGM_KBN
	,	STAT.STAT_KBN
	,   BSTA.ERR_CD
	,	BSTA.EXEC_USER
	,	BSTA.START_TMSP
	,	BSTA.END_TMSP
FROM	BR48BSTA BSTA
,       (SELECT MAX(STAT_KBN) AS STAT_KBN
		 FROM  BR48BSTA 
		 WHERE PGM_ID in /*pgmId*/('') 
		 AND   PGM_KBN =/*pgmKbn*/''
		) STAT
WHERE 	BSTA.PGM_ID in /*pgmId*/('')
AND   	BSTA.PGM_KBN =/*pgmKbn*/''
AND     BSTA.STAT_KBN = STAT.STAT_KBN
ORDER BY BSTA.PGM_ID
