SELECT 
count(distinct BM01TENM.MISE_CD) AS COUNT,
BM01TENM.MISE_CD AS MISE_CD, 
BM01TENM.MISE_NAME_KJ AS MISE_NAME_KJ,
bn01d.KBN1 AS TENPO_SHUBETU,
BT74YAGO.YAGO_DETAIL_CD AS MOSG_KBN, 
BM44YDMS.YAGO_DETAIL_NAME AS YAGO_DTL_NAME, 
/*IF dataShu.equals("DOGETU")*/
		sum(BT74YAGO.URIAGE_DOGETU) as URIAGE , 
		sum(BT74YAGO.ONER_YOSAN_DOGETU) as URI_YOSAN, 
		sum(BT74YAGO.EIGYO_DAYS_DOGETU) as EIGYO_DAYS ,
		sum(BT74YAGO.KYAKUSU_DOGETU) as KYAKUSU , 
		sum(BT74YAGO.URIAGE_ZEN_DOGETU) as URIAGE_ZEN, 
		sum(BT74YAGO.KYAKUSU_ZEN_DOGETU) as KYAKUSU_ZEN, 
		sum(BT74YAGO.EIGYO_DAYS_ZEN_DOGETU) as EIGYO_DAYS_ZEN
-- ELSE
		/*IF dataShu.equals("DOYO")*/
				sum(BT74YAGO.URIAGE_DOYO) as URIAGE , 
				sum(BT74YAGO.ONER_YOSAN_DOYO) as URI_YOSAN, 
				sum(BT74YAGO.EIGYO_DAYS_DOYO) as EIGYO_DAYS , 	
				sum(BT74YAGO.KYAKUSU_DOYO) as KYAKUSU , 
				sum(BT74YAGO.URIAGE_ZEN_DOYO) as URIAGE_ZEN, 
				sum(BT74YAGO.KYAKUSU_ZEN_DOYO) as KYAKUSU_ZEN, 
				sum(BT74YAGO.EIGYO_DAYS_ZEN_DOYO) as EIGYO_DAYS_ZEN

		-- ELSE
				sum(BT74YAGO.URIAGE_DOJITU) as URIAGE , 
				sum(BT74YAGO.ONER_YOSAN_DOJITU) as URI_YOSAN, 
				sum(BT74YAGO.EIGYO_DAYS_DOJITU) as EIGYO_DAYS , 	
				sum(BT74YAGO.KYAKUSU_DOJITU) as KYAKUSU , 
				sum(BT74YAGO.URIAGE_ZEN_DOJITU) as URIAGE_ZEN, 
				sum(BT74YAGO.KYAKUSU_ZEN_DOJITU) as KYAKUSU_ZEN, 
				sum(BT74YAGO.EIGYO_DAYS_ZEN_DOJITU) as EIGYO_DAYS_ZEN

		/*END*/
/*END*/

from (BM01TENM 
JOIN (select company_cd,mise_cd,eigyo_ym,kbn1 from BN01DTEN where 
BN01DTEN.COMPANY_CD = /*companyCd*/ 
/*IF taishoKikan.equals("APPMONTH")*/
	AND BN01DTEN.EIGYO_YM = /*kikanFrom*/
/*END*/
/*IF taishoKikan.equals("MONTH")*/
	AND BN01DTEN.EIGYO_YM = /*kikanFrom*/
/*END*/
/*IF taishoKikan.equals("KIBETU")*/
	AND (BN01DTEN.EIGYO_YM between /*kikanFrom*/ AND /*kikanTo*/) 
/*END*/
group by company_cd,mise_cd,eigyo_ym,kbn1) as bn01d on (
 BM01TENM.COMPANY_CD = bn01d.COMPANY_CD AND 
 BM01TENM.MISE_CD = bn01d.MISE_CD 
)
JOIN BT74YAGO on (
 BT74YAGO.COMPANY_CD = bn01d.COMPANY_CD AND
 BT74YAGO.EIGYO_DT = bn01d.EIGYO_YM AND
 BT74YAGO.MISE_CD = bn01d.MISE_CD AND 
 BT74YAGO.OLDM_FLG = '0') 
JOIN BM44YDMS on (
 BM44YDMS.YAGO_DETAIL_CD = BT74YAGO.YAGO_DETAIL_CD )  
 )
WHERE
 	BM01TENM.COMPANY_CD = /*companyCd*/ 
 	AND BM01TENM.ONER_CD = /*onerCd*/
 	AND BT74YAGO.OPEN_KBN = 1 
GROUP BY rollup(
(BT74YAGO.YAGO_DETAIL_CD,BM44YDMS.YAGO_DETAIL_NAME),
(BM01TENM.MISE_CD,
BM01TENM.MISE_NAME_KJ, 
bn01d.KBN1
))
ORDER BY BM01TENM.MISE_CD , BT74YAGO.YAGO_DETAIL_CD
