SELECT
BM44YDMS.YAGO_DETAIL_CD AS YAGO_DETAIL_CD, 
BM44YDMS.YAGO_DETAIL_NAME AS YAGO_DETAIL_NAME 
from BM44YDMS JOIN BM43YMST on (BM43YMST.YAGO_CD = BM44YDMS.YAGO_CD) 
WHERE BM44YDMS.YAGO_CD = /*yagoCd*/
ORDER BY BM44YDMS.SORT_DETAIL