SELECT 
       BM50.COMPANY_CD
,      '' as SIBU_CD
,      BM50.SV_CD
,      rtrim(BR01.USER_NAME_KJ) AS SV_NAME_KJ
,      rtrim(BR01.USER_NAME_KANA) as SV_NAME_KNA

FROM
    BM50TANM BM50
    LEFT OUTER JOIN 
        BM01TENM BM01
    ON  (BM50.COMPANY_CD = BM01.COMPANY_CD
    AND BM50.MISE_CD = BM01.MISE_CD) 
    LEFT OUTER JOIN 
        BM11ONER BM11
    ON  (BM01.COMPANY_CD = BM11.COMPANY_CD
    AND BM01.ONER_CD = BM11.ONER_CD),
    BR01USER BR01

WHERE
    BM50.SV_CD = BR01.USER_ID
/*IF COMPANY_CD_0 != null */AND BM11.COMPANY_CD = /*COMPANY_CD_0*/'00'/*END*/
/*IF SIBU_CD != null */AND BM01.SIBU_CD = /*SIBU_CD*/'031'/*END*/
/*IF ONER_CD != null */AND BM11.ONER_CD = /*ONER_CD*/'36478'/*END*/
/*IF MISE_CD_0 != null */AND BM01.MISE_CD = /*MISE_CD_0*/'01776'/*END*/
/*IF MISE_NAME_KJ_0 != null */AND BM01.MISE_NAME_KJ like /*MISE_NAME_KJ_0*/'abc'/*END*/
/*IF ONER_NAME_KJ != null */AND BM11.ONER_NAME_KJ like /*ONER_NAME_KJ*/'abc'/*END*/

AND (1 = 1
/*IF SV_NAME_KNA_1 != null */AND BR01.USER_NAME_KANA like /*SV_NAME_KNA_1*/'abc'/*END*/
/*IF SV_NAME_KNA_2 != null */OR BR01.USER_NAME_KANA like /*SV_NAME_KNA_2*/'abc'/*END*/
/*IF SV_NAME_KNA_3 != null */OR BR01.USER_NAME_KANA like /*SV_NAME_KNA_3*/'abc'/*END*/
/*IF SV_NAME_KNA_4 != null */OR BR01.USER_NAME_KANA like /*SV_NAME_KNA_4*/'abc'/*END*/
)
GROUP BY 
    BM50.COMPANY_CD
,   ''
,   BM50.SV_CD
,   BR01.USER_NAME_KJ
,   BR01.USER_NAME_KANA

/*IF SORT_TYPE == null */
ORDER BY BM50.SV_CD
/*END*/

/*IF SORT_TYPE != null */
ORDER BY Hex(BR01.USER_NAME_KANA)
/*END*/