SELECT
    USERDATE.USER_ID AS USER_ID,
    USERDATE.HATSUREI_DT,
    USERDATE.USER_NAME_KJ,
    USERDATE.SALARY_CD,
    USERDATE.JINJI_CD,
    USERDATE.BUMON_CD_KAKUTEI8,
    BC08CBMN.BUMON_NAME,
    USERDATE.KBN_SPARE1
FROM
    (SELECT
    VIR51USER.USER_ID AS USER_ID,
    VIR51USER.HATSUREI_DT,
    VIR51USER.USER_NAME_KJ,
    VIR51USER.SALARY_CD,
    VIR51USER.JINJI_CD,
    IR55BKAI.BUMON_CD_KAKUTEI8,
    VIR51USER.KBN_SPARE1
FROM
    VIR51USER LEFT JOIN
    IR55BKAI
ON
    VIR51USER.USER_ID = IR55BKAI.USER_ID
WHERE
    VIR51USER.USER_ID = /*USER_ID*/'55555555') AS USERDATE
    LEFT JOIN BC08CBMN
ON
    USERDATE.BUMON_CD_KAKUTEI8 = BC08CBMN.BUMON_CD