SELECT DISTINCT BM12.ONER_CD
,      RTRIM(BM11.ONER_NAME_KJ) AS ONER_NAME_KJ
,      AREA_DAI
,      RTRIM(SIBU_NAME) AS SIBU_NAME
,      MISE_CD_1
,      RTRIM(BM01.MISE_NAME_KJ) AS MISE_NAME_KJ
,      BM12.STAFF_ID
,      CONCAT(RTRIM(BM12.STAFF_L_NAME_KJ), CONCAT(' ', RTRIM(BM12.STAFF_F_NAME_KJ))) AS STAFF_NAME
,      CASE WHEN BM12.SEX = '0' THEN 'íj'
            WHEN BM12.SEX = '1' THEN 'èó'
            ELSE '' 
       END AS SEX
,      RTRIM(BM12.JOB) AS JOB
,      CASE WHEN BM12.SITUATION_KBN = '0' THEN 'äàìÆíÜ'
            WHEN BM12.SITUATION_KBN = '1' THEN 'ãxêEíÜ'
            WHEN BM12.SITUATION_KBN = '2' THEN 'ëﬁêE'
            ELSE ''
       END AS SITUATION
,      BT26.LICENSE_NO
,      BT26.LICENSE_DT
,      CASE WHEN BT30KOUSIN.COURSE_STATUS = '0' THEN 'ñ¢èCóπ'
            WHEN BT30KOUSIN.COURSE_STATUS = '1' THEN 'èCóπ'
            WHEN BT30KOUSIN.COURSE_STATUS = '2' THEN 'ó\íË'
            ELSE ''
       END AS K_COURSE_STATUS
,      BT32.FIRST_LICENSE_YEAR
,      BT32.FIRST_LICENSE_KAI
,      CASE WHEN BT32.TOTAL_RESULT = '0' THEN 'ñ≥å¯'
            WHEN BT32.TOTAL_RESULT = '1' THEN 'ï€óØ'
            WHEN BT32.TOTAL_RESULT = '2' THEN 'ïsçáäi'
            WHEN BT32.TOTAL_RESULT = '3' THEN 'î≠çsë“Çø'
            WHEN BT32.TOTAL_RESULT = '4' THEN 'î≠çsçœ'
            WHEN BT32.TOTAL_RESULT = '9' THEN 'ñ¢éÛå±'
            ELSE ''
       END AS TOTAL_RESULT
,      CASE WHEN BT30ZENTEI.COURSE_STATUS = '0' THEN 'ñ¢èCóπ'
            WHEN BT30ZENTEI.COURSE_STATUS = '1' THEN 'èCóπ'
            WHEN BT30ZENTEI.COURSE_STATUS = '2' THEN 'ó\íË'
            ELSE ''
       END AS Z_COURSE_STATUS
,    BM12.NOTE
FROM BC02COMP BC02
,    BM01TENM BM01
,    BM10GSIB BM10
,    BM11ONER BM11
,    BM12STAF BM12
LEFT JOIN (SELECT STAFF_ID 
           ,      LICENSE_NO
           ,      LICENSE_DT
           FROM BT26UPJK 
           WHERE EXPIRE_FLG <> '1'
          ) BT26 ON (BT26.STAFF_ID = BM12.STAFF_ID)
LEFT JOIN (SELECT STAFF_ID 
           ,      COURSE_STATUS
           FROM BT30ENKJ 
           WHERE ENTRY_CD = '30' 
           AND COMPLE_COURSE_DT BETWEEN /*sysNendoFrom*/'200904' AND /*sysNendoTo*/'201003'
           AND COURSE_STATUS = '1'
          ) BT30KOUSIN ON (BT30KOUSIN.STAFF_ID = BM12.STAFF_ID)
LEFT JOIN (SELECT STAFF_ID 
           ,      COURSE_STATUS
           FROM BT30ENKJ 
           WHERE ENTRY_CD IN ('01', '05') 
           AND COURSE_STATUS = '1'
          ) BT30ZENTEI ON (BT30ZENTEI.STAFF_ID = BM12.STAFF_ID)
LEFT JOIN (SELECT LICENSE_INF.STAFF_ID
           ,      LICENSE_INF.EXAM_NO
           ,      SUB.FIRST_LICENSE
           ,      SUBSTR(SUB.FIRST_LICENSE, 1,4) AS FIRST_LICENSE_YEAR
           ,      SUBSTR(SUB.FIRST_LICENSE, 5,3) AS FIRST_LICENSE_KAI
           ,      LICENSE_INF.TOTAL_RESULT
           FROM BT32MLKR LICENSE_INF
           ,    (SELECT LASTEST.STAFF_ID
                 ,      LASTEST.EXAM_NO
                 ,      MIN(CONCAT(MAIN.TOTAL_LAST_YEAR,MAIN.TOTAL_LAST_KAI)) AS FIRST_LICENSE
                 ,      MAX(CONCAT(MAIN.TOTAL_LAST_YEAR,MAIN.TOTAL_LAST_KAI)) AS LAST_LICENSE
                 FROM (SELECT MAIN.STAFF_ID 
                       ,      MAIN.EXAM_NO
                       FROM BT32MLKR MAIN 
                       ,    (SELECT STAFF_ID
                             ,      SUBSTR(MAX(CONCAT(TOTAL_LAST_YEAR, TOTAL_LAST_KAI)), 1,4) AS MAX_YEAR
                             ,      SUBSTR(MAX(CONCAT(TOTAL_LAST_YEAR, TOTAL_LAST_KAI)), 5,3) AS MAX_KAI
                             FROM BT32MLKR 
                             GROUP BY STAFF_ID) SUB
                       WHERE MAIN.STAFF_ID = SUB.STAFF_ID
                       AND   MAIN.TOTAL_LAST_YEAR = SUB.MAX_YEAR
                       AND   MAIN.TOTAL_LAST_KAI  = SUB.MAX_KAI) LASTEST
                 ,    BT32MLKR MAIN
                 WHERE MAIN.STAFF_ID = LASTEST.STAFF_ID
                 AND   MAIN.EXAM_NO  = LASTEST.EXAM_NO
                 GROUP BY LASTEST.STAFF_ID
                 ,        LASTEST.EXAM_NO
           ) SUB
           WHERE LICENSE_INF.STAFF_ID = SUB.STAFF_ID
           AND   LICENSE_INF.EXAM_NO  = SUB.EXAM_NO
           AND   CONCAT(TOTAL_LAST_YEAR,LICENSE_INF.TOTAL_LAST_KAI)=SUB.LAST_LICENSE
          ) BT32 ON (BT32.STAFF_ID   = BM12.STAFF_ID)

WHERE BM01.COMPANY_CD = /*companyCd*/'00'
AND   BM12.SITUATION_KBN <> '2'
AND   (BT26.STAFF_ID = BM12.STAFF_ID
        OR BT30KOUSIN.STAFF_ID = BM12.STAFF_ID
           OR BT30ZENTEI.STAFF_ID = BM12.STAFF_ID)
AND   BM12.COMPANY_CD = BM01.COMPANY_CD
AND   BM12.MISE_CD_1  = BM01.MISE_CD
AND   BM10.COMPANY_CD = BM01.COMPANY_CD
AND   BM10.SIBU_CD    = BM01.AREA_DAI
AND   BM12.COMPANY_CD = BM11.COMPANY_CD
AND   BM12.ONER_CD    = BM11.ONER_CD

ORDER BY AREA_DAI
,        BM12.ONER_CD
,        MISE_CD_1
,        BM12.STAFF_ID