SELECT CASE WHEN MAX(ENTRY_KAI) IS NULL THEN /*entryKai*/'001' 
            ELSE SUBSTR(CHAR(DECIMAL(DECIMAL(MAX(ENTRY_KAI))+1, 3,0)), 1, 3)  END AS ENTRY_KAI
FROM    BR17ENTL
WHERE   ENTRY_CD = /*entryCd*/'25'
AND     ENTRY_YEAR = /*entryYear*/'2006'
