SELECT  BR17.ENTRY_CD
,       BR17.ENTRY_YEAR
,       BR17.ENTRY_KAI
,       RTRIM(BR17.ENTRY_TITLE) AS ENTRY_TITLE
,       RTRIM(BR17.ENTRY_PLACE) AS ENTRY_PLACE
,       BR17.NUMBER_LIMIT
,       BR17.PLACE_LIMIT
,       RTRIM(BR17.NOTE) AS NOTE
,       BR18EXEDT.FROM_DT AS EXEC_DT
,       BR18ENTRY.FROM_DT AS ENTRY_FROM
,       BR18ENTRY.TO_DT AS ENTRY_TO
,       BR18DISP.FROM_DT AS DISP_FROM
,       BR18DISP.TO_DT AS DISP_TO
,       BR18ONER_ENTRY.FROM_DT AS ONER_ENTRY_FROM
,       BR18ONER_ENTRY.TO_DT AS ONER_ENTRY_TO
,       BR18ONER_DISP.FROM_DT AS ONER_DISP_FROM
,       BR18ONER_DISP.TO_DT AS ONER_DISP_TO
,       RTRIM(BR51.NOTICE1) AS NOTICE1

FROM BR17ENTL BR17
,    BR51ENCI BR51
,    (SELECT ENTRY_YEAR, ENTRY_KAI, FROM_DT, TO_DT 
      FROM BR18ENTD 
      WHERE ENTRY_CD = /*entryCd*/'25' AND ENTRY_YEAR >= /*sysLastNendo*/'2005' 
      AND   USERTYPE_CD = '99' AND DAY_KBN = '01') BR18EXEDT
,    (SELECT ENTRY_YEAR, ENTRY_KAI, FROM_DT, TO_DT 
      FROM BR18ENTD 
      WHERE ENTRY_CD = /*entryCd*/'25' AND ENTRY_YEAR >= /*sysLastNendo*/'2005' 
      AND USERTYPE_CD = '01' AND DAY_KBN = '04') BR18ENTRY
,    (SELECT ENTRY_YEAR, ENTRY_KAI, FROM_DT, TO_DT 
      FROM BR18ENTD 
      WHERE ENTRY_CD = /*entryCd*/'25' AND ENTRY_YEAR >= /*sysLastNendo*/'2005' 
      AND USERTYPE_CD = '01' AND DAY_KBN = '03') BR18DISP
,    (SELECT ENTRY_YEAR, ENTRY_KAI, FROM_DT, TO_DT 
      FROM BR18ENTD 
      WHERE ENTRY_CD = /*entryCd*/'25' AND ENTRY_YEAR >= /*sysLastNendo*/'2005' 
      AND USERTYPE_CD = '02' AND DAY_KBN = '04') BR18ONER_ENTRY
,    (SELECT ENTRY_YEAR, ENTRY_KAI, FROM_DT, TO_DT 
      FROM BR18ENTD 
      WHERE ENTRY_CD = /*entryCd*/'25' AND ENTRY_YEAR >= /*sysLastNendo*/'2005' 
      AND USERTYPE_CD = '02' AND DAY_KBN = '03') BR18ONER_DISP

WHERE BR17.ENTRY_CD        = /*entryCd*/'25'
AND   BR17.ENTRY_YEAR      >= /*sysLastNendo*/'2005'
AND   BR17.SAKUJO_FLG      <> '1'
AND   BR51.ENTRY_CD        = BR17.ENTRY_CD
AND   BR51.ENTRY_YEAR      = BR17.ENTRY_YEAR
AND   BR18EXEDT.ENTRY_YEAR = BR51.ENTRY_YEAR
AND   BR18ENTRY.ENTRY_YEAR = BR18EXEDT.ENTRY_YEAR
AND   BR18DISP.ENTRY_YEAR  = BR18ENTRY.ENTRY_YEAR
AND   BR18ONER_ENTRY.ENTRY_YEAR = BR18EXEDT.ENTRY_YEAR
AND   BR18ONER_DISP.ENTRY_YEAR = BR18ENTRY.ENTRY_YEAR
AND   BR51.ENTRY_KAI       = BR17.ENTRY_KAI
AND   BR18EXEDT.ENTRY_KAI  = BR51.ENTRY_KAI
AND   BR18ENTRY.ENTRY_KAI  = BR18EXEDT.ENTRY_KAI
AND   BR18ONER_DISP.ENTRY_KAI = BR18ENTRY.ENTRY_KAI
AND   BR18ONER_ENTRY.ENTRY_KAI = BR18EXEDT.ENTRY_KAI
AND   BR18DISP.ENTRY_KAI = BR18ENTRY.ENTRY_KAI

ORDER BY EXEC_DT DESC
,        BR17.ENTRY_YEAR DESC
,        BR17.ENTRY_KAI DESC