SELECT DISTINCT MISE_CD
   ,            COMPANY_CD
   ,			RTRIM(CHAR(REPLACE(MISE_NAME_KJ , '  ', '  '), 40)) as MISE_NAME_KJ 
FROM   BM01TENM 
WHERE ONER_CD = /*onerCd*/'36001' 
AND COMPANY_CD = /*companyCd*/'00'
AND CLOSE_DT >= /*sysDate*/'20060507'
ORDER BY MISE_CD
