SELECT DISTINCT MISE_CD
   ,            COMPANY_CD
   ,			RTRIM(CHAR(REPLACE(MISE_NAME_KJ , '  ', '  '), 40)) as MISE_NAME_KJ 
FROM   BM01TENM 
WHERE COMPANY_CD = /*companyCd*/'00'
AND MISE_CD  = /*miseCd*/'02001'
ORDER BY MISE_CD
