select
	rtrim(BM21.COMPANY_CD) as COMPANY_CD,
	rtrim(BM21.MISE_CD) as MISE_CD,
	rtrim(BM21.MISE_LEASE_SHU) as MISE_LEASE_SHU,
	rtrim(BC18.MISE_LEASE_NAME) as MISE_LEASE_NAME,
	rtrim(BM21.MISE_LEASE_START) as MISE_LEASE_START,
	rtrim(BM21.MISE_LEASE_END) as MISE_LEASE_END,
	rtrim(BM21.FIRST_USER) as FIRST_USER,
	rtrim(BM21.FIRST_PGM) as FIRST_PGM,
	BM21.FIRST_TMSP,
	rtrim(BM21.LAST_USER) as LAST_USER,
	rtrim(BM21.LAST_PGM) as LAST_PGM,
	BM21.LAST_TMSP
	
from
	BM21CHIT BM21,
	BC18CHIT BC18 
where
	BM21.COMPANY_CD = BC18.COMPANY_CD
and BM21.MISE_LEASE_SHU = BC18.MISE_LEASE_SHU
and	BM21.COMPANY_CD = /*companyCd*/'01'
and BM21.MISE_CD = /*miseCd*/'01776' 
order by 
	BM21.MISE_LEASE_SHU,
	BM21.MISE_LEASE_START