select
	rtrim(COMPANY_CD) as COMPANY_CD,
	rtrim(MISE_CD) as MISE_CD,
	rtrim(EMERGENCE_TEL1) as EMERGENCE_TEL1,
	rtrim(EMERGENCE_TEL2) as EMERGENCE_TEL2,
	rtrim(EMERGENCE_TEL3) as EMERGENCE_TEL3,
	rtrim(EMERGENCE_NAME1) as EMERGENCE_NAME1,
	rtrim(EMERGENCE_NAME2) as EMERGENCE_NAME2,
	rtrim(EMERGENCE_NAME3) as EMERGENCE_NAME3,
	rtrim(YOBI_FREE_1) as YOBI_FREE_1,
	rtrim(YOBI_FREE_2) as YOBI_FREE_2,
	rtrim(YOBI_FREE_3) as YOBI_FREE_3,
	rtrim(YOBI_FREE_4) as YOBI_FREE_4,
	rtrim(YOBI_FREE_5) as YOBI_FREE_5,
	rtrim(FIRST_USER) as FIRST_USER,
	rtrim(FIRST_PGM) as FIRST_PGM,
	FIRST_TMSP,
	rtrim(LAST_USER) as LAST_USER,
	rtrim(LAST_PGM) as LAST_PGM,
	LAST_TMSP
from
	BM23MIYO BM23
where
	COMPANY_CD = /*companyCd*/'01'
and MISE_CD = /*miseCd*/'01776' 
