SELECT
	CLOSE_DT , MISE_CD , MISE_NAME_KJ , COMPANY_CD
FROM
	(SELECT DISTINCT  MISE_CD
	   , 			MISE_NAME_KJ
	   ,            COMPANY_CD
	   ,            CLOSE_DT
	FROM   BM01TENM
	WHERE ONER_CD = /*onerCd*/'36001'
	AND COMPANY_CD = /*companyCd*/'00'
	ORDER BY MISE_CD) as TBL
ORDER BY CLOSE_DT DESC, MISE_CD

