SELECT BT15.INFO_SHU
,      BT15.REG_DATE
,      BT15.SEQ
,      BT15.GYOTAI_KBN
,      BT15.COMPANY_CD
,      BT15.KOBETSU_CD
,      BM10.SIBU_NAME AS KOBETSU_NAME
FROM (
	SELECT BT15.INFO_SHU
	,      BT15.REG_DATE
	,      BT15.SEQ
	,      BT14.GYOTAI_KBN
	,      BM04.COMPANY_CD
	,      RTRIM(BT15.KOBETSU_CD) AS KOBETSU_CD
	FROM (SELECT * FROM BT14IAGT WHERE INFO_SHU='02' AND DATE(LAST_TMSP) = /*lastTmspDt*/'2009-10-01' AND KOBETSU_FLG = '1') BT14
	,    (SELECT * FROM BT15IAID WHERE INFO_SHU='02' AND DATE(LAST_TMSP) = /*lastTmspDt*/'2009-10-01') BT15
	,    BM04GTCP BM04
	WHERE BT15.INFO_SHU = BT14.INFO_SHU
	AND   BT15.REG_DATE = BT14.REG_DATE
	AND   BT15.SEQ      = BT14.SEQ
	AND   BT14.GYOTAI_KBN = BM04.GYOTAI_KBN
	AND   BT15.GYOTAI_KBN = BT14.GYOTAI_KBN
	GROUP BY BT15.INFO_SHU
	,        BT15.REG_DATE
	,        BT15.SEQ
	,        BT14.GYOTAI_KBN
	,        BM04.COMPANY_CD
	,        RTRIM(BT15.KOBETSU_CD)
) BT15
LEFT JOIN BM10GSIB BM10
      ON (BM10.AREA_DAI_FLG = '1'
          AND  BM10.COMPANY_CD = BT15.COMPANY_CD
          AND  BM10.SIBU_CD = BT15.KOBETSU_CD)

GROUP BY BT15.INFO_SHU
,      BT15.REG_DATE
,      BT15.SEQ
,      BT15.GYOTAI_KBN
,      BT15.COMPANY_CD
,      BT15.KOBETSU_CD
,      BM10.SIBU_NAME

ORDER BY BT15.INFO_SHU
,      BT15.REG_DATE
,      BT15.SEQ
,      BT15.COMPANY_CD
,      BT15.KOBETSU_CD
,      BT15.GYOTAI_KBN
