SELECT MAIN.REG_DATE
,      MAIN.SEQ
,      MAIN.CATE_ID
,      MAIN.CATE_NAME
,      MAIN.KANRI_NO
,      MAIN.FILE_NAME
,      MAIN.TITLE
,      MAIN.SUB_TITLE
,      MAIN.ATTACH_NAME1
,      MAIN.ATTACH_NAME2
,      MAIN.ATTACH_NAME3
,      MAIN.ATTACH_FL1
,      MAIN.ATTACH_FL2
,      MAIN.ATTACH_FL3
,      CASE WHEN MAIN.KOBETU_FLG = 1 THEN '—L' ELSE '–³' END AS KOBETSU_UMU
,      CASE WHEN MAIN.MISE_FLG = 1 THEN '—L' ELSE '–³' END AS MISE_UMU
,      MAIN.PUB_DATE
,      MAIN.PUB_USER
,      MAIN.PUB_ORG
,      MAIN.PUB_ORG_NAME
,      MAIN.R_COMPANY_CD
,      MAIN.SAKUJO_FLG
,      MAIN.GYOTAI_KBN
,      MAIN.GYOTAI_KBN_NAME
,      BT16.KOTEN_CNT
,      MAIN.FIRST_TMSP
,      MAIN.LAST_TMSP

FROM (
select BT02.REG_DATE
,      BT02.SEQ
,      BT02.CATE_ID
,      rtrim(BM02.CATE_NAME) CATE_NAME
,      rtrim(BT02.KANRI_NO) KANRI_NO
,      rtrim(BT02.FILE_NAME) FILE_NAME
,      rtrim(BT02.TITLE) TITLE
,      rtrim(BT02.SUB_TITLE) SUB_TITLE
,      rtrim(BT02.ATTACH_NAME1) ATTACH_NAME1
,      rtrim(BT02.ATTACH_NAME2) ATTACH_NAME2
,      rtrim(BT02.ATTACH_NAME3) ATTACH_NAME3
,      rtrim(BT02.ATTACH_FL1) ATTACH_FL1
,      rtrim(BT02.ATTACH_FL2) ATTACH_FL2
,      rtrim(BT02.ATTACH_FL3) ATTACH_FL3
,      BT14.GYOTAI_KBN
,      BC09.GYOTAI_KBN_NAME
,      MAX(CASE WHEN BT14.KOBETSU_FLG ='1' THEN 1 ELSE 0 END) KOBETU_FLG
,      MAX(CASE WHEN BT14.MISE_FLG ='1' THEN 1 ELSE 0 END) MISE_FLG
,      BT02.PUB_DATE
,      BT02.PUB_USER
,      BT02.PUB_ORG
,      rtrim(BT02.PUB_ORG_NAME) PUB_ORG_NAME
,      BT02.R_COMPANY_CD
,      BT02.SAKUJO_FLG
,      BT02.FIRST_TMSP
,      BT02.LAST_TMSP

FROM (SELECT * FROM BT02NTCM WHERE DATE(LAST_TMSP) = /*lastTmspDt*/'2010-03-02') AS BT02
LEFT JOIN (SELECT * FROM BT12IACP WHERE DATE(LAST_TMSP) = /*lastTmspDt*/'2010-03-02' AND INFO_SHU='02') as BT12
ON (BT02.REG_DATE = BT12.REG_DATE AND BT02.SEQ      = BT12.SEQ)
LEFT JOIN (SELECT * FROM BT13IASZ WHERE DATE(LAST_TMSP) = /*lastTmspDt*/'2010-03-02' AND INFO_SHU='02') as BT13
ON (BT02.REG_DATE = BT13.REG_DATE AND BT02.SEQ      = BT13.SEQ)
LEFT JOIN (SELECT * FROM BT14IAGT WHERE DATE(LAST_TMSP) = /*lastTmspDt*/'2010-03-02' AND INFO_SHU='02') as BT14
ON (BT02.REG_DATE = BT14.REG_DATE AND BT02.SEQ      = BT14.SEQ)
LEFT JOIN BC09GTAI BC09 ON (BT14.GYOTAI_KBN = BC09.GYOTAI_KBN)
,    BM02IFCT BM02

WHERE BM02.INFO_SHU='02'
AND   BM02.INFO_SHU = BM02.INFO_SHU
AND   BT02.CATE_ID  = BM02.CATE_ID

GROUP BY BT02.REG_DATE
,        BT02.SEQ
,        BT02.CATE_ID
,        rtrim(BM02.CATE_NAME)
,        rtrim(BT02.KANRI_NO)
,        rtrim(BT02.FILE_NAME)
,        rtrim(BT02.TITLE)
,        rtrim(BT02.SUB_TITLE)
,        rtrim(BT02.ATTACH_NAME1)
,        rtrim(BT02.ATTACH_NAME2)
,        rtrim(BT02.ATTACH_NAME3)
,        rtrim(BT02.ATTACH_FL1)
,        rtrim(BT02.ATTACH_FL2)
,        rtrim(BT02.ATTACH_FL3)
,        BT14.GYOTAI_KBN
,        BC09.GYOTAI_KBN_NAME
,        BT02.PUB_DATE
,        BT02.PUB_USER
,        BT02.PUB_ORG
,        rtrim(BT02.PUB_ORG_NAME)
,        BT02.R_COMPANY_CD
,        BT02.SAKUJO_FLG
,        BT02.FIRST_TMSP
,        BT02.LAST_TMSP
) MAIN
LEFT JOIN (
SELECT BT16.REG_DATE
	   ,      BT16.SEQ
       ,      BT14.GYOTAI_KBN
	   ,      BC09.GYOTAI_KBN_NAME
	   ,      COUNT(DISTINCT BT16.MISE_CD) AS KOTEN_CNT
	   FROM BM01TENM BM01
       ,    BM04GTCP BM04
	   ,    BC09GTAI BC09
       ,    (SELECT * FROM BT14IAGT
	         WHERE INFO_SHU='02'
             AND   MISE_FLG = '1'
	         AND DATE(LAST_TMSP) = /*lastTmspDt*/'2010-03-02') as BT14
	   ,    (SELECT * FROM BT16IAST
             WHERE INFO_SHU='02'
             AND  DATE(LAST_TMSP) = /*lastTmspDt*/'2010-03-02') BT16

       WHERE BM04.COMPANY_CD = BM01.COMPANY_CD
       AND   BM04.GYOTAI_KBN = BM01.MISE_GRP1
       AND   BT14.GYOTAI_KBN = BM04.GYOTAI_KBN
       AND   BT16.REG_DATE   = BT14.REG_DATE
       AND   BT16.SEQ        = BT14.SEQ
       AND   BT16.GYOTAI_KBN = BT14.GYOTAI_KBN
       AND   BT16.MISE_CD    = BM01.MISE_CD
       AND   BC09.GYOTAI_KBN = BT14.GYOTAI_KBN
       GROUP BY BT16.REG_DATE
	   ,        BT16.SEQ
       ,      BT14.GYOTAI_KBN
	   ,      BC09.GYOTAI_KBN_NAME
) as BT16 on (BT16.REG_DATE = MAIN.REG_DATE
                AND BT16.SEQ = MAIN.SEQ
                  AND BT16.GYOTAI_KBN= MAIN.GYOTAI_KBN)
ORDER BY MAIN.PUB_DATE desc
,        MAIN.KANRI_NO
,        MAIN.REG_DATE
,        MAIN.SEQ
,        MAIN.R_COMPANY_CD
,        MAIN.GYOTAI_KBN