SELECT 
     BUNSEKI_KBN  
   , CHAR( REPLACE(LTRIM( RTRIM( CHAR( REPLACE( BUNSEKI_NAME  , '  ', '  '), 60 ) ) ) , '  ', '  '), 60 ) as BUNSEKI_NAME 
  FROM BC25MSPS  WHERE BUNSEKI_NAME<>'' 
  AND BUNSEKI_KBN IN ('02') 
 ORDER BY BUNSEKI_KBN 