select
    BR17.ENTRY_CD,
    BR17.ENTRY_YEAR,
    BR17.ENTRY_KAI,
    rtrim(BR17.ENTRY_TITLE) as ENTRY_TITLE,
    rtrim(BR17.ENTRY_PLACE) as ENTRY_PLACE,
    BR17.NUMBER_LIMIT,
    BR17.PLACE_LIMIT,
    rtrim(BR17.NOTE) as NOTE,
    BR17.SPARE_FLG1,
    BR17.SPARE_FLG2,
    BR17.SAKUJO_FLG,
    BR17.FIRST_USER,
    BR17.FIRST_PGM,
    BR17.FIRST_TMSP,
    BR17.LAST_USER,
    BR17.LAST_PGM,
    BR17.LAST_TMSP,
    BASIC.FROM_DT as BASIC_FROM_DT,
    BASIC.TO_DT as BASIC_TO_DT,
    VISIT.FROM_DT as VISIT_FROM_DT,
    VISIT.TO_DT as VISIT_TO_DT,
    DISPLAYHEAD.FROM_DT as DISPLAYHEAD_FROM_DT,
    DISPLAYHEAD.TO_DT as DISPLAYHEAD_TO_DT,
    DISPLAYONER.FROM_DT as DISPLAYONER_FROM_DT,
    DISPLAYONER.TO_DT as DISPLAYONER_TO_DT,
    APPLYHEAD.FROM_DT as APPLYHEAD_FROM_DT,
    APPLYHEAD.TO_DT as APPLYHEAD_TO_DT,
    APPLYONER.FROM_DT as APPLYONER_FROM_DT,
    APPLYONER.TO_DT as APPLYONER_TO_DT,
    RESULT.FROM_DT as RESULT_FROM_DT,
    RESULT.TO_DT as RESULT_TO_DT
from
    BR17ENTL as BR17
    left outer join BR18ENTD as BASIC on BR17.ENTRY_CD = BASIC.ENTRY_CD and BR17.ENTRY_YEAR = BASIC.ENTRY_YEAR and BR17.ENTRY_KAI = BASIC.ENTRY_KAI and BASIC.USERTYPE_CD = '99' and BASIC.DAY_KBN = '01'
    left outer join BR18ENTD as VISIT on BR17.ENTRY_CD = VISIT.ENTRY_CD and BR17.ENTRY_YEAR = VISIT.ENTRY_YEAR and BR17.ENTRY_KAI = VISIT.ENTRY_KAI and VISIT.USERTYPE_CD = '99' and VISIT.DAY_KBN = '02'
    left outer join BR18ENTD as DISPLAYHEAD on BR17.ENTRY_CD = DISPLAYHEAD.ENTRY_CD and BR17.ENTRY_YEAR = DISPLAYHEAD.ENTRY_YEAR and BR17.ENTRY_KAI = DISPLAYHEAD.ENTRY_KAI and DISPLAYHEAD.USERTYPE_CD = '01' and DISPLAYHEAD.DAY_KBN = '03'
    left outer join BR18ENTD as DISPLAYONER on BR17.ENTRY_CD = DISPLAYONER.ENTRY_CD and BR17.ENTRY_YEAR = DISPLAYONER.ENTRY_YEAR and BR17.ENTRY_KAI = DISPLAYONER.ENTRY_KAI and DISPLAYONER.USERTYPE_CD = '02' and DISPLAYONER.DAY_KBN = '03'
    left outer join BR18ENTD as APPLYHEAD on BR17.ENTRY_CD = APPLYHEAD.ENTRY_CD and BR17.ENTRY_YEAR = APPLYHEAD.ENTRY_YEAR and BR17.ENTRY_KAI = APPLYHEAD.ENTRY_KAI and APPLYHEAD.USERTYPE_CD = '01' and APPLYHEAD.DAY_KBN = '04'
    left outer join BR18ENTD as APPLYONER on BR17.ENTRY_CD = APPLYONER.ENTRY_CD and BR17.ENTRY_YEAR = APPLYONER.ENTRY_YEAR and BR17.ENTRY_KAI = APPLYONER.ENTRY_KAI and APPLYONER.USERTYPE_CD = '02' and APPLYONER.DAY_KBN = '04'
    left outer join BR18ENTD as RESULT on BR17.ENTRY_CD = RESULT.ENTRY_CD and BR17.ENTRY_YEAR = RESULT.ENTRY_YEAR and BR17.ENTRY_KAI = RESULT.ENTRY_KAI and RESULT.USERTYPE_CD = '01' and RESULT.DAY_KBN = '06'
where
    BR17.ENTRY_CD = /*entryCd*/'01' and
    BR17.SAKUJO_FLG <> '1' and
    substr(BASIC.FROM_DT, 1, 4) >= /*fromYear*/'2005' 
order by
    APPLYONER_FROM_DT desc,
    BR17.ENTRY_YEAR desc,
    BR17.ENTRY_KAI desc
