SELECT (CASE WHEN BT4YOSAN.YOSAN_DT IS NULL THEN BD36.EIGYO_DT ELSE BT4YOSAN.YOSAN_DT END) AS EIGYO_DT 
,      (CASE WHEN BD36.URIAGE IS NULL THEN 0 ELSE BD36.URIAGE END) AS URIAGE
,      (CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END) AS YOSAN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.EIGYO_DAYS END) AS EIGYO_DAYS
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.URIAGE_ZEN END) AS URIAGE_ZEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.EIGYO_DAYS_ZEN END) AS EIGYO_DAYS_ZEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.KYAKUSU END) AS KYAKUSU
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.KYAKUSU_ZEN END) AS KYAKUSU_ZEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.CHARGE_KIN_CANCEL END) AS CHARGE_KIN_CANCEL
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.CHARGE_KEN_CANCEL END) AS CHARGE_KEN_CANCEL
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.USE_KIN_CANCEL END) AS USE_KIN_CANCEL
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.USE_KEN_CANCEL END) AS USE_KEN_CANCEL
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.BONUS_V_ISSUE END) AS BONUS_V_ISSUE
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.BONUS_V_USE END) AS BONUS_V_USE
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.COUPON_V_ISSUE END) AS COUPON_V_ISSUE
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.COUPON_V_USE END) AS COUPON_V_USE
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ZANDAKA END) AS ZANDAKA
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ISSUE_CNT END)  AS ISSUE_CNT
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.CHARGE_KIN END) AS CHARGE_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.CHARGE_KEN END) AS CHARGE_KEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.KESSAI_KIN END) AS KESSAI_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.KESSAI_KEN END) AS KESSAI_KEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ZEN_ISSUE_CNT END)  AS ZEN_ISSUE_CNT
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ZEN_CHARGE_KIN END) AS ZEN_CHARGE_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ZEN_CHARGE_KEN END) AS ZEN_CHARGE_KEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ZEN_KESSAI_KIN END) AS ZEN_KESSAI_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.ZEN_KESSAI_KEN END) AS ZEN_KESSAI_KEN
/*IF paramsDto.selectHosei */
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_URIAGE END) AS NET_URIAGE
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_EIGYO_DAYS END) AS NET_EIGYO_DAYS
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_URIAGE END) AS NET_URIAGE_ZEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_EIGYO_DAYS END) AS NET_EIGYO_DAYS_ZEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_KYAKUSU END) AS NET_KYAKUSU
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_KYAKUSU END) AS NET_KYAKUSU_ZEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ISSUE_CNT END) AS NET_ISSUE_CNT
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_CHARGE_KIN END) AS NET_CHARGE_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_CHARGE_KEN END) AS NET_CHARGE_KEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_KESSAI_KIN END) AS NET_KESSAI_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_KESSAI_KEN END) AS NET_KESSAI_KEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_ISSUE_CNT END) AS NET_ZEN_ISSUE_CNT
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_CHARGE_KIN END) AS NET_ZEN_CHARGE_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_CHARGE_KEN END) AS NET_ZEN_CHARGE_KEN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_KESSAI_KIN END) AS NET_ZEN_KESSAI_KIN
,      (CASE WHEN BD36.EIGYO_DT IS NULL THEN 0 ELSE BD36.HOSEI_ZEN_KESSAI_KEN END) AS NET_ZEN_KESSAI_KEN
/*END*/
from (SELECT YOSANTBL.YOSAN_DT
      ,      SUM(YOSANTBL.YOSAN) AS YOSAN
      FROM   (SELECT BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */
            ,      BM01.MISE_CD 
/*END*/
            FROM BM01TENM BM01
            WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF paramsDto.taishoJoken.equals("MISE") */  
            AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
	/*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM10GSIB BM10
                          WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM10./*$paramsDto.taishoJoken*/'SIBU'_CD = /*paramsDto.hyojiTaisho*/'031'
		/*IF "SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd */  
                          AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
		/*END*/
                          AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
	/*END*/
	/*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM09GTSG BM09
                          WHERE SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                          AND BM09.GYOTAI_KBN = BM01.GYOTAI_KBN)
	/*END*/
	/*IF birdUserInfo.limit*/
            AND EXISTS (SELECT * FROM BM51SVSB AS BM51
                          WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM51.SV_CD      = /*birdUserInfo.userID*/'00000921'
                          AND   BM51.SIBU_CD    = BM01.SIBU_CD)
	/*END*/
/*END*/
/*IF (("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken))==false */
        GROUP BY BM01.SIBU_CD
/*END*/
     ) BM01
,    BT44MSJY YOSANTBL
      WHERE YOSANTBL.YOSAN_DT BETWEEN /*kikanFrom*/'201203' AND /*kikanTo*/'201304'
      AND   YOSANTBL.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "1".equals(paramsDto.tenpoShubetu) || "3".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU = /*paramsDto.tenpoShubetu*/'1'
/*END*/
/*IF "2".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU IN ('1', '2')
/*END*/
      AND   YOSANTBL.SIBU_CD = BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.blockCd != null) || "MISE".equals(paramsDto.taishoJoken) */
      AND   YOSANTBL.MISE_CD = BM01.MISE_CD
/*END*/
      
/*END*/
      group by YOSANTBL.YOSAN_DT
      ) BT4YOSAN
FULL OUTER JOIN    (
      SELECT SUB.EIGYO_DT
      ,      SUM(ZANDAKA) AS ZANDAKA
      ,      SUM(URIAGE) AS URIAGE
      ,      SUM(ONER_YOSAN) AS ONER_YOSAN
      ,      SUM(EIGYO_DAYS) AS EIGYO_DAYS
      ,      SUM(URIAGE_ZEN) AS URIAGE_ZEN
      ,      SUM(EIGYO_DAYS_ZEN) AS EIGYO_DAYS_ZEN
      ,      SUM(KYAKUSU) AS KYAKUSU
      ,      SUM(KYAKUSU_ZEN) AS KYAKUSU_ZEN
      ,      SUM(CHARGE_KIN_CANCEL) AS CHARGE_KIN_CANCEL
      ,      SUM(CHARGE_KEN_CANCEL) AS CHARGE_KEN_CANCEL
      ,      SUM(USE_KIN_CANCEL) AS USE_KIN_CANCEL
      ,      SUM(USE_KEN_CANCEL) AS USE_KEN_CANCEL
      ,      SUM(BONUS_V_ISSUE) AS BONUS_V_ISSUE
      ,      SUM(BONUS_V_USE) AS BONUS_V_USE
      ,      SUM(COUPON_V_ISSUE) AS COUPON_V_ISSUE
      ,      SUM(COUPON_V_USE) AS COUPON_V_USE
      ,      SUM(ISSUE_CNT) AS ISSUE_CNT
      ,      SUM(CHARGE_KIN) AS CHARGE_KIN
      ,      SUM(CHARGE_KEN) AS CHARGE_KEN
      ,      SUM(KESSAI_KIN) AS KESSAI_KIN
      ,      SUM(KESSAI_KEN) AS KESSAI_KEN	
      ,      SUM(ZEN_ISSUE_CNT) AS ZEN_ISSUE_CNT
      ,      SUM(ZEN_CHARGE_KIN) AS ZEN_CHARGE_KIN
      ,      SUM(ZEN_CHARGE_KEN) AS ZEN_CHARGE_KEN
      ,      SUM(ZEN_KESSAI_KIN) AS ZEN_KESSAI_KIN
      ,      SUM(ZEN_KESSAI_KEN) AS ZEN_KESSAI_KEN	
/*IF paramsDto.selectHosei */
      ,      SUM(HOSEI_URIAGE)         AS HOSEI_URIAGE
      ,      SUM(HOSEI_ONER_YOSAN)     AS HOSEI_ONER_YOSAN
      ,      SUM(HOSEI_EIGYO_DAYS)     AS HOSEI_EIGYO_DAYS
      ,      SUM(HOSEI_ZEN_URIAGE)     AS HOSEI_ZEN_URIAGE
      ,      SUM(HOSEI_ZEN_EIGYO_DAYS) AS HOSEI_ZEN_EIGYO_DAYS
      ,      SUM(HOSEI_KYAKUSU)        AS HOSEI_KYAKUSU
      ,      SUM(HOSEI_ZEN_KYAKUSU)    AS HOSEI_ZEN_KYAKUSU
      ,      SUM(HOSEI_CHARGE_KIN_CANCEL) AS HOSEI_CHARGE_KIN_CANCEL
      ,      SUM(HOSEI_CHARGE_KEN_CANCEL) AS HOSEI_CHARGE_KEN_CANCEL
      ,      SUM(HOSEI_USE_KIN_CANCEL)    AS HOSEI_USE_KIN_CANCEL
      ,      SUM(HOSEI_USE_KEN_CANCEL)    AS HOSEI_USE_KEN_CANCEL
      ,      SUM(HOSEI_BONUS_V_ISSUE)     AS HOSEI_BONUS_V_ISSUE
      ,      SUM(HOSEI_BONUS_V_USE)       AS HOSEI_BONUS_V_USE
      ,      SUM(HOSEI_COUPON_V_ISSUE)    AS HOSEI_COUPON_V_ISSUE
      ,      SUM(HOSEI_COUPON_V_USE)      AS HOSEI_COUPON_V_USE
      ,      SUM(HOSEI_ISSUE_CNT)  AS HOSEI_ISSUE_CNT
      ,      SUM(HOSEI_CHARGE_KIN) AS HOSEI_CHARGE_KIN
      ,      SUM(HOSEI_CHARGE_KEN) AS HOSEI_CHARGE_KEN
      ,      SUM(HOSEI_KESSAI_KIN) AS HOSEI_KESSAI_KIN
      ,      SUM(HOSEI_KESSAI_KEN) AS HOSEI_KESSAI_KEN
      ,      SUM(HOSEI_ZEN_ISSUE_CNT)  AS HOSEI_ZEN_ISSUE_CNT
      ,      SUM(HOSEI_ZEN_CHARGE_KIN) AS HOSEI_ZEN_CHARGE_KIN
      ,      SUM(HOSEI_ZEN_CHARGE_KEN) AS HOSEI_ZEN_CHARGE_KEN
      ,      SUM(HOSEI_ZEN_KESSAI_KIN) AS HOSEI_ZEN_KESSAI_KIN
      ,      SUM(HOSEI_ZEN_KESSAI_KEN) AS HOSEI_ZEN_KESSAI_KEN
/*END*/
      FROM ( 
 
      SELECT BD36.EIGYO_DT
      ,      BD36.MISE_CD
      ,      MAX(CASE WHEN BD36.OPEN_KBN = 1 THEN BD36./*$zdsColmunName*/'DOGETU'_ZANDAKA ELSE null END) AS ZANDAKA
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_URIAGE) AS URIAGE
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ONER_YOSAN) AS ONER_YOSAN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_EIGYO_DAYS) AS EIGYO_DAYS
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_URIAGE) AS URIAGE_ZEN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_EIGYO_DAYS) AS EIGYO_DAYS_ZEN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_KYAKUSU) AS KYAKUSU
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_KYAKUSU) AS KYAKUSU_ZEN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_CHARGE_KIN_CANCEL) AS CHARGE_KIN_CANCEL
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_CHARGE_KEN_CANCEL) AS CHARGE_KEN_CANCEL
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_USE_KIN_CANCEL) AS USE_KIN_CANCEL
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_USE_KEN_CANCEL) AS USE_KEN_CANCEL
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_BONUS_V_ISSUE) AS BONUS_V_ISSUE
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_BONUS_V_USE) AS BONUS_V_USE
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_COUPON_V_ISSUE) AS COUPON_V_ISSUE
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_COUPON_V_USE) AS COUPON_V_USE
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ISSUE_CNT) AS ISSUE_CNT
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_CHARGE_KIN) AS CHARGE_KIN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_CHARGE_KEN) AS CHARGE_KEN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_KESSAI_KIN) AS KESSAI_KIN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_KESSAI_KEN) AS KESSAI_KEN	
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_ISSUE_CNT) AS ZEN_ISSUE_CNT
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_CHARGE_KIN) AS ZEN_CHARGE_KIN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_CHARGE_KEN) AS ZEN_CHARGE_KEN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_KESSAI_KIN) AS ZEN_KESSAI_KIN
      ,      SUM(BD36./*$zdsColmunName*/'DOGETU'_ZEN_KESSAI_KEN) AS ZEN_KESSAI_KEN	
/*IF paramsDto.selectHosei */
      ,      SUM(BD36.HOSEI_URIAGE)         AS HOSEI_URIAGE
      ,      SUM(BD36.HOSEI_ONER_YOSAN)     AS HOSEI_ONER_YOSAN
      ,      SUM(BD36.HOSEI_EIGYO_DAYS)     AS HOSEI_EIGYO_DAYS
      ,      SUM(BD36.HOSEI_ZEN_URIAGE)     AS HOSEI_ZEN_URIAGE
      ,      SUM(BD36.HOSEI_ZEN_EIGYO_DAYS) AS HOSEI_ZEN_EIGYO_DAYS
      ,      SUM(BD36.HOSEI_KYAKUSU)        AS HOSEI_KYAKUSU
      ,      SUM(BD36.HOSEI_ZEN_KYAKUSU)    AS HOSEI_ZEN_KYAKUSU
      ,      SUM(BD36.HOSEI_CHARGE_KIN_CANCEL) AS HOSEI_CHARGE_KIN_CANCEL
      ,      SUM(BD36.HOSEI_CHARGE_KEN_CANCEL) AS HOSEI_CHARGE_KEN_CANCEL
      ,      SUM(BD36.HOSEI_USE_KIN_CANCEL)    AS HOSEI_USE_KIN_CANCEL
      ,      SUM(BD36.HOSEI_USE_KEN_CANCEL)    AS HOSEI_USE_KEN_CANCEL
      ,      SUM(BD36.HOSEI_BONUS_V_ISSUE)     AS HOSEI_BONUS_V_ISSUE
      ,      SUM(BD36.HOSEI_BONUS_V_USE)       AS HOSEI_BONUS_V_USE
      ,      SUM(BD36.HOSEI_COUPON_V_ISSUE)    AS HOSEI_COUPON_V_ISSUE
      ,      SUM(BD36.HOSEI_COUPON_V_USE)      AS HOSEI_COUPON_V_USE
      ,      SUM(BD36.HOSEI_ISSUE_CNT)  AS HOSEI_ISSUE_CNT
      ,      SUM(BD36.HOSEI_CHARGE_KIN) AS HOSEI_CHARGE_KIN
      ,      SUM(BD36.HOSEI_CHARGE_KEN) AS HOSEI_CHARGE_KEN
      ,      SUM(BD36.HOSEI_KESSAI_KIN) AS HOSEI_KESSAI_KIN
      ,      SUM(BD36.HOSEI_KESSAI_KEN) AS HOSEI_KESSAI_KEN
      ,      SUM(BD36.HOSEI_ZEN_ISSUE_CNT)  AS HOSEI_ZEN_ISSUE_CNT
      ,      SUM(BD36.HOSEI_ZEN_CHARGE_KIN) AS HOSEI_ZEN_CHARGE_KIN
      ,      SUM(BD36.HOSEI_ZEN_CHARGE_KEN) AS HOSEI_ZEN_CHARGE_KEN
      ,      SUM(BD36.HOSEI_ZEN_KESSAI_KIN) AS HOSEI_ZEN_KESSAI_KIN
      ,      SUM(BD36.HOSEI_ZEN_KESSAI_KEN) AS HOSEI_ZEN_KESSAI_KEN
/*END*/

      FROM BD36ZGMC BD36
      WHERE BD36.EIGYO_DT BETWEEN /*kikanFrom*/'201203' AND /*kikanTo*/'201304'
      AND   BD36.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF paramsDto.taishoJoken.equals("MISE") */  
      AND   BD36.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) && "ALL".equals(paramsDto.tenpoShubetu) */
      AND   (BD36.OPEN_KBN + BD36.OPEN_KBN_ZEN)>0
 --ELSE
      AND   BD36.OPEN_KBN  = 1
/*END*/
      AND   BD36.OLDM_FLG = '0'
      AND   EXISTS (
      		SELECT * FROM (
                SELECT COMPANY_CD, MISE_CD FROM BM01TENM BM01
                WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
                AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
	/*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
                AND   EXISTS (SELECT * FROM BM10GSIB BM10
                              WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                              AND   BM10./*$paramsDto.taishoJoken*/'SIBU'_CD = /*paramsDto.hyojiTaisho*/'031'
		/*IF "SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd */  
                              AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
		/*END*/
                              AND   BM10.COMPANY_CD = BM01.COMPANY_CD
                              AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
	/*END*/         
	/*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
                AND   EXISTS (SELECT * FROM BM09GTSG BM09
                              WHERE BM09.SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                              AND   BM09.GYOTAI_KBN   = BM01.GYOTAI_KBN)
	/*END*/
	/*IF birdUserInfo.limit*/
                AND   EXISTS (SELECT * FROM BM51SVSB AS BM51
                              WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                              AND   BM51.SV_CD = /*birdUserInfo.userID*/'00000921'
                              AND   BM51.COMPANY_CD = BM01.COMPANY_CD 
                              AND   BM51.SIBU_CD    = BM01.SIBU_CD)
	/*END*/
	/*IF "ALL".equals(paramsDto.taishoJoken) */
      		UNION ALL 
            SELECT CAST(/*paramsDto.companyCd*/'00' AS CHAR(2)) AS COMPANY_CD, CAST('00000' AS CHAR(5)) AS MISE_CD FROM BM01TENM
	/*END*/
/*END*/
        ) BM01 
        WHERE BD36.MISE_CD    = BM01.MISE_CD)
      GROUP BY BD36.EIGYO_DT
      ,        BD36.MISE_CD
      ) SUB
/*IF "ALL".equals(paramsDto.tenpoShubetu) ==false */
      WHERE EXISTS (
         SELECT * FROM BN01DTEN BN01
         WHERE BN01.COMPANY_CD = /*paramsDto.companyCd*/'00'
		/*IF paramsDto.tenpoShubetu == "2" */
         AND   BN01.KBN1 IN ('1', '2')
		--ELSE
         AND   BN01.KBN1 = /*paramsDto.tenpoShubetu*/'1'
		/*END*/
         AND   SUB.EIGYO_DT   = BN01.EIGYO_YM
         AND   SUB.MISE_CD    = BN01.MISE_CD 
	  )
	/*IF "ALL".equals(paramsDto.taishoJoken) */
		OR SUB.MISE_CD = '00000'
	/*END*/
/*END*/
      GROUP BY SUB.EIGYO_DT
) BD36
ON (BD36.EIGYO_DT = BT4YOSAN.YOSAN_DT)
order by EIGYO_DT
