SELECT BD35.EIGYO_DT
,      SUM(BD35.URIAGE) AS URIAGE
,      SUM(BD35.ONER_YOSAN) AS YOSAN
,      SUM(BD35.EIGYO_DAYS) AS EIGYO_DAYS
,      MAX(BD35.TENKO_KBN) AS TENKO_KBN
,      SUM(BD35.KYAKUSU) AS KYAKUSU
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_URIAGE)    AS URIAGE_ZEN
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_EIGYO_DAYS) AS EIGYO_DAYS_ZEN
,      MAX(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_TENKO_KBN)  AS TENKO_KBN_ZEN
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_KYAKUSU)    AS KYAKUSU_ZEN
,      SUM(BD35.CHARGE_KIN_CANCEL)  AS CHARGE_KIN_CANCEL
,      SUM(BD35.CHARGE_KEN_CANCEL) AS CHARGE_KEN_CANCEL
,      SUM(BD35.USE_KIN_CANCEL) AS USE_KIN_CANCEL
,      SUM(BD35.USE_KEN_CANCEL) AS USE_KEN_CANCEL
,      SUM(BD35.BONUS_V_ISSUE) AS BONUS_V_ISSUE
,      SUM(BD35.BONUS_V_USE)  AS BONUS_V_USE
,      SUM(BD35.COUPON_V_ISSUE) AS COUPON_V_ISSUE
,      SUM(BD35.COUPON_V_USE) AS COUPON_V_USE
,      SUM(BD35.ZANDAKA) AS ZANDAKA
,      SUM(BD35.ISSUE_CNT)  AS ISSUE_CNT
,      SUM(BD35.CHARGE_KIN) AS CHARGE_KIN
,      SUM(BD35.CHARGE_KEN) AS CHARGE_KEN
,      SUM(BD35.KESSAI_KIN) AS KESSAI_KIN
,      SUM(BD35.KESSAI_KEN) AS KESSAI_KEN	
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_ISSUE_CNT)  AS ZEN_ISSUE_CNT
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_CHARGE_KIN) AS ZEN_CHARGE_KIN
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_CHARGE_KEN) AS ZEN_CHARGE_KEN						
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_KESSAI_KIN) AS ZEN_KESSAI_KIN
,      SUM(BD35./*$paramsDto.zennenDataShubetu*/'DOGETU'_ZEN_KESSAI_KEN) AS ZEN_KESSAI_KEN	
FROM BD35ZNMC BD35
WHERE BD35.EIGYO_DT < /*birdDateInfo.sysDate*/'20130507'
AND   BD35.EIGYO_DT BETWEEN /*paramsDto.focusTabFromAddDay*/ AND /*paramsDto.focusTabToAddDay*/
AND   BD35.COMPANY_CD = /*paramsDto.companyCd*/'00'
AND   BD35.OPEN_KBN = 1
AND   BD35.OLDM_FLG = '0'
AND   EXISTS (SELECT * FROM BM01TENM BM01
              WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
              AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'00108'
--ELSE
              AND   BM01.ONER_CD    = /*paramsDto.hyojiTaisho*/'37006'
/*END*/
              AND   BM01.COMPANY_CD = BD35.COMPANY_CD
              AND   BM01.MISE_CD    = BD35.MISE_CD
)
GROUP BY BD35.EIGYO_DT
ORDER BY EIGYO_DT