SELECT (CASE WHEN BT4YOSAN.YOSAN_DT IS NOT NULL THEN BT4YOSAN.YOSAN_DT ELSE BD54.EIGYO_DT END) AS EIGYO_DT 
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE END) AS URIAGE
,      (CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END) AS YOSAN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.TENKO_KBN END) AS TENKO_KBN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_ZEN END) AS URIAGE_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.TENKO_KBN_ZEN END) AS TENKO_KBN_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU END)  AS KYAKUSU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_ZEN END)  AS KYAKUSU_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.MISECNT_KBN_NSUM END)  AS MISECNT_KBN_NSUM
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_NSUM END)  AS URIAGE_NSUM
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_NSUM_ZEN END) AS URIAGE_NSUM_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_NSUM END) AS KYAKUSU_NSUM
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_NSUM_ZEN END) AS KYAKUSU_NSUM_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.MISECNT_KBN_NTAKE END) AS MISECNT_KBN_NTAKE
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_NTAKE END) AS URIAGE_NTAKE
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_NTAKE_ZEN END) AS URIAGE_NTAKE_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_NTAKE END) AS KYAKUSU_NTAKE
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_NTAKE_ZEN END) AS KYAKUSU_NTAKE_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.MISECNT_KBN_NTAKU END) AS MISECNT_KBN_NTAKU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_NTAKU END) AS URIAGE_NTAKU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.URIAGE_NTAKU_ZEN END) AS URIAGE_NTAKU_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_NTAKU END) AS KYAKUSU_NTAKU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.KYAKUSU_NTAKU_ZEN END) AS KYAKUSU_NTAKU_ZEN
/*IF paramsDto.selectHosei==true */
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE END) AS NET_URIAGE
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_ZEN END) AS NET_URIAGE_ZEN      
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU END) AS NET_KYAKUSU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_ZEN END) AS NET_KYAKUSU_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_NSUM END) AS NET_URIAGE_NSUM
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_NSUM_ZEN END) AS NET_URIAGE_NSUM_ZEN      
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_NSUM END) AS NET_KYAKUSU_NSUM
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_NSUM_ZEN END) AS NET_KYAKUSU_NSUM_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_NTAKE END) AS NET_URIAGE_NTAKE
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_NTAKE_ZEN END) AS NET_URIAGE_NTAKE_ZEN      
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_NTAKE END) AS NET_KYAKUSU_NTAKE
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_NTAKE_ZEN END) AS NET_KYAKUSU_NTAKE_ZEN
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_NTAKU END) AS NET_URIAGE_NTAKU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_URIAGE_NTAKU_ZEN END) AS NET_URIAGE_NTAKU_ZEN      
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_NTAKU END) AS NET_KYAKUSU_NTAKU
,      (CASE WHEN BD54.EIGYO_DT IS NULL THEN 0 ELSE BD54.NET_KYAKUSU_NTAKU_ZEN END) AS NET_KYAKUSU_NTAKU_ZEN
/*END*/
from (SELECT YOSANTBL.YOSAN_DT
      ,      SUM(YOSANTBL.YOSAN) AS YOSAN
      FROM (SELECT BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */  
             , BM01.MISE_CD 
/*END*/
             FROM BM01TENM BM01
             WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
             AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
    /*IF "SIBU".equals(paramsDto.taishoJoken) */
            AND   BM01.SIBU_CD = /*paramsDto.hyojiTaisho*/'004'
        /*IF paramsDto.existsBlockCd */  
            AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
        /*END*/
    /*END*/
    /*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
             AND   EXISTS (SELECT * FROM BM10GSIB BM10
                           WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                           AND   BM10./*$paramsDto.taishoJoken*/'SIBU'_CD = /*paramsDto.hyojiTaisho*/'031'
                           AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
    /*END*/         
    /*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM09GTSG BM09
                      WHERE BM09.SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                      AND   BM09.GYOTAI_KBN = BM01.GYOTAI_KBN)
    /*END*/
    /*IF birdUserInfo.limit*/
            AND   EXISTS (SELECT * FROM BM51SVSB AS BM51
                      WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                      AND   BM51.SV_CD      = /*birdUserInfo.userID*/'00000921'
                      AND   BM51.SIBU_CD    = BM01.SIBU_CD)
    /*END*/
/*END*/
		    GROUP BY BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */  
            ,        BM01.MISE_CD 
/*END*/
     ) BM01
     ,      BT45DSJY YOSANTBL
      WHERE YOSANTBL.YOSAN_DT < /*birdDateInfo.sysDate*/'20110228'
      AND   YOSANTBL.YOSAN_DT BETWEEN /*paramsDto.focusTabFromAddDay*/ AND /*paramsDto.focusTabToAddDay*/
/*IF "SIBU".equals(paramsDto.taishoJoken) */  
      AND   YOSANTBL.SIBU_CD = /*paramsDto.hyojiTaisho*/'031'
/*END*/
/*IF "MISE".equals(paramsDto.taishoJoken) */  
      AND   YOSANTBL.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "1".equals(paramsDto.tenpoShubetu) || "3".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU = /*paramsDto.tenpoShubetu*/'1'
/*END*/
/*IF "2".equals(paramsDto.tenpoShubetu) */
      AND   YOSANTBL.TENPO_SHU IN ('1', '2')
/*END*/
      AND   YOSANTBL.SIBU_CD    = BM01.SIBU_CD
/*IF ("SIBU".equals(paramsDto.taishoJoken) && paramsDto.existsBlockCd) || "MISE".equals(paramsDto.taishoJoken) */
      AND   YOSANTBL.MISE_CD = BM01.MISE_CD
/*END*/
      group by YOSANTBL.YOSAN_DT
      ) BT4YOSAN
FULL OUTER JOIN ( 
      SELECT BD54.EIGYO_DT
      ,      SUM(BD54.URIAGE) AS URIAGE
      ,      MAX(BD54.TENKO_KBN) AS TENKO_KBN
      ,      SUM(BD54.KYAKUSU) AS KYAKUSU
      ,		 SUM(BD54.MISECNT_KBN_NSUM) AS MISECNT_KBN_NSUM
      ,		 SUM(BD54.URIAGE_NSUM) AS URIAGE_NSUM
      ,		 SUM(BD54.KYAKUSU_NSUM) AS KYAKUSU_NSUM
      ,		 SUM(BD54.MISECNT_KBN_NTAKE) AS MISECNT_KBN_NTAKE
      ,		 SUM(BD54.URIAGE_NTAKE) AS URIAGE_NTAKE
      ,		 SUM(BD54.KYAKUSU_NTAKE) AS KYAKUSU_NTAKE
      ,		 SUM(BD54.MISECNT_KBN_NTAKU) AS MISECNT_KBN_NTAKU
      ,		 SUM(BD54.URIAGE_NTAKU) AS URIAGE_NTAKU
      ,		 SUM(BD54.KYAKUSU_NTAKU) AS KYAKUSU_NTAKU
      ,      SUM(BD54.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU') AS URIAGE_ZEN
      ,      MAX(BD54.TENKO_KBN_ZEN_/*$zdsColmunName*/'DOGETU') AS TENKO_KBN_ZEN
      ,      SUM(BD54.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU') AS KYAKUSU_ZEN
      ,      SUM(BD54.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU'_NSUM) AS URIAGE_NSUM_ZEN
      ,      SUM(BD54.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU'_NSUM) AS KYAKUSU_NSUM_ZEN
      ,      SUM(BD54.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKE) AS URIAGE_NTAKE_ZEN
      ,      SUM(BD54.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKE) AS KYAKUSU_NTAKE_ZEN
      ,      SUM(BD54.URIAGE_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKU) AS URIAGE_NTAKU_ZEN
      ,      SUM(BD54.KYAKUSU_ZEN_/*$zdsColmunName*/'DOGETU'_NTAKU) AS KYAKUSU_NTAKU_ZEN
/*IF paramsDto.selectHosei==true */
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE ELSE 0 END) AS NET_URIAGE
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU ELSE 0 END) AS NET_KYAKUSU
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_NSUM ELSE 0 END) AS NET_URIAGE_NSUM
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_NSUM ELSE 0 END) AS NET_KYAKUSU_NSUM
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_NTAKE ELSE 0 END) AS NET_URIAGE_NTAKE
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_NTAKE ELSE 0 END) AS NET_KYAKUSU_NTAKE
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_NTAKU ELSE 0 END) AS NET_URIAGE_NTAKU
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_NTAKU ELSE 0 END) AS NET_KYAKUSU_NTAKU
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_ZEN_DOGETU ELSE 0 END) AS NET_URIAGE_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_ZEN_DOGETU ELSE 0 END) AS NET_KYAKUSU_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_ZEN_DOGETU_NSUM ELSE 0 END) AS NET_URIAGE_NSUM_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_ZEN_DOGETU_NSUM ELSE 0 END) AS NET_KYAKUSU_NSUM_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_ZEN_DOGETU_NTAKE ELSE 0 END) AS NET_URIAGE_NTAKE_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_ZEN_DOGETU_NTAKE ELSE 0 END) AS NET_KYAKUSU_NTAKE_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.URIAGE_ZEN_DOGETU_NTAKU ELSE 0 END) AS NET_URIAGE_NTAKU_ZEN
      ,      SUM(CASE WHEN BD54.URIAGE > 0 AND BD54.URIAGE_ZEN_DOGETU > 0 THEN BD54.KYAKUSU_ZEN_DOGETU_NTAKU ELSE 0 END) AS NET_KYAKUSU_NTAKU_ZEN
      
/*END*/ 
      FROM (SELECT BM01.MISE_CD FROM BM01TENM BM01
            WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
            AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'01776'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) */
    /*IF "SIBU".equals(paramsDto.taishoJoken) */
            AND   BM01.SIBU_CD = /*paramsDto.hyojiTaisho*/'004'
        /*IF paramsDto.existsBlockCd */  
            AND   BM01.BLOCK_CD = /*paramsDto.blockCd*/'004'
        /*END*/
    /*END*/
    /*IF "JIGYOU".equals(paramsDto.taishoJoken) || "SLAREA".equals(paramsDto.taishoJoken) || "SIBU".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM10GSIB BM10
                          WHERE BM10.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM10./*$paramsDto.taishoJoken*/'JIGYOU'_CD = /*paramsDto.hyojiTaisho*/'031'
                          AND   BM10.COMPANY_CD = BM01.COMPANY_CD
                          AND   BM10.SIBU_CD    = BM01.SIBU_CD) 
    /*END*/         
    /*IF "SEGMENT".equals(paramsDto.taishoJoken) */  
            AND   EXISTS (SELECT * FROM BM09GTSG BM09
                          WHERE SEGMENT_TYPE = /*paramsDto.hyojiTaisho*/'M' 
                          AND BM09.GYOTAI_KBN = BM01.GYOTAI_KBN)
    /*END*/
    /*IF birdUserInfo.limit */
            AND   EXISTS (SELECT * FROM BM51SVSB AS BM51
                          WHERE BM51.COMPANY_CD = /*paramsDto.companyCd*/'00'
                          AND   BM51.SV_CD = /*birdUserInfo.userID*/'00000921'
                          AND   BM51.SIBU_CD = BM01.SIBU_CD)
    /*END*/
    /*IF "ALL".equals(paramsDto.taishoJoken) */
		UNION ALL 
            SELECT CAST('00000' AS CHAR(5)) AS MISE_CD FROM BM01TENM BM01
            WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
            GROUP BY CAST('00000' AS CHAR(5))  
    /*END*/
/*END*/
        ) BM01 
      ,     BD54NNIP BD54 
      WHERE BD54.EIGYO_DT BETWEEN /*paramsDto.focusTabFromAddDay*/ AND /*paramsDto.focusTabToAddDay*/
      AND   BD54.EIGYO_DT < /*birdDateInfo.sysDate*/'20130520'
      AND   BD54.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
      AND   BD54.MISE_CD = /*paramsDto.hyojiTaisho*/'02001'
/*END*/
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) && "ALL".equals(paramsDto.tenpoShubetu) */
      AND   (BD54.OPEN_KBN + BD54.OPEN_KBN_ZEN_DOGETU) > 0
--ELSE
      AND   BD54.OPEN_KBN   = 1
/*END*/
      AND   BD54.OLDM_FLG   = '0'
/*IF "01".equals(birdUserInfo.mstUser.userTypeCd) && "ALL".equals(paramsDto.tenpoShubetu) ==false */
      AND   (EXISTS (
         SELECT * FROM BN01DTEN BN01
         WHERE BN01.COMPANY_CD = /*paramsDto.companyCd*/'00'
		/*IF paramsDto.tenpoShubetu == "2" */
         AND   BN01.KBN1 IN ('1', '2')
		--ELSE
         AND   BN01.KBN1 = /*paramsDto.tenpoShubetu*/'1'
		/*END*/
         AND   BD54.EIGYO_DT   = BN01.EIGYO_DT
         AND   BD54.MISE_CD    = BN01.MISE_CD 
	  )
	/*IF "ALL".equals(paramsDto.taishoJoken) */
		OR BD54.MISE_CD = '00000'
	/*END*/
	)
/*END*/
      AND   BD54.MISE_CD    = BM01.MISE_CD
      GROUP BY BD54.EIGYO_DT
) BD54 ON (BD54.EIGYO_DT = BT4YOSAN.YOSAN_DT)
ORDER BY EIGYO_DT
