SELECT BD54.EIGYO_DT
,      SUM(BD54.URIAGE) AS URIAGE
,      SUM(BD54.ONER_YOSAN) AS YOSAN
,      MAX(BD54.TENKO_KBN) AS TENKO_KBN
,      SUM(BD54.KYAKUSU) AS KYAKUSU
,      SUM(BD54.EIGYO_DAYS) AS EIGYO_DAYS
,	   SUM(BD54.MISECNT_KBN_NSUM) AS MISECNT_KBN_NSUM
,	   SUM(BD54.URIAGE_NSUM) AS URIAGE_NSUM
,	   SUM(BD54.KYAKUSU_NSUM) AS KYAKUSU_NSUM
,      SUM(BD54.EIGYO_DAYS_NSUM) AS EIGYO_DAYS_NSUM
,	   SUM(BD54.MISECNT_KBN_NTAKE) AS MISECNT_KBN_NTAKE
,	   SUM(BD54.URIAGE_NTAKE) AS URIAGE_NTAKE
,	   SUM(BD54.KYAKUSU_NTAKE) AS KYAKUSU_NTAKE
,      SUM(BD54.EIGYO_DAYS_NTAKE) AS EIGYO_DAYS_NTAKE
,	   SUM(BD54.MISECNT_KBN_NTAKU) AS MISECNT_KBN_NTAKU
,	   SUM(BD54.URIAGE_NTAKU) AS URIAGE_NTAKU
,	   SUM(BD54.KYAKUSU_NTAKU) AS KYAKUSU_NTAKU
,      SUM(BD54.EIGYO_DAYS_NTAKU) AS EIGYO_DAYS_NTAKU
,      SUM(BD54.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS URIAGE_ZEN
,      MAX(BD54.TENKO_KBN_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS TENKO_KBN_ZEN
,      SUM(BD54.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS KYAKUSU_ZEN
,      SUM(BD54.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS URIAGE_NSUM_ZEN
,      SUM(BD54.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS KYAKUSU_NSUM_ZEN
,      SUM(BD54.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS URIAGE_NTAKE_ZEN
,      SUM(BD54.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS KYAKUSU_NTAKE_ZEN
,      SUM(BD54.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS URIAGE_NTAKU_ZEN
,      SUM(BD54.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS KYAKUSU_NTAKU_ZEN	
FROM BD54NNIP BD54
WHERE BD54.EIGYO_DT < /*birdDateInfo.sysDate*/'20130507'
AND   BD54.EIGYO_DT BETWEEN /*paramsDto.focusTabFromAddDay*/ AND /*paramsDto.focusTabToAddDay*/
AND   BD54.COMPANY_CD = /*paramsDto.companyCd*/'00'
AND   BD54.OPEN_KBN = 1
AND   BD54.OLDM_FLG = '0'
AND   EXISTS (SELECT * FROM BM01TENM BM01
              WHERE BM01.COMPANY_CD = /*paramsDto.companyCd*/'00'
/*IF "MISE".equals(paramsDto.taishoJoken) */  
              AND   BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'00108'
--ELSE
              AND   BM01.ONER_CD    = /*paramsDto.hyojiTaisho*/'37006'
/*END*/
              AND   BM01.COMPANY_CD = BD54.COMPANY_CD
              AND   BM01.MISE_CD    = BD54.MISE_CD
)
GROUP BY BD54.EIGYO_DT
ORDER BY EIGYO_DT