  SELECT SUB.EIGYO_DT
  ,      SUM(URIAGE) AS URIAGE
  ,      SUM(ONER_YOSAN) AS YOSAN
  ,      SUM(EIGYO_DAYS) AS EIGYO_DAYS
  ,      SUM(KYAKUSU) AS KYAKUSU
  ,      SUM(URIAGE_ZEN) AS URIAGE_ZEN
  ,      SUM(KYAKUSU_ZEN) AS KYAKUSU_ZEN
  ,      SUM(EIGYO_DAYS_ZEN) AS EIGYO_DAYS_ZEN
  ,      SUM(EIGYO_DAYS_NSUM) AS EIGYO_DAYS_NSUM
  ,      SUM(MISECNT_NSUM) AS MISECNT_KBN_NSUM
  ,      SUM(URIAGE_NSUM) AS URIAGE_NSUM
  ,      SUM(KYAKUSU_NSUM) AS KYAKUSU_NSUM
  ,      SUM(URIAGE_NSUM_ZEN) AS URIAGE_NSUM_ZEN
  ,      SUM(KYAKUSU_NSUM_ZEN) AS KYAKUSU_NSUM_ZEN
  ,      SUM(EIGYO_DAYS_NTAKE) AS EIGYO_DAYS_NTAKE
  ,      SUM(MISECNT_NTAKE) AS MISECNT_KBN_NTAKE
  ,      SUM(URIAGE_NTAKE) AS URIAGE_NTAKE
  ,      SUM(KYAKUSU_NTAKE) AS KYAKUSU_NTAKE
  ,      SUM(URIAGE_NTAKE_ZEN) AS URIAGE_NTAKE_ZEN
  ,      SUM(KYAKUSU_NTAKE_ZEN) AS KYAKUSU_NTAKE_ZEN
  ,      SUM(EIGYO_DAYS_NTAKU) AS EIGYO_DAYS_NTAKU
  ,      SUM(MISECNT_NTAKU) AS MISECNT_KBN_NTAKU
  ,      SUM(URIAGE_NTAKU) AS URIAGE_NTAKU
  ,      SUM(KYAKUSU_NTAKU) AS KYAKUSU_NTAKU
  ,      SUM(URIAGE_NTAKU_ZEN) AS URIAGE_NTAKU_ZEN
  ,      SUM(KYAKUSU_NTAKU_ZEN) AS KYAKUSU_NTAKU_ZEN
      FROM ( 
SELECT BD53.EIGYO_DT
,      BD53.MISE_CD
,      SUM(BD53.URIAGE_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS URIAGE
,      SUM(BD53.ONER_YOSAN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS ONER_YOSAN
,      SUM(BD53.EIGYO_DAYS_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS EIGYO_DAYS
,      SUM(BD53.KYAKUSU_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS KYAKUSU
,      SUM(BD53.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS URIAGE_ZEN
,      SUM(BD53.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS KYAKUSU_ZEN
,      SUM(BD53.EIGYO_DAYS_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU') AS EIGYO_DAYS_ZEN
,      SUM(BD53.EIGYO_DAYS_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS EIGYO_DAYS_NSUM
,      MAX(BD53.MISECNT_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS MISECNT_NSUM
,      SUM(BD53.URIAGE_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS URIAGE_NSUM
,      SUM(BD53.KYAKUSU_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS KYAKUSU_NSUM
,      SUM(BD53.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS URIAGE_NSUM_ZEN
,      SUM(BD53.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NSUM) AS KYAKUSU_NSUM_ZEN
,      SUM(BD53.EIGYO_DAYS_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS EIGYO_DAYS_NTAKE
,      MAX(BD53.MISECNT_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS MISECNT_NTAKE
,      SUM(BD53.URIAGE_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS URIAGE_NTAKE
,      SUM(BD53.KYAKUSU_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS KYAKUSU_NTAKE
,      SUM(BD53.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS URIAGE_NTAKE_ZEN
,      SUM(BD53.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKE) AS KYAKUSU_NTAKE_ZEN
,      SUM(BD53.EIGYO_DAYS_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS EIGYO_DAYS_NTAKU
,      MAX(BD53.MISECNT_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS MISECNT_NTAKU
,      SUM(BD53.URIAGE_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS URIAGE_NTAKU
,      SUM(BD53.KYAKUSU_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS KYAKUSU_NTAKU
,      SUM(BD53.URIAGE_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS URIAGE_NTAKU_ZEN
,      SUM(BD53.KYAKUSU_ZEN_/*$paramsDto.zennenDataShubetu*/'DOGETU'_NTAKU) AS KYAKUSU_NTAKU_ZEN	
FROM   BD53NGEP BD53
WHERE  BD53.EIGYO_DT BETWEEN /*paramsDto.kikanSiteiFrom*/'201203' AND /*paramsDto.kikanSiteiTo*/'201304'
AND    BD53.COMPANY_CD = /*paramsDto.companyCd*/'00'
AND    OPEN_KBN = 1
AND    OLDM_FLG = '0'
AND    EXISTS (SELECT * FROM BM01TENM BM01
/*IF "MISE".equals(paramsDto.taishoJoken) */  
               WHERE BM01.MISE_CD = /*paramsDto.hyojiTaisho*/'00108'
--ELSE
               WHERE BM01.ONER_CD = /*paramsDto.hyojiTaisho*/'37006'
/*END*/
               AND   BM01.COMPANY_CD = BD53.COMPANY_CD
               AND   BM01.MISE_CD    = BD53.MISE_CD)
      GROUP BY BD53.EIGYO_DT
      ,      BD53.MISE_CD
) SUB
GROUP BY SUB.EIGYO_DT
ORDER BY SUB.EIGYO_DT