SELECT RANK_NO
,      SIBU_CD
,      MISE_CD
,      MISE_NAME_KJ
,      URIAGE
,      YOSAN
,      YOSAN_TASSEI_RITU
,      EIGYO_DAYS
,      URIAGE_ZEN
,      URIAGE_ZENNEN_HI
,      EIGYO_DAYS_ZEN
,      KYAKUSU
,      KYAKUSU_ZEN
,      KYAKUSU_ZENNEN_HI
,      KYAKUTANKA
,      KYAKUTANKA_ZEN
,      KYAKUTANKA_ZENNEN_HI
FROM (

SELECT RANK() OVER(order by DATA4./*$rankTarget*/ /*$rankType*/) AS RANK_NO
,      BM01.SIBU_CD
,      BM01.MISE_CD
,      BM01.MISE_NAME_KJ
,      DATA4.URIAGE
,      DATA4.YOSAN
,      DATA4.YOSAN_TASSEI_RITU
,      DATA4.EIGYO_DAYS
,      DATA4.URIAGE_ZEN
,      DATA4.URIAGE_ZENNEN_HI
,      DATA4.EIGYO_DAYS_ZEN
,      DATA4.KYAKUSU
,      DATA4.KYAKUSU_ZEN
,      DATA4.KYAKUSU_ZENNEN_HI
,      DATA4.KYAKUTANKA
,      DATA4.KYAKUTANKA_ZEN
,      DATA4.KYAKUTANKA_ZENNEN_HI

FROM (
		SELECT BM01.SIBU_CD
		,      BM01.MISE_CD
		,      BM01.MISE_NAME_KJ
		FROM BM01TENM BM01
		/*IF userTypeCd == "02" */
		,    BM06UONR BM06
		/*END*/
		/*IF userTypeCd == "03" */
		,    BM07UTEN BM07
		/*END*/
		WHERE BM01.COMPANY_CD = /*companyCd*/'00'
/*IF userTypeCd == "01" && limitFlg == true */
		AND    BM01.SIBU_CD IN (
			SELECT   BM51.SIBU_CD
			FROM     BM51SVSB BM51
			WHERE  BM51.COMPANY_CD = /*companyCd*/'00'
			AND    BM51.SV_CD      = /*userId*/'99990001'
			GROUP BY BM51.SIBU_CD
			)
/*END*/
/*IF userTypeCd == "02" */
		AND   BM06.USER_ID    = /*userId*/'99990002'
		AND   BM06.COMPANY_CD = BM01.COMPANY_CD
		AND   BM06.ONER_CD    = BM01.ONER_CD
/*END*/
/*IF userTypeCd == "03" */
		AND   BM07.USER_ID    = /*userId*/'99990003'
		AND   BM07.COMPANY_CD = BM01.COMPANY_CD
		AND   BM07.MISE_CD    = BM01.MISE_CD
/*END*/
		GROUP BY BM01.SIBU_CD
		,      BM01.MISE_CD
		,      BM01.MISE_NAME_KJ
	) BM01
,   (
	SELECT SUBBT64.MISE_CD AS MISE_CD
	,      SUM(SUBBT64.URIAGE) AS URIAGE
	,      SUM(CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END) AS YOSAN
	,      DECIMAL(
	           CASE WHEN SUM(CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END) = 0 THEN 0.00
	                ELSE ((DOUBLE(SUM(SUBBT64.URIAGE))/DOUBLE(SUM(CASE WHEN BT4YOSAN.YOSAN IS NULL THEN 0 ELSE BT4YOSAN.YOSAN END))*100)+0.005)
	           END, 20, 2) AS YOSAN_TASSEI_RITU
	,      SUM(SUBBT64.EIGYO_DAYS) AS EIGYO_DAYS
	,      SUM(SUBBT64.URIAGE_ZEN) AS URIAGE_ZEN

	,      DECIMAL(
	           CASE WHEN SUM(SUBBT64.URIAGE_ZEN) <= 0 THEN 0.00
	                ELSE ((DOUBLE(SUM(SUBBT64.URIAGE))/DOUBLE(SUM(SUBBT64.URIAGE_ZEN))*100)+0.005)
	           END, 20, 2) AS URIAGE_ZENNEN_HI

	,      SUM(SUBBT64.EIGYO_DAYS_ZEN) AS EIGYO_DAYS_ZEN
	,      SUM(SUBBT64.KYAKUSU) AS KYAKUSU
	,      SUM(SUBBT64.KYAKUSU_ZEN) AS KYAKUSU_ZEN
	,      DECIMAL(
	           CASE WHEN SUM(SUBBT64.KYAKUSU_ZEN) <= 0 THEN 0.00
	                WHEN SUM(SUBBT64.KYAKUSU) <= 0 THEN 0.00
	                ELSE ((DOUBLE(SUM(SUBBT64.KYAKUSU))/DOUBLE(SUM(SUBBT64.KYAKUSU_ZEN))*100)+0.005)
	           END, 20, 2) AS KYAKUSU_ZENNEN_HI
	,      DECIMAL(
	           CASE WHEN SUM(SUBBT64.KYAKUSU) <= 0 THEN 0.00
	                ELSE ((DOUBLE(SUM(SUBBT64.URIAGE) )/DOUBLE(SUM(SUBBT64.KYAKUSU)))+0.5)
	           END, 11, 0) AS KYAKUTANKA

	,      DECIMAL(
	           CASE WHEN SUM(SUBBT64.KYAKUSU_ZEN) <= 0 THEN 0.00
	                ELSE ((DOUBLE(SUM(SUBBT64.URIAGE_ZEN) )/DOUBLE(SUM(SUBBT64.KYAKUSU_ZEN)))+0.5)
	           END, 11, 0) AS KYAKUTANKA_ZEN
	,      DECIMAL(
	           CASE WHEN SUM(SUBBT64.KYAKUSU) <= 0 THEN 0.00
	                WHEN SUM(SUBBT64.KYAKUSU_ZEN) <= 0 THEN 0.00
	                ELSE ((DECIMAL(((DOUBLE(SUM(SUBBT64.URIAGE) )/DOUBLE(SUM(SUBBT64.KYAKUSU)))+0.5), 11,0)
	                      /DECIMAL(((DOUBLE(SUM(SUBBT64.URIAGE_ZEN) )/DOUBLE(SUM(SUBBT64.KYAKUSU_ZEN)))+0.5), 11,0)
	                         *100
	                      )+0.005)
	           END, 10, 2) AS KYAKUTANKA_ZENNEN_HI
FROM (
    SELECT BT64.EIGYO_DT
    ,      BT64.MISE_CD
    ,      BT64.URIAGE_DOGETU AS URIAGE
    ,      BT64.ONER_YOSAN_DOGETU AS ONER_YOSAN
    ,      BT64.EIGYO_DAYS_DOGETU AS EIGYO_DAYS
    ,      BT64.URIAGE_ZEN_DOGETU AS URIAGE_ZEN
    ,      BT64.EIGYO_DAYS_ZEN_DOGETU AS EIGYO_DAYS_ZEN
    ,      BT64.KYAKUSU_DOGETU AS KYAKUSU
    ,      BT64.KYAKUSU_ZEN_DOGETU AS KYAKUSU_ZEN
	FROM (
		SELECT EIGYO_YM
		,      MISE_CD
		FROM BN01DTEN
		WHERE COMPANY_CD = /*companyCd*/'00'
	/*IF "KIBETU".equals(taishoKikan) */
		AND   EIGYO_YM BETWEEN /*kikanSitei*/'200804' AND /*kikanSiteiTo*/'200809'
	--ELSE
		AND   EIGYO_YM = /*kikanSitei*/'200809'
	/*END*/
	/*IF tenpoShubetu == "1" || tenpoShubetu == "3"*/
		AND   KBN1 = /*tenpoShubetu*/'1'
	/*END*/
	/*IF tenpoShubetu == "2" */
		AND   KBN1 IN ('1', '2')
	/*END*/
		GROUP BY EIGYO_YM
		,        MISE_CD
		) BN01
	,   BT64ZGEP BT64

	WHERE BT64.COMPANY_CD = /*companyCd*/'00'
    AND   BT64.OLDM_FLG <> '1'
    AND   BT64.OPEN_KBN = 1
    AND   BT64.EIGYO_DT = BN01.EIGYO_YM
	AND   BT64.MISE_CD = BN01.MISE_CD

    GROUP BY BT64.EIGYO_DT
    ,        BT64.MISE_CD
    ,        BT64.URIAGE_DOGETU
    ,        BT64.ONER_YOSAN_DOGETU
    ,        BT64.EIGYO_DAYS_DOGETU
    ,        BT64.URIAGE_ZEN_DOGETU
    ,        BT64.EIGYO_DAYS_ZEN_DOGETU
    ,        BT64.KYAKUSU_DOGETU
    ,        BT64.KYAKUSU_ZEN_DOGETU
	) SUBBT64
LEFT JOIN (
      SELECT BT44.YOSAN_DT
      ,      BT44.MISE_CD
      ,      SUM(BT44.YOSAN) AS YOSAN
      FROM   BT44MSJY BT44
/*IF "KIBETU".equals(taishoKikan) */
      WHERE YOSAN_DT BETWEEN /*kikanSitei*/'200804' AND /*kikanSiteiTo*/'200809'
--ELSE
	  WHERE YOSAN_DT = /*kikanSitei*/'200809'
/*END*/
/*IF tenpoShubetu == "1" || tenpoShubetu == "3" */
      AND   TENPO_SHU = /*tenpoShubetu*/'1'
/*END*/
/*IF tenpoShubetu == "2" */
      AND   TENPO_SHU IN ('1', '2')
/*END*/
      AND   BT44.COMPANY_CD = /*companyCd*/'00'
/*IF limitFlg*/
      AND   BT44.SIBU_CD IN (
         SELECT   BM51.SIBU_CD
         FROM     BM51SVSB BM51
         WHERE  BM51.COMPANY_CD = /*companyCd*/'00'
         AND    BM51.SV_CD      = /*userId*/'9999000a'
         GROUP BY BM51.SIBU_CD
      )
/*END*/
      GROUP BY BT44.YOSAN_DT
      ,        BT44.MISE_CD
      ) BT4YOSAN
	ON( SUBBT64.EIGYO_DT = BT4YOSAN.YOSAN_DT
	AND SUBBT64.MISE_CD = BT4YOSAN.MISE_CD )
	GROUP BY SUBBT64.MISE_CD
) DATA4
WHERE   BM01.MISE_CD = DATA4.MISE_CD
)SUB
WHERE RANK_NO <=100
ORDER BY RANK_NO
,        SIBU_CD
,        MISE_CD
