SELECT TBL.MISE_CD                AS MISE_CD
,      TBL.EIGYO_DT               AS EIGYO_DT
,      TBL.URIAGE                 AS URIAGE
,      TBL.ONER_YOSAN             AS YOSAN
,      TBL.KYAKUSU                AS KYAKUSU
,      TBL.TENKO_KBN              AS TENKO_KBN
,      TBL.ZEN_DOYO_DT            AS ZEN_DOYO_DT
,      TBL.ISSUE_CNT              AS ISSUE_CNT
,      TBL.CHARGE_KIN             AS CHARGE_KIN
,      TBL.CHARGE_KEN             AS CHARGE_KEN
,      TBL.KESSAI_KIN             AS KESSAI_KIN
,      TBL.KESSAI_KEN             AS KESSAI_KEN
,      TBL.CHARGE_KIN_CANCEL      AS CHARGE_KIN_CANCEL
,      TBL.CHARGE_KEN_CANCEL      AS CHARGE_KEN_CANCEL
,      TBL.USE_KIN_CANCEL         AS USE_KIN_CANCEL
,      TBL.USE_KEN_CANCEL         AS USE_KEN_CANCEL
,      TBL.BONUS_V_ISSUE          AS BONUS_V_ISSUE
,      TBL.BONUS_V_USE            AS BONUS_V_USE
,      TBL.COUPON_V_ISSUE         AS COUPON_V_ISSUE
,      TBL.COUPON_V_USE           AS COUPON_V_USE
,      TBL.ZANDAKA                AS ZANDAKA

,      CASE WHEN TBL.URIAGE_ZEN_DOYO        IS NULL THEN 0 ELSE TBL.URIAGE_ZEN_DOYO        END AS URIAGE_ZEN_DOYO
,      CASE WHEN TBL.KYAKUSU_ZEN_DOYO       IS NULL THEN 0 ELSE TBL.KYAKUSU_ZEN_DOYO       END AS KYAKUSU_ZEN_DOYO
,      TBL.TENKO_KBN_ZEN_DOYO     AS TENKO_KBN_ZEN_DOYO
,      CASE WHEN TBL.ISSUE_CNT_ZEN_DOYO     IS NULL THEN 0 ELSE TBL.ISSUE_CNT_ZEN_DOYO     END AS ISSUE_CNT_ZEN_DOYO  
,      CASE WHEN TBL.CHARGE_KIN_ZEN_DOYO    IS NULL THEN 0 ELSE TBL.CHARGE_KIN_ZEN_DOYO         END AS CHARGE_KIN_ZEN_DOYO
,      CASE WHEN TBL.CHARGE_KEN_ZEN_DOYO    IS NULL THEN 0 ELSE TBL.CHARGE_KEN_ZEN_DOYO         END AS CHARGE_KEN_ZEN_DOYO
,      CASE WHEN TBL.KESSAI_KIN_ZEN_DOYO    IS NULL THEN 0 ELSE TBL.KESSAI_KIN_ZEN_DOYO         END AS KESSAI_KIN_ZEN_DOYO
,      CASE WHEN TBL.KESSAI_KEN_ZEN_DOYO    IS NULL THEN 0 ELSE TBL.KESSAI_KEN_ZEN_DOYO         END AS KESSAI_KEN_ZEN_DOYO

,      CASE WHEN TBL.URIAGE_ZEN_DOJITU      IS NULL THEN 0 ELSE TBL.URIAGE_ZEN_DOJITU      END AS URIAGE_ZEN_DOJITU
,      CASE WHEN TBL.KYAKUSU_ZEN_DOJITU     IS NULL THEN 0 ELSE TBL.KYAKUSU_ZEN_DOJITU     END AS KYAKUSU_ZEN_DOJITU
,      CASE WHEN TBL.ISSUE_CNT_ZEN_DOJITU   IS NULL THEN 0 ELSE TBL.ISSUE_CNT_ZEN_DOJITU      END AS ISSUE_CNT_ZEN_DOJITU
,      CASE WHEN TBL.CHARGE_KIN_ZEN_DOJITU  IS NULL THEN 0 ELSE TBL.CHARGE_KIN_ZEN_DOJITU     END AS CHARGE_KIN_ZEN_DOJITU
,      CASE WHEN TBL.CHARGE_KEN_ZEN_DOJITU  IS NULL THEN 0 ELSE TBL.CHARGE_KEN_ZEN_DOJITU     END AS CHARGE_KEN_ZEN_DOJITU
,      CASE WHEN TBL.KESSAI_KIN_ZEN_DOJITU  IS NULL THEN 0 ELSE TBL.KESSAI_KIN_ZEN_DOJITU     END AS KESSAI_KIN_ZEN_DOJITU
,      CASE WHEN TBL.KESSAI_KEN_ZEN_DOJITU  IS NULL THEN 0 ELSE TBL.KESSAI_KEN_ZEN_DOJITU     END AS KESSAI_KEN_ZEN_DOJITU



,      CASE WHEN TBL.URIAGE_RUI             IS NULL THEN 0 ELSE TBL.URIAGE_RUI             END AS URIAGE_RUI
,      CASE WHEN TBL.YOSAN_RUI              IS NULL THEN 0 ELSE TBL.YOSAN_RUI              END AS YOSAN_RUI
,      CASE WHEN TBL.KYAKUSU_RUI            IS NULL THEN 0 ELSE TBL.KYAKUSU_RUI            END AS KYAKUSU_RUI
,      CASE WHEN TBL.ISSUE_CNT_RUI          IS NULL THEN 0 ELSE TBL.ISSUE_CNT_RUI          END AS ISSUE_CNT_RUI
,      CASE WHEN TBL.CHARGE_KIN_RUI         IS NULL THEN 0 ELSE TBL.CHARGE_KIN_RUI         END AS CHARGE_KIN_RUI
,      CASE WHEN TBL.CHARGE_KEN_RUI         IS NULL THEN 0 ELSE TBL.CHARGE_KEN_RUI         END AS CHARGE_KEN_RUI
,      CASE WHEN TBL.KESSAI_KIN_RUI         IS NULL THEN 0 ELSE TBL.KESSAI_KIN_RUI         END AS KESSAI_KIN_RUI
,      CASE WHEN TBL.KESSAI_KEN_RUI         IS NULL THEN 0 ELSE TBL.KESSAI_KEN_RUI         END AS KESSAI_KEN_RUI
,      CASE WHEN TBL.CHARGE_KIN_CANCEL_RUI  IS NULL THEN 0 ELSE TBL.CHARGE_KIN_CANCEL_RUI  END AS CHARGE_KIN_CANCEL_RUI
,      CASE WHEN TBL.CHARGE_KEN_CANCEL_RUI  IS NULL THEN 0 ELSE TBL.CHARGE_KEN_CANCEL_RUI  END AS CHARGE_KEN_CANCEL_RUI
,      CASE WHEN TBL.USE_KIN_CANCEL_RUI     IS NULL THEN 0 ELSE TBL.USE_KIN_CANCEL_RUI     END AS USE_KIN_CANCEL_RUI
,      CASE WHEN TBL.USE_KEN_CANCEL_RUI     IS NULL THEN 0 ELSE TBL.USE_KEN_CANCEL_RUI     END AS USE_KEN_CANCEL_RUI
,      CASE WHEN TBL.BONUS_V_ISSUE_RUI      IS NULL THEN 0 ELSE TBL.BONUS_V_ISSUE_RUI      END AS BONUS_V_ISSUE_RUI
,      CASE WHEN TBL.BONUS_V_USE_RUI        IS NULL THEN 0 ELSE TBL.BONUS_V_USE_RUI        END AS BONUS_V_USE_RUI
,      CASE WHEN TBL.COUPON_V_ISSUE_RUI     IS NULL THEN 0 ELSE TBL.COUPON_V_ISSUE_RUI     END AS COUPON_V_ISSUE_RUI
,      CASE WHEN TBL.COUPON_V_USE_RUI       IS NULL THEN 0 ELSE TBL.COUPON_V_USE_RUI       END AS COUPON_V_USE_RUI

,      CASE WHEN TBL.URIAGE_ZEN_DOJITU_RUI      IS NULL THEN 0 ELSE TBL.URIAGE_ZEN_DOJITU_RUI  END AS URIAGE_ZEN_DOJITU_RUI
,      CASE WHEN TBL.KYAKUSU_ZEN_DOJITU_RUI     IS NULL THEN 0 ELSE TBL.KYAKUSU_ZEN_DOJITU_RUI END AS KYAKUSU_ZEN_DOJITU_RUI
,      CASE WHEN TBL.ISSUE_CNT_ZEN_DOJITU_RUI   IS NULL THEN 0 ELSE TBL.ISSUE_CNT_ZEN_DOJITU_RUI    END AS ISSUE_CNT_ZEN_DOJITU_RUI
,      CASE WHEN TBL.ISSUE_CNT_ZEN_DOJITU_RUI   IS NULL THEN 0 ELSE TBL.ISSUE_CNT_ZEN_DOJITU_RUI      END AS ISSUE_CNT_ZEN_DOJITU_RUI
,      CASE WHEN TBL.CHARGE_KIN_ZEN_DOJITU_RUI  IS NULL THEN 0 ELSE TBL.CHARGE_KIN_ZEN_DOJITU_RUI     END AS CHARGE_KIN_ZEN_DOJITU_RUI
,      CASE WHEN TBL.CHARGE_KEN_ZEN_DOJITU_RUI  IS NULL THEN 0 ELSE TBL.CHARGE_KEN_ZEN_DOJITU_RUI     END AS CHARGE_KEN_ZEN_DOJITU_RUI
,      CASE WHEN TBL.KESSAI_KIN_ZEN_DOJITU_RUI  IS NULL THEN 0 ELSE TBL.KESSAI_KIN_ZEN_DOJITU_RUI     END AS KESSAI_KIN_ZEN_DOJITU_RUI
,      CASE WHEN TBL.KESSAI_KEN_ZEN_DOJITU_RUI  IS NULL THEN 0 ELSE TBL.KESSAI_KEN_ZEN_DOJITU_RUI     END AS KESSAI_KEN_ZEN_DOJITU_RUI

,      DECIMAL( CASE WHEN TBL.ONER_YOSAN       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.ONER_YOSAN)*100)+0.05)
                END, 20, 1) AS YOSANHI

,      DECIMAL( CASE WHEN TBL.KYAKUSU          <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.KYAKUSU))+0.5)
                END, 11, 0) AS KYAKUTANKA

,      DECIMAL( CASE WHEN TBL.KYAKUSU_ZEN_DOYO <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE_ZEN_DOYO)/DOUBLE(TBL.KYAKUSU_ZEN_DOYO))+0.5)
                END, 11, 0) AS KYAKUTANKA_ZEN_DOYO

,      DECIMAL( CASE WHEN TBL.KYAKUSU          <= 0 THEN 0.00 
                     WHEN TBL.KYAKUSU_ZEN_DOYO <= 0 THEN 0.00
                     ELSE ((DECIMAL(((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.KYAKUSU))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(TBL.URIAGE_ZEN_DOYO)/DOUBLE(TBL.KYAKUSU_ZEN_DOYO))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS KYAKUTANKA_ZEN_DOYONENHI

,      DECIMAL( CASE WHEN TBL.YOSAN_RUI       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE_RUI)/DOUBLE(TBL.YOSAN_RUI)*100)+0.05)
                END, 20, 1) AS YOSANHI_RUI

,      DECIMAL( CASE WHEN TBL.URIAGE_ZEN_DOJITU_RUI <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.URIAGE_RUI)/DOUBLE(TBL.URIAGE_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS URIAGE_ZENNENHI_RUI

,      DECIMAL( CASE WHEN TBL.KYAKUSU_ZEN_DOJITU_RUI       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KYAKUSU_RUI)/DOUBLE(TBL.KYAKUSU_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS KYAKUSU_ZENNENHI_RUI

,      DECIMAL( CASE WHEN TBL.ISSUE_CNT_ZEN_DOJITU_RUI     <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.ISSUE_CNT_RUI)/DOUBLE(TBL.ISSUE_CNT_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS ISSUE_CNT_ZENNENHI_RUI

,      DECIMAL( CASE WHEN TBL.URIAGE                       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KIN)/DOUBLE(TBL.URIAGE)*100)+0.05)
                END, 20, 1) AS CHARGE_KIN_URIAGEHI

,      DECIMAL( CASE WHEN TBL.URIAGE_RUI                       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KIN_RUI)/DOUBLE(TBL.URIAGE_RUI)*100)+0.05)
                END, 20, 1) AS CHARGE_KIN_URIAGEHI_RUI

,      DECIMAL( CASE WHEN TBL.CHARGE_KIN_ZEN_DOJITU_RUI            <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KIN_RUI)/DOUBLE(TBL.CHARGE_KIN_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS CHARGE_KIN_ZENURIAGEHI

,      DECIMAL( CASE WHEN TBL.KYAKUSU                       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KEN)/DOUBLE(TBL.KYAKUSU)*100)+0.05)
                END, 20, 1) AS CHARGE_KEN_KYAKUSUHI

,      DECIMAL( CASE WHEN TBL.KYAKUSU_RUI                   <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KEN_RUI)/DOUBLE(TBL.KYAKUSU_RUI)*100)+0.05)
                END, 20, 1) AS CHARGE_KEN_KYAKUSUHI_RUI

,      DECIMAL( CASE WHEN TBL.CHARGE_KEN_ZEN_DOJITU_RUI     <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KEN_RUI)/DOUBLE(TBL.CHARGE_KEN_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS CHARGE_KEN_ZENKYAKUSUHI

,      DECIMAL( CASE WHEN TBL.CHARGE_KEN      <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KIN)/DOUBLE(TBL.CHARGE_KEN))+0.5)
                END, 11, 0) AS CHARGETANKA

,      DECIMAL( CASE WHEN TBL.CHARGE_KEN_ZEN_DOYO         <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.CHARGE_KIN_ZEN_DOYO)/DOUBLE(TBL.CHARGE_KEN_ZEN_DOYO))+0.5)
                END, 11, 0) AS CHARGETANKA_ZEN_DOYO

,      DECIMAL( CASE WHEN TBL.CHARGE_KEN       <= 0 THEN 0.00 
                     WHEN TBL.KYAKUSU          <= 0 THEN 0.00
                     ELSE ((DECIMAL(((DOUBLE(TBL.CHARGE_KIN)/DOUBLE(TBL.CHARGE_KEN))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.KYAKUSU))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS CHARGETANKA_TANKAHI

,      DECIMAL( CASE WHEN TBL.CHARGE_KEN       <= 0 THEN 0.00 
                     WHEN TBL.CHARGE_KEN_ZEN_DOYO  <= 0 THEN 0.00
                     ELSE ((DECIMAL(((DOUBLE(TBL.CHARGE_KIN)/DOUBLE(TBL.CHARGE_KEN))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(TBL.CHARGE_KIN_ZEN_DOYO)/DOUBLE(TBL.CHARGE_KEN_ZEN_DOYO))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS CHARGETANKA_ZENHI

,      DECIMAL( CASE WHEN TBL.URIAGE                       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KIN)/DOUBLE(TBL.URIAGE)*100)+0.05)
                END, 20, 1) AS KESSAI_KIN_URIAGEHI

,      DECIMAL( CASE WHEN TBL.URIAGE_RUI                       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KIN_RUI)/DOUBLE(TBL.URIAGE_RUI)*100)+0.05)
                END, 20, 1) AS KESSAI_KIN_URIAGEHI_RUI

,      DECIMAL( CASE WHEN TBL.KESSAI_KIN_ZEN_DOJITU_RUI            <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KIN_RUI)/DOUBLE(TBL.KESSAI_KIN_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS KESSAI_KIN_ZENURIAGEHI

,      DECIMAL( CASE WHEN TBL.KYAKUSU                       <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KEN)/DOUBLE(TBL.KYAKUSU)*100)+0.05)
                END, 20, 1) AS KESSAI_KEN_KYAKUSUHI

,      DECIMAL( CASE WHEN TBL.KYAKUSU_RUI                   <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KEN_RUI)/DOUBLE(TBL.KYAKUSU_RUI)*100)+0.05)
                END, 20, 1) AS KESSAI_KEN_KYAKUSUHI_RUI

,      DECIMAL( CASE WHEN TBL.KESSAI_KEN_ZEN_DOJITU_RUI     <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KEN_RUI)/DOUBLE(TBL.KESSAI_KEN_ZEN_DOJITU_RUI)*100)+0.05)
                END, 20, 1) AS KESSAI_KEN_ZENKYAKUSUHI

,      DECIMAL( CASE WHEN TBL.KESSAI_KEN      <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KIN)/DOUBLE(TBL.KESSAI_KEN))+0.5)
                END, 11, 0) AS KESSAITANKA

,      DECIMAL( CASE WHEN TBL.KESSAI_KIN_ZEN_DOYO         <= 0 THEN 0.00
                     ELSE ((DOUBLE(TBL.KESSAI_KIN_ZEN_DOYO)/DOUBLE(TBL.KESSAI_KEN_ZEN_DOYO))+0.5)
                END, 11, 0) AS KESSAITANKA_ZEN_DOYO

,      DECIMAL( CASE WHEN TBL.KESSAI_KEN       <= 0 THEN 0.00 
                     WHEN TBL.KYAKUSU          <= 0 THEN 0.00
                     ELSE ((DECIMAL(((DOUBLE(TBL.KESSAI_KIN)/DOUBLE(TBL.KESSAI_KEN))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(TBL.URIAGE)/DOUBLE(TBL.KYAKUSU))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS KESSAITANKA_TANKAHI

,      DECIMAL( CASE WHEN TBL.KESSAI_KEN       <= 0 THEN 0.00 
                     WHEN TBL.KESSAI_KEN_ZEN_DOYO  <= 0 THEN 0.00
                     ELSE ((DECIMAL(((DOUBLE(TBL.KESSAI_KIN)/DOUBLE(TBL.KESSAI_KEN))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(TBL.KESSAI_KIN_ZEN_DOYO)/DOUBLE(TBL.KESSAI_KEN_ZEN_DOYO))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS KESSAITANKA_ZENHI

,      CASE WHEN TBL.TENKO_KBN = 1 THEN '°'
            WHEN TBL.TENKO_KBN = 2 THEN '“Ü'
            WHEN TBL.TENKO_KBN = 3 THEN '‰J'
            WHEN TBL.TENKO_KBN = 4 THEN 'á'
            WHEN TBL.TENKO_KBN = 5 THEN '—’'
            ELSE '' END  AS TENKO_KBN_KJ

,      CASE WHEN TBL.TENKO_KBN_ZEN_DOYO = 1 THEN '°'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 2 THEN '“Ü'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 3 THEN '‰J'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 4 THEN 'á'
            WHEN TBL.TENKO_KBN_ZEN_DOYO = 5 THEN '—’'
            ELSE '' END  AS TENKO_KBN_ZEN_DOYO_KJ
FROM 
     (
        SELECT BM45.MISE_CD        AS MISE_CD
        ,      MAX(BM45.OPEN_KBN)  OVER(partition by BM45.MISE_CD) AS OPENING_FLG
        ,      BM45.EIGYO_DT       AS EIGYO_DT
        ,      URIAGE              AS URIAGE
        ,      ONER_YOSAN          AS ONER_YOSAN
        ,      KYAKUSU             AS KYAKUSU
        ,      TENKO_KBN           AS TENKO_KBN
        ,      ISSUE_CNT           AS ISSUE_CNT
        ,      CHARGE_KIN          AS CHARGE_KIN
        ,      CHARGE_KEN          AS CHARGE_KEN
        ,      KESSAI_KIN          AS KESSAI_KIN
        ,      KESSAI_KEN          AS KESSAI_KEN
        ,      CHARGE_KIN_CANCEL   AS CHARGE_KIN_CANCEL
        ,      CHARGE_KEN_CANCEL   AS CHARGE_KEN_CANCEL
        ,      USE_KIN_CANCEL      AS USE_KIN_CANCEL
        ,      USE_KEN_CANCEL      AS USE_KEN_CANCEL
        ,      BONUS_V_ISSUE       AS BONUS_V_ISSUE
        ,      BONUS_V_USE         AS BONUS_V_USE
        ,      COUPON_V_ISSUE      AS COUPON_V_ISSUE
        ,      COUPON_V_USE        AS COUPON_V_USE
        ,      ZANDAKA             AS ZANDAKA

        ,      BM45.ZEN_DOYO_DT    AS ZEN_DOYO_DT
        ,      DOYO_ZEN_URIAGE     AS URIAGE_ZEN_DOYO
        ,      DOYO_ZEN_KYAKUSU    AS KYAKUSU_ZEN_DOYO
        ,      DOYO_ZEN_TENKO_KBN  AS TENKO_KBN_ZEN_DOYO
        ,      DOYO_ZEN_ISSUE_CNT  AS ISSUE_CNT_ZEN_DOYO
        ,      DOYO_ZEN_CHARGE_KIN AS CHARGE_KIN_ZEN_DOYO
        ,      DOYO_ZEN_CHARGE_KEN AS CHARGE_KEN_ZEN_DOYO
        ,      DOYO_ZEN_KESSAI_KIN AS KESSAI_KIN_ZEN_DOYO
        ,      DOYO_ZEN_KESSAI_KEN AS KESSAI_KEN_ZEN_DOYO

        ,      DOJITU_ZEN_URIAGE   AS URIAGE_ZEN_DOJITU
        ,      DOJITU_ZEN_KYAKUSU  AS KYAKUSU_ZEN_DOJITU
        ,      DOJITU_ZEN_ISSUE_CNT  AS ISSUE_CNT_ZEN_DOJITU
        ,      DOJITU_ZEN_CHARGE_KIN AS CHARGE_KIN_ZEN_DOJITU
        ,      DOJITU_ZEN_CHARGE_KEN AS CHARGE_KEN_ZEN_DOJITU
        ,      DOJITU_ZEN_KESSAI_KIN AS KESSAI_KIN_ZEN_DOJITU
        ,      DOJITU_ZEN_KESSAI_KEN AS KESSAI_KEN_ZEN_DOJITU

        ,      SUM(URIAGE)             OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS URIAGE_RUI
        ,      SUM(ONER_YOSAN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS YOSAN_RUI
        ,      SUM(KYAKUSU)            OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KYAKUSU_RUI
        ,      SUM(DOJITU_ZEN_URIAGE)  OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS URIAGE_ZEN_DOJITU_RUI
        ,      SUM(DOJITU_ZEN_KYAKUSU) OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KYAKUSU_ZEN_DOJITU_RUI
        ,      SUM(ISSUE_CNT)          OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ISSUE_CNT_RUI
        ,      SUM(CHARGE_KIN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHARGE_KIN_RUI
        ,      SUM(CHARGE_KEN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHARGE_KEN_RUI
        ,      SUM(KESSAI_KIN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KESSAI_KIN_RUI
        ,      SUM(KESSAI_KEN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KESSAI_KEN_RUI
        ,      SUM(CHARGE_KIN_CANCEL)  OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHARGE_KIN_CANCEL_RUI
        ,      SUM(CHARGE_KEN_CANCEL)  OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHARGE_KEN_CANCEL_RUI
        ,      SUM(USE_KIN_CANCEL)     OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS USE_KIN_CANCEL_RUI
        ,      SUM(USE_KEN_CANCEL)     OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS USE_KEN_CANCEL_RUI
        ,      SUM(BONUS_V_ISSUE)      OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS BONUS_V_ISSUE_RUI
        ,      SUM(BONUS_V_USE)        OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS BONUS_V_USE_RUI
        ,      SUM(COUPON_V_ISSUE)     OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COUPON_V_ISSUE_RUI
        ,      SUM(COUPON_V_USE)       OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COUPON_V_USE_RUI


        ,      SUM(DOJITU_ZEN_ISSUE_CNT)          OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ISSUE_CNT_ZEN_DOJITU_RUI
        ,      SUM(DOJITU_ZEN_CHARGE_KIN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHARGE_KIN_ZEN_DOJITU_RUI
        ,      SUM(DOJITU_ZEN_CHARGE_KEN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHARGE_KEN_ZEN_DOJITU_RUI
        ,      SUM(DOJITU_ZEN_KESSAI_KIN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KESSAI_KIN_ZEN_DOJITU_RUI
        ,      SUM(DOJITU_ZEN_KESSAI_KEN)         OVER(partition by BM45.MISE_CD order by BM45.EIGYO_DT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KESSAI_KEN_ZEN_DOJITU_RUI

        FROM BM01TENM BM01
        ,    BM45ZDAY BM45
                LEFT JOIN BD35ZNMC BD35 ON (
                          BM45.COMPANY_CD = BD35.COMPANY_CD 
                    AND   BM45.MISE_CD   = BD35.MISE_CD
                    AND   BM45.EIGYO_DT  = BD35.EIGYO_DT
                    ) 
        WHERE BM01.COMPANY_CD = '00'
        AND   BM01.ONER_CD    = '37006'
        AND   BM01.COMPANY_CD = BM45.COMPANY_CD
        AND   BM01.MISE_CD    = BM45.MISE_CD
        AND   BM45.OLDM_FLG   = '0'
        AND   SUBSTR(BM45.EIGYO_DT, 1,6)  = /*taishoYM*/'201301' 
    ) AS TBL    
WHERE OPENING_FLG =1  
ORDER BY TBL.MISE_CD,TBL.EIGYO_DT