SELECT TOUAVG.MISE_CD       AS MISE_CD
,      BM01.MISE_NAME_KJ  AS MISE_NAME_KJ
,      TOUAVG.THREE_KBN     AS THREE_KBN
,      TOUAVG.URIAGE        AS URIAGE_AVG
,      TOUAVG.KYAKUSU       AS KYAKUSU_AVG
,      TOUAVG.ISSUE_CNT     AS ISSUE_CNT_AVG
,      TOUAVG.CHARGE_KIN    AS CHARGE_KIN_AVG
,      TOUAVG.CHARGE_KEN    AS CHARGE_KEN_AVG
,      TOUAVG.KESSAI_KIN    AS KESSAI_KIN_AVG
,      TOUAVG.KESSAI_KEN    AS KESSAI_KEN_AVG
,      TOUAVG.EIGYO_DAYS    AS EIGYO_DAYS_SUM
,      ZENAVG.URIAGE        AS URIAGE_ZEN_DOGETU_AVG
,      ZENAVG.KYAKUSU       AS KYAKUSU_ZEN_DOGETU_AVG
,      ZENAVG.ISSUE_CNT     AS ISSUE_CNT_ZEN_DOGETU_AVG
,      ZENAVG.CHARGE_KIN    AS CHARGE_KIN_ZEN_DOGETU_AVG
,      ZENAVG.CHARGE_KEN    AS CHARGE_KEN_ZEN_DOGETU_AVG
,      ZENAVG.KESSAI_KIN    AS KESSAI_KIN_ZEN_DOGETU_AVG
,      ZENAVG.KESSAI_KEN    AS KESSAI_KEN_ZEN_DOGETU_AVG
,      ZENAVG.EIGYO_DAYS    AS EIGYO_DAYS_ZEN_DOGETU_SUM

,      DECIMAL( CASE WHEN ZENAVG.URIAGE  <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.URIAGE)/DOUBLE(ZENAVG.URIAGE)*100)+0.05)
                END, 20, 1) AS URIAGE_ZENNENHI

,      DECIMAL( CASE WHEN ZENAVG.KYAKUSU <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.KYAKUSU)/DOUBLE(ZENAVG.KYAKUSU)*100)+0.05)
                END, 20, 1) AS KYAKUSU_ZENNENHI


,      DECIMAL( CASE WHEN TOUAVG.KYAKUSU <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.URIAGE )/DOUBLE(TOUAVG.KYAKUSU))+0.5)
                END, 11, 0) AS KYAKUTANKA

,      DECIMAL( CASE WHEN ZENAVG.KYAKUSU <= 0 THEN 0.00
                     ELSE ((DOUBLE(ZENAVG.URIAGE )/DOUBLE(ZENAVG.KYAKUSU))+0.5)
                END, 11, 0) AS KYAKUTANKA_ZEN_DOGETU

,      DECIMAL( CASE WHEN TOUAVG.KYAKUSU <= 0 THEN 0.00 
                     WHEN ZENAVG.KYAKUSU <= 0 THEN 0.00 
                     WHEN ZENAVG.URIAGE <= 0 THEN 0.00 
                     ELSE ((DECIMAL(((DOUBLE(TOUAVG.URIAGE )/DOUBLE(TOUAVG.KYAKUSU))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(ZENAVG.URIAGE )/DOUBLE(ZENAVG.KYAKUSU))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS KYAKUTANKA_ZEN_DOGETUHI

,      DECIMAL( CASE WHEN ZENAVG.ISSUE_CNT <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.ISSUE_CNT)/DOUBLE(ZENAVG.ISSUE_CNT)*100)+0.05)
                END, 20, 1) AS ISSUE_CNT_ZENNENHI

,      DECIMAL( CASE WHEN ZENAVG.CHARGE_KIN <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.CHARGE_KIN)/DOUBLE(ZENAVG.CHARGE_KIN)*100)+0.05)
                END, 20, 1) AS CHARGE_KIN_ZENNENHI

,      DECIMAL( CASE WHEN ZENAVG.CHARGE_KEN <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.CHARGE_KEN)/DOUBLE(ZENAVG.CHARGE_KEN)*100)+0.05)
                END, 20, 1) AS CHARGE_KEN_ZENNENHI

,      DECIMAL( CASE WHEN TOUAVG.CHARGE_KEN <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.CHARGE_KIN )/DOUBLE(TOUAVG.CHARGE_KEN))+0.5)
                END, 11, 0) AS CHARGE_TANKA

,      DECIMAL( CASE WHEN ZENAVG.CHARGE_KEN <= 0 THEN 0.00
                     ELSE ((DOUBLE(ZENAVG.CHARGE_KIN )/DOUBLE(ZENAVG.CHARGE_KEN))+0.5)
                END, 11, 0) AS CHARGE_TANKA_ZEN_DOGETU

,      DECIMAL( CASE WHEN TOUAVG.CHARGE_KEN <= 0 THEN 0.00 
                     WHEN ZENAVG.CHARGE_KEN <= 0 THEN 0.00 
                     ELSE ((DECIMAL(((DOUBLE(TOUAVG.CHARGE_KIN )/DOUBLE(TOUAVG.CHARGE_KEN))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(ZENAVG.CHARGE_KIN )/DOUBLE(ZENAVG.CHARGE_KEN))+0.5), 11,0) *100 )+0.05) 
                END, 20, 1) AS CHARGE_TANKA_ZEN_DOGETUHI

,      DECIMAL( CASE WHEN ZENAVG.KESSAI_KIN <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.KESSAI_KIN)/DOUBLE(ZENAVG.KESSAI_KIN)*100)+0.05)
                END, 20, 1) AS KESSAI_KIN_ZENNENHI

,      DECIMAL( CASE WHEN ZENAVG.KESSAI_KEN <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.KESSAI_KEN)/DOUBLE(ZENAVG.KESSAI_KEN)*100)+0.05)
                END, 20, 1) AS KESSAI_KEN_ZENNENHI

,      DECIMAL( CASE WHEN TOUAVG.KESSAI_KEN <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.KESSAI_KIN )/DOUBLE(TOUAVG.KESSAI_KEN))+0.5)
                END, 11, 0) AS KESSAI_TANKA

,      DECIMAL( CASE WHEN ZENAVG.KESSAI_KEN <= 0 THEN 0.00
                     ELSE ((DOUBLE(ZENAVG.KESSAI_KIN )/DOUBLE(ZENAVG.KESSAI_KEN))+0.5)
                END, 11, 0) AS KESSAI_TANKA_ZEN_DOGETU

,      DECIMAL( CASE WHEN TOUAVG.KESSAI_KEN <= 0 THEN 0.00 
                     WHEN ZENAVG.KESSAI_KEN <= 0 THEN 0.00 
                     ELSE ((DECIMAL(((DOUBLE(TOUAVG.KESSAI_KIN )/DOUBLE(TOUAVG.KESSAI_KEN))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(ZENAVG.KESSAI_KIN )/DOUBLE(ZENAVG.KESSAI_KEN))+0.5), 11,0) *100 )+0.05) 
                END, 20, 1) AS KESSAI_TANKA_ZEN_DOGETUHI

,      CASE WHEN TOUAVG.THREE_KBN = '9' THEN '•½‹Ï'
            WHEN TOUAVG.THREE_KBN = '1' THEN '•½“ú'
            WHEN TOUAVG.THREE_KBN = '2' THEN '“y—j“ú'
            WHEN TOUAVG.THREE_KBN = '3' THEN '“úÕ“ú'        
            ELSE '' END  AS THREE_NAME
FROM 
     (
        SELECT BD35.MISE_CD                    AS MISE_CD
        ,      MAX(OPEN_KBN)                   AS OPENING_FLG
        ,      (CASE WHEN BD14.THREE_KBN IS NULL THEN '9' ELSE BD14.THREE_KBN END)  AS THREE_KBN
        ,      DECIMAL(AVG(URIAGE) +0.5 ,11,0) AS URIAGE
        ,      DECIMAL(AVG(KYAKUSU)+0.5 ,11,0) AS KYAKUSU
        ,      DECIMAL(AVG(ISSUE_CNT)+0.5 ,11,0) AS ISSUE_CNT
        ,      DECIMAL(AVG(CHARGE_KIN)+0.5 ,11,0) AS CHARGE_KIN
        ,      DECIMAL(AVG(CHARGE_KEN)+0.5 ,11,0) AS CHARGE_KEN
        ,      DECIMAL(AVG(KESSAI_KIN)+0.5 ,11,0) AS KESSAI_KIN
        ,      DECIMAL(AVG(KESSAI_KEN)+0.5 ,11,0) AS KESSAI_KEN        
        ,      COUNT(EIGYO_DAYS)               AS EIGYO_DAYS
        FROM BD14ACAL BD14
        ,    BD35ZNMC BD35
        WHERE BD35.COMPANY_CD = /*companyCd*/'00'
        AND   SUBSTR(BD35.EIGYO_DT, 1,6)  = /*taishoYM*/'201302'
        AND   OLDM_FLG  = '0'
        AND   HONBU_KBN = '0'
        AND   BD35.EIGYO_DT   = BD14.EIGYO_DT
        GROUP BY ROLLUP((BD35.MISE_CD)
              ,(BD35.MISE_CD,BD14.THREE_KBN))
     ) AS TOUAVG
,   (
        SELECT BD35.MISE_CD                     AS MISE_CD
        ,      (CASE WHEN BD14.THREE_KBN IS NULL THEN '9' ELSE BD14.THREE_KBN END) AS THREE_KBN
        ,      DECIMAL(AVG(DOGETU_ZEN_URIAGE) +0.5 ,11,0) AS URIAGE
        ,      DECIMAL(AVG(DOGETU_ZEN_KYAKUSU)+0.5 ,11,0) AS KYAKUSU
        ,      DECIMAL(AVG(DOGETU_ZEN_ISSUE_CNT)+0.5 ,11,0) AS ISSUE_CNT
        ,      DECIMAL(AVG(DOGETU_ZEN_CHARGE_KIN)+0.5 ,11,0) AS CHARGE_KIN
        ,      DECIMAL(AVG(DOGETU_ZEN_CHARGE_KEN)+0.5 ,11,0) AS CHARGE_KEN
        ,      DECIMAL(AVG(DOGETU_ZEN_KESSAI_KIN)+0.5 ,11,0) AS KESSAI_KIN
        ,      DECIMAL(AVG(DOGETU_ZEN_KESSAI_KEN)+0.5 ,11,0) AS KESSAI_KEN        
        ,      COUNT(EIGYO_DAYS)                AS EIGYO_DAYS
        FROM BD14ACAL BD14
        ,    BD35ZNMC BD35
        WHERE BD35.COMPANY_CD = /*companyCd*/'00'
        AND   SUBSTR(BD35.EIGYO_DT, 1,6)  = /*taishoYM*/'201302'
        AND   OLDM_FLG  = '0'
        AND   HONBU_KBN = '0'        
        AND   BD35.ZENNEN_DT   = BD14.EIGYO_DT
        GROUP BY ROLLUP((BD35.MISE_CD)
              ,(BD35.MISE_CD,BD14.THREE_KBN))
     ) AS ZENAVG
,    BM01TENM BM01

WHERE TOUAVG.OPENING_FLG =1
AND   BM01.COMPANY_CD = /*companyCd*/'00'
AND   BM01.ONER_CD    = /*onerCd*/'37006'
AND   TOUAVG.MISE_CD    = BM01.MISE_CD
AND   TOUAVG.MISE_CD  =ZENAVG.MISE_CD 
AND   TOUAVG.THREE_KBN=ZENAVG.THREE_KBN

ORDER BY TOUAVG.MISE_CD , THREE_KBN