SELECT TOUAVG.MISE_CD       AS MISE_CD
,      TOUAVG.MISE_NAME_KJ  AS MISE_NAME_KJ
,      (CASE WHEN TOUAVG.THREE_KBN IS NULL THEN '9' ELSE TOUAVG.THREE_KBN END)    AS THREE_KBN
,      TOUAVG.URIAGE        AS URIAGE_AVG
,      TOUAVG.KYAKUSU       AS KYAKUSU_AVG
,      TOUAVG.EIGYO_DAYS    AS EIGYO_DAYS_SUM
,      ZENAVG.URIAGE        AS URIAGE_ZEN_DOGETU_AVG
,      ZENAVG.KYAKUSU       AS KYAKUSU_ZEN_DOGETU_AVG
,      ZENAVG.EIGYO_DAYS    AS EIGYO_DAYS_ZEN_DOGETU_SUM

,      DECIMAL( CASE WHEN ZENAVG.URIAGE  <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.URIAGE)/DOUBLE(ZENAVG.URIAGE)*100)+0.05)
                END, 20, 1) AS URIAGE_ZENNENHI

,      DECIMAL( CASE WHEN ZENAVG.KYAKUSU <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.KYAKUSU)/DOUBLE(ZENAVG.KYAKUSU)*100)+0.05)
                END, 20, 1) AS KYAKUSU_ZENNENHI


,      DECIMAL( CASE WHEN TOUAVG.KYAKUSU <= 0 THEN 0.00
                     ELSE ((DOUBLE(TOUAVG.URIAGE )/DOUBLE(TOUAVG.KYAKUSU))+0.5)
                END, 11, 0) AS KYAKUTANKA

,      DECIMAL( CASE WHEN ZENAVG.KYAKUSU <= 0 THEN 0.00
                     ELSE ((DOUBLE(ZENAVG.URIAGE )/DOUBLE(ZENAVG.KYAKUSU))+0.5)
                END, 11, 0) AS KYAKUTANKA_ZEN_DOGETU

,      DECIMAL( CASE WHEN TOUAVG.KYAKUSU <= 0 THEN 0.00 
                     WHEN ZENAVG.KYAKUSU <= 0 THEN 0.00 
                     ELSE ((DECIMAL(((DOUBLE(TOUAVG.URIAGE )/DOUBLE(TOUAVG.KYAKUSU))+0.5), 11,0) 
                           /DECIMAL(((DOUBLE(ZENAVG.URIAGE )/DOUBLE(ZENAVG.KYAKUSU))+0.5), 11,0) *100 )+0.05) 
                END, 10, 1) AS KYAKUTANKA_ZEN_DOGETUHI
                
,      CASE WHEN TOUAVG.THREE_KBN IS NULL THEN '•½‹Ï'
            WHEN TOUAVG.THREE_KBN = '1'   THEN '•½“ú'
            WHEN TOUAVG.THREE_KBN = '2'   THEN '“y—j“ú'
            WHEN TOUAVG.THREE_KBN = '3'   THEN '“úÕ“ú'        
            ELSE '' END  AS THREE_NAME
FROM 
     (
        SELECT BM01.MISE_CD                    AS MISE_CD
        ,      MAX(OPEN_KBN)                   AS OPENING_FLG
        ,      BM01.MISE_NAME_KJ               AS MISE_NAME_KJ
        ,      BD14.THREE_KBN                  AS THREE_KBN
        ,      DECIMAL(AVG(URIAGE) +0.5 ,11,0) AS URIAGE
        ,      DECIMAL(AVG(KYAKUSU)+0.5 ,11,0) AS KYAKUSU
        ,      COUNT(EIGYO_DAYS)               AS EIGYO_DAYS
        FROM 
             BM01TENM BM01
        ,    BD14ACAL BD14
        ,    BT60ZNIP TOU
        WHERE BM01.COMPANY_CD = /*companyCd*/'00'
        AND   BM01.ONER_CD    = /*onerCd*/'36257'
        AND   BM01.COMPANY_CD = TOU.COMPANY_CD
        AND   BM01.MISE_CD    = TOU.MISE_CD
        AND   OLDM_FLG  = '0'
        AND   SUBSTR(TOU.EIGYO_DT, 1,6)  = /*taishoYM*/'200803'
        AND   TOU.EIGYO_DT   = BD14.EIGYO_DT
        GROUP BY ROLLUP((BM01.MISE_CD,BM01.MISE_NAME_KJ)
              ,(BM01.MISE_CD,BM01.MISE_NAME_KJ,BD14.THREE_KBN))
     ) AS TOUAVG,

     (
        SELECT BM01.MISE_CD                     AS MISE_CD
        ,      BM01.MISE_NAME_KJ                AS MISE_NAME_KJ
        ,      BD14.THREE_KBN                   AS THREE_KBN
        ,      DECIMAL(AVG(URIAGE_ZEN_DOGETU) +0.5 ,11,0) AS URIAGE
        ,      DECIMAL(AVG(KYAKUSU_ZEN_DOGETU)+0.5 ,11,0) AS KYAKUSU
        ,      COUNT(EIGYO_DAYS)                AS EIGYO_DAYS
        FROM 
             BM01TENM BM01
        ,    BD14ACAL BD14
        ,    BT60ZNIP ZEN
        WHERE BM01.COMPANY_CD = /*companyCd*/'00'
        AND   BM01.ONER_CD    = /*onerCd*/'36257'
        AND   BM01.COMPANY_CD = ZEN.COMPANY_CD
        AND   BM01.MISE_CD    = ZEN.MISE_CD
        AND   OLDM_FLG  = '0'
        AND   SUBSTR(ZEN.EIGYO_DT, 1,6)  = /*taishoYM*/'200803'
        AND   ZEN.ZENNEN_DT   = BD14.EIGYO_DT
        GROUP BY ROLLUP((BM01.MISE_CD,BM01.MISE_NAME_KJ)
              ,(BM01.MISE_CD,BM01.MISE_NAME_KJ,BD14.THREE_KBN))
     ) AS ZENAVG
WHERE TOUAVG.OPENING_FLG =1
AND TOUAVG.MISE_CD  =ZENAVG.MISE_CD
AND (TOUAVG.THREE_KBN=ZENAVG.THREE_KBN OR (TOUAVG.THREE_KBN IS NULL AND ZENAVG.THREE_KBN IS NULL))
ORDER BY TOUAVG.MISE_CD , THREE_KBN