select
    BR17.ENTRY_CD,
    BR17.ENTRY_YEAR,
    BR17.ENTRY_KAI,
    rtrim(BR17.ENTRY_TITLE) as ENTRY_TITLE,
    rtrim(BR17.ENTRY_PLACE) as ENTRY_PLACE,
    BR17.NUMBER_LIMIT,
    BR17.PLACE_LIMIT,
    rtrim(BR17.NOTE) as NOTE,
    BR17.SPARE_FLG1,
    BR17.SPARE_FLG2,
    BR17.SAKUJO_FLG,
    BR17.FIRST_USER,
    BR17.FIRST_PGM,
    BR17.FIRST_TMSP,
    BR17.LAST_USER,
    BR17.LAST_PGM,
    BR17.LAST_TMSP,
    rtrim(OPEN.FROM_DT) as OPEN_FROM_DT,
    rtrim(OPEN.TO_DT) as OPEN_TO_DT,
    DISPLAY.FROM_DT as DISPLAY_FROM_DT,
    DISPLAY.TO_DT as DISPLAY_TO_DT,
    APPLY.FROM_DT as APPLY_FROM_DT,
    APPLY.TO_DT as APPLY_TO_DT
from
    BR17ENTL as BR17
    left outer join BR18ENTD as OPEN on BR17.ENTRY_CD = OPEN.ENTRY_CD and BR17.ENTRY_YEAR = OPEN.ENTRY_YEAR and BR17.ENTRY_KAI = OPEN.ENTRY_KAI and OPEN.USERTYPE_CD = '99' and OPEN.DAY_KBN = '01'
    left outer join BR18ENTD as DISPLAY on BR17.ENTRY_CD = DISPLAY.ENTRY_CD and BR17.ENTRY_YEAR = DISPLAY.ENTRY_YEAR and BR17.ENTRY_KAI = DISPLAY.ENTRY_KAI and DISPLAY.USERTYPE_CD = '02' and DISPLAY.DAY_KBN = '03'
    left outer join BR18ENTD as APPLY on BR17.ENTRY_CD = APPLY.ENTRY_CD and BR17.ENTRY_YEAR = APPLY.ENTRY_YEAR and BR17.ENTRY_KAI = APPLY.ENTRY_KAI and APPLY.USERTYPE_CD = '02' and APPLY.DAY_KBN = '04'
where
    BR17.ENTRY_CD = /*entryCd*/'10' and
    BR17.SAKUJO_FLG <> '1' and
    substr(OPEN.FROM_DT, 1, 4) >= /*fromYear*/'2005' 
order by
    APPLY_FROM_DT desc,
    BR17.ENTRY_YEAR desc,
    BR17.ENTRY_KAI desc
