SELECT
    BT05.REG_DATE,
    BT05.SEQ,
    RTRIM(BT05.TITLE) AS TITLE,
    BT05.PUB_DATE_FROM,
    BT05.PUB_DATE_TO,
    BT05.PUB_USER,
    BT05.PUB_ORG,
    BT05.PUB_ORG_NAME,
    RTRIM(BT05.SIMPLE_MSG) AS SIMPLE_MSG,
    RTRIM(BT05.MESSAGE) AS MESSAGE,
    RTRIM(BT05.ATTACH_NAME1) AS ATTACH_NAME1,      
    RTRIM(BT05.ATTACH_NAME2) AS ATTACH_NAME2,      
    RTRIM(BT05.ATTACH_NAME3) AS ATTACH_NAME3,     
    RTRIM(BT05.ATTACH_FL1) AS ATTACH_FL1,       
    RTRIM(BT05.ATTACH_FL2) AS ATTACH_FL2,        
    RTRIM(BT05.ATTACH_FL3) AS ATTACH_FL3,        
    BT05.SAKUJO_FLG,
    BT05.FIRST_USER,
    BT05.FIRST_PGM,
    BT05.FIRST_TMSP,
    BT05.LAST_USER,
    BT05.LAST_PGM,
    BT05.LAST_TMSP,
    BR01.USER_NAME_KJ
FROM
    BT05WNEW BT05
,   BR01USER BR01
WHERE
    BT05.REG_DATE like /*REG_DATE*/'200812%'
AND BT05.PUB_USER = BR01.USER_ID
AND BR01.BUMON_CD = (SELECT BUMON_CD FROM BR01USER WHERE USER_ID =/*USER_ID*/'99990001')
ORDER BY BT05.PUB_DATE_FROM DESC, BT05.REG_DATE DESC, BT05.SEQ DESC