SELECT DISTINCT
    rtrim(BM06UONR.ONER_CD) as ONER_CD,
    rtrim(BM11ONER.ONER_NAME_KJ) as ONER_NAME_KJ 
FROM 
    BM06UONR
    INNER JOIN BM11ONER ON BM06UONR.COMPANY_CD = BM11ONER.COMPANY_CD
                        AND BM06UONR.ONER_CD = BM11ONER.ONER_CD
WHERE
    BM06UONR.USER_ID = /*userId*/'99990003'
AND BM06UONR.COMPANY_CD = /*companyCd*/'00'