select
	rtrim(BT21.ENTRY_CD) AS ENTRY_CD,
	rtrim(BT21.ENTRY_YEAR) AS ENTRY_YEAR,
	rtrim(BT21.ENTRY_KAI) AS ENTRY_KAI,
	rtrim(BT21.COMPANY_CD) as COMPANY_CD,
	rtrim(BT21.ONER_CD) as ONER_CD,
	rtrim(BT21.ATESAKI_KBN) as ATESAKI_KBN,
	rtrim(BT21.NAME) as NAME,
	rtrim(BT21.TEL) as TEL,
	rtrim(BT21.ZIP) as ZIP,
	rtrim(BT21.ADDRESS1) as ADDRESS1,
	rtrim(BT21.ADDRESS2) as ADDRESS2,
	rtrim(BT21.ADDRESS3) as ADDRESS3,
	rtrim(BT21.SOUFU_NAME) as SOUFU_NAME,
	rtrim(BT21.JOB_TYPE) as JOB_TYPE,
	rtrim(BT21.FIRST_USER) as FIRST_USER,
	rtrim(BT21.FIRST_PGM) as FIRST_PGM,
	BT21.FIRST_TMSP,
	rtrim(BT21.LAST_USER) as LAST_USER,
	rtrim(BT21.LAST_PGM) as LAST_PGM,
	BT21.LAST_TMSP,
	rtrim(BM11.ONER_NAME_KJ) as ONER_NAME_KJ
from
	BT21ENOJ BT21,
	BM11ONER BM11 
where
	BT21.COMPANY_CD = BM11.COMPANY_CD
and BT21.ONER_CD = BM11.ONER_CD 
and BT21.ENTRY_CD = /*entryCd*/'05'
and BT21.ENTRY_YEAR = /*entryYear*/'2006'
and BT21.ENTRY_KAI = /*entryKai*/'047'
and BT21.COMPANY_CD = /*companyCd*/'00'
and BT21.ONER_CD = /*onerCd*/'36478'