SELECT 
	RTRIM(BR01USER.USER_ID) as USER_ID,
	RTRIM(BR01USER.USER_NAME_KJ) as USER_NAME_KJ,
	RTRIM(BR01USER.USER_NAME_KANA) as USER_NAME_KANA,
	RTRIM(BR01USER.USER_ID) || ' ' || RTRIM(BR01USER.USER_NAME_KJ) as USER_CD_NAME_KJ,
	RTRIM(BR01USER.USERTYPE_CD) as USERTYPE_CD,
	RTRIM(BR01USER.BUMON_CD) as BUMON_CD,
	RTRIM(BC08CBMN.BUMON_NAME) as BUMON_NAME,
	RTRIM(BR01USER.BUMON_CD) || ' ' || RTRIM(BC08CBMN.BUMON_NAME) as BUMON_CD_NAME,
	BR01USER.USER_PSWD,
	BR01USER.PSWD_UPDT_DT,
	BR01USER.LAST_PSWD,
	RTRIM(BR01USER.SEKYU_FLG) as SEKYU_FLG,
	RTRIM(BR01USER.MAIL_ADD) as MAIL_ADD,
	RTRIM(BR01USER.APPLIED_DT) as APPLIED_DT,
	RTRIM(BR01USER.SEKYU_DT) as SEKYU_DT,
	RTRIM(BR01USER.SEKYU_UPDT_DT) as SEKYU_UPDT_DT,
	RTRIM(BR01USER.LIMIT_KBN) as LIMIT_KBN,
	RTRIM(BR01USER.STOP_FLG) as STOP_FLG,
	RTRIM(BR01USER.FIRST_USER) as FIRST_USER,
	RTRIM(BR01USER.FIRST_PGM) as FIRST_PGM,
	BR01USER.FIRST_TMSP,
	RTRIM(BR01USER.LAST_USER) as LAST_USER,
	RTRIM(BR01USER.LAST_PGM) as LAST_PGM,
	BR01USER.LAST_TMSP
FROM  
   BR01USER BR01USER LEFT JOIN 
    (select BC08CBMN.BUMON_CD, BC08CBMN.BUMON_NAME from BM03USCP, BC08CBMN where BM03USCP.USER_ID = /*user_id*/'99990003' and BM03USCP.R_COMPANY_CD = BC08CBMN.R_COMPANY_CD and BM03USCP.ZOKUSEI_KBN = '1') BC08CBMN 
   on (BR01USER.BUMON_CD = BC08CBMN.BUMON_CD)  
WHERE
    BR01USER.USER_ID = /*user_id*/
ORDER BY
    BR01USER.USER_ID