select
	BC10.ENTRY_CD
,	BR17.ENTRY_YEAR
,	BR17.ENTRY_KAI
,   BM12.COMPANY_CD
,   BC05.COMPANY_NAME
,   BM12.ONER_CD
,   BM11.ONER_NAME_KJ
,   BM12.MISE_CD_1 AS MISE_CD
,   BM01.MISE_NAME_KJ
,   BM01.AREA_DAI 
,   BM10.SIBU_NAME 
,	BM12.STAFF_ID
,	BM12.STAFF_L_NAME_KJ
,	BM12.STAFF_F_NAME_KJ
,	BM12.STAFF_L_NAME_KNA
,	BM12.STAFF_F_NAME_KNA
,	CASE WHEN BT30.COURSE_STATUS IS NULL 
         THEN CASE WHEN BT22.STAFF_ID IS NULL 
                   THEN '0' ELSE '2' END 
         ELSE BT30.COURSE_STATUS 
    END AS COURSE_STATUS
,   CASE WHEN BT30.COURSE_STATUS IS NULL THEN '—\’è'
         WHEN BT30.COURSE_STATUS = '0' THEN '–¢C—¹'
         WHEN BT30.COURSE_STATUS = '1' THEN 'C—¹'
         WHEN BT30.COURSE_STATUS = '2' THEN '—\’è'
         ELSE '' END AS COURSE_STATUS_NAME
,   CASE WHEN BT30.COMPLE_COURSE_DT IS NULL THEN '' ELSE RTRIM(BT30.COMPLE_COURSE_DT) END AS COMPLE_COURSE_DT
,   CASE WHEN BT30.COMPLE_COURSE_CD IS NULL THEN '' ELSE BT30.COMPLE_COURSE_CD END AS COMPLE_COURSE_CD
,   CASE WHEN BT30.COMPLE_COURSE_CD IS NULL THEN '' 
         WHEN BT30.COMPLE_COURSE_NAME IS NULL THEN '' 
         ELSE BT30.COMPLE_COURSE_NAME END AS COMPLE_COURSE_NAME
,   DECIMAL((CASE WHEN BT30.COMPLE_POINT IS NULL THEN 0 ELSE BT30.COMPLE_POINT END), 3,0) AS COMPLE_POINT
,   CASE WHEN BT22.STAFF_ID IS NULL THEN '0' ELSE '1' END AS ENTRY_FLG
,   CASE WHEN BT30.COURSE_STATUS IS NULL THEN 'INSERT' ELSE 'UPDATE' END AS DATA_STATUS_ET30
,   CASE WHEN VBT32.STAFF_ID IS NULL THEN 'INSERT' ELSE 'UPDATE' END AS DATA_STATUS
,   CASE WHEN BT30.COURSE_STATUS IS NULL THEN '0' ELSE '1' END AS REG_FLG
,   CASE WHEN SHURYO.SHURYO_CNT > 0 THEN '1' ELSE '0' END AS SHURYO_FLG
,   '' AS FIRST_USER
,   '' AS FIRST_PGM
,   current timestamp AS FIRST_TMSP
,   '' AS LAST_USER
,   '' AS LAST_PGM
,   current timestamp AS LAST_TMSP
from
	BC10ENTM BC10
,   BR17ENTL BR17
,   BM01TENM BM01
    LEFT JOIN BM10GSIB BM10 
         ON (BM10.COMPANY_CD = BM01.COMPANY_CD and BM10.SIBU_CD = BM01.AREA_DAI ) 
,   BM11ONER BM11
,   BC05KCOM BC05
,   BT22ENKN BT22
,   BM12STAF BM12
LEFT JOIN (select LIST.STAFF_ID
           ,      LIST.COURSE_STATUS
           ,      LIST.COMPLE_COURSE_DT
           ,      LIST.COMPLE_COURSE_CD
           ,      BR19.COURSE_NAME AS COMPLE_COURSE_NAME
           ,      LIST.COMPLE_POINT
           from      BT30ENKJ LIST
        		LEFT JOIN BR19MLCR BR19 ON (
                    LIST.ENTRY_CD = BR19.ENTRY_CD
                AND LIST.ENTRY_YEAR = BR19.ENTRY_YEAR
                AND LIST.ENTRY_KAI = BR19.ENTRY_KAI
                AND LIST.COMPLE_COURSE_CD = BR19.COURSE_CD)
           where LIST.ENTRY_CD   = /*entryCd*/'01'
           AND   LIST.ENTRY_YEAR = /*entryYear*/'2006'
           AND   LIST.ENTRY_KAI  = /*entryKai*/'001'
     ) BT30
     ON (BT30.STAFF_ID   = BM12.STAFF_ID) 
LEFT JOIN (select LIST.STAFF_ID
           ,      SUM(CASE WHEN (ENTRY_CD = /*entryCd*/'01' AND ENTRY_YEAR = /*entryYear*/'2006' AND ENTRY_KAI  = /*entryKai*/'001')
                           THEN 0
                           ELSE 1
                           END
                  ) SHURYO_CNT 
           from      BT30ENKJ LIST
           where LIST.COURSE_STATUS   = '1'
           group by  LIST.STAFF_ID
           
     ) SHURYO
     ON (SHURYO.STAFF_ID   = BM12.STAFF_ID) 
LEFT JOIN VBT32MLKR VBT32
     ON (VBT32.STAFF_ID   = BM12.STAFF_ID and VBT32.TOTAL_LAST_YEAR = /*entryYear*/'2006' and VBT32.TOTAL_LAST_KAI = /*entryKai*/'001') 
where
      BC10.ENTRY_TYPE='1'
AND   BC10.ENTRY_CD = /*entryCd*/'01'
AND   BR17.ENTRY_YEAR = /*entryYear*/'2006'
AND   BR17.ENTRY_KAI = /*entryKai*/'001'
/*IF sibuCd != null*/
    AND   BM01.AREA_DAI = /*sibuCd*/'011'
/*END*/
AND   BC05.COMPANY_CD = /*companyCd*/'00'
AND   BM12.COMPANY_CD = BC05.COMPANY_CD
AND   BR17.ENTRY_CD = BC10.ENTRY_CD
AND   BT22.ENTRY_CD = BR17.ENTRY_CD
AND   BT22.ENTRY_YEAR = BR17.ENTRY_YEAR
AND   BT22.ENTRY_KAI = BR17.ENTRY_KAI
AND   BM12.MISE_CD_1 = BM01.MISE_CD
AND   BM12.ONER_CD = BM11.ONER_CD
AND   BT22.STAFF_ID = BM12.STAFF_ID
AND   BM12.COMPANY_CD = BM01.COMPANY_CD
AND   BM01.COMPANY_CD = BM11.COMPANY_CD
order by 
	CASE WHEN BT22.STAFF_ID IS NULL THEN '0' ELSE '1' END
,   BC10.ENTRY_CD
,	BR17.ENTRY_YEAR
,	BR17.ENTRY_KAI
,   BM12.COMPANY_CD
,   BM12.ONER_CD
,   BM12.MISE_CD_1
,	hex(BM12.STAFF_F_NAME_KNA)
,	hex(BM12.STAFF_L_NAME_KNA)
